### ISSUE TITLE
windows8.1【Startup】An error occurred

### ISSUE THREAD

**Issue by Whichbfj28** [localsend/localsend#1002]
### Describe the bug

![image](https://github.com/localsend/localsend/assets/47915665/c7a488ba-82d4-46fb-ac35-84bad14737c3)

### To reproduce

Just click this button and this error box will pop up. As a result, I cannot automatically start localsend to the tray icon when I turn on the computer.

### Expected behavior

Can be started automatically. And the tray icon directly in the lower right corner. No UI pop-up

### Desktop (please complete the following information)

v1.13.0
windows8.1 x64bit

**Comment by Tienisto** [comment]
What version did you use? exe, msix or zip? Did earlier versions work?

**Comment by Whichbfj28** [comment]
V1.10.0 is also invalid
All using zip versions
