### ISSUE TITLE
 iOS upgraded to version 1.13.0 the app crashes automatically when staying on the send page.

### ISSUE THREAD

**Issue by wbsnpc** [localsend/localsend#1004]
### Describe the bug

On my iPhone 8 Plus, when I open the app and stay on the Discover page, after a few seconds, the app automatically exits.

### To reproduce

none

### Expected behavior

none

**Comment by Tienisto** [comment]
I will probably publish a bug fix release soon that downgrades Flutter back from 3.16 to 3.13 due to high instability #1005, #999.

**Comment by Vilmodao** [comment]
Looks like I can reproduce this crash on an iPhone 7 with iOS 15.8 on it ( not tested on other devices).

To crash, you just need to go to the Send tab and wait.
For this to happen, there **must be no other Localsend devices on the network available for discovery**. In this case, the app performs a scan and apparently crashes at the end of it.
If the scan is able to find another available Localsend device, **then everything works fine**. 

You can crash the app even faster if you disable Wi-Fi and mobile data on an iPhone. In this case, the crash will happen almost instantly as soon as you switch to the Send tab.

Hope this helps

**Comment by Tienisto** [comment]
Thank you @Vilmodao. This will help a lot

**Comment by Tienisto** [comment]
This should be fixed in v1.13.1 feel free to reopen if you still encounter this bug.

**Comment by Vilmodao** [comment]
I updated the application to version 1.13.1 (42).
Unfortunately, crashes still here.

**Comment by Tienisto** [comment]
Have you tried to reinstall the app? @Vilmodao 
The only difference with 1.12.0 is that it also scans the IP address of favorite devices.
Unfortunately, I cannot reproduce this on my test iphone.

**Comment by Vilmodao** [comment]
I have reinstalled the app. Default settings. It still crashes every time I go to the Send tab and wait about 10 seconds.
It's a weird bug. But overall, the app does its job. It crashes only if it fails to detect other devices on the network.
I could make a video, but I don't know how that would help. It's nothing happened 10 sec. and after that, the app just closes.
Actually, maybe the app was crashing in previous versions as well, and I just didn't notice it. I decided to pay attention to it only because I saw this ticket.

**Comment by fightroad** [comment]
1.13.1  also crash

**Comment by Insprill** [comment]
I can confirm that 1.13.1 is crashing on an iPhone 8 running IOS 16.7.2.

**Comment by Tienisto** [comment]
Please checkout the exclusive 1.13.2 update that I just released only on iOS. Maybe it fixed the problem

**Comment by wbsnpc** [comment]
I believe this bug has already been fixed. On my iOS version 16.3, the app no longer crashes

**Comment by Vilmodao** [comment]
> Please checkout the exclusive 1.13.2 update that I just released only on iOS. Maybe it fixed the problem

I just updated the app, didn't reinstall it. Yeah, it seems to be okay now, no more crashes.
Thanks for fix and great app.
