### ISSUE TITLE
Feature request: Stretchable blocks for buttons

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#1007]
### Is your feature request related to a problem? Please describe.

Although I translate the application into Russian, I personally use Ukrainian everywhere. And since changes weren't always made to the Russian translation in a timely manner, and I possess Russian at a sufficient level to be able to translate, I decided to support this translation as well, because I simply can. There are probably many people who use the application and the Russian language in it, so it's more for them. But less lyrics.
I was passing the file to an acquaintance who uses Russian and noticed that the inscription "Приложение" (App), doesn't fit into the block for button, since it's long, so the font for it's reduced (if you remember, this was the case with the Clipboard earlier). And it doesn't look pretty at all. And the word "Приложение" (App), for such a case there is no correspondingly correct synonym to replace it and there is also no abbreviation, such as App (Application) in English. The only option is the word "Программа" (Program), but it's a bad match in this case. And this word is only one letter shorter, so it's not guaranteed that it'll be suitable either.

I don't know if it's possible to implement such an option, but according to my logic it should be possible. As far as I understand, currently, if some text doesn't fit in the block for button, the font size is reduced to fit it. Perhaps it would be possible to implement so that the font size doesn't decrease, but just so the block for button itself was stretched in width until the inscription would fit in it. For example, there is a minimum size for a block for button as it's now. And if all inscriptions fit into the block for button, then accordingly, nothing happens. But if the inscription doesn't fit into the block for button, then the block increases in width, for example, by 5% (because mostly only 1-2 letters don't fit), if it doesn't fit further, then by another 5%, and so on. Of course, there should be some limiting parameter so that the block for one button doesn't take up the entire screen. For example, the maximum allowable button size is no more than 50% of the original size. And if such an increase occurs for a button/s, then the size for all buttons in this case is set the same – the size of the largest button. That is, if the size of one button has increased by 105%, and another, for example, by 110%, then the size of all buttons in this case will be 110%. Even for those buttons that didn't stretch at all. This is simply to preserve the existing symmetry for all the buttons.
The same option can be applied to the settings tab, but there, the blocks would stretch in height (although in the case of settings, it's not as critical and noticeable). Of course, this is a lot of IF operators in theory, but it'll not break the design of the application at all and will allow you to use more correct inscription, instead of looking for synonyms which, in many cases, are not entirely suitable. Of course, this won't allow you to enter 100% of all the desired inscriptions, because in some cases they can really be too long and really need to be shortened, but both in Ukrainian and in Russian languages there are a lot of long words, and when literally 1-2 letters don't fit, and the font size is reduced, it's visually unpleasant. And in some cases, as, for example, in this case, the word cannot be replaced by anything. Therefore, we get such a stalemate, where the options are either to come up with an abbreviation for the word yourself, or to put up with a lowercase font for one button.

### Describe the solution you'd like

Described above.

### Describe alternatives you've considered

If the solution I proposed isn't feasible, too cumbersome, or simply not to your liking, then in that case, I'd be very grateful if you could at least stretch the blocks for buttons in width slightly so that they could accommodate 10 characters, there are exactly 10 letters in the word "Приложение" (App). It's literally a few pixels. Because I can't find any adequate substitute for this word.

### Additional context

![1](https://github.com/localsend/localsend/assets/125032334/6a9cc020-da2f-46f8-8991-0203c37264bd)

**Comment by Tienisto** [comment]
Thanks for this notice! I have removed the maximum width constraint of each button. I think this should be fine for now.

Adjusting the width of all buttons would be too difficult.
The Russian "Приложение" name is really long so it would make the other buttons that long that the user has to scroll a while to reach the last button.

**Comment by sergd88** [comment]
> Thanks for this notice! I have removed the maximum width constraint of each button. I think this should be fine for now.

Yes, such behavior is much better.

> Adjusting the width of all buttons would be too difficult. 

Clearly. I suspected as much. But removing the width restriction for each button isn't bad either. At least, it visually looks better than reducing the font size.

> The Russian "Приложение" name is really long so it would make the other buttons that long that the user has to scroll a while to reach the last button.

Well, in the Ukrainian word "Додаток", there are only three letters less than in the similar Russian "Приложение". Therefore, the size wouldn't be radically different from the current one. However, I wouldn't want it to affect all users, so the option of removing the width restriction for each button is a great compromise.

**Comment by sergd88** [comment]
@Tienisto Regarding "the user has to scroll a while to reach the last button": I don't want to open a separate issue for this, so I'll mention it here. If you wish, you can format this inquiry as a separate issue. I just don't know if you'll consider it at all, so I'll leave it here.

Currently, many users aren't even aware that besides the four visible buttons, there is an additional one, and this list can be scrolled. Well, at least, all those with a standard screen and aspect ratio, and the fifth button or its part (narrow screen on Sony) is simply not noticeable to them. I deliberately showed friends that on Android, you can share apps, which is the fifth additional button. Although the indents on the left and right are different, not everyone can guess that this is due to additional elements.

If you pay attention, in most such cases, they show an additional part of the next element for this purpose. A vivid example of this is the display of workspaces in GNOME, which came to mind first. There it's implemented in this way (screenshot 1). I don't know how difficult it'll be to implement such an option here, but you can implement it, in my opinion, in a slightly simpler way (screenshot 2), although perhaps it's not as obvious and common. Specifically, by adding a "scroll" button next to the "Selection" section. And when pressed, the entire list of section buttons is automatically scrolled to the last one.

You can also add animation where the button rotates in the opposite direction so that when the user presses it again, the list automatically returns to the first section button. A reverse action. In my opinion, this would look nice.

P.S. I'll also note that when I created the image with scrolling, I noticed that not all icons are aligned in color. Some of them are lighter, and some are darker, for example, the "Settings gear icon" and "the heart icon for Favorites". It would also be good to fix this.

![1](https://github.com/localsend/localsend/assets/125032334/12b33a5d-4c8e-4c39-9b36-7dfe4a7ab8a6)

![2](https://github.com/localsend/localsend/assets/125032334/9cd50d44-a5c7-483c-b278-571702edc499)

I'm also attaching the icon just in case.

[scroll.zip](https://github.com/localsend/localsend/files/13614324/scroll.zip)

**Comment by sergd88** [comment]
@Tienisto Sorry to bother you again, but the thing is that not all of my Russian-speaking acquaintances liked the fact that now one button is wider than all the others. It turned out that they preferred the previous option where the font on the button simply decreased and adjusted to fit the button, and all the buttons were of the same size. Indeed, most of them liked the current version with a wider button. But, roughly speaking, opinions on this matter are divided.

So, I've a request, if possible, please add a toggle switch in Advanced settings through which one could enable the maximum width limitation for each button, as it was before.

**Comment by Tienisto** [comment]
I don't think it is something that should be configurable because it adds unecessary complexity to the app.
I am indifferent regarding the "stretchable" buttons though.

Another solution would be to display 2 rows for languages where it doesn't fit in one line.

**Comment by sergd88** [comment]
> I don't think it is something that should be configurable because it adds unecessary complexity to the app. I am indifferent regarding the "stretchable" buttons though.

I'm completely satisfied with the wider button. In my opinion, it looks visually better than reducing the font size. I was asked to convey this to you, and I've done so. I'll communicate your response to them.
Sorry again for any inconvenience.

**Comment by sergd88** [comment]
> Another solution would be to display 2 rows for languages where it doesn't fit in one line.

As for displaying the word on two lines, there might be issues with the word being grammatically divided incorrectly. The current option, in my opinion, is the most optimal among all possibilities.

**Comment by sergd88** [comment]
@Tienisto 

Sorry to bother you again about this matter, but I wanted to inquire whether the issue of reducing internal indents to make the text on the button occupy more useful space has been resolved? Are there certain restrictions on this and everything will remain as it's now? A short answer will be enough so as not to waste your time.

The reason I ask is that we've managed to find an alternative for the word "Приложение" (Application) which seems to suit everyone, more or less. However, it's essentially just a physical abbreviation of the word "Приложение" to "Прилож.", and it doesn't look very good or nice to me, but as I mentioned earlier, it's much more suitable for people who directly use the Russian language than the current version with a really wide button. Regarding the length of the word "Прилож.", it's identical in terms of character count and size to the word "Додаток" (Application), which is used in the Ukrainian language, so it should fit well in terms of size without changing the width of the button itself. But I would sincerely appreciate it if you could test this in practice before releasing the next version.

Regarding changing the width of the button. To avoid prolonging the discussion, I'll write in advance if the issue regarding internal indents has **NOT BEEN RESOLVED**.

In summary. Through all the discussions, it turned out that the previous option, where the button size is static, actually appeals to most people with a really good argument, in my opinion. "Reducing the font size on the button encourages the translator to seek alternatives and changes, whereas increasing the width of the button is perceived as more normal and doesn't stimulate further search for alternatives, so everything will remain unchanged, even if the button turns out to be very wide". And the increase in the width of the button, as it turned out, is really quite significant due to large indents, and even the growth of the word by 1 character noticeably increases the width of the button itself in relation to others. And it's really very noticeable, and it really doesn't look very nice. Ultimately, as I was told, this isn't very good for people who simply use the app in their native language and don't participate in the translation process. Therefore, if you haven't received any more complaints regarding this issue, perhaps it's indeed worth reverting to the previous option with static button width size.

**Comment by Tienisto** [comment]
Thanks for your response @sergd88 

I have tried to remove the padding, here is a screenshot of this change:

![Bildschirmfoto 2024-02-17 um 02 45 06](https://github.com/localsend/localsend/assets/38380847/24b2d3ac-1f94-4de0-ade3-8a6329de59b5)

**Comment by sergd88** [comment]
> Thanks for your response @sergd88
> 
> I have tried to remove the padding, here is a screenshot of this change:
> 
> ![Bildschirmfoto 2024-02-17 um 02 45 06](https://private-user-images.githubusercontent.com/38380847/305589885-24b2d3ac-1f94-4de0-ade3-8a6329de59b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNjUwMzgsIm5iZiI6MTcwODE2NDczOCwicGF0aCI6Ii8zODM4MDg0Ny8zMDU1ODk4ODUtMjRiMmQzYWMtMWY5NC00ZGUwLWFkZTMtOGE2MzI5ZGU1OWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDEwMTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNGM4NmQzMzQzNGYxMGUwNzFmNWY1OWMwMDI4NWFlYjY5NTA3OTA5NzBiNjcyMzA3NWRjZDVhYWNhYmIwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cR3yujgjo1ZF6A5fYEq83djH3Wd-KjqVDmtMJ5spfkk)

Oh, that's great. I'm truly appreciative ❤️
