### ISSUE TITLE
[Bug report] wrong winget version

### ISSUE THREAD

**Issue by hyunicode** [localsend/localsend#1015]
### Describe the bug

When I tried to upgrade LocalSend through `winget upgrade LocalSend.LocalSend` command, an error occurred. The log prompts that the installation is different from the current one. Please uninstall and reinstall the new version. I have installed LocalSend using `release 1.13.1 ... x86-64.exe`, the version information in winget is still 1.12.0

### To reproduce

1. open Windows Terminal, run `winget upgrade LocalSend.LocalSend`
2. the log should be 'current installation diffs from the new version'
3. completely uninstall 1.12 and install 1.13.1 using release exe
4. run `winget list LocalSend` to check version, you will see the error

### Expected behavior

After I have installed the new version, the version (winget) should be updated to 1.13.1

### Screenshots

![image](https://github.com/localsend/localsend/assets/81250265/4dc1e245-0fc2-4da4-b169-a965cc063121)
![image](https://github.com/localsend/localsend/assets/81250265/818bfbff-997e-485e-8fe1-8415f68470b9)

### Desktop (please complete the following information)

- OS: Windows 10 Pro 22H2
- Version: 19045.3758

**Comment by Tienisto** [comment]
Winget uses the MSIX version. The EXE version is stored differently.
