### ISSUE TITLE
File greater than 5GB will cause error

### ISSUE THREAD

**Issue by Warborn123** [localsend/localsend#1026]
### Describe the bug

Hi, I was trying to transfer 4 identical large files (2GB each) from my iPad Pro to PC, and I always got this error message before the last file was transferred.

Error
DioException [unknown]: null
Error: PathNotFoundException: Cannot open file, path = '/private/var/mobile/Containers/Data/Application/F113BB37-75C7-43CE-9CAE-BB34854ED218/tmp/org.localsend.localsendApp-Inbox/ Test.mp4' (OS Error: No such file or directory, errno = 2)

### Expected behavior

Being able to transfer file more than 5GB at once

### Smartphone (please complete the following information)

iPad Pro M1, iOS 17.2
Windows 11

**Comment by Tienisto** [comment]
Can you select a folder (with only that file). Does this work?

**Comment by HelloMusician** [comment]
I just tested it. Sending a folder(1171 files, 20.6G) from Android 13 to windows 10 x64 is available, but when sending another folder(2413 files, 21.2G), the app crashed.

**Comment by HypJii** [comment]
so is there any solution???

**Comment by ch1lam** [comment]
I am experiencing the same issue. When I transfer multiple files with a total size of 7.9 GB from my MBP to Windows, the application on Windows crashes. However, there is no problem when transferring small batches.

**Comment by Tienisto** [comment]
@ch1lam Regarding Windows, there is a bug in the newest update (1.15.0): #1506

**Comment by Evand3r** [comment]
An update on my end. My phone died (Android 12) and I recently purchased an Android 14 phone. Tested with a 6.4 GB file and it worked just fine with Localsend v1.15.1.

**Comment by Tienisto** [comment]
I believe that the device that sends the files needs as much RAM as the biggest file, while the receiving device can receive files with unlimited size.

**Comment by uttaran-das** [comment]
> so is there any solution???

Updating the app in both the devices solved this problem for me.

**Comment by Tienisto** [comment]
This should be fixed in the latest update now (1.15.2)

**Comment by bigemrg** [comment]
Hi, I'm using v1.15.3 on iPhone (14 Pro) and iMac (Intel based / Sonoma), and transferring a single 5.6GB video file from the iPhone to the Mac causes the iPhone app to crash.

**Comment by Levan7** [comment]
I have the same problem from windows 1.17 to linux flatpak same crash 5gb issue
