### ISSUE TITLE
Please add a Ukrainian translation for the website

### ISSUE THREAD

**Issue by OstapDerka4h** [localsend/localsend#1029]
### Is your feature request related to a problem? Please describe.

No, this is not related to the issue, but the app supports Ukrainian while, for some reason, the website does not, despite supporting many other languages

### Describe the solution you'd like

Translate the website into Ukrainian

**Comment by sergd88** [comment]
Translated.

**Comment by ekottifiok** [comment]
okay this issue can be closed since it's being translated
