### ISSUE TITLE
Can right-click menus be added to the Windows platform? 

### ISSUE THREAD

**Issue by heyeruoqi** [localsend/localsend#1032]
### Is your feature request related to a problem? Please describe.

Can right-click menus be added to the Windows platform? Of course, other computer platforms such as Mac also hope to add this feature. If you can right-click on the file > use Localsend to send, it is more convenient and immersive than dragging.

### Describe the solution you'd like

no

### Describe alternatives you've considered

no

**Comment by Tienisto** [comment]
Duplicate of #115
