### ISSUE TITLE
DioException [connection error]

### ISSUE THREAD

**Issue by RodBarnes** [localsend/localsend#1034]
### Describe the bug

Attempts to connect to LocalSend on Fedora 39 Cinnamon is problematic.  Running it on my desktop (Fedora 39 Cinnamon) or on my laptop (Fedora 39 Cinnamon) exhibits the same behavior.  Both are installed via AppoImage.  It works fine on my LinuxMint partition (also AppImage), Windows partition, and Android 12 phone.  All systems are on the same network, the desktop is cabled, the phone and laptop are WiFi.

On Fedora:
* It often cannot see other instances
* If it sees another instance, I can send successfully but other instances cannot send to Fedora and fail with an error (below).

```
DioException [connection error]: The connection errored: No route to host This indicates an error which most likely cnanot be solved by the library.
Error: SocketException: No route to host (OS Error: No route to host, errno = 113), address = <ip>, port = 56222.
```

### To reproduce

1. Open app on non-Fedora (e.g., Android, Windows) system
2. Open app on Fedora system
3. On Fedora, select to send
4. Non-Fedora system may not appear.
5. If it is visible, attempt to send.  This seems to work fine.
6. On Non-Fedora, select to send
7. Enter the text
8. Select the Fedora instance and send
9. It will fail on the Non-Fedora system 

### Expected behavior

All instances on the network should be visible and should receive/send with success.

### Screenshots

Desktop Fedora 39 Cinnamon
![Desktop-fedora-39-cinnamon](https://github.com/localsend/localsend/assets/3944607/8db50d75-18f6-48d2-8980-4487f0c3c63e)

Laptop Fedora 39 Cinnamon
![Laptop-fedora-39-cinnamon](https://github.com/localsend/localsend/assets/3944607/cf597a77-7d03-4245-b42d-4486bc50e87a)
llowing information)

### Desktop (please complete the fo

- Desktop: Linux Fedora 39 Cinnamon; kernel 6.6.4
- Desktop: Linux Mint 21.2; kernel 5.15
- Desktop: Windows 11 23H2
- Laptop: Linux Fedora 39 Cinnamon; kernel 6.6.4

### Smartphone (please complete the following information)

- Samsung Galaxy S10+ Android 12

**Comment by RodBarnes** [comment]
Firewall issue on Fedora.  I saw the troubleshooting link... :-)

**Comment by forerser** [comment]
what troubleshooting link? I'm with same error
