### ISSUE TITLE
[Feature request]: Add Checkmark Verification for the LocalSend Flathub Page

### ISSUE THREAD

**Issue by MysteriousOrb2000** [localsend/localsend#1036]
### Is your feature request related to a problem? Please describe.

LocalSend officially releases the Flatpak version via Flathub. However, the Flathub page lacks the Checkmark verified symbol. This may cause some confusion with users mistakenly believing the Flatpak version is not official.  

https://flathub.org/apps/org.localsend.localsend_app

### Describe the solution you'd like

The developer just needs to verify the app to get the checkmark.

https://docs.flathub.org/docs/for-users/verification/

**Comment by mijorus** [comment]
Yeah, I also think that they should add the verification badge.

**Comment by Tienisto** [comment]
I've verified LocalSend through the domain (should be updated in a moment).

Not sure how a proper "Verified" like the one you see on the "Firefox" app works...

**Comment by mijorus** [comment]
> I've verified LocalSend through the domain (should be updated in a moment).
> 
> Not sure how a proper "Verified" like the one you see on the "Firefox" app works...

Some apps are verified manually by the flathub team (usually those from big projects like firefox or KDE). Others rely on domain verification based on the app id
