### ISSUE TITLE
[Feature request]Can automatically transfer images from a folder on the computer, and also automatically transfer images to a folder on the computer on the mobile phone

### ISSUE THREAD

**Issue by AlexanderDash** [localsend/localsend#1039]
### Is your feature request related to a problem? Please describe.

Can automatically transfer images from a folder on the computer, and also automatically transfer images to a folder on the computer on the mobile phone

### Describe the solution you'd like

.

**Comment by Tienisto** [comment]
Use https://syncthing.net for this.
