### ISSUE TITLE
[BUG] Permission denied to send files from Windows to an external storage in Android 10 or older

### ISSUE THREAD

**Issue by EarthGuard0** [localsend/localsend#1045]
### Describe the bug

I can't send my any sort of files either png,mp4,mp3,etc from PC to android using an external storage, however it can send files to the internal storage. I'm encountering a persistent error [500] on my windows, while my phone reports a PathAccessException: Creation failed, path = "SD Card directory" (OS Error: Permission denied, errno = 13). I searched up the issues #710 and it seems that correlates with this one.

I tried enabling android.permission.MANAGE_EXTERNAL_STORAGE for LocalSend in an app called App Ops but I couldn't find it and used Powershell to type this: .\adb shell appops set --uid org.localsend.localsend_app MANAGE_EXTERNAL_STORAGE allow. And also tried this as well:  

.\adb shell appops set --uid org.localsend.localsend_app MANAGE_EXTERNAL_STORAGE allow
.\adb shell "appops set --uid 'org.localsend.localsend_app' MANAGE_EXTERNAL_STORAGE allow"
.\adb shell pm grant org.localsend.localsend_app android.permission.MANAGE_EXTERNAL_STORAGE

I'm not a programmer by the way and used ChatGPT 3.5 to find out the problem and it said that "It appears that the prompt either appops, pm grant and android.permission.MANAGE_EXTERNAL_STORAGE permission are not recognized by your device or Android version". 

Android 8 only includes READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE in which are have been allowed access in both LocalSend app info and in App Ops standalone application. 

### To reproduce

2. Click on '...'
3. Scroll down to '...'

![localsend_app-23-12-16(15-47-29-369)](https://github.com/localsend/localsend/assets/153980173/03c98fb2-9e68-4c34-85e7-32c4232b9d15)

### Expected behavior

Sending in files through an external storage with an Android 8.

### Screenshots

![Localsend error](https://github.com/localsend/localsend/assets/153980173/ae5c9453-493a-4581-8384-309f3b8c0535)

### Desktop (please complete the following information)

Windows 10 Pro - version 10.0.19044 Build 19044
LocalSend version 1.12.0 (38)

### Smartphone (please complete the following information)

Asus Zenfone 5 ZE620KL
Android 8 (unfornately, I can't update it higher than that)

### Additional context

The localsend HTTPS logs can only be produce in windows in which the android can't.

**Comment by Tienisto** [comment]
Unfortunately, `MANAGE_EXTERNAL_STORAGE` is only available in Android 11 or higher.

LocalSend should have WRITE_EXTERNAL_STORAGE to support older Android versions.

It's weird that it still doesn't work

**Comment by plebius-lo3** [comment]
Any updates, please? I can't use localsend at all because of this error. My phone's internal storage is too low to receive the files that I'm sending. Some tips or helpful tricks would be nice.

**Comment by zimulili** [comment]
I tested upgrading my Android 10 to Android 11, and it solves this problem.

**Comment by plebius-lo3** [comment]
> I tested upgrading my Android 10 to Android 11, and it solves this problem.

My phone's already updated to Android 11

**Comment by chendi2** [comment]
I encountered the same problem
