### ISSUE TITLE
Possibly Necessary: Transition to Newer Version Number?

### ISSUE THREAD

**Issue by ooghry** [localsend/localsend#1068]
I think this number should be changed to `1.13.1`:
https://github.com/localsend/localsend/blob/df50a3265a993aec986e5c672c78a67322dc008d/scripts/compile_windows_exe-inno.iss#L7

**Comment by Tienisto** [comment]
Fixed in https://github.com/localsend/localsend/commit/78b90d3c0f8ca7c6975348a8b50cac7497571bbb
