### ISSUE TITLE
我觉得文档中构建那里有个错误

### ISSUE THREAD

**Issue by nesteiner** [localsend/localsend#1078]
我记得直接 flutter build 是构建 debug 版本，得需要 flutter build --release 构建 release 版本，文档里是不是弄错了

**Comment by Tienisto** [comment]
`flutter build` defaults to `release`: https://docs.flutter.dev/deployment/android#build-an-app-bundle

**Comment by nesteiner** [comment]
哦，抱歉，我把 flutter build 和 flutter run 混淆了
