### ISSUE TITLE
dll missning in windows 

### ISSUE THREAD

**Issue by FreeH02** [localsend/localsend#1086]
### Describe the bug

vcruntime140_1.dll is not included in the latest Windows build. 
To run LocalSend, you have to install Microsoft Visual c++ 2015-2022 Redistributable or manually download vcruntime140_1.dll and put it in the LocalSend applicant folder.

### To reproduce

1. Reinstall windows.
2. Install the latest version of LocalSend.
3. Open LocalSend.

### Expected behavior

Open the applicant.

### Desktop (please complete the following information)

Windows 11

**Comment by Darrenpig** [comment]
# install Microsoft Visual c++ 2015-2022 Redistributable
## https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by Temacc0531** [comment]
https://github.com/localsend/localsend/issues/682
