### ISSUE TITLE
Send directory along with files in the directory

### ISSUE THREAD

**Issue by anaxonda** [localsend/localsend#1089]
### Is your feature request related to a problem? Please describe.

In localsend I can easily send the content of a directory, but I would prefer to send those files *in the directory* that they came in.

### Describe the solution you'd like

Add an option to send the directory, not just the files in the directory.

### Additional context

Sorry if this is already possible to do, I have not figured it out if so.

**Comment by agil3st** [comment]
Is this the feature are you looking for? If it so, I believe it is currently possible to send a **Directory/Folder** alongside with all the files in it. Just tested and all working good.
![Screenshot 2024-01-20 110435](https://github.com/localsend/localsend/assets/29949806/ce8e9fd0-8e1d-4b8a-b1b2-e6e7df931951)

**Comment by anaxonda** [comment]
You're right. I just did some tests and it does appear to be working, not sure what was happening before. However now I am not receiving all the contents of the directory, that might be another issue.
