### ISSUE TITLE
Quickly clear selection

### ISSUE THREAD

**Issue by chenxuan353** [localsend/localsend#1091]
### Is your feature request related to a problem? Please describe.

Cannot be cleared quickly after selection

### Describe the solution you'd like

Add a clean selection button to the main interface

**Comment by Tienisto** [comment]
Open the selected files, then there is a "Delete All" button

**Comment by chenxuan353** [comment]
> Open the selected files, then there is a "Delete All" button

I'd like it to be simpler, like being able to quickly handle additions, deletions and edits on the same page.

**Comment by Caesarovich** [comment]
I join @chenxuan353 on this issue. Whilst having to click "only one more" button isn't that bad, it would be better UX if it was directly next to the Add / Edit buttons.

After refreshing myself on Flutter I managed to add the desired button (Mostly copy-pasted the existing one). Here's the current iteration:
![Screenshot from 2024-04-02 14-21-23](https://github.com/localsend/localsend/assets/38408878/78b9fc2f-9122-4685-bfbf-65f5bcba7c50)

Now I'd like feedback from @Tienisto and the community on where/how to display and implement this button.

My screenshot above is what I personally feel to fit the best. But we can have a different color:
![Screenshot from 2024-04-02 14-24-21](https://github.com/localsend/localsend/assets/38408878/4547b302-c2e4-4326-8719-15a888d7f6e8)

We could also not space it from the other buttons:

![Screenshot from 2024-04-02 14-25-29](https://github.com/localsend/localsend/assets/38408878/fd564d4c-08f5-4f95-8cd3-c197e38316ef)

Or even make it an icon button ?

I'd advocate for it to be spaced from the other buttons though. From a UX stand point I feel it is bad to have a "destructive" action right next to others, it would be bad for the user to miss-click on it.

I'll open a PR once a design is agreed upon.

**Comment by Tienisto** [comment]
I have received a similar user request that I also quite like:

![unnamed](https://github.com/localsend/localsend/assets/38380847/56f70673-6efe-4f55-9594-b424264ea789)

**Comment by Caesarovich** [comment]
Hi, thanks for your reply @Tienisto . Here's my latest iteration following your message:

https://github.com/localsend/localsend/assets/38408878/0f05dd53-e055-4a96-b5ba-65d4903b6a36

**Comment by chenxuan353** [comment]
> @chenxuan353 I think you can close this issue :)

Thank you!
