### ISSUE TITLE
Add support to Raspberry 4b/armhf

### ISSUE THREAD

**Issue by haai-team** [localsend/localsend#1093]
### Is your feature request related to a problem? Please describe.

When I tried to install LocalSend-1.13.1-linux-arm-64.deb, OS said CPU arch is not armhf.

pi@rasp4b:~/Desktop $ sudo dpkg -i ./LocalSend-1.13.1-linux-arm-64.deb 
dpkg: 处理归档 ./LocalSend-1.13.1-linux-arm-64.deb (--install)时出错：
 软件包体系结构(arm64)与本机系统体系结构(armhf)不符
在处理时有错误发生：
 ./LocalSend-1.13.1-linux-arm-64.deb

OS info:
pi@rasp4b:~/Desktop $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"

### Describe the solution you'd like

Add support to Raspberry 4b/armhf. Many many thanks!

**Comment by Tienisto** [comment]
Only ARMv8 (64bit) ist supported.
Please compile the app yourself if you want to use it on more niche architectures.
