### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by agil3st** [localsend/localsend#1098]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Is it possible to change all the icons to [Flutter TablerIcons](https://pub.dev/packages/flutter_tabler_icons) which has better UI and might be matched with current design.

### Describe alternatives you've considered

If it takes you much time to do it, how can I contribute to apply this feature?

### Additional context

Please give a reason if this request is not necessary.

**Comment by Tienisto** [comment]
The current icons match the Material Design which is used in the app. I think it is subjective if the "TablerIcons" are better or not.
