### ISSUE TITLE
[Android] [Bug report] FAT32-invalid characters result in a failed transfer

### ISSUE THREAD

**Issue by Pixadus** [localsend/localsend#1101]
### Describe the bug

When attempting to send a file that contains characters considered invalid by FAT32 including `* / : < > ? \ | + ; = []`, the file will be unable to send with error 500. 

### To reproduce

1. Create a file (such as <hello>.txt or Part1:TheTest.txt)
2. Send the file to an Android device running Android 13
3. Transfer will "finish", but then return error 500 afterward.

### Expected behavior

It was not immediately apparent that the file naming was an issue - this is more a problem with Android providing vague error messages when invalid file names are supplied. 

One idea is that LocalSend's Android version could sanitize file names of FAT32 invalid characters. 

### Desktop (please complete the following information)

- Host OS: Linux

### Smartphone (please complete the following information)

- Version: 1.13.1
- Android 13

**Comment by Tienisto** [comment]
Fixed in #1336
