### ISSUE TITLE
Feature request : add authorized auto-save device

### ISSUE THREAD

**Issue by xmaxrayx** [localsend/localsend#1106]
### Is your feature request related to a problem? Please describe.

Hi . my network has a lot of people , is there any chand to auto-save only my device? like pair them one time and auto-save paired devices only. 

### Describe the solution you'd like

1. do password, pin for pairing.
2. add auto-save for paired app only
3. have "device list" to add or remove some device
4. add auto bluck other request outside paired device.

**Comment by zazitufu** [comment]
我也非常希望有这个功能，就是A端可以设个简单密码，然后局域网内任意B/C/D端可以保存A端的简单密码，然后发送到A端时可以自动保存。

其他端没有A端这个密码的，发送到A端就需要手动确认接受。

**Comment by ArtexJay** [comment]
Or they could do like what EasyJoin has done which is to add the device as their favorite or trusted device and whatever that device sends is auto accepted and saved.

**Comment by Tienisto** [comment]
Closing this in favor of #1384
