### ISSUE TITLE
Drag and Drop not working on Linux Mint

### ISSUE THREAD

**Issue by exercismnow** [localsend/localsend#1130]
### Describe the bug

Drag and Drop works on Windows and Fedora Gnome, but doesn't work on Linux Mint

### To reproduce

1. Open LocalSend
2. Open Neno (Linux Mint's file manager)
3. Drag file from Nemo over the LocalSend window
4. Observe that LocalSend recognizes I'm holding files over it, as it displays the message "Place items to share."
5. Drop the items by releasing the mouse button
6. Observe that no items have been queued for sharing

### Expected behavior

I expected drag-and-drop to work on Linux Mint, like it does for other OSes

### Desktop (please complete the following information)

- OS: Linux Mint
- Version: 21.2, 21.1

**Comment by Caesarovich** [comment]
I am on Linux Mint 21.3 x86_64 and I can't reproduce this issue.

**Comment by Shihabus-Sakib-Rad** [comment]
Same problem on Linux Mint 21.3 Virginia

**Comment by Tienisto** [comment]
I believe that LocalSend doesn't have sufficient permissions to read the dropped file. Can you try to move your desired file into the "Downloads" folder and then drop it from there?

**Comment by Caesarovich** [comment]
> I believe that LocalSend doesn't have sufficient permissions to read the dropped file. Can you try to move your desired file into the "Downloads" folder and then drop it from there?

@Tienisto Should we add handling for such cases ? Like a Snackbar alert saying "LocalSend can't read this file..."

**Comment by Tienisto** [comment]
Yes, I guess. But I am not sure if my assumption is correct @Shihabus-Sakib-Rad

**Comment by exercismnow** [comment]
> I believe that LocalSend doesn't have sufficient permissions to read the dropped file. Can you try to move your desired file into the "Downloads" folder and then drop it from there?

Thanks for this observation @Tienisto !

I tried this, and observed the following:
- Drag-and-drop works on files from Downloads
- Drag-and-drop doesn't work on files from Documents, Pictures, Music, Videos, or the Home folder

Any idea how if LocalSend can handle this at install, or if I'd have to tweak something in Linux Mint, or if moving files to Downloads is the only workaround?

**Comment by Tienisto** [comment]
Did you install LocalSend via flatpak? Flatpak only allow LocalSend to read and write to Downloads folder by default. You may need to allow full disk access.

**Comment by exercismnow** [comment]
> Did you install LocalSend via flatpak? Flatpak only allow LocalSend to read and write to Downloads folder by default. You may need to allow full disk access.

Yup, I installed it via Flatpak. It seemed like the best choice to have automatic updates :)

I just looked it up, and it seems like Flatseal is a recommended permissions manager for Flatpak apps. Is that my best option?
https://github.com/tchx84/Flatseal

**Comment by Tienisto** [comment]
See #256
