### ISSUE TITLE
Android version cannot receive files

### ISSUE THREAD

**Issue by yarray** [localsend/localsend#114]
F-droid version 1.5.2 (16)

 The Android client cannot receive files from Mac/Windows clients (completed with errors and no file resides on Android). Sending texts is ok though.

The issue can be manually fixed by allow NO_ISOLATED_STORAGE and MANAGE_EXTERNAL_STORAGE with App Manager.

**Comment by Tienisto** [comment]
Do you know why these permissions are needed?

**Comment by yarray** [comment]
@Tienisto Unfortunately I'm not familiar with Android development and do not understand what actually happens. But I noticed that App Manager reported the two permissions were "denied" 1 minutes ago.

**Comment by Tienisto** [comment]
Thanks for your feedback. What Android version do you have?

**Comment by yarray** [comment]
Android 11
