### ISSUE TITLE
Impossible to build on MacOS

### ISSUE THREAD

**Issue by TheJavaGuy** [localsend/localsend#1149]
### Describe the bug

I wanted to contribute by translating LocalSend to Serbian. Unfortunately I couldn't even build the project on MacOS Sonoma 14.2.1.

### To reproduce

1. Clone the project
2. Execute:
```bash
cd app
fvm flutter pub get
sudo gem install drb -v 2.0.6 # otherwise cocoapods won't install on ruby 2.6.10
sudo gem install activesupport -v 6.1.7.6 # otherwise cocoapods won't install on ruby 2.6.10
sudo gem install cocoapods
fvm flutter run
```
3. Observe error as in screenshot below

### Expected behavior

The project builds.

### Screenshots

<img width="1387" alt="image" src="https://github.com/localsend/localsend/assets/11942401/dcebb2d2-ada0-4229-a32a-04726f5cc544">

### Desktop (please complete the following information)

- OS: MacOS Sonoma, Version: 14.2.1

**Comment by Aed-p** [comment]
I also encountered the same problem

**Comment by Tienisto** [comment]
Building for macOS requires a developer license by Apple AFAIK

**Comment by ShlomoCode** [comment]
> @Tienisto Even for compiling/running locally I need developer license? That's really fierce by Apple 😢

it does not cost money

**Comment by nebojsatomic** [comment]
I provided Serbian translation a few days ago, before I even saw this issue :)
Just to let you know if you are still thinking about translating @TheJavaGuy

**Comment by TheJavaGuy** [comment]
Since it looks like Apple dev account could be obtained for free (and @nebojsatomic already did what I wanted to do anyway) I'm closing this issue.
