### ISSUE TITLE
Windows context menu (right click menu)

### ISSUE THREAD

**Issue by dr-baba** [localsend/localsend#115]
Hi, I love the application. This is a feature request.

Can you add this program into the Windows 10/11 context menu so you can quickly right click a file and share?

**Comment by techgamers2** [comment]
yes pls add this option then finally i can switch from send anywhere .. btw love ur work i tried many but ur app was the one i ws looking for :) keep it up bro

**Comment by Tienisto** [comment]
Flutter currently doesn't offer an easy way to add context menus.

**Comment by dancojocaru2000** [comment]
This could possibly be implemented by adding a shortcut to the app in the SendTo folder, and reading the path to the file/folder from the command line arguments (in the `main` function).

**Comment by TSnatch72** [comment]
> This could possibly be implemented by adding a shortcut to the app in the SendTo folder, and reading the path to the file/folder from the command line arguments (in the `main` function).

I came to open a issue specifically asking for this implementation. Big support

**Comment by tahayparker** [comment]
any update on this? this issue has been stale for 4 months now

**Comment by swanknight** [comment]
> > This could possibly be implemented by adding a shortcut to the app in the SendTo folder, and reading the path to the file/folder from the command line arguments (in the `main` function).
> 
> I came to open a issue specifically asking for this implementation. Big support

+1

**Comment by tahayparker** [comment]
Hi Tien, when can we expect this feature to be part of a release?

**Comment by Tienisto** [comment]
Around next week

**Comment by tahayparker** [comment]
Thank you very much Tien
I would like to express my gratitude, and I recognize the effort that goes into implementing such a feature.

**Comment by ClareBDragons** [comment]
I'd also like to add my thanks for the time and effort.

**Comment by PandaFiredoge** [comment]
能否支持Win11新版右键菜单的系统分享？
Can the system sharing of the new right-click menu of Win11 be supported?
![image](https://github.com/user-attachments/assets/3d9ab91f-73b3-4602-bcdc-9ba475635e27)

**Comment by tahayparker** [comment]
Hi @Tienisto
I believe that this issue was fixed and is part of v1.15.0
However, I do not see the context menu entry

**Comment by Tienisto** [comment]
@tahayparker you need to start the app at least once, optionally there is a setting hidden under the "advanced" toggle where you can enable context menu.
Also, LocalSend is available under "Send to" not as an share option in Windows 10/11

**Comment by tahayparker** [comment]
i see, i had disabled the "send to" as i didn't need it
would it be possible to create the entry in the "main" context menu rather than in the "send to" submenu?

**Comment by lsq** [comment]
> @tahayparker you need to start the app at least once, optionally there is a setting hidden under the "advanced" toggle where you can enable context menu. Also, LocalSend is available under "Send to" not as a share option in Windows 10/11

![localsend_2024-08-11_09-28-25](https://github.com/user-attachments/assets/467d7c75-be99-459e-a3d2-599892689947)
i enable it, but Shortcuts in the "Send To" folder not appearing in the menu.

**Comment by Downmars** [comment]
> i see, i had disabled the "send to" as i didn't need it would it be possible to create the entry in the "main" context menu rather than in the "send to" submenu?

You can try manually modifying the registry to add LocalSend's sending function to the main context menu of the right-click.

**Comment by tahayparker** [comment]
> You can try manually modifying the registry to add LocalSend's sending function to the main context menu of the right-click.

unforuantely, that is beyond my capabilities at the moment

**Comment by Downmars** [comment]
I have tried to modify the registration expression to put the send directive in the context menu, you can try to create a txt document type the following (if you localsend is the default installation address) and change the txt suffix to reg.
:Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\LocalSend]
@="Send with LocalSend"
"Icon"="C:\\Program Files\\LocalSend\\localsend_app.exe"

[HKEY_CLASSES_ROOT\*\shell\LocalSend\command]
@="\"C:\\Program Files\\LocalSend\\localsend_app.exe\" \"%1\""

[HKEY_CLASSES_ROOT\Directory\shell\LocalSend]
@="Send with LocalSend"
"Icon"="C:\\Program Files\\LocalSend\\localsend_app.exe"

[HKEY_CLASSES_ROOT\Directory\shell\LocalSend\command]
@="\"C:\\Program Files\\LocalSend\\localsend_app.exe\" \"%V\""

[HKEY_CLASSES_ROOT\Directory\Background\shell\LocalSend]
@="Send with LocalSend"
"Icon"="C:\\Program Files\\LocalSend\\localsend_app.exe"

[HKEY_CLASSES_ROOT\Directory\Background\shell\LocalSend\command]
@="\"C:\\Program Files\\LocalSend\\localsend_app.exe\" \"%V\""

**Comment by Downmars** [comment]
> > 您可以尝试手动修改注册表，将 LocalSend 的发送功能添加到右键单击的主上下文菜单中。
> 
> 遗憾的是，这超出了我目前的能力范围

I have tried to modify the registration expression to put the send directive in the context menu, you can try to create a txt document type the following (if you localsend is the default installation address) and change the txt suffix to reg.
:Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\LocalSend]
@="Send with LocalSend"
"Icon"="C:\\Program Files\\LocalSend\\localsend_app.exe"

[HKEY_CLASSES_ROOT\*\shell\LocalSend\command]
@="\"C:\\Program Files\\LocalSend\\localsend_app.exe\" \"%1\""

[HKEY_CLASSES_ROOT\Directory\shell\LocalSend]
@="Send with LocalSend"
"Icon"="C:\\Program Files\\LocalSend\\localsend_app.exe"

[HKEY_CLASSES_ROOT\Directory\shell\LocalSend\command]
@="\"C:\\Program Files\\LocalSend\\localsend_app.exe\" \"%V\""

[HKEY_CLASSES_ROOT\Directory\Background\shell\LocalSend]
@="Send with LocalSend"
"Icon"="C:\\Program Files\\LocalSend\\localsend_app.exe"

[HKEY_CLASSES_ROOT\Directory\Background\shell\LocalSend\command]
@="\"C:\\Program Files\\LocalSend\\localsend_app.exe\" \"%V\""
