### ISSUE TITLE
Do not send text in file

### ISSUE THREAD

**Issue by sonichy** [localsend/localsend#117]
Text is a message, no need to send in file.

**Comment by Tienisto** [comment]
You mean in QuickSave mode?

**Comment by sonichy** [comment]
QuickSave mode? Yes. Any difference ?

**Comment by DinoDevel** [comment]
> Text is a message, no need to send in file.

In a file-transfer app  everything is a file. To send messages you have thousands of messengers out there. Better to have a least one decent file-transfer app then one more crippled messenger.

**Comment by Tienisto** [comment]
This is actually already implemented in the upcoming 1.7.0 release.

Like in non-QuickSave mode, a payload must only contain a single text file to be treated as a message.

**Comment by Tienisto** [comment]
Duplicate of #67
