### ISSUE TITLE
安卓4.4版本的，无法安装

### ISSUE THREAD

**Issue by leexiao2021** [localsend/localsend#1170]
### Is your feature request related to a problem? Please describe.

软件非常的好用，但是我的车机是安卓4.4版本的，无法安装，作者是否考虑匹配，因为目前还有为数众多的车机和电视使用安卓4.4版本，谢谢！

### Describe the solution you'd like

匹配安卓4.4版本

**Comment by Tienisto** [comment]
There will be no Android 4.4 support. This is a limitation by Flutter.
