### ISSUE TITLE
My iPhone can't be seen by any device, but can send files

### ISSUE THREAD

**Issue by g1sbi** [localsend/localsend#1179]
### Describe the bug

I'm testing with a Mac, Windows PC and iPhone. The iPhone can send files to everyone, the Mac and Windows can send and receive, but my iPhone can't be seen by neither the Mac nor PC.

### To reproduce

1. Open Localsend on iPhone and PC
2. Try to receive a file on iPhone
3. Try to locate the iPhone on the PC, but can't

### Expected behavior

I should be able to see the iPhone appear as a device on both computers.

### Desktop (please complete the following information)

- OS: Windows 11, 10.0.22631 Build 22631
- Version: 1.14.0

### Smartphone (please complete the following information)

- Device: iPhone 15 Pro Max
- OS: iOS 17.2.1
- Version: 1.14.0

**Comment by Tienisto** [comment]
You can try to press on the "Scan/Sync" button on Windows / Mac. Then it might be also detected by the iphone

**Comment by World-Homeostasis** [comment]
You can try to directly input the IP address.

**Comment by Tienisto** [comment]
Closing this due to #527
