### ISSUE TITLE
Error when tansferring files with special characters.

### ISSUE THREAD

**Issue by tuqueque** [localsend/localsend#1180]
### Describe the bug

When I try to Drag&Drop some file with special characters  (ñ, |, :, 🙂) into LocalSend, it doesn't do anything... and even worse, if I Drag&Drop a folder with files inside that have special characters, the transfer takes place, but at the end of the file transfer, throws an error.

### To reproduce

Either have a file with special characters or a folder with files inside that have especial characters and try to transfer it with LocalSend.

### Expected behavior

Transfer the file!

### Desktop (please complete the following information)

OS: Manjaro (Linux).
LocalSend version: 1.14.0

**Comment by tuqueque** [comment]
The target OS is Windows, yes... Although, I don't see why when I drag and drop a file with special characters into LocalSend, it doesn't do anything but if I place the file into a folder (that doesn't have special characters) the Drag&Drop function does work... and also, I really doubt that I'll have any problem if I send files with special characters through other methods like USB drive or even croc ( https://github.com/schollz/croc )... I can do the tests if you want.

So... is this fixable?

**Comment by Tienisto** [comment]
I just sent a file named `ñ.png` and `🙂.png` and it did worked. But when adding a `|` it didn't because Windows doesn't support this character.

I don't know how other solutions work but I can imagine that they replace unsupported characters.

**Comment by tuqueque** [comment]
Does it support Drag&Drop into LocalSend? (dragging and dropping files with special characters into LocalSend's window).

**Comment by CorvinYu** [comment]
i meet the question too.
![image](https://github.com/localsend/localsend/assets/138097462/ce0062c9-12c8-4451-a15f-f64eb535569c)

whishing sort.

**Comment by Tienisto** [comment]
Fixed in #1336
