### ISSUE TITLE
Quickly open saved directory

### ISSUE THREAD

**Issue by hadis91** [localsend/localsend#1189]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

no

### Describe alternatives you've considered

I hope to be able to quickly open the directory for receiving files after receiving them，thanks

**Comment by Tienisto** [comment]
You can click on the "download directory" link on the top of the screen during transfer (and also after the transfer)

**Comment by Howie-Z** [comment]
I hope to have a quick access feature to open the download directory either in the system tray or in the software interface. Currently, the link to the download directory is located in the third-level menu of the transfer history, which is inconvenient to access every time. I hope the team can add this feature.

> You can click on the "download directory" link on the top of the screen during transfer (and also after the transfer)
