### ISSUE TITLE
Feature request: share via the same LAN

### ISSUE THREAD

**Issue by xingyunjohn1** [localsend/localsend#1190]
### Is your feature request related to a problem? Please describe.

while my desktop connect my router via wire and my phone connect via WIFI to the same network, the software cannot discover and share.

### Describe the solution you'd like

Try to identify all devices in the network no wonder the connection method.

**Comment by EDIflyer** [comment]
This works fine for me - no issues at all transferring across wired/wireless LAN - are you sure you don't have any ports blocked? Is the firewall open OK on your desktop?

**Comment by Tienisto** [comment]
Discovery issues should be commented on #527.
Duplicate of #527
