### ISSUE TITLE
Feature request: Can we have a Command Line Interface for automation and efficiency?

### ISSUE THREAD

**Issue by anasouardini** [localsend/localsend#1206]
### Is your feature request related to a problem? Please describe.

Not a problem, but it could be considered as a limitation in terms of automation.

## Why?
These are personal reasons, and I don't know if there are people who may experience the same issues:
- I have a Desktop PC and I, sometimes, need to have to get a way from it while some process is doing some job in the background, but at the same time, I don't want to miss the result of the background process/job or if there were any problems while I'm away from it. A CLI to automate pushing notifications to my phone would be really nice in such scenario.
- I also have this home server that might stop working for some reason, etc (you get the idea)

Now, I'm already doing this using hacks, but it would be so nice to have be able to just type "restart" on my phone to restart the background compiling/building process in my PC while I'm eating or something.

## thanks
Thanks, in advance, for considering my needs. Sorry if this feature is out of scope.

**Comment by thoschworks** [comment]
I think, the headless mode #11  is what you need.
