### ISSUE TITLE
Localisation problem, after adding new language Exception is raised

### ISSUE THREAD

**Issue by nebojsatomic** [localsend/localsend#1209]
### Describe the bug

After adding new translation file,  /app/assets/i18n/strings_rs.i18n.json  in my case, i ran the application the first time, and everything went ok. 
According to the Contributing guide I executed 
```
flutter pub run slang
``` 
Then I started the app the second time with 'flutter run', and chose the language to 'Srpski' ( Serbian ),
after that got an error that you can see on the screenshot.

In the terminal there is the following information:
```
══╡ EXCEPTION CAUGHT BY WIDGETS ╞═══════════════════════════════════════════════════════════════════
The following message was thrown:
Warning: This application's locale, rs, is not supported by all of its localization delegates.

• A CupertinoLocalizations delegate that supports the rs locale was not found.
• A MaterialLocalizations delegate that supports the rs locale was not found.

The declared supported locales for this app are: en, ar, bn, ca, cs, da, de, el, es_ES, eu, fa,
fil_PH, fr, he, hu, id, it, ja, km, ko, ne, nl, pl, pt_BR, rs, ru, sv, th, tr, uk, ur, vi, zh_CN,
zh_HK, zh_TW

``` 

### To reproduce

1. Pull the newest code ( main branch contains the strings_rs file )
2. Run the app the first time, see that base language is working fine, and other languages too, other than Serbian, then exit
3. Run 'flutter pub run slang'
4. Start the app once again, go to Settings and choose Srpski from the Language Menu.

### Expected behavior

Expected to see Serbian translation in the UI.

### Screenshots

![Screenshot from 2024-03-13 10-08-34](https://github.com/localsend/localsend/assets/1038256/f608202e-3396-4fe5-be0d-ad87405f13ca)

### Desktop (please complete the following information)

- OS: Ubuntu 20.04

**Comment by Tienisto** [comment]
It seems that `sr` should be used instead of `rs`: https://localizely.com/language-code/sr/

**Comment by nebojsatomic** [comment]
Hm, 'sr' makes more sense.But I could have sworn that it was 'rs' written on the link that was referenced in a Readme.md for locale.

However, 'sr' works.

Will update the file name first in my fork, and then create another PR.

Thanks @Tienisto

**Comment by nebojsatomic** [comment]
One more thing @Tienisto  :)
In order to get app starting the first time ever without errors, I had to change app/pubspec.yaml : 
 
![Screenshot from 2024-03-13 15-18-28](https://github.com/localsend/localsend/assets/1038256/65797892-aa51-4728-9b97-ba89f2326b4c)

I did not put it in a PR #1211 since it is not related to contributing to translation.
