### ISSUE TITLE
Transfer directories preserving structure

### ISSUE THREAD

**Issue by DinoDevel** [localsend/localsend#121]
Hello! This is a feature request.
While transferring files one by one is better than nothing, obviously it's not a complete file-transfer solution. There is many cases where one need to transfer directory between devices along with sub-directories preserving structure. Examples are:
- Music directory with structure sorted by artist\year\album.
- Photos directory with structure sorted by date\place.
- Books  directory with structure sorted by author\year.
- etc
So  It would be nice to have not only single-file transfer but also a directory-tree transfer feature.
Thanks!

**Comment by Tienisto** [comment]
Implemented. Will be released in the coming `v1.9.0` update.
