### ISSUE TITLE
Feature request:Add swiping gesture

### ISSUE THREAD

**Issue by Ahhh9h** [localsend/localsend#1218]
### Is your feature request related to a problem? Please describe.

It would be more perfect if added.

### Describe the solution you'd like

Add swiping gesture function to all platforms.
加入滑动切换选项卡功能。

### Describe alternatives you've considered

.

**Comment by sudhar08** [comment]
Hi @Ahhh9h can you please provide some Refrences for the feature you have mentioned

**Comment by Ahhh9h** [comment]
> Hi @Ahhh9h can you please provide some Refrences for the feature you have mentioned

Just swipe left/right to change to receive/send/settings

**Comment by Tienisto** [comment]
Thanks for the feature request.
Unfortunately, "swiping" is not considered good user experience anymore because it causes users to accidentally switch pages.
That's why popular apps abandoned this gesture.

**Comment by sudhar08** [comment]
That was a good idea 👍
