### ISSUE TITLE
两部手机之间可以互相看到，电脑和手机之间却看不到

### ISSUE THREAD

**Issue by canglaoshifu** [localsend/localsend#1219]
Two mobile phones can see each other, but not between the computer and the phone

**Comment by ittqqzz** [comment]
点击那个螺帽按钮，你要用“通过链接分享”，在浏览器里面访问局域网服务，就可以全平台使用了

**Comment by ittqqzz** [comment]
> Two mobile phones can see each other, but not between the computer and the phone


点击那个螺帽按钮，你要用“通过链接分享”，在浏览器里面访问局域网服务，就可以全平台使用了

**Comment by canglaoshifu** [comment]
还是不可以，难道是因为我双端都启用了VPN？

**Comment by kylin-lawliet** [comment]
如果电脑插了网线，又连了 WiFi 的话。要选一下网卡。
![image](https://github.com/localsend/localsend/assets/35247756/41509779-d3ab-4213-90f1-8cf2e7c7e55a)

**Comment by xiang0818** [comment]
> 如果电脑插了网线，又连了 WiFi 的话。要选一下网卡。 ![image](https://private-user-images.githubusercontent.com/35247756/315961438-41509779-d3ab-4213-90f1-8cf2e7c7e55a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTA3ODgsIm5iZiI6MTcxMzExMDQ4OCwicGF0aCI6Ii8zNTI0Nzc1Ni8zMTU5NjE0MzgtNDE1MDk3NzktZDNhYi00MjEzLTkwZjEtOGNmMmU3YzdlNTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE2MDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YzNmMTE1YWMwYmEzMGZmYWQyYTg5NjhmMjdjOTdlYzE3YTI5Y2I4MmFlYzI3NGI1YmQ2ODQwZDUxNTBhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ELODW8pk7M0aHQ36JbFgSef50ULor5HjhXVDZmnZ-kE)

没啥用，手机还是不行。发送不了

**Comment by yishangfei** [comment]
win得设置公有网络
![image](https://github.com/user-attachments/assets/ab30c042-5661-4400-9f7a-029fe3865a35)
