### ISSUE TITLE
Save last IP when send to custom IP

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#123]
When device could not be found, we need to enter the IP address manually.

Save up to 5 IP addresses and show them in the dialog. (don't persist them as we only need them temporarily)

**Comment by SelaseKay** [comment]
Would love to work on this. Can you assign it to me?

**Comment by Tienisto** [comment]
Hi, unfortunately, this has already been implemented :)

**Comment by SelaseKay** [comment]
Oh ok. Cool.

**Comment by Tienisto** [comment]
Added in `v1.7.0`
