### ISSUE TITLE
Doesn't start hidden even though it's enabled

### ISSUE THREAD

**Issue by maggotb** [localsend/localsend#1231]
### Describe the bug

During Windows 7 staartup this window appears

![34319789](https://github.com/localsend/localsend/assets/62154223/67095388-2fac-437c-b25d-d84c18d512a4)

Even though "Autostart: Start hidden" is enabled

![27343892](https://github.com/localsend/localsend/assets/62154223/fcda1a0e-3d14-4954-b0ab-3b83d2bbd157)

### To reproduce

On Windows 7 enable "Autostart: Start hidden" then restart Localsend 

### Expected behavior

Localsend should start minimized to tray

### Desktop (please complete the following information)

Windows 7 Ultimate

**Comment by AlphaNERD-** [comment]
This issue also occurs on my Windows 10 PCs at home running 1809 and later, my GPD Win Mini with Windows 11 23H2 and my MacBook Pro 2019 at work running macOS Sonoma.

**Comment by RPXbr** [comment]
I created a quick solution in Windows until this bug is fixed. I hope this helps:

https://github.com/localsend/localsend/issues/464#issuecomment-2156997926

**Comment by conualfy** [comment]
I can confirm on Ubuntu 24.04 that it does not start hidden, even though the option is activated.

![2024-07-06-17:03:12_001-LocalSend](https://github.com/localsend/localsend/assets/475091/db512e38-5afd-4d04-bf99-e4b33168fddc)
the option is activated.
