### ISSUE TITLE
Feature request: start LocalSend in menu bar MacOS

### ISSUE THREAD

**Issue by Tsjoep** [localsend/localsend#1242]
### Is your feature request related to a problem? Please describe.

On login, LocalSend starts as an open window in the dock.

### Describe the solution you'd like

On login, start LocalSend minimized in the menu bar instead as an open window in the dock.

### Additional context

For example, just as Google Drive starts minimized in the menu bar on login.

**Comment by Mennaruuk** [comment]
This is a good feature request, but I hope it doesn't become the default behavior, since some LocalSend users will be confused why no window appears after launching the program and resort to another file-sharing app. Hopefully there is an option to enable/disable it as needed.

**Comment by Tienisto** [comment]
Added in #1467

**Comment by Tsjoep** [comment]
> Added in #1467

I don't see an option to enable this on the MacOS app? Am I missing something?

**Comment by Tienisto** [comment]
@Tsjoep sorry, this only works in the DMG version or homebrew. If you installed LocalSend via App Store, then it currently does not work

**Comment by Tsjoep** [comment]
**Feature request update**

As of now, LocalSend can start minimized (hidden) in the dock - but not in the menu bar.
It can however be minimized to the menu bar when closing.

Would it be possible to add an option to autostart LocalSend hidden in the menu bar instead of the dock?
