### ISSUE TITLE
readme: link to nix package is labeled "NixOS"

### ISSUE THREAD

**Issue by lolbinarycat** [localsend/localsend#1258]
### Describe the bug

nix can be used on any linux distro (and even some non-linux OSes, like MacOS/darwin), not just nixos.

the correct label for this link would be "nixpkgs", not "nixos".

### To reproduce

go to https://github.com/localsend/localsend?tab=readme-ov-file#download

### Expected behavior

the nixpkgs package should be labeled "nixpkgs"

### Additional context

idk if this should be a bug report, but there is no "documentation issue" template.

**Comment by Tienisto** [comment]
Sounds reasonable

**Comment by Caesarovich** [comment]
@lolbinarycat You can now close this issue as it as been solved :)
