### ISSUE TITLE
Big file in Android app

### ISSUE THREAD

**Issue by a123455392** [localsend/localsend#129]
- When transfer big file, e.g. 700MB avi file, Android app takes about 10 seconds to show up file name in "Selection".
- Also, transfer speed is very slow.
  - Android to Windows: 50 Mbps.
  - Windows to Android: 100 Mbps.
  - When using Samsung Flow or Dex, the speed is up to about 500 Mbps in WIFI 5 or 6. FTP speed is about 600 Mbps.

**Comment by Yuslendo** [comment]
I don't know the transfer speed but I'm having the big file issue too. When I want to send it, I press to the document button not share, and wait a while for the file I select from the Samsung Gallery application. When I receive a large file, I have to wait a bit for Android, while the iPhone shows that the transfer is finished without any problems. Also, after I got the file, I exited the application and closed it, but I got the "application crashed" warning 3 times.

**Comment by E0697** [comment]
I think the app copies the files to temporary cache first, which is why it takes some time.
Am I correct about this?

**Comment by Tienisto** [comment]
Yes, you are correct. This happens on Android and maybe on iOS. Currently, I cannot change the behaviour because the file picker is not implemented by me.

**Comment by Tienisto** [comment]
In `v1.8.0` there is now a loading indicator, so that you know that the file is copied to the cache.
