### ISSUE TITLE
上架华为应用商城

### ISSUE THREAD

**Issue by senique** [localsend/localsend#1298]
### Is your feature request related to a problem? Please describe.

你好，请问有没有考虑上架华为应用商城，便于及时收到更新和反馈问题，参考: https://developer.huawei.com/consumer/cn/doc/app/agc-help-releaseapkrpk-0000001106463276

### Describe the solution you'd like

也可以考虑授权，代为发布

**Comment by TJNOV** [comment]
不用想了，上架要备案的，你看看有哪些开源应用上架的

**Comment by Arturia169** [comment]
想法是好的但需要备案

**Comment by LanYunDev** [comment]
不建议在如何国内任何平台上架,缘由: 非法

**Comment by senique** [comment]
thks for all
