### ISSUE TITLE
Bug report: couldn't transfer files to android at certain times

### ISSUE THREAD

**Issue by cscnk52** [localsend/localsend#130]
### Describe the bug

when other device transfer files to Android app, the app show nothing only with white

### To reproduce

1. transfer files to Android
2. Android device show nothing, see screenshot

### Expected behavior

when transfer files from Windows to Android, Android phone show option correctly.

### Screenshots

![S30207-10211457](https://user-images.githubusercontent.com/63527850/217131712-a7b9b9e9-0e99-493d-ad4e-ed4ccffcbda8.png)

### Desktop (please complete the following information)

- OS: Windows 11 22H2
- Browser: Firefox
- Version: 1.6.1

### Smartphone (please complete the following information)

- Device: MEIZU 18s
- OS: Flyme 9.3.1.0A, Android 11
- Broswer: Fennec, Ungoogled Chromium, via
- Version: 1.6.2

### Additional context

only show in these situation
1. when transfer files from Windows(other system unknown) to android
2. quick save is off

**Comment by CaoKang-David** [comment]
I’m having the same issue, my smartphone is XIAOMI K40 pro with MIUI 13.0.7, Android 12, The desktop OS is windows 11 22H2.

**Comment by Tienisto** [comment]
This seems like a bug in `v1.6.1` using Chinese app language. See #37

**Comment by cscnk52** [comment]
yes, thank for reply, but app version of F-doird still in 1.6.1, please update
