### ISSUE TITLE
macOS Improvments

### ISSUE THREAD

**Issue by SABRE1982** [localsend/localsend#1308]
### Is your feature request related to a problem? Please describe.

Adding Localsend to macOS login items starts the app fully, it would be great to have it auto-minimise to the menu bar. Also, if you want to share an item, you need to open the app instead of selecting from the share picker.

### Describe the solution you'd like

Start app on login with an option to auto minimise to the menubar. Add Localsend extension so that it can be added to the macOS share picker.

### Describe alternatives you've considered

I haven't considered any alternatives.

**Comment by stagelevel** [comment]
+1 to all these things.

**Comment by ShlomoCode** [comment]
The share extension has already been done and will be included in the next release

**Comment by ShlomoCode** [comment]
The option to minimize at launch also already exists (in the dmg/homebrew version)
@Tienisto This issue should be closed
