### ISSUE TITLE
Feature request: It may look better if not using the default UI font of Windows

### ISSUE THREAD

**Issue by bamboo512** [localsend/localsend#131]
### Is your feature request related to a problem? Please describe.

Localsend looks terrible with __Segoe UI__, the default UI font of Windows.

**Segoe UI**
![image](https://user-images.githubusercontent.com/16702370/217177806-5a6698dc-ed42-4e40-8361-e3046f6146aa.png)

### Describe the solution you'd like

It is a splendid idea to change the UI font on Windows 11 into __Segoe UI Variable Display__ or __Inter__, etc. 

**Segoe UI Variable Display**
![image](https://user-images.githubusercontent.com/16702370/217175956-b43a73eb-6889-435d-a6dc-0f7aba091236.png)

**Inter**
![image](https://user-images.githubusercontent.com/16702370/217176043-1b69de1b-fc26-4148-8063-fc033de7c55a.png)

**Comment by Tienisto** [comment]
Updated in 9662a2e1695c2633f36f78f55ca50235ad33e73a
