### ISSUE TITLE
Preserve File Metadata

### ISSUE THREAD

**Issue by Sponge-bink** [localsend/localsend#1316]
### Is your feature request related to a problem? Please describe.

When I send files via AirDrop or copying files from/to an SMB drive, the metadata of file, such as date modified is preserved. But files sent using LocalSend will have modified dates of when then files are received. 

### Describe the solution you'd like

Preserve all file metadata if possible. So that the result file would be exactly the same as if it would have been sent using AirDrop or SMB.

**Comment by Caesarovich** [comment]
As the Dart:IO API doesn't provide any method to change a file's stats, this issue will sadly not be resolved anytime soon. If preservation of such data is important, I suggest [archiving](https://en.wikipedia.org/wiki/Archive_file) the file for the transfer.

**Comment by Tienisto** [comment]
Let's close this in favor of #650 because modified / access date is likely the only thing that can be realistically implemented
