### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by CrawFordddd** [localsend/localsend#1318]
### Describe the bug

I want to know why I can't transfer files from my Android phone to my MacBook through LocalSend, and the displayed content is errno=1. I have tried many things but none of them worked

<img width="902" alt="截屏2024-05-05 23 06 06" src="https://github.com/localsend/localsend/assets/168981522/3c94e5c9-6a13-4703-9955-ab97d2c120a2">

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

They had previously shown that it was acceptable, but after the progress bar was loaded, an orange exclamation mark and incorrect identification popped up, which prevented me from reading on MacBook

<img width="902" alt="截屏2024-05-05 23 06 06" src="https://github.com/localsend/localsend/assets/168981522/c8c65f60-0965-4538-b204-181c3eaf5bcb">

### Desktop (please complete the following information)

MacOS：13.6.1

### Smartphone (please complete the following information)

Device：Xiaomi 14Ultra
OS：Xiaomi HyperOS
Version：1.0.8.0

**Comment by Tienisto** [comment]
Can you try to change the destination directory?

**Comment by CrawFordddd** [comment]
> 您可以尝试更改目标目录吗？

It seems possible. Do we need to set the storage directory first each time? Thank you!!!

**Comment by Caesarovich** [comment]
@CrawFordddd has this issue been solved ? It seems like a permission issue on the Desktop/LocalSend folder.

**Comment by CrawFordddd** [comment]
The problem has been successfully solved, thank you very much!!!! It means that the storage directory needs to be reset every time, but the main issue has been resolved
