### ISSUE TITLE
Feature request: Confirmation dialogue window when removing a device from Favorites

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#1324]
### Is your feature request related to a problem? Please describe.

Lately, I've accidentally removed devices from Favorites a few times by tapping on the heart icon itself on the right (shown in the screenshot), even though the add/remove button is conveniently placed at the edge. Nevertheless, I still manage to accidentally tap it sometimes 😬 So, I think it wouldn't be a bad idea if, before removing from Favorites (by clicking on the heart icon), we also received a confirmation dialogue window, as it happens when deleting in edit/settings mode for Favorites, where we are asked if we really want to delete the device.

As for adding, perhaps it would be worth it to also immediately open the device settings window when when adding to Favorites (by clicking on the heart icon), just like it happens directly from the Favorites section. Then, if needed, you could immediately change the device name, as well as confirm adding the device to Favorites or cancel the addition if you accidentally tapped the heart icon. This would be more informative because perhaps not everyone is aware that there is the option to assign custom names to other devices, and, as mentioned earlier, it would completely eliminate accidental additions to Favorites.

### Describe the solution you'd like

Described above.

### Additional context

![1](https://github.com/localsend/localsend/assets/125032334/b86cbec3-072d-40d3-97ce-aec867d9e7c7)

**Comment by Tienisto** [comment]
I agree that the behaviour should be made more explicit instead of only changing its icon
