### ISSUE TITLE
Bidirectionality

### ISSUE THREAD

**Issue by doriangrey03** [localsend/localsend#1333]
### Describe the bug

Hi all, I have installed localsend on multiple hosts : 2 windows machines 1 linux machine 1 VM and 1 Android. The problem is that the linux machine see s all the other devices and can send files and messages, but the others don't see the linux machine, why?

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

i can see every hosts with my linux machine, i expect to see my linux machine with every hosts

### Desktop (please complete the following information)

Kali Linux
Windows 10

### Smartphone (please complete the following information)

Android 12

**Comment by Tienisto** [comment]
Likely blocked by your firewall. You can try to send by typing the IP address manually

**Comment by barbax7** [comment]
Close the issue, it is resolved in discussion
