### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by drake-anaki** [localsend/localsend#1337]
### Is your feature request related to a problem? Please describe.

I am used to use the pc when i am not at home, so i do hotspot with my phone.
In theory the pc and the phone should be in the same network, right?
By the way in the phone i am not able to see the phone and viceversa. 

### Describe the solution you'd like

If  i do hotspot with the phone to the pc i can send the file ecc.. 

### Describe alternatives you've considered

No others ideas

### Additional context

The phone is Android and the pc is Linux (Fedora)

**Comment by Tienisto** [comment]
Yes, a hotspot should already work

**Comment by drake-anaki** [comment]
> Yes, a hotspot should already work

I just uninstall both the app and the appImage i now it is working.
sorry my bad
