### ISSUE TITLE
visual bug with main window after update nvidia driver

### ISSUE THREAD

**Issue by f242** [localsend/localsend#1357]
### Describe the bug

visual bug with main window after update nvidia driver
i need to close localsend and start it again to fix

### To reproduce

open localsend main window
start update nvidia video driver
bug appears after update finished

https://github.com/localsend/localsend/assets/10371194/43a970b1-468a-4eae-9dc1-2f0bb69d4ed3

### Expected behavior

window contents do not disappear or become distorted

### Desktop (please complete the following information)

ver. 1.14.0 (45)
win 11 23h2

**Comment by Tienisto** [comment]
Difficult to fix on LocalSend side.

**Comment by f242** [comment]
Found out that the process uses the 3D functionality of my video card, I suspect this problem has something to do with that. Is there any way to disable 3D usage in the application? 3D is hardly necessary to perform the functions of the application.

![Image](https://github.com/user-attachments/assets/25e8760a-9f71-48a2-a95a-aa5a5a19341e)

**Comment by f242** [comment]
@Tienisto 

Also, because Localsendis defined as a 3D application, its menus display monitoring data that is commonly used in games

![Image](https://github.com/user-attachments/assets/c1326c9b-79ab-478b-8950-7afec75d2de9)

**Comment by f242** [comment]
workaround https://github.com/localsend/localsend/issues/2380#issuecomment-4413687627
