### ISSUE TITLE
Linux recipient rejected the request (no prompt)

### ISSUE THREAD

**Issue by wbaes** [localsend/localsend#136]
### Describe the bug

I've installed the app on Arch linux via the AUR (tried both the `bin` and `git` versions), and whenever I try to send anything to it from my Android (installed via F-Droid), the message `The recipient has rejected the request` appears, without ever having seen a prompt, and nothing is transferred. Turning Quick Save on does not change anything.

The other way around, from Linux to Android, does work.

### To reproduce

1. Go to 'Send' tab on Android
2. Add file or text to transfer
3. Click on Linux device
6. See error

### Expected behavior

For the file or text to be transferred.

### Desktop (please complete the following information)

- OS: Arch Linux x86_64
- Kernel: 6.1.9-arch1-1

### Smartphone (please complete the following information)

- Device: Samsung S20 5G (SMB-G981B/DS)
- OS: Android 13

**Comment by Word-Maps** [comment]
(0958275937)

**Comment by Word-Maps** [comment]
(ALL_IN_ONE)

**Comment by matejdro** [comment]
Opening it via terminal reveals this error:

```
ProcessException: Failed to find "xdg-user-dir" in the search path.
  Command: xdg-user-dir
```

Installing `xdg-user-dirs` package seems to resolve the issue.

Although it would be nice if program would display a message, instead of just silently failing.

**Comment by Tienisto** [comment]
In `v1.7.0` you can see the exact error

**Comment by wbaes** [comment]
> Installing `xdg-user-dirs` package seems to resolve the issue.
> 

This has fixed it for me, so maybe that's something that could be added as a dependency on the AUR

**Comment by Nixuge** [comment]
> > Installing `xdg-user-dirs` package seems to resolve the issue.
> 
> This has fixed it for me, so maybe that's something that could be added as a dependency on the AUR

Done

**Comment by Tienisto** [comment]
This should be fixed now
