### ISSUE TITLE
[Android] Download location bug

### ISSUE THREAD

**Issue by bibsp** [localsend/localsend#1363]
### Describe the bug

Default location for receiving files is Download. But still it is saving files in different folder like Pictures, Movies. For example images are saving is pictures folder and videos are in movies folder. Even though I tried to change the download location in a different folder named LocalSend, but it is still saving those in pictures and movies.

Edit: If I send unsupported files (like .exe) then it is saved in my desired location.

### To reproduce

Send photos and videos from windows pc.
Receive it in android.
Photos will be saved in pictures folder and videos will be saved in movies folder.

### Expected behavior

I expect all files in a same folder.

### Desktop (please complete the following information)

Windows 11 23H2

### Smartphone (please complete the following information)

Redmi note 7s
Android 10

**Comment by Tienisto** [comment]
You need to disable "Save media to photos"

**Comment by arikadiusz** [comment]
there's no "save media to photos". I have disabled the "save media to galery" having the same issue. It won't let me send Downloads folder
