### ISSUE TITLE
White titlebar in dark mode?

### ISSUE THREAD

**Issue by userzzzq** [localsend/localsend#1375]
### Is your feature request related to a problem? Please describe.

White titlebar

### Describe the solution you'd like

please change to black titlebar
![Snipaste_2024-05-25_07-28-19](https://github.com/localsend/localsend/assets/69742519/af45a7a6-9816-4736-9381-eecada4f81cc)

**Comment by Caesarovich** [comment]
Hi,

Is Dark mode enabled on your Windows system or only in LocalSend settings ? @userzzzq

**Comment by Derakoptes** [comment]
I also have it installed and in both cases it's white

**Comment by bharathajjarapu** [comment]
I have added Mica titlebar and also background, 
[Uploading LocalSend Fix.zip…]()

**Comment by bharathajjarapu** [comment]
[Mica.zip](https://github.com/user-attachments/files/15569818/Mica.zip)
I have added Mica titlebar for LocalSend

**Comment by bharathajjarapu** [comment]
I also made a full background version of this here it is 
[Background.zip](https://github.com/user-attachments/files/15569845/Background.zip)

**Comment by Tienisto** [comment]
@bharathajjarapu Please do not share unverified compiled applications. Instead, provide the source code (or make a pull request).

**Comment by bharathajjarapu** [comment]
"I'll push the changes tomorrow, okay? I thought I could send him a file faster. I haven't abstracted, classified, or properly documented the changes yet."

**Comment by IdkWhatToCallMe123** [comment]
> I also have it installed and in both cases it's white

use Mica for everyone

**Comment by JustAdreamerFL** [comment]
I think that if only windows would have a native looking theme it would be also appropriate for other platforms to have native like look. 
I would be happy with only a dark title bar for dark theme and white title bar for light theme :)
