### ISSUE TITLE
Text overflow in File information modal.

### ISSUE THREAD

**Issue by explorer2040** [localsend/localsend#1382]
### Describe the bug

file name overflowing on file information modal in history, when width of the app adjusted small or in small screen devices.

### To reproduce

**Reproducing bug on desktop**
1. send a file with a very long name to any localsend app. very long use this: `e6aafd1992a4d6fb51bb20c0206d664m`
2. click history clock on top right.
3. click three dots of the longname file received .
4. click Information.
5. resize the entire app window.
6. File information modal overflows text.

**Reproducing bug on android**
1. send a file with a very long name to any localsend app. very long use this: `e6aafd1992a4d6fb51bb20c0206d664m`
2. click history clock on top right.
3. click three dots of the longname file received .
4. click Information.
5. File information modal overflows text.

### Expected behavior

under small screen sizes, file names should be displayed to limited number of characters with file-extension at end.
idk how to implement - we can't trim filename backwards, since it removes the file extensions.
maybe we can add a dedicated file extension tag in the modal.

### Screenshots

![Screenshot_20240527_195439](https://github.com/localsend/localsend/assets/114521419/39f6c895-d7c5-45f4-b5bb-5d74b338aab8)

### Desktop (please complete the following information)

Windows 10
app version 1.14.0

### Smartphone (please complete the following information)

Android 14
app version 1.13.1

**Comment by 247b** [comment]
@Tienisto  can we fix this without adding any additional components.

**Comment by Caesarovich** [comment]
> @Tienisto can we fix this without adding any additional components.

Yes it's possible pretty easily. I'll get on it tomorrow....

**Comment by 247b** [comment]
> > @Tienisto can we fix this without adding any additional components.
> 
> Yes it's possible pretty easily. I'll get on it tomorrow....

What is the solution.

**Comment by Caesarovich** [comment]
Hi @247b,

It was not as easy as I thought, I learned that AlertDialogs and Tables have specific sizing constraints.
But nevertheless here's a screen recording of my current iteration: 

[TextOverflow.webm](https://github.com/localsend/localsend/assets/38408878/570eebfa-16e6-4e36-8705-1f4a2e895fd6)

I've fitted the table into a sizedbox with *unlimited* width, that makes it expand to the maximum of the screen and gives the table a decisive constraint. I don't particularly like that it defaults to taking all the space.

**Comment by Caesarovich** [comment]
Another solution I propose is to make the table scroll-able. Here's my screen recording:
[TextOverflow.webm](https://github.com/localsend/localsend/assets/38408878/256d29e1-5b18-4f28-a847-79d7ac82ea3c)

This solution is much cleaner in my opinion. What do you guys think ? @Tienisto @247b

**Comment by Tienisto** [comment]
LGTM @Caesarovich

**Comment by 247b** [comment]
> Hi @247b,
> 
> It was not as easy as I thought, I learned that AlertDialogs and Tables have specific sizing constraints.
> But nevertheless here's a screen recording of my current iteration: 
> 
> [TextOverflow.webm](https://github.com/localsend/localsend/assets/38408878/570eebfa-16e6-4e36-8705-1f4a2e895fd6)
> 
> I've fitted the table into a sizedbox with *unlimited* width, that makes it expand to the maximum of the screen and gives the table a decisive constraint. I don't particularly like that it defaults to taking all the space.
> 

Cool LGTM @Caesarovich

**Comment by 247b** [comment]
@Caesarovich LGTM

**Comment by 247b** [comment]
@Caesarovich with this implementation, does larger file names increase the height of the modal in small screens.@Caesarovich @Tienisto how about employing new way to show the modal contents consisely.
