### ISSUE TITLE
Bug report: Linux AppImage broken

### ISSUE THREAD

**Issue by ThatOneCalculator** [localsend/localsend#139]
### Describe the bug

Fails to launch:

```
➜  ~ chmod +x Downloads/LocalSend-1.6.2.AppImage 
➜  ~ ./Downloads/LocalSend-1.6.2.AppImage 

(localsend_app:2762391): Gdk-WARNING **: 10:33:29.846: Failed to load cursor theme Qogir

(localsend_app:2762391): Gtk-WARNING **: 10:33:29.855: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/window-minimize-symbolic.symbolic.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
[1]    2762391 IOT instruction (core dumped)  ./Downloads/LocalSend-1.6.2.AppImage
➜  ~ 
```

### To reproduce

1. Download AppImage
2. chmod
3. launch

Alternatively
1. `yay -S localsend-bin`
2. launch

### Expected behavior

Launches

### Desktop (please complete the following information)

- OS: Arch GNU/Linux x86_64
- Hyprland

**Comment by Drsheppard01** [comment]
Can you add your icon from /assets directory?

**Comment by rocky19888** [comment]
Yes I can, bit I have no idea how it all happened, I am not a developer, so took some help from a developer as well, actually I still need help with my accounts and contracts that I have, because I was hacked, I would like to secure my assets, and I am not well versed with these stakings and contracts, can you help???

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by ThatOneCalculator** [comment]
spambot? lol

**Comment by Caesarovich** [comment]
@ThatOneCalculator can you confirm that this issue is still valid with the latest version LocalSend ? If it solved you can safely close this issue.

**Comment by ThatOneCalculator** [comment]
It's no longer an issue
