### ISSUE TITLE
Feature request : add extension for Sharing direct from Finder

### ISSUE THREAD

**Issue by akashkmr** [localsend/localsend#1393]
### Is your feature request related to a problem? Please describe.

It needs one last extreme useful feature to ease of use for adding share extension, which can be used directly from finder with  macOs. 

<img width="295" alt="image" src="https://github.com/localsend/localsend/assets/12050075/bd086091-d0de-4b5b-9c34-7b18591f7bfd">

### Describe the solution you'd like

Adding share extension will help users to send files without going to app.

**Comment by gingerbeardman** [comment]
came here to post this!

perhaps an easier alternative, or addition, would be to support Deep Links (UTI) to send data to the file using system tools.

https://blog.openreplay.com/deep-linking-in-flutter/
