### ISSUE TITLE
Feature request adding a wifi mouse

### ISSUE THREAD

**Issue by volkansari** [localsend/localsend#1394]
### Is your feature request related to a problem? Please describe.

It would be great if you add a Wifi remote mouse feature to the Localsend application.

### Describe the solution you'd like

It would be great to have a mouse that can be controlled from a phone.

**Comment by Tienisto** [comment]
Hello, this is out of the scope of LocalSend (a file sharing app to share files locally).

**Comment by volkansari** [comment]
I understand, thank you for your interest.
