### ISSUE TITLE
autostart after login error

### ISSUE THREAD

**Issue by Sielier** [localsend/localsend#1412]
### Describe the bug

autostart after login cant use and have garbled characters.

### To reproduce

when i press the "settings" 
![image](https://github.com/localsend/website/assets/79133624/2a80b111-659c-4efb-8623-fcb36d505d10)
the windows settings will say "can't find the app". The details page also seems to have garbled characters.
![image](https://github.com/localsend/website/assets/79133624/9d78d950-9b2a-4ad9-9dd4-06201a698898)
but when i found the value of localsend and changed [ D:\Software\LocalSend\localsend_app.exe ] to [ "D:\Software\LocalSend\localsend_app.exe" --hidden ] in register
![image](https://github.com/localsend/website/assets/79133624/cd00cd2d-74a0-4b0e-b5be-dc9aba69dd01)
it would be ok
![image](https://github.com/localsend/website/assets/79133624/3f12e9c5-e1ad-4137-9d5f-4d692b69fb82)

### Expected behavior

Bug fixes

### Desktop (please complete the following information)

Windows 11 26120.770

**Comment by Tienisto** [comment]
Should be fixed in the next update (around next week)
