### ISSUE TITLE
Disabling window decorations.

### ISSUE THREAD

**Issue by MillionsToOne** [localsend/localsend#1413]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

I'd like an option to disable window decorations. As a WM user, I really hate window decorations with a passion. Especially those that have only a close button and the app name.

### Describe alternatives you've considered

Toggle to disable window decorations.

**Comment by thatLeaflet** [comment]
This is possible via this merge: https://github.com/localsend/localsend/pull/669

Launching with the environmental variable `GTK_CSD=0` disables the CSD.
