### ISSUE TITLE
Basic Web client?

### ISSUE THREAD

**Issue by Arttast** [localsend/localsend#1417]
### Is your feature request related to a problem? Please describe.

No. 

### Describe the solution you'd like

A simple Web client(maybe even receive only)

**Comment by IdkWhatToCallMe123** [comment]
For now, if you want something that works on the web, you could use [https://pairdrop.net/](https://pairdrop.net/).

**Comment by Arttast** [comment]
I mean I already do (If I remember correctly local send is more efficient with the data transfers and the mobile apps actually exist and that why I asked)

**Comment by Arttast** [comment]
oops
