### ISSUE TITLE
Speed is about 600 KB/s when using HTTPS (I already checked other threads about this)

### ISSUE THREAD

**Issue by StoopidoMan** [localsend/localsend#1429]
### Describe the bug

I have read other Issues but for me the speed is much slower, so I am not sure why.

with HTTPs on I get no more than 700 KB/s and on HTTP 8 MB/s

I know you said nothing can be done, but this is too slow, I get with 2-6 MB/s with Resilio Sync. so take this as a feedback for future improvement if there nothing you can do.

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Faster Speed

**Comment by ProjectInfinity** [comment]
Yeah speed is abysmal when there are many small files, seems to be huge amount of overhead between each file.

![image](https://github.com/localsend/localsend/assets/593870/1ffda3eb-77af-4d22-9238-be4fccce264d)

**Comment by StoopidoMan** [comment]
In my case it was just 1 file, I transferred one single big file just to test the speed because I didn't like how slow Resilio Sync was. even though theoretically Wifi 5 GHz should be way faster. 

It is sad to see that sharing file between devices must be done through commercial apps that you don't know what data they collect.

**Comment by Tienisto** [comment]
The overhead of small files should be fixed this #491.
As you've pointed out, HTTPS is generally slower due to Flutter (the underlying framework to develop LocalSend): #384
