### ISSUE TITLE
UI slows down or locks up during transfer of large amount of files

### ISSUE THREAD

**Issue by ProjectInfinity** [localsend/localsend#1431]
### Describe the bug

Application and interface slows down immensely when adding a lot of files to receive.

I thought first that it was perhaps HTTPS that slowed down my 8100 file transfer (around 6.6GB) but on the receiving end the UI almost completely locks up, constantly eating 100% of one core and transfer speeds slow to a crawl.

I've tested with both 4000 and 8100 files and 4000 is starting to slow down but is considerably faster, 8000 is actually unusable.

### To reproduce

Just load up 8100 files to send and start.

### Expected behavior

The UI to not lock up or render at 1 FPS.

### Desktop (please complete the following information)

Both machines run Arch Linux.

**Comment by Christian-Nerd** [comment]
Sounds like a hardware issue what computers do you have? Did you consider disabling encruption?

**Comment by ProjectInfinity** [comment]
I tried both encrypted and non encrypted. The machine in question is a Mac Pro 2013 model with 12 cores, 64GB RAM and dual FirePro D700.
