### ISSUE TITLE
Need a better selection list

### ISSUE THREAD

**Issue by eachgo** [localsend/localsend#147]
### Is your feature request related to a problem? Please describe.

It is very convenient to distribute the same files to different devices, but there are too many steps in the case of distributing different files to different devices.

For example, I need to send files 1, 2 and 3 to device A and 4, 5 and 6 to device B. Now the steps to go through are to drag and drop 123 into the list, select device A, then go to the edit list, click delete all, then drag and drop 456 into the list and click on device B.

### Describe the solution you'd like

Make the selection bar easier to edit. For example, on the desktop side let user  click the right mouse button to delete the files in the selection. On the mobile side, tap twice to delete files.

Or give a checkbox near selection to decide if you want to keep the selection after sending all files.
Just check the box when you want to transfer files to multiple devices.

**Comment by Tienisto** [comment]
Added send modes in `v1.8.0`
