### ISSUE TITLE
Missing pull request template and i18n labels

### ISSUE THREAD

**Issue by mertssmnoglu** [localsend/localsend#1474]
## Describe the situation

LocalSend is a nice multi language supported open source app that I enjoy while using it. 

i18n PRs are usually created by the localsend users. It would be nice to provide a pull request template and an `i18n` issue/pr label to the community.

## Pull request templates
- [devspace/awesome-github-templates](https://github.com/devspace/awesome-github-templates#rocket-templates-for-pull-requests)
- [VantaInc/sdlc-templates](https://github.com/VantaInc/sdlc-templates)

**Comment by mertssmnoglu** [comment]
You said PR template's are not needed right now. That's ok. https://github.com/localsend/localsend/pull/1475#issuecomment-2221761049

What about adding an `i18n` or `translation` to [labels](https://github.com/localsend/localsend/labels).

For example you can filter the translations PRs easily
![20240711_15h37m29s_grim](https://github.com/localsend/localsend/assets/61623638/7ac8b06b-314d-4508-9b57-0b702fb2d83f)

**Comment by Tienisto** [comment]
Thanks, I've added `translation` to labels
