### ISSUE TITLE
Bug report Image Timestamps

### ISSUE THREAD

**Issue by X-eno** [localsend/localsend#1504]
### Describe the bug

Not sure if it's really a bug or i'm just mistaken.
But if i tranfer images from my Android 11 to my Windows 10 the timestamps on the image are rewritten.
It's "normal" that the created date will be updated with the current time. But i though the "changed date" would stay as the original "changed date".
So actually it's:
created date = current time
changed date = current time

When i transfer the images oldschool over usb cable the changed date stays the same.

Because this will break the sorting of many galeries, i think. (well it' broke mine,)

I'm not sure if it's really "changed date" in english but i hope you know what i mean.

### To reproduce

1. Tranfer an Image
2. Check the timestaps

### Expected behavior

That the changed date the original changed date get.

### Desktop (please complete the following information)

Windows 10

### Smartphone (please complete the following information)

Android 11

**Comment by Tienisto** [comment]
Images can store the timestamps in two ways:
- metadata in the image binary (this is not lost)
- metadata of the file (currently, I am working on it, see #650)
