### ISSUE TITLE
EXE installer lacks Visual C++ Redistributable DLLs

### ISSUE THREAD

**Issue by brogers5** [localsend/localsend#1513]
### Describe the bug

When using the EXE installer, LocalSend will fail to start on systems that do not have `Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.20.27508` or later installed. 

This was not a requirement for the legacy MSIX package, as the runtime libraries were instead included as part of the packaging. Previous consumers of the MSIX package could consider this to be a feature regression.

### To reproduce

1. Install LocalSend v1.12.0 or later with the EXE package.
2. Attempt to start LocalSend.

### Expected behavior

The EXE package should include any required DLLs, as has historically been done for the MSIX package.

Alternatively, this needs to be more clearly documented as a runtime requirement for Windows platforms.

### Screenshots

![MSVCP140.dll error](https://github.com/user-attachments/assets/a9f81686-3d8c-472a-a986-3e0140fb8ff7)
![VCRUNTIME140_1.dll error](https://github.com/user-attachments/assets/7937f66c-2992-4338-98d6-e13870dfe7a7)
![VCRUNTIME140.dll error](https://github.com/user-attachments/assets/88a440a7-2435-4ea8-8dc4-ed3c29019967)

### Desktop (please complete the following information)

- OS: Windows Server 2019 Datacenter
- Version: 17763.3887

### Additional context

For the v1.15.0 release of the installable Chocolatey package (`localsend.install`), I'm working around this by taking a new package dependency on `vcredist140` v14.20.27508.1+.

The same issue exists with the portable version, and if any packaging changes are planned to address this, please consider making the same fix there.

This is not a showstopper by any means, but figured it's at least worth a mention since I happened to run into it during testing.

Related: #682

**Comment by Tienisto** [comment]
It seems easier than I thought:

https://docs.flutter.dev/platform-integration/windows/building#building-your-own-zip-file-for-windows

I guess, I need to include these dll files next time
