### ISSUE TITLE
传大文件直接崩了

### ISSUE THREAD

**Issue by yopoyan** [localsend/localsend#1515]
版本：1.15
操作环境：Windows 10 专业版 22H2  19045.4529
当文件大小为：6G的时候 软件崩溃了。直接死掉了。希望改正，谢谢。

**Comment by QPYIDRWIMG** [comment]
我用 LocalSend 传六十G左右的文件也崩溃了，LocalSend 版本是1.15.0，系统是 Windows10

**Comment by yopoyan** [comment]
> 我用 LocalSend 传六十G左右的文件也崩溃了，LocalSend 版本是1.15.0，系统是 Windows10

你那6G不会崩溃吗？我最大传不了6G

**Comment by QPYIDRWIMG** [comment]
> > 我用 LocalSend 传六十G左右的文件也崩溃了，LocalSend 版本是1.15.0，系统是 Windows10
> 
> 你那6G不会崩溃吗？我最大传不了6G

我没用 LocalSend 传过6G大小的文件，不知道传6G大小的文件会不会崩溃。不过我觉得 6G 和 60G 都很大，传60G大小的文件会崩溃，传6G大小的文件大概也一样，都会崩溃。

**Comment by Joackk** [comment]
2G以上就会崩溃，这个问题已经被提过了，等下个版本修复吧

**Comment by Joackk** [comment]
#1506

**Comment by Tienisto** [comment]
https://github.com/localsend/localsend/releases/download/v1.15.0/LocalSend-1.15.0-windows-x86-64--fix-big-files.exe
