### ISSUE TITLE
Blank App Icon on Android < 8

### ISSUE THREAD

**Issue by E0697** [localsend/localsend#153]
### Describe the bug

The icon is blank on Android 5.
The green droid avatar is displayed instead.

### To reproduce

Using stock launcher on an Android 5 device, the app icon isn't displayed properly.

### Expected behavior

Icon should be displayed properly.

### Smartphone (please complete the following information)

-  OS: Android 5 (Cyanogen Mod, TouchWiz)
-  Version: 1.7.0

**Comment by Tienisto** [comment]
Fixed in b5aea933051bc1c11923a0cd84e44edcc88423e7

**Comment by E0697** [comment]
Thank you!
