### ISSUE TITLE
Update LocalSend to Latest Version on Winget

### ISSUE THREAD

**Issue by tEctutoRIt** [localsend/localsend#1530]
The latest versions (v1.15 and v1.15.1) of LocalSend have been released on GitHub but are not yet available on Winget, which is still at v1.14.

I am aware of recent switch from MISX to EXE but could you please update the Winget package to the latest version? Keeping it up-to-date helps users who rely on Winget for software management.

Thank you for your hard work and for providing such a useful tool!

**Comment by Tienisto** [comment]
Generally speaking, Github releases are always several days ahead than most other channels.

You can follow https://github.com/microsoft/winget-pkgs/pull/163635 to see when it gets merged.
