### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [localsend/localsend#1534]
### Describe the bug

Only the armv7 libapp.so is not reproducible. This also happens on other apps. I don't know how to fix it. Maybe we can split the abi and drop armv7 build temporarily?

[org.localsend.localsend_app_50.apk.html.zip](https://github.com/user-attachments/files/16318673/org.localsend.localsend_app_50.apk.html.zip)

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

The build is reproducible.

**Comment by Tienisto** [comment]
The newest version now uses Java 17. Maybe that should be changed on F-Droid too?

https://github.com/localsend/localsend/blob/main/.github/workflows/release.yml#L57

Other than that, the Flutter version has not changed

**Comment by Tienisto** [comment]
There should be different apks now. I updated the github workflow to

```
flutter build apk --split-per-abi
```

**Comment by linsui** [comment]
Could you please change the version code schema? See https://github.com/nfcim/nfsee/blob/master/android/app/build.gradle#L105 for example. E.g., we need something like 522 for arm64 instead of 2052.

**Comment by Tienisto** [comment]
Hi, I've updated the version codes in the latest release

**Comment by linsui** [comment]
It works, thanks!
