### ISSUE TITLE
can't install 1.6.2 apk

### ISSUE THREAD

**Issue by gkdgo** [localsend/localsend#154]
### Describe the bug

![Screenshot_2023-02-13-09-13-48-735_com miui packa](https://user-images.githubusercontent.com/55651847/218349739-e70ada85-9fde-4bc3-8635-37d8efc0bffc.jpg)

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

install succeed

### Smartphone (please complete the following information)

readme note 10 pro miui 13.0.11
android 12
apk 1.6.2

**Comment by Tienisto** [comment]
Have you tried deinstalling the old version?

**Comment by gkdgo** [comment]
> Have you tried deinstalling the old version?

thanks for ur quick response , it works fine after rebooting my phone , the problem is due to the "miui优化" option .
