### ISSUE TITLE
LocalSend can no longer be installed on Windows 11 on ARM64

### ISSUE THREAD

**Issue by tobiasmboelz** [localsend/localsend#1540]
### Describe the bug

While LocalSend could be installed on Windows 11 on ARM64 using the MSIX package, the EXE installer fails with an error. As the MSIX packages no longer exist, there's no way to install LocalSend any more. 

Installation also doesn't work with winget any more, as the winget package switched from the MSIX to the EXE installer.

### To reproduce

1. Download and run `LocalSend-1.15.1-windows-x86-64.exe` (or any other more or less recent version).
2. See error message.

or:

1. `> winget install LocalSend.LocalSend`
3. `Installer failed with exit code: 1` 

### Expected behavior

The installation completes successfully.

### Screenshots

![Screenshot 2024-07-21 070532](https://github.com/user-attachments/assets/f0951d41-be4f-4e44-b3cb-8a3c06adad56)

### Desktop (please complete the following information)

- OS: Windows
- Version: 11

### Additional context

In `scripts/compile_windows_exe-inno.iss`, `ArchitecturesAllowed` and `ArchitecturesInstallIn64BitMode` should be set to `x64compatible`[^1]. This requires Inno Setup 6.3 or later. I did not provide a pull request as I couldn't find out how the installer package is build and therefore if that change would work without further adjustments.

[^1]: See https://jrsoftware.org/ishelp/topic_setup_architecturesinstallin64bitmode.htm.

**Comment by Tienisto** [comment]
Hi, can you try out: https://github.com/localsend/localsend/releases/download/v1.15.1/LocalSend-1.15.1-windows-x86-64--fix-arm.exe

**Comment by tobiasmboelz** [comment]
> Hi, can you try out: https://github.com/localsend/localsend/releases/download/v1.15.1/LocalSend-1.15.1-windows-x86-64--fix-arm.exe

It works.

**Comment by Tienisto** [comment]
Thanks! This change will be official in the next bug fix release

**Comment by jp-sjc** [comment]
Worked on Surface pro. Thanks.
