### ISSUE TITLE
[enhancement] Nearby devices are discovering a bit slow

### ISSUE THREAD

**Issue by bearcloney** [localsend/localsend#1543]
### Is your feature request related to a problem? Please describe.

Under normal network conditions, the PC finds the device almost instantly,
But the phone needs to wait about three seconds to find the computer
When the computer is connected to the mobile phone hotspot, it takes about 9 seconds for the mobile phone to search for the computer.
### Describe the solution you'd like

Every time I send a file, I have to wait for the device to be searched. I don't know what causes this, but since the computer can connect immediately, it shouldn't be a big problem, right? I hope it can be improved. Thank you.

### Additional context

android:13
windows:10
version:1.15.1

**Comment by Tienisto** [comment]
Decreased timeout in 655c83442f9e200ca1887cf3ce4c27d5952a48ec
