### ISSUE TITLE
[bug] File Transfer Fails in Custom Directories on Android 1.15+ Versions

### ISSUE THREAD

**Issue by shing-yu** [localsend/localsend#1544]
### Describe the bug

After updating to LocalSend version 1.15+ on my Android device, I have encountered an issue where file transfers fail when the save directory is set to a location outside the default "Download" directory. This issue was not present in previous versions.

Based on my observations, the issue seems to be related to the permissions requested by the app. In earlier versions, after setting a custom path, the app would request "Manage All Files (MANAGE_EXTERNAL_STORAGE) " permission, which allowed file transfers to custom directories. However, in versions 1.15+ this permission request appears to be removing, leading to transfer failures when using non-default directories.  

I am not certain if this issue occurs on all devices, but it has consistently occurred on my device.

### To reproduce

1. Update LocalSend to version 1.15+ on an Android device.
2. Change the save directory to a non-Download directory.
3. Try transferring the file to this device.
4. Observe the error message indicating a failure in file transfer.

### Expected behavior

The file transfer operation was successful.

### Screenshots

![7a97beb819056ed858518ef95c939301](https://github.com/user-attachments/assets/fe3d5f80-3aee-42ab-b572-4a7946b3131e)

### Desktop (please complete the following information)

- OS: Windows 11 (22631.3880)
- Version: 1.15.1

### Smartphone (please complete the following information)

- Device: Redmi Note 12 Turbo
- OS: HyperOS 1.0.3.0 with Android 14
- Version: 1.15.0 & 1.15.1

### Additional context

I tried using `adb shell appops set --uid org.localsend.localsend_app MANAGE_EXTERNAL_STORAGE allow`, but it didn't help.

May be related to #1493 .

**Comment by weiwei-cool** [comment]
Yes！i can reapper on ColorOS 14 with Android 14.  Error will apper unless the path is "Download"

**Comment by weiwei-cool** [comment]
I trid to give it root access or adb access, but  Error still apper.

**Comment by Tienisto** [comment]
Yes, #1493 did broke some things. I've noticed that you can create a sub folder like "Download/LocalSend" and it should work (if you want to have a separate LocalSend folder).

Other than that, I guess we need to use "content URI" to save files outside the Download folder.
For example: https://github.com/localsend/localsend/blob/422e65dde19726c8f35a5a09e31f7103b0c88b3e/app/lib/util/native/file_saver.dart#L33

It might have a performance impact because Dart/Flutter doesn't write directly to the file system anymore.

**Comment by shing-yu** [comment]
> I've noticed that you can create a sub folder like "Download/LocalSend" and it should work (if you want to have a separate LocalSend folder).

Yeah, this is indeed a temporary solution.

**Comment by SRC267** [comment]
Can confirm, The temporary solution does work, however applying the same sub folder method still throws an error if i select external SD Card as download path.
