### ISSUE TITLE
[Bug report]: Starting from version 1.15.0, the app interface on Windows 11 freezes heavily and becomes unresponsive for a certain period of time

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#1546]
### Describe the bug

Starting from version 1.15.0, the app interface on Windows 11 freezes heavily and becomes unresponsive for a certain period of time. This wasn't the case in previous versions. For clarity, I've attached a screencast (orange circles mean mouse click).

https://github.com/user-attachments/assets/8d0b9a08-f32e-4465-80e3-0482b477a4e2

I've been using the .exe version since its release for quite some time, and I didn't encounter such problems before. Windows itself has not been updated recently and if I go back to the previous version of the program 1.14.0, it works without complaints. I update the app by installing the new version on top of the old one. I've also tried a clean install by deleting the configuration file from the "Roaming" folder, but that didn't help. In addition, I disabled the switch "Show LocalSend in context menu", because it's the only one that is enabled of the new ones that have been added, and besides, it's directly related to Windows, but this also didn't help. If anyone else has encountered this on Windows 11, please let me know, I'll be very grateful.

### To reproduce

Described above.

### Expected behavior

Described above.

### Desktop (please complete the following information)

LocalSend v1.15.1
Windows 11 23H2

**Comment by Tienisto** [comment]
Did you notice a difference between 1.15.0 and 1.15.1?

**Comment by Tienisto** [comment]
Can you try the portable (zip) versions?

**Comment by sergd88** [comment]
> Did you notice a difference between 1.15.0 and 1.15.1?

> Can you try the portable (zip) versions?

Yes, since from version 1.5.0 and including the portable version as well. But now I'm experiencing an issue even with older versions of the app. The problem becomes noticeable when there aren't nearby devices, meaning there aren't devices running LocalSend on the network anymore. So, I suspect there is some issue with detecting devices on the network, during which the app interface simply freezes. Previously, I didn't notice this at all, even though I've been the only device on the network many times. Now it's just a complete freeze of the interface, even on version 1.9.0. I tried version 1.6.2 and there my device is also displayed as a participant on the network, causing the interface to lag somewhat when switching tabs, but within reason.

**Comment by Tienisto** [comment]
Alright, so you mean 1.5.0 (I thought you misspelled 1.15.0). This is a very old version

**Comment by sergd88** [comment]
> Alright, so you mean 1.5.0 (I thought you misspelled 1.15.0). This is a very old version

Yes, I meant versions 1.15.0 and 1.15.1. Sorry for the typo.

**Comment by Tienisto** [comment]
Based on your description, I believe that LocalSend tries manual IP scanning when the more efficient multicast method failed (due to no found devices). Although true multithreading still requires significant work, maybe I can at least move discovery to a separate thread

**Comment by sergd88** [comment]
> Based on your description, I believe that LocalSend tries manual IP scanning when the more efficient multicast method failed (due to no found devices). Although true multithreading still requires significant work, maybe I can at least move discovery to a separate thread

Today I checked the app's performance on another Windows computer, where I hadn't updated to versions 1.15.0 or 1.15.1. The app runs smoothly without any complaints, even when no devices are connected to the network. Both computers are on the same network. I also haven't experienced any such issues on older versions of the app before installing version 1.15.0.

From the recent Windows updates, I see that .NET Framework 3.5 and 4.8.1 were updated on July 11th. However, I was using version 1.14.0 of the app at that time, and the issue wasn't observed yet.

**Comment by sergd88** [comment]
In the course of observations, I can confirm that the app hangs after switching to the "Send" tab, if you switch between the "Receive" and "Settings" tabs, the problem isn't observed.
In addition, I noticed the following feature: if after reinstalling the app versions 1.14.0 and 1.15.0, check the box "Launch the application after installation", then the app starts and works without any complaints until closing. Repeated opening causes the interface to freeze. If you don't check the box "Launch the application after installation" and run the app for the first time yourself, manually, then the problem with the interface freezing is present. With version 1.15.1 of the app, such manipulations don't work, the interface freezes, even if you check the box. That's the situation at hand.

**Comment by sergd88** [comment]
> What happens if you have 2 devices connected to the same network so that they should discover each other? Then, I think, it should not freeze, but if you tap on the "scan" button, it should freeze

Yes, you're right. When there are two or more devices on the network, the interface doesn't freeze until you press the "scan" button.

I actually encountered interface freezing for the first time in version 1.15.0 when I was changing the language settings. Then there were freezes when transferring files, opening the file selection menu, and changing settings. Probably, after some time, "automatic device scanning" activates, which also causes the interface to freeze.

I'm just surprised that rolling back to version 1.14.0 didn't fix the issue and the interface continues to freeze, even though everything was fine before. And for some reason, if you uncheck the "Launch application after installation" option during the first launch of the app, the interface freezes, but if you check the option, the first launch works well, even if you repeatedly click the "scan" button and there are no devices on the network at all. It's all very strange.

**Comment by Tienisto** [comment]
Please checkout https://github.com/localsend/localsend/releases/download/v1.15.1/LocalSend-1.15.1-windows-x86-64--fix-lag.exe

**Comment by sergd88** [comment]
> Please checkout https://github.com/localsend/localsend/releases/download/v1.15.1/LocalSend-1.15.1-windows-x86-64--fix-lag.exe

Yes, in this regard everything is fine, at least for now, after several app restarts the interface freezing issue is no longer observed.

However, it's worth noting that in "device search" mode, the app abnormally burdens the processor, up to 30%, which is quite high considering I have an 11th generation i7 installed. This is a problem, especially for people who use automatic startup of the app when the system starts and who have even weaker processors. In such cases, "automatic scanning" will significantly burden their system, and considering that most likely use laptops, it will also negatively impact battery life.

Perhaps the app previously consumed as many resources, I just didn't pay attention to it, but overall, this isn't very good.

**Comment by sergd88** [comment]
I understand that the search process is typically resource-intensive. As an option, I think it wouldn't be a bad idea to limit "automatic scanning" when the app is minimized or running in the background. Then, in principle, the user doesn't need device search at all. And only when the app window is open, then it's worth starting the "automatic scanning".

**Comment by sergd88** [comment]
And in general, probably the best option would be for the "auto scanning" to run every time only when switching to the "Send" tab. This way, the app wouldn't burden the system in all other cases (for example, when you're just configuring it), until the user actually wants to send files and switches to the "Send" tab. Then the resource costs would be completely justified because the app is trying to find a device. This would effectively add a "device rescan" function as well. Sometimes you might have closed the app on the device a while ago, but it still appears in the found devices.

**Comment by sergd88** [comment]
**This isn't related to the current issue, but since the issue is essentially closed, I'll add it here instead of opening a new one and unnecessarily cluttering the issues, as the problem isn't significant:** ___Please use the .ico icon format not only for the app itself but also for its installation file (and removal if possible). Currently, the icon of the installation file appears smaller during installation, about 20%, compared to other icons on the panel.___

**Comment by Tienisto** [comment]
Is the CPU usage high on app start? It actually shouldn't be. During app start, a broadcast is sent to the network which should be very efficient. Only when the send tab is opened, the resource intensive manual scanning is started if no devices are found.

**Comment by sergd88** [comment]
> Is the CPU usage high on app start? It actually shouldn't be. During app start, a broadcast is sent to the network which should be very efficient. Only when the send tab is opened, the resource intensive manual scanning is started if still no devices are found.

No, everything is fine when launching the app, CPU usage is low, but after switching to the "Send" tab, it becomes high. The problem is that if I switch to another tab ("Receive", "Settings"), the scanning doesn't stop, and the app continues searching for devices, thus loading the CPU unnecessarily. Device search is only needed on the "Send" tab, not on "Receive" or "Settings". It's a waste of CPU resources. Also, the app likely has an "auto scan" feature that may start from any part of the app. That's probably why I encountered the app interface freezing not only on the "Send" tab but also on the "Settings" tab when I changed the language and faced freezing for the first time. That's why I mentioned that it would be good and logical for any kind of scanning to operate only within the "Send" tab, where it's actually needed.

I also checked CPU usage on another computer with a weaker processor, running version 1.14.0 of the app, which I haven't updated. There, CPU usage when no devices are on the network doesn't exceed 10%. Currently, with this fix-lag version on my computer, CPU usage is around 30%, sometimes jumping to 40%. Both computers are on the same network.

**Comment by Tienisto** [comment]
Alright, can you test the older portable version 1.14.0? Or use the newest (portable) version on your weaker computer? I want to know if 1.15 introduced problems or not - unfortunately, on my Windows machine, the CPU usage never exceeds 1% during network scan

**Comment by sergd88** [comment]
> Alright, can you test the older portable version 1.14.0? Or use the newest (portable) version on your weaker computer? I want to know if 1.15 introduced problems or not - unfortunately, on my Windows machine, the CPU usage never exceeds 1% during network scan

On my computer, even in the portable version 1.14.0, the app interface freezes. I don't want to install version 1.15.0 on another computer to avoid encountering the same problems there. Before version 1.15, I didn't have problems with excessive CPU usage either. It's either version 1.15.0 causing these problems or the Windows update from July 11, which somehow broke the app. After the Windows update, version 1.14.0 of the app worked without any complaints. Your fix-lag fixes helped. Now the interface doesn't freeze, so the freezing problem most likely did pertain to app problem, simply this problem didn't manifest itself to me earlier. I understand it's very difficult to fix a problem that cannot be reproduced, so thank you for that fix. At least I can use the app now. However, I would be very grateful if you would consider the possibility of limiting the detection of new devices to only the "Send" tab.

**Comment by Tienisto** [comment]
Thanks for your input. Regarding detection limitation: There should be no auto scan but if you open the send tab, then

(1) the efficient method is used
(2) if after 1 second there are still no devices found, then the more resource intensive method is used

Due to the delay, you might think that LocalSend periodically scans the network but it shouldn't do that.

I can implement that the process of starting (2) is aborted if the user left the send tab within one second, but if (2) has already been started, then it is currently not easy to abort

**Comment by sergd88** [comment]
> Thanks for your input. Regarding detection limitation: There should be no auto scan but if you open the send tab, then
> 
> (1) the efficient method is used (2) if after 1 second there are still no devices found, then the more resource intensive method is used
> 
> Due to the delay, you might think that LocalSend periodically scans the network but it shouldn't do that.
> 
> I can implement that the process of starting (2) is aborted if the user left the send tab within one second, but if (2) has already been started, then it is currently not easy to abort

"currently not easy to abort" — I understood.

I noticed that the scanning itself feels like an endless process. If there are no devices on the network and you press the "scan" button, it continues for several minutes without interruption. I get tired of waiting and just close the app. If there are no devices on the network and you press the "scan" button, launching the app on another device stops the scanning as soon as a device is found, meaning it stops searching for other devices. However, if you press the "scan" button again with that one found device, the app resumes scanning until at least one more device appears on the network, only then does the scanning stop. So, to stop scanning, at least one device must be found. This doesn't seem quite normal to me. I would prefer scanning similar to Wi-Fi network scanning, Bluetooth, etc., with specific intervals and periodic automatic scanning. Currently, the endless scanning looks very strange to me.

**Comment by Tienisto** [comment]
It shouldn't take that long. There is a "discovery timeout" setting (hidden as "advanced"), can you change it to 500 or lower? This is the time in milliseconds to wait if a device is online or not in a network.

**Comment by sergd88** [comment]
> It shouldn't take that long. There is a "discovery timeout" setting (hidden as "advanced"), can you change it to 500 or lower? This is the time in milliseconds to wait if a device is online or not in a network.

I know about this parameter, but it doesn't work, or maybe it does work, but the processor remains under load, and the "device discovery" animation itself doesn't stop and lasts a few minutes, I just didn't wait any longer. By default, it's set to 2000 milliseconds, which is 2 seconds. Changing it to 500 or 10 milliseconds had no effect whatsoever.
If the CPU load were at 30% for 2 seconds, I wouldn't even pay attention to it, the problem is precisely that it doesn't stop until the app is closed. I've gotten used to opening the app in the send tab, and then in the file explorer look for the files I need to transfer, and then I launch LocalSend on another device and just drag the files. So very often there are no devices on the network for me. Now this habit has been disrupted by this problem, that's why I noticed it.

**Comment by sergd88** [comment]
Right now, if I install version 1.14.0 on my computer and check the "Launch the program after installation" option, the program starts, and switching to the "Send" tab when there are no devices on the network and device discovery is ongoing, it does not load my processor more than 1-2%. However, this occurs only on the first launch with the checkbox checked. That's the same load I experienced before. During device discovery, it operates correctly, searching for a few seconds and then stopping. Manually initiating a rescan also functions properly and similarly loads the processor at 1-2%.

**Comment by Tienisto** [comment]
Since you mentioned somewhere that launching LocalSend from the installer is smoothly in 1.14 and 1.15 but not in 1.15.1, then you can try to remove the 3 added dll files:

- msvcp140.dll
- vcruntime140.dll
- vcruntime140_1.dll

These files are located next to the executable.
I've included them in 1.15.1 so that users don't need to install Visual C++ (it is sometimes not installed). 

If you remove them, it might help

**Comment by sergd88** [comment]
> Since you mentioned somewhere that launching LocalSend from the installer is smoothly in 1.14 and 1.15 but not in 1.15.1, then you can try to remove the 3 added dll files:
> 
> * msvcp140.dll
> * vcruntime140.dll
> * vcruntime140_1.dll
> 
> These files are located next to the executable. I've included them in 1.15.1 so that users don't need to install Visual C++ (it is sometimes not installed).
> 
> If you remove them, it might help.
> 
> Another solution is to copy the same dll files from 1.14 to 1.15.

I tried to delete the specified files, but it didn't help at all. Copying dll files from version 1.14 to version 1.15 is not possible, as you yourself mentioned that you only included them in version 1.15.1. Perhaps, you meant to copy them from version 1.15.1 to version 1.14?? I tried that as well, but it didn't help either.

After identifying the problem, I've repeatedly performed "clean installs," deleting all files, including the configuration file from the "Roaming" folder. The only thing I haven't removed is any remaining registry entries, if there are any.

**Comment by Tienisto** [comment]
Sorry, the portable version of 1.14 indeed doesn't has those DLL files but the msix installer has. I don't know what installer you used before. Regardless, I don't think the DLL files are the cause.

I have uploaded another possible fix where I've used the same network library version as in 1.14.0. I am not sure if this fixes the problem, but you can try it:

[LocalSend-1.15.1-windows-x86-64--fix-lag-2.zip](https://github.com/user-attachments/files/16366496/LocalSend-1.15.1-windows-x86-64--fix-lag-2.zip)

**Comment by sergd88** [comment]
> Sorry, the portable version of 1.14 indeed doesn't has those DLL files but the msix installer has. I don't know what installer you used before. Regardless, I don't think the DLL files are the cause.
> 
> I have uploaded another possible fix where I've used the same network library version as in 1.14.0. I am not sure if this fixes the problem, but you can try it:
> 
> [LocalSend-1.15.1-windows-x86-64--fix-lag-2.zip](https://github.com/user-attachments/files/16366496/LocalSend-1.15.1-windows-x86-64--fix-lag-2.zip)

No, this version also puts load on the processor. But now, after restarting version 1.15.1 (standard), LocalSend-1.15.1-windows-x86-64--fix-lag, and LocalSend-1.15.1-windows-x86-64--fix-lag-2 are working fine and don't burden the processor 😂 The timeout detection is also working. I haven't tried version 1.15.0 and it's probably better not to. I don't know what's going on at all, but it's better if I don't touch anything and let everything work. Thank you very much for spending so much time on solving the problem.

Another point. You mentioned that auto detection/auto scanning of devices is missing. And that's strange because I thought such an option was present, especially since the file transfer apps I used before had auto scanning, or at least I thought so. I think it would be good to add such a parameter, even optionally with the ability to disable it. Because very often a device is no longer on the network but still appears. So I think such a parameter would be very useful. It would also be great if the auto scanning interval could be set manually, but some arbitrary 10-15 seconds that would be a fixed parameter would also be quite sufficient.
