### ISSUE TITLE
Feature request: Retry failed files

### ISSUE THREAD

**Issue by maheshrijal** [localsend/localsend#1552]
### Is your feature request related to a problem? Please describe.

I was sending a bunch of small files and noticed that some files had failed (Probably because I disconnected from the wifi network). It would be nice to have an option to retry failed files. 

### Describe the solution you'd like

An option to retry sending failed files

**Comment by FrederikLauber** [comment]
I would also love seeing this implemented.

For example, when I am sending my pictures from my phone to my PC, I just send all files at ones which may take 1h. If one file fails, I have to start all over again.

**Comment by black-ish** [comment]
Second that.
