### ISSUE TITLE
[Bug report] Folder being deleted after transmission.

### ISSUE THREAD

**Issue by UnCLAS-Prommer** [localsend/localsend#1553]
### Describe the bug

After I sent the whole folder to my PC, the folder on my iphone disappeared.
After chedking the storage usage, I can confrim that those files were deleted.

### To reproduce

1. Go to 'Send'
2. Select 'Folder' and choose a folder
3. Click 'Send'
4. After another client received the folder, the folder on the phone disappered.

### Expected behavior

Does the folder needed to be deleted after transmission?

### Desktop (please complete the following information)

- OS: Windows 11 23H2
- LocalSend Ver: 1.15.1

### Smartphone (please complete the following information)

- Device: iPhone Xs Max
- OS: iOS 16.3

**Comment by Tienisto** [comment]
Likely this bug https://github.com/miguelpruivo/flutter_file_picker/issues/1412

**Comment by Tienisto** [comment]
Fixed in c1dab3e4230147d3fbd967f4df24328304f7871a
