### ISSUE TITLE
Bug report:Multiple process bug in portable version caused Socket Exception

### ISSUE THREAD

**Issue by Ahhh9h** [localsend/localsend#1561]
### Describe the bug

In portable version,enable "minimize to system tray" and "Autostart" options will allow the program to create a new process when starting,instead of using the already existed one,which caused a Socket Exception.
Since there is no portable version before 1.13.0,this bug only occurs after this version.
This bug won't occur in exe version.

### To reproduce

1. Select portable version
2. tick on these two options
3. reboot PC and start the program more than once

### Expected behavior

fix the bug or remove it in portable version.

### Screenshots

![1721886005720](https://github.com/user-attachments/assets/3cad2661-60b5-4192-8812-485c6ae28a29)
![Screenshot_2024-07-25-13-56-35-148_com limelight](https://github.com/user-attachments/assets/6555d8b3-b68b-418f-9876-e916a01149f2)
![Screenshot_2024-07-25-14-06-14-563_com limelight](https://github.com/user-attachments/assets/2525c837-203a-438c-8fda-e4f88036f011)

### Desktop (please complete the following information)

OS: Windows 10 Enterprise LTSC
Version: 21H2
Localsend:1.15.1

### Additional context

This bug also works on Android device,but very hard to trigger.

**Comment by Tienisto** [comment]
Currently, starting the exe file always creates a new instance. To avoid having multiple instances opened at the same time, it contacts the existing instance via http using a secret that is stored in the `settings.json`. It seems that if you start the portable manually, then it correctly reads the `settings.json` in the same directory. However, when it is started via autostart (after login), then it can't find the `settings.json` and instead uses or creates a different `settings.json` in AppData/Roaming.
