### ISSUE TITLE
Scoop releases override the settings

### ISSUE THREAD

**Issue by SiriosDev** [localsend/localsend#1565]
### Describe the bug

With each update via scoop the settings are overwritten (not sure if it should be reported here, though seeing it in the readme I thought I'd open the issue here)

### To reproduce

1. With localsend installed via scoop run `scoop update extras/localsend`

### Expected behavior

The expected behavior is that the update does not overwrite the settings

### Desktop (please complete the following information)

- OS: Windows 11
- Version: 1.15.2

**Comment by Tienisto** [comment]
This should be already fixed in https://github.com/ScoopInstaller/Extras/pull/13645
Maybe you updated from 1.15.0 to 1.15.2

**Comment by SiriosDev** [comment]
Going from 1.15.1 to 1.15.2 the setting was overwritten, I will try the next version when it comes out and update this issue

**Comment by SiriosDev** [comment]
yep confirmed, is resolved during the update between 1.15.2 -> 1.15.3

**Comment by SiriosDev** [comment]
yep confirmed, is resolved during the update between 1.15.2 -> 1.15.3
