### ISSUE TITLE
"No route to host" I can't solve it, help plz 🙏😢

### ISSUE THREAD

**Issue by SilntRavn** [localsend/localsend#1572]
I meet the following problem:
DioException [connection error]: The connection errored: No route to host This indicates an error which most likely cannot be solved by the library.
Error: SocketException: No route to host (OS Error: No route to host, errno = 113)

If anyone could help me, I would be extremely grateful🙏🙏🙏

**Comment by SilntRavn** [comment]
![Uploading Screenshot_20240728_020123.png…]()

**Comment by Tienisto** [comment]
Are both devices in the same wifi?

**Comment by SilntRavn** [comment]
> Are both devices in the same wifi?

yes,and devices can recognize each other

**Comment by SilntRavn** [comment]
![Screenshot_20240728_094644](https://github.com/user-attachments/assets/dc526a91-96a1-4695-a7fe-eb7233cfbcfc)

**Comment by HarshNarayanJha** [comment]
Firewall or something?

**Comment by SilntRavn** [comment]
> Firewall or something?

![Image_1722150440298](https://github.com/user-attachments/assets/9fdee041-6a35-4e76-8443-7848d66e401e)

I have allowed all inbound rules

**Comment by gargeyak** [comment]
I'm facing the similar issue with Android and Mac

**Comment by SilntRavn** [comment]
> I'm facing the similar issue with Android and Mac

There will always be various inexplicable problems on the computer. I consulted many people but couldn't find a solution. In the end, I restarted the router and everything was resolved🤕🤕

**Comment by chiragdhunna** [comment]
> > I'm facing the similar issue with Android and Mac
> 
> There will always be various inexplicable problems on the computer. I consulted many people but couldn't find a solution. In the end, I restarted the router and everything was resolved🤕🤕

Exactly I restarted VS Code, and the error was resolved.
