### ISSUE TITLE
When  support the web version

### ISSUE THREAD

**Issue by orzuzro** [localsend/localsend#1576]
### Is your feature request related to a problem? Please describe.

Thank you for your extraordinary work~ First time I know there is such a software!

I would like to ask if there is any plan to support the web version? When will it be available?

Thanks again for your work!

### Describe the solution you'd like

Thank you for your extraordinary work~ First time I know there is such a software!

I would like to ask if there is any plan to support the web version? When will it be available?

Thanks again for your work!

**Comment by Magnusretrotech** [comment]
There will most likely never be a web version unless someone generous builds a web app. For now, I would recommend using https://snapdrop.net/.
