### ISSUE TITLE
[Bug report] Mobile: When transferring "Media", if the translation for the "Preview" function is quite long and many media files are selected, the entire line shifts to the right, causing it to be cut off

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#1578]
### Describe the bug

In the "Media" transfer, there is a "Preview" function, which is called "Попередній перегляд" in Ukrainian. This name has become standard for this function, and it is used by everyone. The name is quite long, and there is no abbreviation for it. If only a few media files are selected and the number is single-digit, everything is fine. However, if the number becomes double-digit, triple-digit, and so on, the entire line starts shifting to the right, causing part of it to be cut off. It looks something like this:

![1](https://github.com/user-attachments/assets/aeb259a5-ccd3-4fe0-b285-727c6ba15718)

It would be great if you could reduce the size of the "Confirm" button (meaning the size of the green border around the "Confirm" text), or if when the line doesn't fit in one line, it wrapped to the next line, making it wider, as is done in the "Settings". I’m not sure if you can fix this, as you're using a third-party media viewer, but I would be very grateful if you could check if anything can be done about it.

### To reproduce

Described above.

### Expected behavior

Described above.

### Smartphone (please complete the following information)

Any Android device.

**Comment by Orest19Marko** [comment]
Also faced such an issue.

**Comment by Tienisto** [comment]
Since this is a third-party library, I don't know if this is fixable. I would like to use the native picker but it still has the issue that the file names are lost: #376
