### ISSUE TITLE
1.15.3 has wrong build number in APK

### ISSUE THREAD

**Issue by TenchMaviatorius2759** [localsend/localsend#1585]
### Describe the bug

In version[ 1.15.3](https://github.com/localsend/localsend/releases/tag/v1.15.3), the architectures arm32v7, arm64v8, and x64 do not update over the previous version (1.15.2). Only if installed cleanly, as the build number is incorrect.
For example, the arm7 architecture version 1.15.2 has a build number of 1052, while version 1.15.3 has 532.
The file with the "google play" prefix updates without any issues.

### To reproduce

1. Download the architecture file for arm64, arm7, x64 from release 1.15.3  
2. Try to update over version 1.15.2  
3. Error with the message "App not installed as package appears to be invalid."

### Expected behavior

Fix the update error.

### Screenshots

![Screenshot_20240729-192619](https://github.com/user-attachments/assets/27413e10-ef95-4b36-9783-db73d8236c88)
![Screenshot_20240729-192647](https://github.com/user-attachments/assets/2ce2ed27-a525-4cc1-9faf-ebd6c97d2e3b)

### Desktop (please complete the following information)

Android 13

**Comment by Tienisto** [comment]
Sorry for the inconvenience. Actually, I needed to update the build numbers of the previous version (1.15.2) to fix #1534.
So the newest version should have the correct schema (53 * 10 + 2)
