### ISSUE TITLE
Record the most recently used IP addresses

### ISSUE THREAD

**Issue by DearZack** [localsend/localsend#1587]
### Is your feature request related to a problem? Please describe.

I use it in complex network environments, with second level and third level routing. Localsend cannot directly detect other devices, but can connect using input IP. Can we add a feature to record the IP addresses of the devices that have been sent, so that they can be quickly selected for the next startup? When this IP is no longer needed, it can also be manually deleted

### Describe the solution you'd like

I use it in complex network environments, with second level and third level routing. Localsend cannot directly detect other devices, but can connect using input IP. Can we add a feature to record the IP addresses of the devices that have been sent, so that they can be quickly selected for the next startup? When this IP is no longer needed, it can also be manually deleted

**Comment by Tienisto** [comment]
You can add custom IP addresses to favorites (heart symbol)

**Comment by DearZack** [comment]
thanks
