### ISSUE TITLE
My Android system cannot install the latest version

### ISSUE THREAD

**Issue by CloverAn** [localsend/localsend#1593]
### Describe the bug

I downloaded the LocalSend-1.15.3-android-x64.apk file and sent it to my Android phone, but it seems that it cannot be installed properly

### To reproduce

Normal installation is sufficient

### Expected behavior

Normal installation is sufficient

### Screenshots

![1722388772039](https://github.com/user-attachments/assets/50a9da46-c70f-4382-a333-9c6e55d2ec6b)
![1722388772041](https://github.com/user-attachments/assets/018a9225-b238-42d2-afd8-d32d77c580e1)

**Comment by CloverAn** [comment]
How should I handle it

**Comment by Tienisto** [comment]
Are you sure that you need x64? Most phones should have arm64

**Comment by huluwa-dev** [comment]
Hi @CloverAn Snapdragon 8+ is an ARM64 CPU, you should download the apks end with "android-arm64v8.apk".

**Comment by CloverAn** [comment]
I got it! Could you please pay attention to a few other requirements. thank you  @huluwa-dev @Tienisto
