### ISSUE TITLE
Dockerfile and Docker compose with instructions needed for selfhosting

### ISSUE THREAD

**Issue by HakaishinShwet** [localsend/localsend#1601]
### Is your feature request related to a problem? Please describe.

Please make it docker compatible if it is not so that it is easy to selfhost and manage with docker.

### Describe the solution you'd like

:-))

**Comment by Magnusretrotech** [comment]
It's already self-hosted. It sends files through your local network. In a simple way, it sets up a bridge between the first device and the second device, over the network; then it sends the files over that bridge. No server or docker needed.

**Comment by bverkron** [comment]
Sorry to necro this issue but it says it was completed yet I cannot find anything in the doc or repo about a docker compose setup. There is a Dockerfile in the server directory but I'd rather pull an official version than build it myself and have to rebuild when there is a new release.

**Comment by LckySndays** [comment]
It seems like I cannot find it as well
https://github.com/localsend/localsend/issues/2405
