### ISSUE TITLE
FR: Better macOS interoperability - drag and drop files to the menubar icon

### ISSUE THREAD

**Issue by ShlomoCode** [localsend/localsend#1615]
### Is your feature request related to a problem? Please describe.

The **ideal** goal for LocalSend is to be as simple to use as AidrDrop.
Currently the fastest way to send files with LocalSend is to leave the app open in the Dock and then drag the files to the Dock icon.

However, many users prefer a cleaner Dock, especially for apps used intermittently. Constantly visible apps can create visual clutter and potentially distract from primary tasks. This preference aligns with the popularity of menu bar apps in the macOS ecosystem, especially for quick-access\utility tools.

### Describe the solution you'd like

It would be very convenient if it was possible to leave the application running in the background (there is already such an option in the LocalSend settings), and when you want to send a file - just drop it on the menu bar icon.

### Describe alternatives you've considered

https://github.com/localsend/localsend/issues/586 pretty much serves this purpose, but I think throwing to the menu bar icon is more convenient as it's in one motion - just grab the file and drop it.

### Additional context

A macOS app I know of that has this feature is CleanShot X - any image can be dragged to the menu bar icon, and it will open in CleanShot's built-in editor.

**Comment by ShlomoCode** [comment]
@Tienisto Can I suggest swift code for this?

I don't know how to integrate it with Flutter, but it works flawlessly as a native macOS app:

```
import SwiftUI
import Cocoa

@main
struct TestDragDropMenuBarApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    var body: some Scene {
        Settings {
            EmptyView()
        }
    }
}

class AppDelegate: NSObject, NSApplicationDelegate {
    var statusItem: NSStatusItem?
    
    func applicationDidFinishLaunching(_ notification: Notification) {
        statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.squareLength)
        
        if let button = statusItem?.button {
            button.image = NSImage(systemSymbolName: "globe", accessibilityDescription: "Hello World")
            
            let dragView = DraggableView(frame: button.bounds)
            button.addSubview(dragView)
            
            dragView.translatesAutoresizingMaskIntoConstraints = false
            NSLayoutConstraint.activate([
                dragView.topAnchor.constraint(equalTo: button.topAnchor),
                dragView.leadingAnchor.constraint(equalTo: button.leadingAnchor),
                dragView.trailingAnchor.constraint(equalTo: button.trailingAnchor),
                dragView.bottomAnchor.constraint(equalTo: button.bottomAnchor)
            ])
        }
    }
}

class DraggableView: NSView {
    override init(frame frameRect: NSRect) {
        super.init(frame: frameRect)
        setup()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }
    
    private func setup() {
        registerForDraggedTypes([NSPasteboard.PasteboardType.fileURL, NSPasteboard.PasteboardType.URL, NSPasteboard.PasteboardType.string])
    }
    
    override func draggingEntered(_ sender: NSDraggingInfo) -> NSDragOperation {
        return .copy
    }
    
    override func performDragOperation(_ sender: NSDraggingInfo) -> Bool {
        let pasteboard = sender.draggingPasteboard
        
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] {
            for url in urls {
                print(url.path)
            }
            return true
        }
        
        if let strings = pasteboard.readObjects(forClasses: [NSString.self], options: nil) as? [String] {
            for string in strings {
                print(string)
            }
            return true
        }
        
        return false
    }
}
```

It just prints the path, of course you can change that to the real action (broadcast the path to the dart part of the app)

And here it is as a runnable Xcode project so that you can get an impression:
[TestDragDropMenuBar.zip](https://github.com/user-attachments/files/16537670/TestDragDropMenuBar.zip)

**Comment by Tienisto** [comment]
Thanks! I will check this out

**Comment by ShlomoCode** [comment]
@Tienisto Did you have time to check it out? If I can be of any help please let me know!

**Comment by Tienisto** [comment]
Sorry, I dont have any questions since I didn't dived into this topic yet
