### ISSUE TITLE
Excessive RAM use when transferring big files

### ISSUE THREAD

**Issue by stevenwang111** [localsend/localsend#1623]
### Describe the bug

I tried to send a very big file, about 12GB. At first it was all right, but several minutes later I found that both the RAM and swap were full. My computer has 16GB of RAM and 4GB swap. And there were no other programs running except Localsend and the system monitor. 
Then I found that the upload speed almost reached 0, with a sudden increase in CPU usage. It lasted for about 2 minutes. So I simply cancled it.
My computer is using Ubuntu 24.04 and my phone is Android 14.

### To reproduce

Send a very big file.

### Expected behavior

It shouldn't stop. And it would be even better if the RAM usage could be reduced.

### Screenshots

![截图 2024-08-09 22-29-00](https://github.com/user-attachments/assets/06cd3189-5678-4c3f-81d9-55f5167d6eef)

**Comment by Tienisto** [comment]
Do you use the latest version?

**Comment by stevenwang111** [comment]
Maybe,I installed it from snap and F-droid

**Comment by Tienisto** [comment]
Okay. This should has been fixed in 1.15.2 (#1547).

**Comment by stevenwang111** [comment]
Well, thank you and I'll cut the file into smaller ones next time.

**Comment by black-backdoor** [comment]
Hi,
I think this has to do with the way LocalSend works. As far as I understand, it uses HTTP POST requests to upload each file in a single go. I don't know exactly how the protocol is implemented in this repository (I haven’t looked at it), but depending on the server implementation, this could require loading the entire file into memory.

This is why I’m proposing [localsend/protocol#31](https://github.com/localsend/protocol/issues/31) - to switch to a download-based approach instead.
