### ISSUE TITLE
Feature request: Tooltip for the "Refresh" button

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#1626]
### Is your feature request related to a problem? Please describe.

In my opinion, it would be worth adding a "description" for the "Refresh" button, as it's the only button without a tooltip, which makes it stand out compared to all the other buttons that have tooltips.

![1](https://github.com/user-attachments/assets/454ec935-8fbd-490e-a94b-715e250985d6)

### Describe the solution you'd like

Described above.

**Comment by bling-yshs** [comment]
It's normal on my side, the version is 1.15.3
![image](https://github.com/user-attachments/assets/d0ec7832-a5ee-4c60-87ef-326f5e6204f6)

**Comment by Tienisto** [comment]
@bling-yshs It's because you have more than 3 network interfaces which results in a popup button. Most users should have a normal button that scans immediately without opening a popup.

**Comment by sergd88** [comment]
I don’t completely agree with the statement that a tooltip would be distracting or obstructive. Additionally, instead of the "Refresh" label, you could use the existing "Look for devices", it might even be better. Because right now, the absence of a tooltip for just one button among many in a row stands out somewhat.

@Tienisto As I understand it, the lack of a tooltip is intentional, so if you still believe its absence is for the best, feel free to close this issue to avoid cluttering up the issues list.

**Comment by sergd88** [comment]
I don’t completely agree with the statement that a tooltip would be distracting or obstructive. If we draw parallels with browsers, where there is also a "Refresh" button performing a remotely similar function, it has a tooltip available, though it can also be considered an "instant action button". Additionally, instead of the "Refresh" label, you could use the existing "Look for devices", it might even be better. Because right now, the absence of a tooltip for just one button among many in a row stands out somewhat.

@Tienisto As I understand it, the lack of a tooltip is intentional, so if you still believe its absence is for the best, feel free to close this issue to avoid cluttering up the issues list.

**Comment by sergd88** [comment]
I don’t completely agree with the statement that a tooltip would be distracting or obstructive. If we draw parallels with browsers, where there is also a "Refresh" button performing a remotely similar function, it has a tooltip available, though it can also be considered an "immediately action button". Additionally, instead of the "Refresh" label, you could use the existing "Look for devices", it might even be better. Because right now, the absence of a tooltip for just one button among many in a row stands out somewhat.

@Tienisto As I understand it, the lack of a tooltip is intentional, so if you still believe its absence is for the best, feel free to close this issue to avoid cluttering up the issues list.

**Comment by Tienisto** [comment]
Your feature request is reasonable, I just didn't have time & forgot to fix this.
I've added a change so that both buttons show the "Look for devices" tooltip.
