### ISSUE TITLE
Bug report - Invalid APK latest release

### ISSUE THREAD

**Issue by emtreulapollaguera** [localsend/localsend#1631]
### Describe the bug

The last released version fails with "Invalid" argument.
Tried with Obtanium, FR-Droid, NeoStore and direct download.

### To reproduce

![IMG_20240812_135523](https://github.com/user-attachments/assets/f630d04b-7067-472b-a5d2-35319c1d865c)
![IMG_20240812_135539](https://github.com/user-attachments/assets/9b21520e-628e-4581-aaf1-6afa77918148)
![IMG_20240812_135554](https://github.com/user-attachments/assets/27f78104-4f70-4b37-a87d-9190ef441dff)

### Expected behavior

Successful installation

### Screenshots

See above.

### Smartphone (please complete the following information)

Pixel 8 - GrapheneOS - 2024080600

**Comment by emtreulapollaguera** [comment]
Yes, I did after the first failed update.

**Comment by Tienisto** [comment]
This is weird. I just tried to install `LocalSend-1.15.3-android-arm64v8` and it worked on my phone

**Comment by Tienisto** [comment]
There was a build number change from 1.15.1 to 1.15.2 when using APK. Just uninstall the old version

**Comment by emtreulapollaguera** [comment]
I would do it if I would have the app installed, but what you see in the last screenshot with the app uninstalled.

It is somehow that the installer still detects the app installed when is obiously not.

**Comment by emtreulapollaguera** [comment]
Problem solved.

I had 2 different user accounts in my Pixel and the other account had Localsend as well. After uninstalling the application in both user accounts, I could install the latest version.
