### ISSUE TITLE
[question] What's the minimal version of Android supported?

### ISSUE THREAD

**Issue by lilskippyy** [localsend/localsend#1632]
### Describe the bug

Hello! I'm tying to install the app in Android 4.2.2 but it won't install.
I was wondering what's the minimal version supported? Tried searching but couldn't find it.
Thanks.

### To reproduce

1. tried searching for the minimal android version but didn't find.

### Expected behavior

Wanted to find the minimal version.

**Comment by Tienisto** [comment]
Android 5 is required

**Comment by lilskippyy** [comment]
> Android 5 is required (API level 21)

thanks!
