### ISSUE TITLE
Change license from MIT to Apache-2.0

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#1634]
Apache-2.0 protects the project from malicious contributors that own patent rights (risking law suits).

To ensure longevity of LocalSend, changing the license from MIT to Apache-2.0 is beneficial.

Please react with a thumbs up / comment if you agree with this change.

- @TheGB0077 
- @Caesarovich
- @SelaseKay
- @gitstart
- @ix5
- @NightFeather0615
- @MisterChangRay
- @Q1CHENL
- @programmermager
- @gvenusleo
- @Sqbika
- @S-ecki
- @o2e
- @harriseldon
- @h9419
- @twinstar6980
- @CHUNG-HAO

**Comment by CHUNG-HAO** [comment]
good!

**Comment by woheller69** [comment]
you should change it on F-Droid too.

https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.localsend.localsend_app.yml

**Comment by Tienisto** [comment]
Thanks!

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15656
