### ISSUE TITLE
Transferring large files from iPhone to desktop or browser cause iPhone app to crash

### ISSUE THREAD

**Issue by swiblet** [localsend/localsend#1638]
### Describe the bug

When transferring large files from iPhone to desktop (using browser or the app), the iPhone app crashes after a couple of seconds and the transfer fails. The port is opened, the settings are correct, I've tried multiple file types, I made sure all programs are the most recent version, and I've tried from both file manager and photo library. Tried reinstalling app and resetting phone. 1 GB files worked fine, 3 GB+ caused the crash.

### To reproduce

1. Add files or folders to localsend.
2. On desktop, go on browser or accept the transfer through localsend.
3. Watch the iPhone app crash as soon as the large file's transfer begins.

### Expected behavior

I expected the file to transfer to the computer and for the app not to crash.

### Screenshots

No Screenshots, the app just crashes

### Desktop (please complete the following information)

Windows 11 Home

### Smartphone (please complete the following information)

Latest iOS, iPhone 13 Pro Max

**Comment by Kayxue** [comment]
Same as here
Here is the video
iPhone is on iOS 18 beta 5
https://github.com/user-attachments/assets/71d06ae1-bc9d-4045-ae18-fc0a919dac01

**Comment by familyfriendlymikey** [comment]
Same here, but in my case none of the file sharing projects I have tested so far are working with my videos. If I add them via the iPhone gallery, the app hangs. Maybe it's processing. If I save them to Files and send them that way, then the same issue as @Kayxue's video happens. Here's the error I'm getting:

```
HttpException: Connection closed while receiving data, uri = /api/localsend/v2/upload?sessionId=something&token=something
```

**Comment by MaxRev-Dev** [comment]
@Tienisto Is there any stream by chunk processing? After looking through some code, I suspect the file is not read by chunks, but fully loaded into memory (RAM) using OpenFilex here. 
I'm not familiar with the codebase, but trying to figure this out.
https://github.com/localsend/localsend/blob/d9dff50d15464666103c75555c4a2c375e5c7700/app/lib/util/native/open_file.dart#L25

**Comment by Tienisto** [comment]
@MaxRev-Dev This is only the code to open a local file in an external application (e.g. PDF viewer).

The actual sending process is here:

https://github.com/localsend/localsend/blob/d9dff50d15464666103c75555c4a2c375e5c7700/app/lib/provider/network/send_provider.dart#L366

I've tested this on Windows and Android with a file that exceeds available RAM on Android.

**Comment by Trackerlist** [comment]
I'm facing this same issue on android for a while. Transferring large amounts of files (in quantity, not in size) makes the mobile app stop.

I have Localsend installed on both mobile (android) and desktop (windows). Both of them are running version 1.15.3 (latest). When I try to transfer about 5000 image files (~600mb) from my android to my desktop, it crashes. Strange enough, Localsend doesn't crashes when sending few files with a large size on total (5 files, ~200mb each).

If this information helps, my device is a really low end LgK40s, which in my country is 32bits and has 3gb of ram.
