### ISSUE TITLE
App is not working 

### ISSUE THREAD

**Issue by aiyu-ayaan** [localsend/localsend#1654]
### Describe the bug

So i install a fresh version of windows in my system and installed local share but it's not working 

### To reproduce

1. Watch the video 

### Expected behavior

The app should be opened

### Screenshots

https://github.com/user-attachments/assets/82340b31-09f3-4404-8831-8b4436c8047b

### Desktop (please complete the following information)

Window 11

**Comment by Tienisto** [comment]
(1) Do you have multiple monitors?
(2) Can you show me the contents of `%AppData%/LocalSend/settings.json`?

**Comment by JohnnyPC1337** [comment]
I had the same problem also. After deleting the settings.json, as described by @qingchunnh its fixed

**Comment by bearcloney** [comment]
Same problem, deleted settings.json and it returned to normal

**Comment by aiyu-ayaan** [comment]
> (1) Do you have multiple monitors? (2) Can you show me the contents of `%AppData%/LocalSend/settings.json`?

No i don't

**Comment by aiyu-ayaan** [comment]
"Thank you, @qingchunnh . I'd also like to thank you, @Tienisto ."

**Comment by Tienisto** [comment]
Can you please tell me if you have multiple monitors? This will help me to understand the issue

**Comment by bearcloney** [comment]
> 您可以告诉我您是否有多个工程师吗？这将帮助我理解这个问题------------谷歌翻译----------您可以告诉我您是否有多个有哪个显卡？这将帮助我理解这个问题

Intel(R) Core(TM) i5-8250U CPU
NVIDIA MX250
Only one display
[settings.json](https://github.com/user-attachments/files/16657757/settings.json)

**Comment by qingchunnh** [comment]
> Can you please tell me if you have multiple monitors? This will help me to understand the issue

I only have one monitor.
This issue seems to only appear in version 1.15.3, I tried copying the settings.json to version 1.15.2 and didn't encounter the issue.

**Comment by aiyu-ayaan** [comment]
> Can you please tell me if you have multiple monitors? This will help me to understand the issue

No, I dont

**Comment by Tienisto** [comment]
This should be fixed in `v1.15.4`
