### ISSUE TITLE
Feature request: On Android devices with a standard aspect ratio, it isn't obvious that the fifth "App" button is present

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#1658]
### Is your feature request related to a problem? Please describe.

At present, some Android users might not even realize that LocalSend can also send apps, because the fifth button for "App" is simply not visible on the display with a standard aspect ratio. Although the margins on the left and right are different, not everyone will guess that this is related to additional items in the list.

![1](https://github.com/user-attachments/assets/429dd935-2e36-4728-a2fa-ea8b181d1c09)

In most cases I've seen, when using a tile-based list, an additional part of the next item is shown. But this option is likely impractical, as it would require resizing each button. Adding a separate arrow button for "scrolling" isn't obvious and would only clutter the interface. One could add a horizontal scrollbar, which is generally used for such cases, but this might look awkward and be difficult to integrate into the interface, especially since scrollbar aren't used on Android, not even vertically in the "Settings" section. So, in the end, I don't have any obvious suggestions for this. Maybe, someone in the community have. I’m just opening this issue to describe the problem.

### Describe the solution you'd like

At present, I don’t have any solution for this.

**Comment by Trackerlist** [comment]
A good solution would be adding a scroll bar under the tiles, just like we see on browsers, but make it always show by default.

**Comment by Trackerlist** [comment]
A good solution would be adding a scroll bar under the tiles, just like we see on browsers, but make it always show by default. (Tbh, I never thought that 5° button exists lol)

**Comment by Tienisto** [comment]
I've added an algorithm that adjusts the padding between the buttons so that the last button is not shown 100% if there are more buttons to show.

**Comment by sergd88** [comment]
> I've added an algorithm that adjusts the padding between the buttons so that the last button is not shown 100% if there are more buttons to show.

Oh, I also thought today that it might be possible to slightly reduce the margins so that the 5th button "App" could be partially visible. I was just a bit busy and didn't have time to write about it 😬

Even if we only reduce the left margin, it would still look quite reasonable, something like this:

![1](https://github.com/user-attachments/assets/cfce464b-9735-46fb-90c6-53fbe42b429d)

And if we also align all the margins properly, it would be even better.

What do you mean by "the last button is not shown 100% if there are more buttons to show"? Does this mean the last button (i.e., the 4th one) is cut off? If so, that wouldn't look very nice.

In my opinion, if possible, a better approach would be to reduce the margins so that the last button is partially visible if it doesn't fit completely, similar to the screenshot above. If the app analyzes the display resolution and we know this, and the button sizes and margins are static, we could calculate the necessary margins to ensure the last button is partially visible, for example, just 15px.

**Comment by Tienisto** [comment]
Currently, the algorithm ensures that 10 to around 60% must be visible. I can try to optimize this to limit it to 10-20%

**Comment by sergd88** [comment]
> Currently, the algorithm ensures that 10 to around 60% must be visible. I can try to optimize this to limit it to 10-20%

Take a look for yourselves. Perhaps, it still looks good now. I just thought it looks like this:

![2](https://github.com/user-attachments/assets/0e62d728-4059-489f-9419-a0b2d09e12c1)

Back then, it would have been bad. 10-20% probably sounds better. To me, it’s well implemented in GNOME when showing the preview of the next desktop:

![3](https://github.com/user-attachments/assets/7f62ff12-3637-49cb-88a0-c006b26bdae6)
