### ISSUE TITLE
Feature request: The "Retry" button is ineffective if the user has the "Auto Finish" option enabled

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#1671]
### Is your feature request related to a problem? Please describe.

I see that in the latest update you added a "Retry" button to repeat a failed file transfer, and that's great. However, there’s one issue: if the user has the "Auto Finish" option enabled, it’s ineffective because, you physically don’t have time to click "Retry". It would be wonderful if the "Auto Finish" option were ignored in the case of a failed file transfer.

It would also be great if you added a tooltip for this button.

### Describe the solution you'd like

Described above.

**Comment by Tienisto** [comment]
Added in caab80f6634905d07e7c006a170e6c02c9c5a0bb
