### ISSUE TITLE
FR: macOS - Show Transfer Progress in Dock Icon

### ISSUE THREAD

**Issue by ShlomoCode** [localsend/localsend#1688]
### Is your feature request related to a problem? Please describe.

It would be helpful to show a progress line of the file transfer in the Dock icon in macOS, so that you can switch to another window and see the transfer status at a glance

### Describe the solution you'd like

Show file transfer progress in the Dock icon

### Describe alternatives you've considered

display a percentage badge instead of a tick around the icon

### Additional context

A popular Swift library for this: https://github.com/sindresorhus/DockProgress

Example ([Gifski](https://github.com/sindresorhus/Gifski)):

https://github.com/user-attachments/assets/c141dbb5-c001-443e-be4e-939b72e50c00

**Comment by ShlomoCode** [comment]
I see that the feature has already been implemented in #1222 and canceled in https://github.com/localsend/localsend/commit/0ced63b88103f9556f0db234bd6970918cd22985. @Tienisto, could you elaborate on this more?

**Comment by Tienisto** [comment]
@ShlomoCode I couldn't compile it somehow: https://github.com/NightFeather0615/macos_dock_progress/issues/1

**Comment by ShlomoCode** [comment]
OK, We can directly use the original swift package (https://github.com/sindresorhus/DockProgress) in the native macOS Runner. Are you interested in such a PR?

**Comment by Tienisto** [comment]
Sure. You can add any function to https://github.com/localsend/localsend/blob/main/app/lib/util/native/macos_channel.dart that invokes a native macos function
