### ISSUE TITLE
Categorization by file type/extension

### ISSUE THREAD

**Issue by igorskyflyer** [localsend/localsend#1701]
### Describe the bug

Hello, first a **huge** thank you for this exceptional application that I use daily! :)
I wanted to raise awareness of an issue (\*) that occurs when transferring files from Windows to Android.

\* *not sure if it's intentional or not.*

<br>
<br>

<div align="center">
	<figure>
		<img src="https://github.com/user-attachments/assets/c5ebc628-8f36-4ffc-b0bc-6f4eeee0abbb">
		<figcaption><em>Image 1. LocalSend settings</em></figcaption>
	</figure>
</div>

<br>
<br>

Some files, like music (`.mp3`, `.m4a`) and documents (`.pdf`) get saved to the `Save to folder` of my choice but other file types, like all image types `.jpg`, `.png`, etc. and video types `.mp4`, etc. get saved to predefined locations, i.e. `Pictures` and `Movies` respectively.  

Is it possible to disable such file type categorization and save all files to the user-defined folder?

### To reproduce

1. Set the `Save to folder` setting to an arbitrary folder
2. Send an `.mp4` file from Windows to Android
3. Notice the `.mp4` **not** being saved in the folder defined in the step no. 2

### Expected behavior

The provided `.mp4` file should be saved in the user-defined folder.

### Desktop (please complete the following information)

- OS: Windows 11 Pro (22631.4037), feature experience pack 1000.22700.1027.0
- Version: 1.15.4

### Smartphone (please complete the following information)

- Device: Samsung A6+ 2018 (SM-A605FN)
- OS: Android Q (10)
- Version: 1.15.4

**Comment by Tienisto** [comment]
Have you tried to disable "Save media to gallery"?

**Comment by igorskyflyer** [comment]
> Have you tried to disable "Save media to gallery"?

😐

Well... I feel **stupid** now. 😂  

I assumed that setting controls the inclusion of the received files in the `MediaStore`/`MediaScanner`, so I enabled it on install and never tested toggling it.

Thank you for a very quick response and fix! ☺️
