### ISSUE TITLE
Bug report: Destination link does not open folder (Win)

### ISSUE THREAD

**Issue by Brugman** [localsend/localsend#1706]
### Describe the bug

When a transfer from phone to Windows 10 is done, I am presented with the Destination location. Because of the different color and hand cursor, I expect to be able to click on this to open the folder. It doesn't.

Absolutely LOVE the app!

### To reproduce

1. Transfer file from phone to Windows.
2. Click on Destination location.
3. Nothing happens.

### Expected behavior

Open Windows Explorer at the Destination location.

### Screenshots

![2024-08-27-14-35-32](https://github.com/user-attachments/assets/231d58d2-15e2-456f-a475-34e9288fe066)

### Desktop (please complete the following information)

- Windows 10, LocalSend 1.13.1 (42)

**Comment by Tienisto** [comment]
I cannot reproduce this

**Comment by Brugman** [comment]
That's strange...

Anything on another drive works.
The Downloads default works.
The Desktop works.
`C:\Users\Tim\Desktop\<anything>` works.
`D:\localsend` works.

It's just that one folder.

I'll just use a different one. ¯\_(ツ)_/¯
