### ISSUE TITLE
[Android 15] App reloads when selecting a file

### ISSUE THREAD

**Issue by deathblade666** [localsend/localsend#1720]
### Describe the bug

When i select a file to send the app reloads and doesn’t not retain the file for sending. Selecting a media file works fine, just when selecting a file via the file option (file type does not seem to matter).

### To reproduce

1. Go to send screen
2. Click on file
3. Select file
4. App reloads

https://github.com/user-attachments/assets/71163c68-4469-46df-bc4c-886bc47f8e45

### Expected behavior

for the app to not reload clearing the selected file

### Smartphone (please complete the following information)

- Pixel 6
- Android 15
- August beta release

### Additional context

I have found that many plugin packages that interact with the file system simply do not work on android 15. Not sure if applicable here or not.

**Comment by dawsonjiang** [comment]
hi，

Which one are you using
the branch and version codes？

**Comment by Tienisto** [comment]
This likely happen when you are low on RAM

**Comment by deathblade666** [comment]
> hi，
> 
> Which one are you using the branch and version codes？

Its the latest on fdroid, so not sure exactly what branch but version number is 1.15.4(543)

**Comment by deathblade666** [comment]
it appears this was an issue with android 15 beta that has been fixed by the android 15 QPR1 beta 3 release. as such i'm closing this issue.
