### ISSUE TITLE
Themed icon for Android

### ISSUE THREAD

**Issue by Turbolqk** [localsend/localsend#174]
### Is your feature request related to a problem? Please describe.

Aside from the Material You issue, Introducing a themed icon for Android 13 would be pretty cool.

### Describe the solution you'd like

A themed icon.

**Comment by ctntt** [comment]
PR https://github.com/localsend/localsend/pull/354 solves this issue. According to the [changelog](https://github.com/localsend/localsend/blob/main/assets/CHANGELOG.md) this feature will be available in version 1.9.0
