### ISSUE TITLE
Support larger subnets

### ISSUE THREAD

**Issue by XPH0816** [localsend/localsend#175]
### Is your feature request related to a problem? Please describe.

- This app only support on /24 subnet which is not suitable for the LAN with VLSM design
- I have read your source code which is single use first three digits of IP address as IP prefix to do a discovery device

### Describe the solution you'd like

 - When I want to find my device I can't even find it in the LAN which is designed in VLSM subnet which is smaller than /24

### Describe alternatives you've considered

- Get a List of First Usable IP to Last Usable IP on that Interface on Network Model

**Comment by Tienisto** [comment]
In the meantime, discovery via multicast should work?

**Comment by Tienisto** [comment]
You can see the multicast logs in
```text
About LocalSend > Debugging > Multicast
```

**Comment by wxk6b1203** [comment]
As shown in the main page, all of the local ip postfix will be added as a tag. Can we have a way to detemine which is the correct pair of ther peer device?
![image](https://user-images.githubusercontent.com/8924149/219957102-1ba02ce8-51b7-40cc-bdd8-a7a136d49853.png)
For example, if this app is going to transfer data via http, there may another network interface that can not be achieved.
![image](https://user-images.githubusercontent.com/8924149/219957209-f5964bfe-8fe1-4f95-a42d-8352ff3c2d75.png)
As shown above, if 192.168.191.105 is a fake one, and the user chooses a wrong tag as SHARP 105, the peer cannot be established.

One more thing, I cannot find my mobile devices (Android, iPhone) on my windows app. Is there any settings error?

**Comment by Tienisto** [comment]
It is not possible to know what the correct IP address is. That's why this app uses multicast (UDP) primarily.

If Android and Iphone can discover each over, then it is most likely a firewall issue on Windows. Please allow TCP and UDP on Port 53317.

I also see an empty hashtag `#`. It seems that the IP address is missing for this network interface.

**Comment by Tienisto** [comment]
In the send tab, for each network interface there is a sync button. You should press the button next to `192.168.155.106` if you think that your mobile devices are inside this IP range.

**Comment by wxk6b1203** [comment]
Update: I can find my device after manually clicking the sync button. 
![image](https://user-images.githubusercontent.com/8924149/219959501-02562a68-f90c-48e0-8ef4-c7722f7a7817.png)
Thank you so much!

**Comment by XPH0816** [comment]
> In the meantime, discovery via multicast should work?

Look Like it's work now !

![image](https://user-images.githubusercontent.com/50739818/220052542-476595bd-a591-46e9-8ec9-0c9f7b325a49.png)
![image](https://user-images.githubusercontent.com/50739818/220052614-3b1a455b-5ee0-44b9-8fab-7f4c6ebac99b.png)

But I think the visual ID needs to be changed at the same time, because the suffix of IP .1 in subnet /23 or smaller has two IPs, which will conflict and make the device send to the wrong place

Example:
This device got
![image](https://user-images.githubusercontent.com/50739818/220051409-d51c218d-a5ad-4d73-b73b-c963367979fc.png)
With ID 1 in 172.16.12.0/23 subnet with IP 172.16.13.1

And This Device
![image](https://user-images.githubusercontent.com/50739818/220051525-8d011e6c-1ca3-4833-8e4c-e72f1368bbe7.png)
With ID 1 in 172.16.12.0/23 subnet with IP 172.16.12.1

When I send it, the figure show that is send to 172.16.12.1 not 172.16.13.1
![image](https://user-images.githubusercontent.com/50739818/220051789-b7f2d086-1cf2-4383-9166-027efc1808fe.png)

**Comment by Tienisto** [comment]
Closed in favor of #525
