### ISSUE TITLE
Bug: image from clipboard on windows is bmp format

### ISSUE THREAD

**Issue by Seidko** [localsend/localsend#1755]
### Describe the bug

The image from clipboard on windows is a bitmap, which is very big. It should be encode or compress.

### To reproduce

1. Install App On Windows.
2. Copy an image to clipboard
3. Click Paste button in send page
4. Send to other device, check the file type

### Expected behavior

Compress or encode the image from the clipboard.

### Screenshots

![image](https://github.com/user-attachments/assets/2181b453-7107-4dd1-908c-051a207994c5)
![image](https://github.com/user-attachments/assets/e422254c-876d-41ab-8407-256320eacc3f)

### Desktop (please complete the following information)

- OS: Windows
- Version: 1.15.4 (54)

### Smartphone (please complete the following information)

- OS: Android 13
- Version: 1.15.4 (54)

**Comment by BrianMwit** [comment]
Looks like this has already been reported in https://github.com/localsend/localsend/issues/872
