### ISSUE TITLE
More actions in receive history page

### ISSUE THREAD

**Issue by realth000** [localsend/localsend#177]
### Is your feature request related to a problem? Please describe.

In the receive history page, is it better to add more actions such as "open folder", "delete history" and "delete file"? just like other downloaders.

Now the only action can do in the yellow rectangle is "open file".

![2023-02-18_14-02](https://user-images.githubusercontent.com/59462104/219844317-4bcb34ac-bf2b-495a-b358-b374012de057.png)

### Describe the solution you'd like

* Also in the yellow rectangle, maybe we can have a context menu (right click to trigger) or some icon buttons (as the tail of each item) to support the actions said above?
* By the way, maybe add a "clear history" button to the receive history page too.

### Additional context

If possible, please assign this issue to me and I will try to finish it, need some time though.

**Comment by Tienisto** [comment]
This is weird.

Actually, there should be 3 dots which opens a menu. Here is how it looks on my side:

![grafik](https://user-images.githubusercontent.com/38380847/219872698-9dddaf7c-f66c-4234-9232-eb6b750c8c32.png)

**Comment by realth000** [comment]
Yes, this looks much better.
If you like, I am willing to provide a PR.

**Comment by Tienisto** [comment]
You can do it, if you want :)

**Comment by Tienisto** [comment]
Implemented in a6d2fd9a3d83391cbaf8b372ec7ac816ebcc03be

**Comment by realth000** [comment]
Thanks!
