### ISSUE TITLE
华为P40鸿蒙3.0 使用最新版本用来传输Apk文件 Bug report

### ISSUE THREAD

**Issue by PLA888** [localsend/localsend#178]
### Describe the bug

传输完成之后无法点开以及安装。

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

传输完成之后无法安装apk文件。

### Smartphone (please complete the following information)

华为P40 Pro 鸿蒙3.0

**Comment by soiamsoNG** [comment]
关闭华为的纯净模式。

**Comment by NITROGENousFish** [comment]
鸿蒙3.0纯净模式关不掉的，我也发现软件无法安全的写入；这并非软件的问题而是鸿蒙的问题，考虑关闭这个issue吧

**Comment by NITROGENousFish** [comment]
Hi _localsend_ developers,
The above issue mentioned: Software failure bug(cannot save any file to android phone) 
Platform: HUAWEI HarmonyOS 3.0 , DEVICE: HUAWEI P40.

**Comment by Tienisto** [comment]
Thank you @NITROGENousFish
