### ISSUE TITLE
Local send minimized tray icon not showing!!

### ISSUE THREAD

**Issue by thegabriele97** [localsend/localsend#1788]
### Discussed in https://github.com/localsend/localsend/discussions/1192

<div type='discussions-op-text'>

<sup>Originally posted by **SDee001** March  8, 2024</sup>
Local send minimized tray icon not showing when downloaded from flathub from linux mint software manager</div>

**Comment by KraXen72** [comment]
![image](https://github.com/user-attachments/assets/c9994eb9-3c81-440c-99f4-b28431743c66)
![image](https://github.com/user-attachments/assets/8d33380f-f16c-46e2-9409-dbd9acc57cc6)

i have the same problem; I am using fedora linux 40 with kde plasma 6.1 DE.
i am using the flatpak as well.
