### ISSUE TITLE
Feature request about windows system tray

### ISSUE THREAD

**Issue by PennHui666** [localsend/localsend#179]
### Is your feature request related to a problem? Please describe.

When I click on the software icon in the system tray, it does not open directly but displays an open option for me to open after clicking, which is not in line with the operating habits.

### Describe the solution you'd like

I hope that when the software is closed and shrunk in the system tray, the left mouse button double-click or click to open it, and the right mouse button is the display option. This is more in line with operating habits.

**Comment by Tienisto** [comment]
Added in 4eb9e8fe80e985105f322683ba33017e17e85352
Will be released in `v1.8.0` in 1 or 2 weeks
