### ISSUE TITLE
suggest  default server port  lower than 49152.

### ISSUE THREAD

**Issue by hgyxbll** [localsend/localsend#1823]
### Is your feature request related to a problem? Please describe.

When Windows user installed wsl or  Hyper-V VM, the windows will reverse some ports to used by Hyper-V.
we can use `netsh int ipv4 show dynamicport tcp` to see the reverse ports.
It is default from 49152 to 65535.
So sometimes localsend will fail to create server socket.

### Describe the solution you'd like

change the default server port to lower than 49152.

**Comment by saurabh12453** [comment]
server change port has completely changed to server 49152-65535 waiting for the response..... done by danish JR Engineer..  please change the module to hyper v model.

**Comment by Tienisto** [comment]
See https://github.com/localsend/protocol/issues/12

**Comment by SynapseScribe** [comment]
On https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements
it is clearly specified that Hyper-v services reserve ports from 49152 - 65535, making localsend unusable on default 53317 port. The randomly reserved ports can be seen through pwsh, in my case:

PS> netsh int ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5985        5985
     47001       47001
     49673       49772
     50000       50059     *
     50060       50159
     50164       50263
     50366       50465
     50466       50565
     50566       50665
     53286       53385
     53386       53485

* - Administered port exclusions.
