### ISSUE TITLE
Bug report sharing photos/videos via Photos app on iOS results in transcode

### ISSUE THREAD

**Issue by dasl-** [localsend/localsend#1830]
### Describe the bug

Hi there, I started using LocalSend today, and it works really well! Thank you for the easy to use app!

One minor thing I noticed: it seems that when photos or videos are sent with LocalSend via the Share dialog in the iOS Photos app, the photos / videos that are sent have a different file size than the originals. I assume this means that the photos / videos are being transcoded or re-encoded before being sent. 

Of course, when photos / videos are selected using LocalSend's media picker on iOS, the original files seems to be sent. So this is only a problem when using the Photos app Share functionality to send via LocalSend.

If we could fix this bug and send the original files, it would allow people to easily select multiple photos / videos at once. This is because the iOS Photos app allows selecting multiple photos / videos without having to tap each one ([demo](https://www.youtube.com/watch?v=xGebGApylWE&t=55s)). So we it might solve these issues as well as a side effect: https://github.com/localsend/localsend/issues/376 https://github.com/localsend/localsend/issues/470 

Steps to reproduce:
1.  Go to Photos app on iOS and select a photo or video, then click the "share" icon in the bottom left corner: 

  <img src="https://github.com/user-attachments/assets/9bd06009-0a27-4679-b6ad-3bb3d73bab41" width="200"/>

2. Click the "More" button on the right side: 
  <img src="https://github.com/user-attachments/assets/72607536-ed6a-4cec-b2be-d92d30ce8be2" width="200"/>

3. Select LocalSend from the list of apps with which to share the photo/video:
  <img src="https://github.com/user-attachments/assets/c88ba9db-be66-4558-be7b-dcce3c95f1ae" width="200"/>

4. Observe that the video gets processed "Preparing"
  <img src="https://github.com/user-attachments/assets/a9e9f704-cc5d-4ed7-820a-ede1bba2de49" width="200"/>

5. Finally, observe that the file size shown in LocalSend is different than the file size shown in the Photos iOS app. In my testing, the file size shown in LocalSend after the photo / video has been transcoded is actually bigger.

### Smartphone (please complete the following information)

iOS 17.6.1, iPhone 13 mini

**Comment by jmarmstrong1207** [comment]
Below "1 Video selected", click Options. You'll see a format selection with 3 settings "Automatic", "Current", and "Most Compatible". Select "Current" and check if it's sending the original video now. Does that work?

**Comment by dasl-** [comment]
@jmarmstrong1207 wow, that works! I didn't realize that was an option, thank you. If only there were a way to make that the default, but my brief googling didn't show anything.

This is great though:

- It gives us a method on iOS to bulk select photos, since the iOS native Photos app provides a bulk select interface. This helps address issues: https://github.com/localsend/localsend/issues/376 https://github.com/localsend/localsend/issues/470
- It gives us a method on iOS to select photos in a UI that shows the dates on which photos were taken, which can be handy.

I will close this issue now.
