### ISSUE TITLE
Feature request: "Select All" button in iOS app Media Selection

### ISSUE THREAD

**Issue by fmutlu** [localsend/localsend#1839]
### Is your feature request related to a problem? Please describe.

I cannot select in one click all photos/videos of a local album on iOS. 

### Describe the solution you'd like

I'd like a "Select All" button that would save me tremendous time. 

### Additional context

iOS app

**Comment by zeykafx** [comment]
On iOS, the media picker is [flutter_wechat_assets_picker](https://github.com/fluttercandies/flutter_wechat_assets_picker). Unfortunately, it doesn't seem to support selecting all images in a directory.
