### ISSUE TITLE
Feature request: Text to Clipboard share

### ISSUE THREAD

**Issue by decipher3114** [localsend/localsend#184]
### Is your feature request related to a problem? Please describe.

The current implementation creates a text file in the reciever device, that is very unconvinient.

### Describe the solution you'd like

When we share the text, it gets shared to the reciever and it will be saved to device's clipboard.

### Describe alternatives you've considered

Also, we can provide a pop-up containing options `Text file` and `Clipboard`, so that we can choose which way to go.

**Comment by Tienisto** [comment]
In `v1.7.0` there should be a dialog instead of a text file
