### ISSUE TITLE
Feature request (Auto-download enabled only for favorite devices)

### ISSUE THREAD

**Issue by srujanb** [localsend/localsend#1845]
### Is your feature request related to a problem? Please describe.

I want to enable auto-download feature but since there are no notifications, I'm afraid I'll received unexpected files when on a public network and not know about it. 

### Describe the solution you'd like

One of the solutions I can think of is enabling auto-download only for favorite devices so that the auto-download works only for my own devices.

**Comment by Tienisto** [comment]
This is part of the next release (1.16.0) https://github.com/localsend/localsend/blob/main/app/assets/CHANGELOG.md
