### ISSUE TITLE
Bug report:Huawei Matepad11 Harmony 3.0 system receives apk files and displays a gray screen, which cannot be accepted.

### ISSUE THREAD

**Issue by Benjamin-Watson0** [localsend/localsend#186]
### Describe the bug

Huawei Matepad11 Harmony 3.0 system receives apk files and displays a gray screen, which cannot be accepted.

### To reproduce

1. Go to 'Select apk file'
2. Click on 'Huawei equipment'
3. Scroll down to '...'
![image](https://user-images.githubusercontent.com/112467275/220255494-2a27fe89-e3df-4ddb-848f-ca01842e393c.png)

![Screenshot_20230221_132255_org localsend localsend_app](https://user-images.githubusercontent.com/112467275/220255194-1c67b1e7-408f-4a7a-8dcc-c877670dcf28.jpg)

### Expected behavior

Ask whether to accept the file

### Screenshots

![image](https://user-images.githubusercontent.com/112467275/220255494-2a27fe89-e3df-4ddb-848f-ca01842e393c.png)

![Screenshot_20230221_132255_org localsend localsend_app](https://user-images.githubusercontent.com/112467275/220255194-1c67b1e7-408f-4a7a-8dcc-c877670dcf28.jpg)

### Desktop (please complete the following information)

- windows
- 11

### Smartphone (please complete the following information)

- Huawei matepad 11
- Huawei Harmony os 
- 3.0

**Comment by Benjamin-Watson0** [comment]
I tried other files, but it still doesn't work.I think it has nothing to do with the file format.

**Comment by Tienisto** [comment]
Are you using `v1.6.1`? Can you try the latest version `v1.7.0`?

**Comment by Tienisto** [comment]
Possible duplicate of #37

**Comment by Benjamin-Watson0** [comment]
I tried it. Version 1.7 is good. Thank you for your help.😉 (F-droid did not update version 1.7, so I mistakenly thought that it had not released a new version.)
Next time, I will search in advance to ensure that the issues is not resubmitted.
