### ISSUE TITLE
Update App Icons with New Styling

### ISSUE THREAD

**Issue by KISHORE-KUMAR-S** [localsend/localsend#1861]
### Feature Request:
The current app icons feel outdated and could benefit from a more modern design. Updating the icons will not only improve the app's overall appearance but also make it more visually appealing and consistent with current design trends.

### Suggestions:
Utilize free, open-source icon libraries for both Android and iOS.

**Comment by Tienisto** [comment]
The app uses Material Icons that are also used in Google Maps and Gmail. I don't see an issue here
