### ISSUE TITLE
Bug report: Media Selection functionality is not working in Android

### ISSUE THREAD

**Issue by KISHORE-KUMAR-S** [localsend/localsend#1862]
### Describe the bug

Media Selection functionality is not working as expected on the Send Page.

### To reproduce

1. Click on 'Send' in Navigation Bar.
2. Click on 'Media' in Selection section.
3. See error

### Expected behavior

When the "Media" option is clicked, the user should be presented with a dialog or window to select Photos and Videos from their device for upload.

### Screenshots

![248aeaf8-a63b-423c-8e8d-7f4cf7f8440f](https://github.com/user-attachments/assets/4aaf906e-d479-4e07-89d5-3d1bae2b2eef)

### Smartphone (please complete the following information)

- Version: Android 14

**Comment by Tienisto** [comment]
What is shown instead?

**Comment by KISHORE-KUMAR-S** [comment]
> What is shown instead?

It's doesn't react when I click.
