### ISSUE TITLE
[Feature Request] Obtain permission "Install from unknown sources" when opening an apk

### ISSUE THREAD

**Issue by DaisyF8** [localsend/localsend#188]
### Is your feature request related to a problem? Please describe.

I installed localsend via F-droid on Android TV.  I use it to send apk I want to sideload to the TV.

When the apk is received in the historylist of LocalSend I can't install it by clicking open.

LocalSend I think is missing the "install from unknown sources"-permission.  In other apps, you get a message asking to enable the permission.  LocalSend doesn't prompt for this.

### Describe the solution you'd like

Prompt for android permission "install from unknown sources" and obtain it.

### Describe alternatives you've considered

I install the apk by leaving LocalSend and using a file explorer

**Comment by Tienisto** [comment]
Added in `v1.8.0`

**Comment by DaisyF8** [comment]
Nice and thanks.
