### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NikIsAwesome** [localsend/localsend#1889]
### Is your feature request related to a problem? Please describe.

When sending images from an iPhone to a windows 10 PC the default format for ios images is HEIF which is annoying to use. This is not an issue with the local send app, rather the default image format on ios.

### Describe the solution you'd like

It would be nice if there was a option in the advance settings to automatically convert images and videos send from mobile devices to be converted into more compatible formats like jpeg and mp4.

### Describe alternatives you've considered

as of now I have changed the default format on my iPhone to "most compatible"  and when I'm sending older images I have to use an image converter or handbrake to make the formats more compatible with the editing software I'm using/

**Comment by Tienisto** [comment]
This is currently out of scope because LocalSend currently doesn't have any encoders.
See #949
