### ISSUE TITLE
proper window decorations on KDE

### ISSUE THREAD

**Issue by KraXen72** [localsend/localsend#1922]
### Is your feature request related to a problem? Please describe.

this is how the window decorations look compared to a native qt app
![image](https://github.com/user-attachments/assets/624c7ebe-481c-47ee-b07e-87bb680f6c12)

obviously they're not going to be perfect, but can something be done so it's not that thick?

### Describe the solution you'd like

better window decorations

### Describe alternatives you've considered

living with this

**Comment by ImxTreme21** [comment]
You can set your own window decorations in plasma settings and problem solved.
![image](https://github.com/user-attachments/assets/991deb6c-ff66-4a6a-a67e-0637e0ab3657)

**Comment by thatLeaflet** [comment]
This is possible via this merge: https://github.com/localsend/localsend/pull/669

Launching with the environmental variable `GTK_CSD=0` disables the CSD.

**Comment by KraXen72** [comment]
okay, this works. please document this.

**Comment by KraXen72** [comment]
the first commadn worked, thanks

**Comment by KraXen72** [comment]
it would be nice if this was documented.
