### ISSUE TITLE
[Feature request] add keyboard shortcut for exiting

### ISSUE THREAD

**Issue by hellodword** [localsend/localsend#194]
### Is your feature request related to a problem? Please describe.

On linux, APPs often use `Control+Q` or `Control+W` or `ESC` for exiting/closing.

I'm using a window manager i3wm. If I want to exit localsend, I need to [kill the window of localsend with `$mod+shift+q`](https://i3wm.org/docs/userguide.html#_closing_windows).

### Describe the solution you'd like

Add keyboard shortcuts configuration.

**Comment by Tienisto** [comment]
Thanks for the issue.

Adding a separate setting will complicate the UI. So `Control+Q` will be the default on Linux.

Implemented in 9cd3286335a97e7f09ab202c1d7fcbf5debd8d61
