### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by miracle859** [localsend/localsend#195]
### Describe the bug

When you send one photo or video. After you sent. And press done. 
the video still on the send area. You have to go to the edit and delete it 
otherwise, if you send another video. The first video will be sent again. dublicat for the first video. 

### To reproduce

1. Go to '...'send
2. Click on '...'video and send  
3. Scroll down to '...'press done
5. then send another video. the first video still exist

### Expected behavior

Please clear the file sent out. 
after done for to send.  The previous file should be clear and then we can send new file

**Comment by miracle859** [comment]
I send file from Android to PC and find this bug

**Comment by Tienisto** [comment]
This is fixed in `v1.8.0`
