### ISSUE TITLE
Transfer to MacOS hangs if I change the Save path.

### ISSUE THREAD

**Issue by kane1985** [localsend/localsend#1971]
### Describe the bug

When I change the Download folder on MacOS to another folder than the default, the transfer to Mac only works as long as I don't close LocalSend. If I restart the App , the transfer hangs at around 90% and It only works again, when I change the download folder to default.

The error is also discussed on [https://github.com/localsend/localsend/discussions/1724](url)

### To reproduce

1. Go to '.Settings'
2. Change Download path to another Folder
3. Restart app
4. See error as quoted above

### Expected behavior

Different download Folder works after restart of LocalSend.

### Screenshots

<img width="904" alt="LocalSendError Sending" src="https://github.com/user-attachments/assets/95382a9d-86dd-438d-a4bc-f9a8f181c097">

### Desktop (please complete the following information)

- OS MacOS 15.01 Sonoma

### Smartphone (please complete the following information)

Google Pixel ( Pro Android 15
also on Google Pixel 7a Android 14

**Comment by kane1985** [comment]
Yes I do.
And due to your question i tried the dmg-Version and it seems it does not have the problem. 
The Size of both version looks to be different: 
65.4 MB for the App Store VErsion and 65.1 MB for the DMG version.

So there could be a difference in both versions (Apps Store and DMG) (both with the current release number).

**Comment by Tienisto** [comment]
The DMG version is currently not sandboxed which means it has full access to your hard drive. The app store version is required to be sandboxed. I guess there is a bug regarding persistent permissions in a sandboxed environment

**Comment by Tienisto** [comment]
@ShlomoCode In my latest commit on main branch, I requested permissions. However, it was only alive while the app is running. As soon as I restarted the app `requestFolderAccess` fails. Do you know why / Have a better solution?

**Comment by ShlomoCode** [comment]
@Tienisto It's probably like https://github.com/localsend/localsend/pull/1739#issuecomment-2334917878 (https://github.com/localsend/localsend/pull/1739/commits/de35bc89a451d3cf5b8382b5bdc3621b2e94dde6)
We actually need to save a file bookmark so that macOS will recognize it as "selected path" and allow us to request access for it.
Do you need help with the implementation of this?

**Comment by Tienisto** [comment]
Sure @ShlomoCode

**Comment by ShlomoCode** [comment]
In fact, since this is the same application (and not a transfer between applications through a shared group), we can save security-scoped bookmark.
