### ISSUE TITLE
Web share (without internet)

### ISSUE THREAD

**Issue by jerryn70** [localsend/localsend#198]
Having a web share option (without internet) in this app is good feature to send files to others those who don't have localsend app installed on their phone .

Currently we have to force other's to install localsend app on their device to send file. With this feature that problem will be solved. There is an app called 'sharex' on fdroid with this feature you can check it out for reference.

**Comment by yurenchen000** [comment]
https://github.com/localsend/protocol/blob/284d95af/README.md#3-file-transfer-http

I guess with current protocol, 
  browser can upload(send) file to localsend app easily.(just little web page, and manually input app address)

 but is unable to download(receive) file yet

**Comment by Tienisto** [comment]
This feature is planned for the next release `v1.9.0`. Maybe in a few weeks but it depends how much time I have

**Comment by septs** [comment]
Compatibility with snapdrop[^1] is a possible low-cost solution

https://github.com/RobinLinus/snapdrop/blob/master/server/index.js

[1]: https://snapdrop.net

**Comment by Tienisto** [comment]
@septs Isn't Snapshot using WebRTC?

**Comment by yurenchen000** [comment]
yes, 
It need a common p2p server for peer-to-peer discover.

**Comment by Tienisto** [comment]
We don't need p2p discover when the file transfer only happens in one direction. This avoids scenarios where one client has no permission to start a HTTP server.

**Comment by Tienisto** [comment]
@yurenchen000 Yes, WebRTC is the reason why LocalSend has been created. I wanted a solution where you don't need any external server.

**Comment by yurenchen000** [comment]
yes,
 that's why we are here :joy:

**Comment by Tienisto** [comment]
Implemented. Will be released in the coming `v1.9.0` update.

**Comment by JannetGen** [comment]
If you're looking for a way to share files over WiFi without needing everyone to install a specific app, you might want to check out [[FileMonkey](https://filemonkey.org/)]. It allows device-to-device file transfers directly through a browser, using the same WiFi network, and doesn't require an internet connection. This could be a handy interim solution until the new feature is released in LocalSend.
