### ISSUE TITLE
Connection failure if the subnet mask is 255.255.0.0

### ISSUE THREAD

**Issue by rzhangbq** [localsend/localsend#199]
### Describe the bug

It seems that the app does not work if the LAN has a subnet mask of 255.255.0.0 (i.e. the last 2 series of number both belongs to the LAN).
e.g. When a device is allocated 10.89.169.124, and the other device is 10.89.176.89, both devices belongs to the LAN, but they cannot connect with each other.

### To reproduce

Use a router that support choosing a subnet mask of 255.255.0.0, connect two devices to the network and try to send files through the app.

### Expected behavior

Could connect successfully.

**Comment by rzhangbq** [comment]
Thanks for your reply. This method does work for me.
However, it is still not convenient to check my IP address all the time, especially when the router is set to DHCP mode. At the same time, at school or at workplace, subnet mask of 255.255.0.0 or even 255.0.0.0 are note rare. 
Could you help fixing the problem?
Thanks so much!

**Comment by Tienisto** [comment]
This app has 2 methods to discover other devices:

- Send a basic http request to each member: This only works for 255.255.255.0. On larger subnets this is not practical because there would be just too many requests.

- Send a broadcast (multicast to be exact), this is implemented in `v1.7.0` and should work in any subnet.

The second solution is faster and more general so I am wondering why this does not work on your side.

**Comment by rzhangbq** [comment]
I think this has something to do with the multicast IP address. It seems that you are using 244.0.0.0/24, so it might only work with subnet mask of 24?

**Comment by Tienisto** [comment]
244.0.0.x is reserved for localhost as far as I know. You could try to change the multicast address to 244.0.1.x or something else

**Comment by Tienisto** [comment]
You can checkout the multicast logs in 

About -> Debugging -> Multicast

**Comment by Tienisto** [comment]
Refer #175

**Comment by rzhangbq** [comment]
Hi,
Thanks for your reply. I have tried clicking the sync button and it does not work as #175 .
It seems that it is not showing other IP segments (my other device has an IP address of 10.89.69.111).
<img width="712" alt="Screen Shot 2023-02-25 at 8 01 59 PM" src="https://user-images.githubusercontent.com/82951500/221355743-0568a2a4-50b2-40b9-b2d6-94847a1423a9.png">
<img width="705" alt="Screen Shot 2023-02-25 at 8 02 36 PM" src="https://user-images.githubusercontent.com/82951500/221355762-a2279ee0-5b73-46c5-930e-2a61d3db07d4.png">
<img width="701" alt="Screen Shot 2023-02-25 at 8 03 31 PM" src="https://user-images.githubusercontent.com/82951500/221355828-f065d574-e984-409c-b007-e801abad2a8b.png">

**Comment by xiaozhubin** [comment]
my pc can receive UDP from my phone, but my phone cannot receive udp from my pc.

**Comment by Tienisto** [comment]
Closed in favor of #525
