### ISSUE TITLE
unable install latest 1.16 apk in my phone

### ISSUE THREAD

**Issue by cisko99za** [localsend/localsend#1993]
### Describe the bug

unable install latest 1.16 apk in my phone (error says not compatible phone. but on my phone i have android 14)
i can install from google play, old 1.15.4 version, but i can't update to 1.16 apk, downloaded from github page

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

update from apk to latest 1.16 version

### Desktop (please complete the following information)

win 11 x64

### Smartphone (please complete the following information)

android 14

**Comment by Tienisto** [comment]
What exact apk did you download? Usually, it should be `LocalSend-1.16.0-android-arm64v8.apk` for armv8
