### ISSUE TITLE
Add all platform binaries to GitHub Releases

### ISSUE THREAD

**Issue by mariobrostech** [localsend/localsend#20]
Hi,

Can you please consider adding other platforms to the GitHub releases page? I don't like using my platform's app store and try to avoid it whenever possible. Having Windows and macOS binary releases, alongside Linux AppImage and Android APK builds would be much appreciated.

Thanks in advance for your help!

**Comment by Tienisto** [comment]
I am a big fan of official stores because of auto updates though.
But sure, I can do that in the next release!

**Comment by mariobrostech** [comment]
I completely understand that, but having the option to download binary releases would be nice. Besides, providing these releases would allow package managers such as winget (for Windows) and Homebrew Cask (for macOS) to manage updates, all without the requirement of dealing with app stores.

**Comment by meiMingle** [comment]
I also agree, because the Windows Store does not work properly in some special office environments. because sometimes the company restricts the use of the extranet

**Comment by Tienisto** [comment]
I have added all binaries in the `v1.6.1` release. Let me know, if something is missing.
