### ISSUE TITLE
Save media to gallery doesn't work on iOS

### ISSUE THREAD

**Issue by k3v1nwrld** [localsend/localsend#200]
### Describe the bug

Title basically explains it all. Whenever I send a photo from my pc to my iOS device, it doesn't save at all unless I disable the Save media to gallery option

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Save said media to the gallery

### Desktop (please complete the following information)

-OS: Windows 10

### Smartphone (please complete the following information)

-Device: iPhone 11 Pro
-OS: iOS 15.0.2
-Version: 1.7.0

**Comment by Tienisto** [comment]
What is the error message on your iPhone?

**Comment by k3v1nwrld** [comment]
> What is the error message on your iPhone?
> 
> 
> 
> You probably forgot to give LocalSend write access to the gallery when the dialog was shown.

I've given it full access to my photo library. As for the error code, there isn't one. It basically acts as if it was saved, but it's just not.

**Comment by Tienisto** [comment]
I just tested this. It does act as if it was saved when the permission was not granted (which is a bug for sure). But as soon as I grant the permission, it worked on my device. Weird.

<img width="391" alt="Screenshot 2023-02-24 at 00 32 17" src="https://user-images.githubusercontent.com/38380847/221055150-dbe43b5f-ce4a-4bbd-a107-409bac65de8f.png">

**Comment by k3v1nwrld** [comment]
> I just tested this. It does act as if it was saved when the permission was not granted (which is a bug for sure). But as soon as I grant the permission, it worked on my device. Weird.
> 
> 
> 
> <img width="391" alt="Screenshot 2023-02-24 at 00 32 17" src="https://user-images.githubusercontent.com/38380847/221055150-dbe43b5f-ce4a-4bbd-a107-409bac65de8f.png">
> 
> 

It works now all of the sudden. It didn't work with one specific photo which I was trying to send over to my device. My bad...

**Comment by Tienisto** [comment]
Nice! Do you know what makes this particular photo special? iPhones only support HEIC and JPEG as far as I know.

**Comment by k3v1nwrld** [comment]
> Nice! Do you know what makes this particular photo special? iPhones only support HEIC and JPEG as far as I know.

No idea tbh. It was a random JPEG photo which I saved from some website
