### ISSUE TITLE
Share intent broken on iOS in 1.16.0

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#2002]
### Describe the bug

Trying to share from another app to LocalSend does not work in 1.16.0 anymore.

See https://github.com/localsend/localsend/discussions/2001

### To reproduce

1. Tap "Share" on another app
2. LocalSend opens, but file is not selected

### Expected behavior

File should be selected

**Comment by SlashDevSlash0** [comment]
Just updatet to 1.16.1 with no effect.
Sharing is still broken from third party apps, files or photos (via menu).
A short flicker on the screen but localsend-app is not coming up.

**Comment by Tienisto** [comment]
I'd love to resolve this bug, but it somehow works on my iPhone. It runs iOS 17, I will update to iOS 18 to see if there is a difference.

**Comment by Rakraor** [comment]
I’ve the same issue with iOS 18.1 and last version of LocalSend

**Comment by G3NSVRV** [comment]
hi. im new to this app, and yeah, it seems that the sharing action is not working on 18.1:

e.g. from Photos app, select a picture, share, localsend:

a window shows, but dissapears inmediately, without making any actions.

I could send a video about that if is not clear.

**Comment by Tienisto** [comment]
Okay, it seems that the iOS update from 17 to 18 broke the share action

**Comment by Tienisto** [comment]
The share library just published an update a few hours ago fixing this problem related to iOS 18 (https://pub.dev/packages/share_handler/changelog).

I will publish a hotfix release 1.16.2 for iOS now.

**Comment by talesm-y** [comment]
Hello, unfortunately this issue still persists on IOS 18. The share intent doesn't work consistently. Many times when you click share on IOS (e.g. notes app) the error appear again: a window shows, but disappears immediately, without forwarding the file to the app
