### ISSUE TITLE
Bug report rhttp can't be built reproducible for F-Droid

### ISSUE THREAD

**Issue by linsui** [localsend/localsend#2009]
### Describe the bug

In 1.16.0 rhttp is introduced. It can't be built reproducibly currently. We need to pin every toolchain used to build it. Currently it seems rust version and cargo-ndk version are not pinned.

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16328

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

rhttp can be built reproducibly

**Comment by Tienisto** [comment]
While I've developed rhttp, I just copied the Rust toolchain helper from https://pub.dev/packages/flutter_rust_bridge

I suspect that it ignores the `rust-toolchain.toml` specified in the root directory and just downloads the newest version

**Comment by linsui** [comment]
Can you pin the rust version in https://github.com/Tienisto/rhttp/blob/17c4b7344c79bbe4ba60db899a0595fda58cb8fb/rhttp/cargokit/build_tool/lib/src/builder.dart#L136 directly? And please add `RUSTFLAGS="--remap-path-prefix=$HOME/.cargo/=/.cargo/"` (maybe in https://github.com/Tienisto/rhttp/blob/17c4b7344c79bbe4ba60db899a0595fda58cb8fb/rhttp/cargokit/build_tool/lib/src/builder.dart#L162?) to remove the embeded home path.

**Comment by Tienisto** [comment]
I've added `--remap-path-prefix=$HOME/.cargo/=/.cargo/` but I didn't pin the Rust version because LocalSend is not the only user of the package.

However, I added a hacky way to read the `rust-toolchain.toml` file that is managed by LocalSend.

**Comment by linsui** [comment]
Thanks! Will see if it's easier to build reproducibly in the next version. :)

**Comment by licaon-kter** [comment]
If remap is not working, we can always just move folders around. We did this recently for an app that had `/root/.cargo`
