### ISSUE TITLE
Why is the transfer speed so slow?

### ISSUE THREAD

**Issue by DbuyCN** [localsend/localsend#2010]
### Is your feature request related to a problem? Please describe.

Transferring files from my Windows PC to my Android phone at a mere 1.2MB/S.

### Describe the solution you'd like

Why is the transfer speed so slow? I am transferring files from my Windows PC to my Android phone at a mere 1.2MB/S. 5G network environment, Gigabit NIC.

**Comment by Tienisto** [comment]
On Android, the bottleneck is mostly the disk write speed. Do you use a custom download location?

**Comment by Tienisto** [comment]
Closing in favor of #384
