### ISSUE TITLE
Connection error, tls handshake eof

### ISSUE THREAD

**Issue by yanthrikv** [localsend/localsend#2017]
### Describe the bug

While adding devices to favorites, it shows an error (see screenshot). Both from phone side and from windows side, the error happens.. using recent version on both devices. The app is allowed in firewall. No issue with sending/receiving files.. but adding favorites not working with an error... please help...
![LocalSend](https://github.com/user-attachments/assets/4fceced4-90b1-429b-a8c8-b752774581b0)

### To reproduce

Click on add to favorites
shows error

### Expected behavior

Succesfully added to favorites for easy connectivity

### Desktop (please complete the following information)

Windows 10 Pro 22H2

### Smartphone (please complete the following information)

Android 14

**Comment by Tienisto** [comment]
Did you change the encryption setting in advaced settings? Make sure to have the same encryption setting on both devices (both enabled or both disabled)

**Comment by yanthrikv** [comment]
> Did you change the encryption setting in advaced settings? Make sure to have the same encryption setting on both devices (both enabled or both disabled)

Great..!! It works.... Thank you for the support

**Comment by yanthrikv** [comment]
Thank you

**Comment by surfnet-niels** [comment]
I get the same error trying to sync between a macOS laptop and Android Phone. Both have encryption enabled. When I disable encruption on both I get another error: 
"RhttpUnknownException ... InCompleteMessage"

**Comment by bao-qian** [comment]
same issue. windows cannot send to ios 18.5 when no matter encryption is on or off. ios can send to ios, and ios can send to windows.
windows send to ios, encryption on, error "tls handshake eof "
windows send to ios, encryption on, error "RhttpUnknownException ... InCompleteMessage"

but windows can send to ios safari using share via link on windows localsend, no matter encryption is on or off.

definitely some cross platform bug.
