### ISSUE TITLE
Bug report IOS 1.16.1版本localsend无法在手机相册多选照片之后统一分享至localsend以发送到其他设备

### ISSUE THREAD

**Issue by vaio386064343** [localsend/localsend#2018]
### Describe the bug

IOS 1.16.1 无法在手机相册多选照片之后统一分享至localsend以发送到其他设备，这个功能再1.16.1之前的版本是可以实现的

### To reproduce

1. Go to 'IOS手机相册'
2. 多选照片后点击分享，选择localsend
3. 屏幕闪一下，无法跳转至localsend

### Expected behavior

正常情况下，应该多选照片，选择分享至localsend后可以跳转到localsend并可发送照片至其他设备

### Smartphone (please complete the following information)

-Device：iphone15
-OS：IOS 18.1
-Version：1.16.1

**Comment by Tienisto** [comment]
Please update to 1.16.2

**Comment by vaio386064343** [comment]
Thank you so much for your help! This solution worked perfectly.
