### ISSUE TITLE
Cant reiceve files on linux

### ISSUE THREAD

**Issue by BlueFox1616** [localsend/localsend#2050]
### Describe the bug

The phone takes a long time to discover the laptop and when trying to send something the laptop doesnt even reiceve the request

### To reproduce

Open the app on a nixos desktop go to recieve and try to send anything with your phone

### Expected behavior

The file gets send after the request is reiceved

### Desktop (please complete the following information)

 OS: NixOS 24.11.20241109.76612b1 (Vicuna) x86_64 

### Smartphone (please complete the following information)

Device; Pixel 8a
Android 15

**Comment by projjalm** [comment]
Do you have any firewall (like `ufw`) enabled/running?

**Comment by BlueFox1616** [comment]
it was a firewall issue which ports should i open exactly
???

**Comment by projjalm** [comment]
Go to Settings, enable Advanced settings at the bottom  
And you'll find the port under Network subheading  
Allow incoming on that.

**Comment by BlueFox1616** [comment]
I dont see any advanced settings i can probably allow them throught the config cause im on nixos .

**Comment by BlueFox1616** [comment]
Anyways i found the ports i need to open   networking.firewall.allowedTCPPorts = [ 53317 ];
  networking.firewall.allowedUDPPorts = [ 53317 ]; its this ones . I wound add it somewhere in the readme
