### ISSUE TITLE
Incorrect APP_NAME on macOS

### ISSUE THREAD

**Issue by fffelix-jan** [localsend/localsend#2059]
### Describe the bug

The window name when right-clicking the app in the Dock on macOS shows as "APP_NAME".

### To reproduce

1. Install LocalSend on macOS
2. Open it
3. Right-click the app icon in the Dock
4. The incorrect name "APP_NAME" gets displayed

### Expected behavior

"LocalSend" or a relevant name or status indication should be displayed.

### Screenshots

![image](https://github.com/user-attachments/assets/81e4d3eb-07d6-495c-ac92-a42a278f5668)

### Desktop (please complete the following information)

- OS: macOS 12.7.6
- App version: 1.16.1

**Comment by Tienisto** [comment]
I cannot reproduce this

**Comment by MarianoRamos2684** [comment]
same mistake in MacOs 11.7

**Comment by fffelix-jan** [comment]
Could it have to do with language or region settings? My computer is on English (Canada).

**Comment by Tienisto** [comment]
The title should be untranslated. But my guess is that the old macos version is causing the problem.
