### ISSUE TITLE
Other devices can detect for the Windows platform, but the Windows platform cannot detect for other devices.

### ISSUE THREAD

**Issue by Mcayear** [localsend/localsend#2064]
### Describe the bug

Windows platform cannot detect for other devices.

Trying to link manually on the Windows platform a timeout.
```
[RhttpTimeoutException] Request timed out. URL: https://192.168.1.3:53317/api/localsend/v1/info
```

but can preview JSON data at browser.

![image](https://github.com/user-attachments/assets/f5a27fe7-891d-488b-993d-fe2708b59e90)

**Firewall is always off.**

On the Windows platform, sending doesn't work properly because it can't detect, **but receiving works fine**.

### To reproduce

Prepare an Android phone and a Windows laptop.
Open LocalSend at the same time.
Android devices can discover Windows devices, but Windows devices can't discover any devices.

### Expected behavior

Windows platform can discover any device.

## Windows 10 Device
Version: 1.16.1

## Android Device
Android: 15
Version: 1.16.1

**Comment by freeok** [comment]
Same problem

**Comment by BlurryLight** [comment]
same problem in 1.16.1.
I random picked an old version and downgraded to 1.11, then everything works fine.

**Comment by homewayma** [comment]
Same problem too!
1.11 works fine!

**Comment by Mcayear** [comment]
Resolved.

It works fine by turning off `encryption` in the `advanced settings`.

> Note that `encryption` needs to be turned off for all clients.

**Comment by zmweske** [comment]
This same issue popped up for me on 1.17.0 (windows and android). I was also able to reach the phone's info endpoint with https from a browser on the windows machine but localsend on the windows machine did not want to see the phone until encryption was disabled for both devices.

**Comment by wish-i-wasnt-here** [comment]
Me too but Linux to iPhone. Info:
- Debian 13 (LocalSend 1.17.0+58) apt installed from .deb with ufw firewall modified like readme
- iOS 16.7.12 (LocalSend 1.17.1)
- Both on VPN

Issue:
- Laptop can't discover phone automatically or with refresh/scan button
- Manually entering IP address creates Error `[RhttpTimeoutException] Request timed out. URL: https://[my address]:53317/api/localsend/v1/info`
- Phone has discovered laptop though

Workaround successful:
- Turned off `Encryption` then `Restart`ed `Server` in `Advanced settings`
- (A message about changing from https to http resulted, and the phone is now discovered on the laptop)

But why? And why is this issue 'Resolved'? Shouldn't I want https? By chance what I'm sharing right now is itself encrypted so I'm not too worried about this file, but in the future,...?
