### ISSUE TITLE
Windows pasted image to .png

### ISSUE THREAD

**Issue by Misaka2298** [localsend/localsend#2080]
### Is your feature request related to a problem? Please describe.

The .bmp image size is just too big and very slow to send, but .png performs much better!

### Describe the solution you'd like

Paste the image format in windows localsend to .png instead of .bmp

### Describe alternatives you've considered

none

### Additional context

Currently on the windows side, only images pasted from the clipboard are forced to be converted to .bmp, sending the image file directly will keep it in the original format, what I mean here is that it is converted to .png when it is pasted from the clipboard.

**Comment by BrianMwit** [comment]
Looks like this has already been reported in https://github.com/localsend/localsend/issues/872
