### ISSUE TITLE
Can i paste picture directly on localsend for windows

### ISSUE THREAD

**Issue by shui-dun** [localsend/localsend#210]
### Is your feature request related to a problem? Please describe.

When I **take a screenshot** or copy an image on a web page, I must first find a way to save it as a file (for example, first paste the picture into Word, and then click "save as"), and then send it through localsend

### Describe the solution you'd like

I hope that localsend can directly read the contents of the clipboard (picture, better if it can be file in any format), and then I can send it.

### Describe alternatives you've considered

Add a paste button or allow to paste directly through ctrl+v

**Comment by saccohuo** [comment]
+1
