### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by CloverAn** [localsend/localsend#2101]
### Describe the bug

![1732773489240](https://github.com/user-attachments/assets/d5e64ae8-5bba-4f2c-a370-37c8d6b0effb)
![1732773489237](https://github.com/user-attachments/assets/b717f951-cc65-432a-a1c7-a943dd18d09a)

### To reproduce

Both issues arise from the same situation. One is that when sending 1.16.1pc to 1.16.0 Android, there was an Android disconnection for the first time and an error occurred when restarting the server. The second one is to close and reopen Android, and then send the Android installation package 1.16.1 again, but it keeps getting stuck.

### Expected behavior

#

**Comment by Tienisto** [comment]
This bug has been resolved in v1.16.1 on Android. See #1992
