### ISSUE TITLE
Localsend on dual boot linux/windows laptop

### ISSUE THREAD

**Issue by roy0581** [localsend/localsend#2124]
I have an issues using Localsend on my Acer Dual boot linux/windows laptop. On Linux Mint it works perfect and sees my other PC and also my smartphone. When installed on Windows it sses my other devices BUT both my other PC and smartphone cannot find my Acer Laptop. I have given different names to distinguish between Linux and Windows but still no joy. Reverted to same name and still nothing. Any hints why and how to make it work?? Thanks

**Comment by roy0581** [comment]
Thanks....resolved. Firewall issue from within Avast One on my laptop.

**Comment by JustAdreamerFL** [comment]
@roy0581 can you close this issue?
