### ISSUE TITLE
LocalSend link from Windows Microsoft Apps is broken

### ISSUE THREAD

**Issue by hao-lh** [localsend/localsend#214]
Neither clicking icon from official website:
https://localsend.org/

OR

using link from following online search engine would not work
https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=8j+DzxhlHUumO6CZ.0.2

Could you help check what's going on and fix this?
Thanks.

**Comment by Tienisto** [comment]
For whatever reason, the account was suspended. You can install it via `winget install LocalSend` for now. Alternatively, you can download it from the releases

**Comment by hao-lh** [comment]
Sorry to hear that.

Also, When building next release, is it possible to have an installer for Windows platform as well, current release for windows is a portable version I think.
Thanks.

**Comment by Tienisto** [comment]
You can use the `msix` installer

**Comment by hao-lh** [comment]
@Tienisto Thanks, problem resolved!!
