### ISSUE TITLE
Feature request:Add the "Share via Localsend" option to the share menu of your iOS device.

### ISSUE THREAD

**Issue by ShawayL** [localsend/localsend#2154]
### Is your feature request related to a problem? Please describe.

If I want to share a photo with a Windows device on my iPhone device, I have to open the LocalSend app to select this photo sharing, is there a way to add the "Share via Localsend" option in the share menu of my iPhone device to quickly share the file of my choice

### Describe the solution you'd like

Add the "Share via Localsend" option to the share menu on my iOS device, and when I select a file and then press and hold the share button, I can quickly share via Localsend

**Comment by AdityaGarg8** [comment]
It's already there.

<img width="1180" alt="image" src="https://github.com/user-attachments/assets/9b8b6a43-7e25-4310-974f-5909e7b565ad" />

**Comment by ShawayL** [comment]
Thanks for reminding me, I didn't notice the app icon above, it's on the far right

**Comment by AdityaGarg8** [comment]
> Thanks for reminding me, I didn't notice the app icon above, it's on the far right

No worries, even I had difficulty in finding this the first time

**Comment by oldman20** [comment]
I have 2 devices iPad Mini 5 (iPados 17.0) & iPad Mini 6 (iPados 15.6). Localsend displays in the Share menu on the mini 5 17.0, while at the mini 6 15.6 it cannot appear in the Share menu
I am not sure if there is any restriction on iOS version, but I have discovered a similar energy app is Blip [blip.net] or TaiScale that can be displayed in the menu share on my iPados 17.0 & 15.6. Hopefully the developer can improve this in IOADOS/ iOS lower than 17.0
