### ISSUE TITLE
Bug report: Build failure

### ISSUE THREAD

**Issue by HardikRa** [localsend/localsend#2159]
### Describe the bug

Build failing on running 
`flutter pub run build_runner build -d`

### To reproduce

1. Install the following versions of software as per `flutter doctor -v`

> [✓] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.22631.4602], locale en-IN)
>     • Flutter version 3.27.1 on channel stable at C:\DevPackages\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 17025dd882 (7 days ago), 2024-12-17 03:23:09 +0900
>     • Engine revision cb4b5fff73
>     • Dart version 3.6.0
>     • DevTools version 2.40.2
> 
> [✓] Windows Version (Installed version of Windows is version 10 or higher)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at C:\Android\SDK
>     • Platform android-35, build-tools 34.0.0
>     • ANDROID_HOME = C:\Android\SDK
>     • Java binary at: C:\Users\Hardik Raheja\.jdks\jbr-17.0.9\bin\java
>     • Java version OpenJDK Runtime Environment JBR-17.0.9+8-1166.2-nomod (build 17.0.9+8-b1166.2)
>     • All Android licenses accepted.
> 
> [✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> 
> [✗] Visual Studio - develop Windows apps
>     ✗ Visual Studio not installed; this is necessary to develop Windows apps.
>       Download at https://visualstudio.microsoft.com/downloads/.
>       Please install the "Desktop development with C++" workload, including all of its default components
> 
> [✓] Android Studio (version 2024.2)
>     • Android Studio at C:\Program Files\Android\AndroidStudio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
> 
> [✓] VS Code (version 1.96.1)
>     • VS Code at C:\Users\Hardik Raheja\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.102.0
> 
> [✓] Connected device (3 available)
>     • SM S918U1 (mobile) • adb-R5CWB31RZJD-4oOi1O._adb-tls-connect._tcp • android-arm64  • Android 14 (API 34)
>     • Windows (desktop)  • windows                                      • windows-x64    • Microsoft Windows [Version 10.0.22631.4602]
>     • Edge (web)         • edge                                         • web-javascript • Microsoft Edge 131.0.2903.99
> 
> [✓] Network resources
>     • All expected network resources are available.

3. Run `flutter pub get`
4. Run `flutter pub run build_runner build -d`
5. See error

> Deprecated. Use `dart run` instead.
> Building package executable... (14.9s)
> Built build_runner:build_runner.
> [INFO] Generating build script completed, took 725ms
> [INFO] Precompiling build script... completed, took 7.4s
> FlutterGen v5.8.0 Loading ...
> Reading FlutterGen options from pubspec.yaml
> [INFO] Building new asset graph completed, took 2.7s
> [INFO] Checking for unexpected pre-existing outputs. completed, took 5ms
> [SEVERE] slang_build_runner on assets/i18n/strings.json:
> 
> "settingsTab.receive.requirePin" in <az> is linked to "webSharePage.requirePin" but "webSharePage.requirePin" is undefined.
> [INFO] Generating SDK summary completed, took 6.3s
> [INFO] 28.2s elapsed, 246/251 actions completed.Generated: lib\gen\assets.gen.dart
> FlutterGen finished.
> [INFO] Running build completed, took 43.9s
> [INFO] Caching finalized dependency graph completed, took 158ms
> [SEVERE] Failed after 44.0s
> Failed to update packages.
> 

### Expected behavior

The build should succeed and then I should be able to run the application. Kindly let me know if I am using incompatible versions for any part and it is noted as a known bug

**Comment by HardikRa** [comment]
I did try that and the build fails as well, here is the output for `flutter run`
(Side Note: Do I need to have rust installed? Could not read that as a pre-requisite)

Here is the full output 

> Package open_filex:linux references dartPluginClass:linux as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: linux: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:macos references dartPluginClass:macos as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: macos: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:windows references dartPluginClass:windows as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: windows: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:linux references dartPluginClass:linux as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: linux: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:macos references dartPluginClass:macos as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: macos: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:windows references dartPluginClass:windows as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: windows: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:linux references dartPluginClass:linux as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: linux: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:macos references dartPluginClass:macos as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: macos: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:windows references dartPluginClass:windows as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: windows: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:linux references dartPluginClass:linux as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: linux: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:macos references dartPluginClass:macos as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: macos: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Package open_filex:windows references dartPluginClass:windows as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: windows: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> 
> Launching lib\main.dart on SM S918U1 in debug mode...
> Warning: This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> Package open_filex:linux references dartPluginClass:linux as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: linux: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> Package open_filex:macos references dartPluginClass:macos as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: macos: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> Package open_filex:windows references dartPluginClass:windows as the default plugin, but the package does not exist, or is not a plugin package.
> Ask the maintainers of open_filex to either avoid referencing a default implementation via `platforms: windows: default_package: dartPluginClass` or create a plugin named dartPluginClass.
> 
> Note: C:\Users\Hardik Raheja\AppData\Local\Pub\Cache\hosted\pub.dev\device_apps-2.2.0\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> The system cannot find the path specified.
> The system cannot find the path specified.
> The system cannot find the file specified.
> The system cannot find the file specified.
> Running pub get in "C:\Users\Hardik Raheja\Documents\development\localsend\app\build\rhttp\build\build_tool"
> Resolving dependencies...
> Downloading packages...
> + adaptive_number 1.0.0
> + args 2.4.2 (2.6.0 available)
> + async 2.12.0
> + build_tool 1.0.0 from path C:\Users\Hardik Raheja\AppData\Local\Pub\Cache\hosted\pub.dev\rhttp-0.9.2\cargokit\build_tool
> + collection 1.18.0 (1.19.1 available)
> + convert 3.1.1 (3.1.2 available)
> + crypto 3.0.3 (3.0.6 available)
> + ed25519_edwards 0.3.1
> + fixnum 1.1.1
> + github 9.17.0 (9.24.0 available)
> + hex 0.2.0
> + http 1.1.0 (1.2.2 available)
> + http_parser 4.0.2 (4.1.1 available)
> + json_annotation 4.9.0
> + logging 1.2.0 (1.3.0 available)
> + meta 1.16.0
> + path 1.8.0 (1.9.1 available)
> + petitparser 5.4.0 (6.0.2 available)
> + source_span 1.10.0 (1.10.1 available)
> + string_scanner 1.4.1
> + term_glyph 1.2.2
> + toml 0.14.0 (0.16.0 available)
> + typed_data 1.4.0
> + version 3.0.0 (3.0.2 available)
> + yaml 3.1.2 (3.1.3 available)
> Changed 25 dependencies!
> 14 packages have newer versions incompatible with dependency constraints.
> Try `dart pub outdated` for more information.
> Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
> SEVERE: ================================================================================
> SEVERE: Cargokit BuildTool failed with error:
> SEVERE: --------------------------------------------------------------------------------
> SEVERE:
> SEVERE: rustup not found in PATH.
> SEVERE:
> SEVERE: Maybe you need to install Rust? It only takes a minute:
> SEVERE:
> SEVERE: https://www.rust-lang.org/tools/install
> SEVERE:
> SEVERE: ================================================================================
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/df4c969b3fc261decf656e616cd5f432/transformed/fragment-1.7.1-api.jar!/META-INF/fragment_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/819d407dd7bfbc5cdbbb8a0440682b4e/transformed/jetified-activity-1.8.1-api.jar!/META-INF/activity_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/2fac300d285cd31a7e1950a3aa42355d/transformed/jetified-lifecycle-livedata-core-ktx-2.7.0-api.jar!/META-INF/lifecycle-livedata-core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/f93275dca6ea38496776026fee411eea/transformed/lifecycle-livedata-2.7.0-api.jar!/META-INF/lifecycle-livedata_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/2c9ab67ac566bb14e9b6ea29a0e91ab3/transformed/lifecycle-viewmodel-2.7.0-api.jar!/META-INF/lifecycle-viewmodel_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/59eb34b6cc53810dcc234976fdf9f1ef/transformed/lifecycle-livedata-core-2.7.0-api.jar!/META-INF/lifecycle-livedata-core_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/26a475b25b565f78295147fa43919415/transformed/jetified-lifecycle-viewmodel-savedstate-2.7.0-api.jar!/META-INF/lifecycle-viewmodel-savedstate_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/dd114eed19ac1a6d51bbb6ac08cd75f0/transformed/jetified-core-ktx-1.13.1-api.jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/cf0e6ef3c82be09fbfd96c2f8ec7d023/transformed/core-1.13.1-api.jar!/META-INF/core_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/8a3d527175339427767784f478cc4856/transformed/lifecycle-runtime-2.7.0-api.jar!/META-INF/lifecycle-runtime_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/a187d1c13911c588aba92d239d9d1ff3/transformed/jetified-lifecycle-process-2.7.0-api.jar!/META-INF/lifecycle-process_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.7.0/85334205d65cca70ed0109c3acbd29e22a2d9cb1/lifecycle-common-2.7.0.jar!/META-INF/lifecycle-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/bfdb5dba35bc35f6e2e29c82c8cabb9c/transformed/jetified-savedstate-1.2.1-api.jar!/META-INF/savedstate_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/8dc7621c5ae097988f94d2ca68cdc7f3/transformed/jetified-window-1.2.0-api.jar!/META-INF/window_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/35c57863c820d0d5fb18ec5864ec4310/transformed/jetified-window-java-1.2.0-api.jar!/META-INF/window-java_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/a420e25d3cca5f95ee3d005058606041/transformed/jetified-kotlinx-coroutines-core-jvm-1.7.1.jar!/META-INF/kotlinx-coroutines-core.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/92c10a54a436a3cbdf37da09dd766374/transformed/jetified-kotlinx-coroutines-android-1.7.1.jar!/META-INF/kotlinx-coroutines-android.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/989fabb02bd38e3bff5410d3f3c4f480/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/989fabb02bd38e3bff5410d3f3c4f480/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/989fabb02bd38e3bff5410d3f3c4f480/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> e: C:/Users/Hardik Raheja/.gradle/caches/transforms-3/0abb03d3062c02a059c9e4cc1cc33484/transformed/jetified-kotlin-stdlib-common-1.8.22.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> Running Gradle task 'assembleDebug'...                            194.2s
> ✓ Built build\app\outputs\flutter-apk\app-debug.apk
> Installing build\app\outputs\flutter-apk\app-debug.apk...          82.6s
> I/flutter ( 8664): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
> I/flutter ( 8664): 2024-12-26 02:04:58.473962  [SEVERE] [Init] Error during init
> I/flutter ( 8664): Invalid argument(s): Failed to load dynamic library 'librhttp.so': dlopen failed: library "librhttp.so" not found
> I/flutter ( 8664): # 0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
> I/flutter ( 8664): # 1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
> I/flutter ( 8664): # 2      new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:42:47)
> I/flutter ( 8664): # 3      loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:56:28)
> I/flutter ( 8664): # 4      loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10)
> I/flutter ( 8664): # 5      BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:141:13)
> I/flutter ( 8664): # 6      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:48:31)
> I/flutter ( 8664): # 7      RustLib.init (package:rhttp/src/rust/frb_generated.dart:31:20)
> I/flutter ( 8664): # 8      Rhttp.init (package:rhttp/src/rhttp.dart:16:19)
> I/flutter ( 8664): # 9      preInit (package:localsend_app/config/init.dart:62:15)
> I/flutter ( 8664): # 10     main (package:localsend_app/main.dart:23:23)
> I/flutter ( 8664): # 11     _runMain.<anonymous closure> (dart:ui/hooks.dart:299:23)
> I/flutter ( 8664): # 12     _delayEntrypointInvocation.<anonymous closure> (dart:isol
> Syncing files to device SM S918U1...                               386ms
> 
> Flutter run key commands.
> r Hot reload. 🔥🔥🔥
> R Hot restart.
> h List all available interactive commands.
> d Detach (terminate "flutter run" but leave application running).
> c Clear the screen
> q Quit (terminate the application on the device).

The UI launched on the phone displays the lines following 

> Invalid argument(s): Failed to load dynamic library 'librhttp.so': dlopen failed: library "librhttp.so" not found

in the above error

I searched for the specific error 

> Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

So I added ext.kotlin_version = '1.6.0' in the build.gradle as suggested by some answers at StackOverflow

> allprojects {
>     ext.kotlin_version = '1.6.0'
>     repositories {
>         google()
>         mavenCentral()
>     }
> }

This build fails with the following error


> * Where:
> Script 'C:\DevPackages\flutter\packages\flutter_tools\gradle\src\main\kotlin\dependency_version_checker.gradle.kts' line: 371
> 
> * What went wrong:
> Failed to apply plugin class 'Dependency_version_checker_gradle$FlutterDependencyCheckerPlugin'.
> > Error: Your project's Kotlin version (1.6.0) is lower than Flutter's minimum supported version of 1.7.0. Please upgrade your Kotlin version.
>   Alternatively, use the flag "--android-skip-build-dependency-validation" to bypass this check.
> 
>   Potential fix: Your project's KGP version is typically defined in the plugins block of the `settings.gradle` file (C:\Users\Hardik Raheja\Documents\development\localsend\app\android/settings.gradle), by a plugin with the id of org.jetbrains.kotlin.android.
>   If you don't see a plugins block, your project was likely created with an older template version, in which case it is most likely defined in the top-level build.gradle file (C:\Users\Hardik Raheja\Documents\development\localsend\app\android/build.gradle) by the ext.kotlin_version property.
> 
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 6s

**Comment by HardikRa** [comment]
@Tienisto could you let me know if I'm making a mistake on my end or is this a bug?

**Comment by Tienisto** [comment]
Yes, you need to install rustup (https://rustup.rs/)
Then, you need to run any `rustup` command inside `app/` directory so that it installs `1.83`. For example

```shell
cd app
rustup show
```

Then, you should be able to run `flutter run`

**Comment by saurabh12453** [comment]
Follow up please these is to be closed on

**Comment by HardikRa** [comment]
This worked, thank you! :)

**Comment by saurabh12453** [comment]
Glad it worked.
