### ISSUE TITLE
Downloads fail when locking iPhone

### ISSUE THREAD

**Issue by sugarylettuce49** [localsend/localsend#2161]
### Describe the bug

The download fails when I press the power button to turn off my phone or when screen times out.

### To reproduce

Attempt transfer file and press side button to turn off phone screen (lock phone.)

### Expected behavior

The solution would be adding Live Activity support for the app, which allows it to display it's progress on the lock screen, as well as letting it progress. This feature is very much needed as some don't like leaving their phone on the whole time, and if I need to do something else on my phone, I'd rather not have to completely restart just because the app terminated.

Another solution would simply be to just allow pausing downloads when it detects the phone is off, so I don't have to restart EVERY TIME. Thank you.

### Desktop (please complete the following information)

Windows 10 build 19043.1348
Ryzen 5 5500U
8GB DDR4 3200MT/S
256GB SSD
HP laptop motherboard

### Smartphone (please complete the following information)

iPhone SE 3rd gen (2022) (same chipset as iPhone 13)
iOS 18.2

**Comment by Tienisto** [comment]
Unfortunately, iOS stops LocalSend when minimized.
Closing in favor of #1468
