### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by thewh1teagle** [localsend/localsend#219]
### Describe the bug

can't install apk file when sending any apk file from the PC to the phone and clicking on it through the app (on android, version 13)

### To reproduce

1. Send apk file from the PC to the phone with localSend
2. Click on the received file
3. Choose to install it
4. See that nothing happens

### Expected behavior

When I click the apk file and choose to install it, it should let me install it

### Smartphone (please complete the following information)

Device: Poco X3
Android version: 13
OS: arrow OS 12
LocalSend version: 1.7.0 (26)

**Comment by Tienisto** [comment]
This should be already fixed in the coming `v1.8.0` release. Hopefully, this will be released in the coming weekend.
