### ISSUE TITLE
Bug report-Autostart:start hidden failed

### ISSUE THREAD

**Issue by aiomkr** [localsend/localsend#224]
### Describe the bug

Autostart:start hidden failed

### To reproduce

1.turn on Autostart:start hidden.
2.restart windows10.
3.Localsend not hidden and displayed directly on desktop.

Localsend v1.7.0

### Expected behavior

repair Autostart: start hidden. localsend is hidden at startup.

### Desktop (please complete the following information)

Edition:Windows 10 Pro
Version:22H2
System build:19045.2604

**Comment by Tienisto** [comment]
Do you use the portable zip version? Then you can checkout #71

**Comment by AetherKong** [comment]
I'm using Microsoft Store version, and the "Autostart:start hidden" does not work either.

**Comment by aiomkr** [comment]
> Do you use the portable zip version? Then you can checkout #71

thanks！
