### ISSUE TITLE
Edit text afterwards before send

### ISSUE THREAD

**Issue by AnLazyOtter** [localsend/localsend#229]
### Is your feature request related to a problem? Please describe.

之前准备好发送的文本，发现有需要修改的地方，希望能再次编辑该文本，或者至少允许将文本重新复制出来，以便粘贴到其他地方编辑。

### Describe the solution you'd like

在”选择“部分，再次点击”编辑“后，希望能展开已添加到清单的文本，允许重新编辑。

### Describe alternatives you've considered

至少，对于多行文本的场景，希望能够提供展开查看全文、重新复制出来的功能。

**Comment by Tienisto** [comment]
Added in `v1.8.0`
