### ISSUE TITLE
Feature request: List flatpak option on github and website and perhaps make it official package

### ISSUE THREAD

**Issue by thatLeaflet** [localsend/localsend#231]
### Is your feature request related to a problem? Please describe.

For Linux, the three options for getting the app currently include the appimage, building from source, and an experimental snap.

The appimage is a bit inconvenient due to the way appimages work. They don't have any sort of update mechanism and they don't integrate nicely with the system (as in they don't show on the apps screen unless you manually create a .desktop file for it, otherwise you need to launch it from the file manager).

The build from source option is obviously a bit cumbersome because you need to have all the compiling stuff installed, then you still have the update issue and integration issue.

The snap build fixes these two pain points, but has other issues of its own. It is currently only experimental and there is a general dislisking of snaps by the Linux community. Ubuntu is also the only major distro pushing for snaps.

### Describe the solution you'd like

Flatpak would be a great option for distribution of the app. Many major distros such as Pop!_OS, Linux Mint, Fedora install it by default.

As a flatpak package uploaded to flathub, it would provide a nice way to update and discover the application. It would be nicely integrated with the system, no need to manually create a .desktop file or launch from a file manager.

Additionally, the work to create the flatpak has already been done and is available on flathub: [link to page](https://flathub.org/apps/details/org.localsend.localsend_app). It seems to be working well. It would be cool to see this to be made an official distribution method of the app.

**Comment by Tienisto** [comment]
Sure, I already updated the readme. Regarding the website, an overhaul is needed

**Comment by Tienisto** [comment]
Closing this as flatpak is now included in the readme
