### ISSUE TITLE
[Feature request] Support for opening folders of received files

### ISSUE THREAD

**Issue by TeackReais** [localsend/localsend#232]
### Is your feature request related to a problem? Please describe.

When a file is received, the user often has the need to open the folder.

### Describe the solution you'd like

As an example, I am using LocalSend on the macOS side. On the receive file screen, the current logic is that there is a line for each file and when you click on that line the file opens. I think the above logic could be removed and then there would be 2 buttons that could be added to the right of this line to open the file and open the folder. In the history screen, in the expand menu on the right hand side, an open folder option could be added.

**Comment by Tienisto** [comment]
Added in `v1.8.0`
