### ISSUE TITLE
Cannot receive files on Windows

### ISSUE THREAD

**Issue by Mylosis** [localsend/localsend#234]
Trying to send from Android to Windows. I get the error message below. The network is detected, but it just doesn't send.

I can however send from Windows to Android. Any ideas why this might be?

`DioError [DioErrorType.connectTimeout]: Connecting timed out [2592000000ms]
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:97)
#3      SendNotifier.startSession (package:localsend_app/provider/network/send_provider.dart:97)
<asynchronous suspension>`

**Comment by rikonaka** [comment]
Same issues here.

![bug](https://user-images.githubusercontent.com/13602602/223168848-ba4c8800-a26a-4821-b3bb-65186d465562.png)

**Comment by Mylosis** [comment]
> 

Hey, disabling firewall ended up working for me. Give it a try!

**Comment by tintad** [comment]
You can try adding Inbound Rule in Firewall Settings for this app. It's working great for me now
