### ISSUE TITLE
Feature request Android custom file save location

### ISSUE THREAD

**Issue by tang-nn** [localsend/localsend#235]
### Is your feature request related to a problem? Please describe.

Android custom file save location

### Describe the solution you'd like

Android custom file save location

**Comment by Tienisto** [comment]
This feature is disabled on Android because it does not play well with "scoped storage". Maybe someone can help solving this issue.

**Comment by GameOverFlowChart** [comment]
> This feature is disabled on Android because it does not play well with "scoped storage". Maybe someone can help solving this issue.

The solution is simple in theory. In the settings you let the user select a folder via scoped storage. The user selects the folder and gives the permission. That's how NewPipe does it. Scoped Storage let's the user decide which folders the app can access (which is exactly what this feature request is about). About the implementation, I guess "ACTION_OPEN_DOCUMENT_TREE" is the keyword here.

It would make sense to still use the download folder as the default, this makes it easy to use the app without configuration. Also some devices (like Android Tv's) don't come with a file picker so this doesn't work with them.

**Comment by trymeouteh** [comment]
This feature is available on Android in 1.9.0
