### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AlanDinkle** [localsend/localsend#24]
Can text be transferred without file？It will be easier to transfer.
And the display of historical records will also be more convenient，you can find some examples in the project "[LANDrop](https://github.com/LANDrop)"

**Comment by EvelynKin** [comment]
@david-kariuki

**Comment by Caesarovich** [comment]
This feature is now present in LocalSend. That issue can be closed as **Solved** if that's okay with you @AlanDinkle @Tienisto
