### ISSUE TITLE
Bug report: Out of Memory,Can't receive large files

### ISSUE THREAD

**Issue by Radium-bit** [localsend/localsend#240]
### Describe the bug

When trying to send a large file to the Android side, it will cause the running memory to be completely occupied, which is finally unacceptable.
The file size in the test is 16GB, single file, after the transmission exceeds the free memory of the receiving device, the LocalSend of the receiving device crashes.

### To reproduce

1. Use an Android device as the receiver.
2. **Prepare a single file that can exceed the RAM of the Android device**, such as a high-definition movie file.
3. In the local area network, transfer this file to the Android device. You'll notice that localsend on the receiving end of Android **freezes or crashes when the available memory is exhausted**.

### Expected behavior

localsend on the receiving end of Android freezes or crashes when the available memory is exhausted.

### Screenshots

Sorry? I can not find an upload button.
But I think I've described the situation.

### Desktop (please complete the following information)

- OS: Microsoft Windows 10
- Version: 1.7.0

### Smartphone (please complete the following information)

- Device: Android Smartphone.
- OS: Android 13
- Version: 1.7.0

### Additional context
```
DioError [DioErrorType.other]: SocketException: Write failed (OS Error: An existing connection was forcibly closed by the remote host.
, errno = 10054), address = 192.168.x.xxx, port = 54081
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:97)
#3      SendNotifier._send (package:localsend_app/provider/network/send_provider.dart:173)
#4      SendNotifier.startSession (package:localsend_app/provider/network/send_provider.dart:147)
<asynchronous suspension>
```

### Proposal
When receiving a file, if the file is too large, the file will be written to disk for caching in time. When the transmission is completed, it moves from the cache to the target path, and if the transmission is canceled, the cache is deleted.

**Comment by Tienisto** [comment]
Is it a media file (mp4, jpeg, etc.)?

The code managing file save only works with data streams so I don't know

**Comment by Radium-bit** [comment]
> Is it a media file (mp4, jpeg, etc.)?
> 
> The code managing file save only works with data streams so I don't know.
> 
> The problem may be related to "Save media to gallery"

Yes, it's a Matroska (mkv) file.  I'll try again with "Save to Gallery" turned off.

**Comment by Radium-bit** [comment]
> Is it a media file (mp4, jpeg, etc.)?
> 
> The code managing file save only works with data streams so I don't know.
> 
> The problem may be related to "Save media to gallery"

Still fail . Nothing changed.
I has been turn off the option.

**Comment by Shadowy0ath** [comment]
I met the same error 10054. After I put the program
