### ISSUE TITLE
Help please, I can't sync my phone, hacker is using my phone, down below is the error from Google cloud, I can't verify my own device

### ISSUE THREAD

**Issue by rocky19888** [localsend/localsend#241]
For security, you can no longer access your encrypted data on this device. Try again using a device you’ve recently used to sign in to your Google Account.

Visit g.co/OnDeviceEncryption to learn more.

**Comment by Tienisto** [comment]
What is this? A bug report? A feature request?

Without giving exact details (version, operating system, hardware details), nobody can help you.
