### ISSUE TITLE
added NL translations but fork will not work... 

### ISSUE THREAD

**Issue by im-ichat** [localsend/localsend#242]
for some reason  github wont let me  edit  or fix   missing_translations_nl      

so plz forgive me for posting its content here.. im entirely not familiar with github: 

i hope these will make it to the next update.. 

{
  "@@info": [
    "Here are translations that exist in <en> but not in <nl>.",
    "After editing this file, you can run 'flutter pub run slang apply --locale=nl' to quickly apply the newly added translations."
  ],
  "sendTab": {
    "sendMode": "Verzend modus",
    "sendModes": {
      "single": "Één ontvanger",
      "multiple": "Meerdere ontvangers",
      "link": "Delen via link"
    },
    "sendModeHelp": "Info"
  },
  "settingsTab": {
    "receive": {
      "downloads": "(Downloads)"
    }
  },
  "receiveHistoryPage": {
    "openFolder": "Map openen ",
    "deleteHistory": "Geschiedenis verwijderen"
  },
  "dialogs": {
    "sendModeHelp": {
      "title": "Verzend opties",
      "single": "Naar één ontvanger zenden. Selectie de-selecteren na verzending.",
      "multiple": "Naar meerdere ontvangers zenden. Selectie blijft geselecteerd na verzending.",
      "link": "Ontvangers die de app niet hebben geïnstalleerd kunnen bestanden downloaden door de link in hun browser te openen."
    }
  }
}

**Comment by Tienisto** [comment]
No problem, thanks!
