### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by jalenzz** [localsend/localsend#25]
Hi, is it possible to add Chinese translation. I can help with it.

**Comment by Tienisto** [comment]
Sure, you can add a file in `https://github.com/localsend/localsend/tree/main/assets/i18n`.

The file should be named `strings_<languageCode>-<scriptCode>-<countryCode>.i18n.json`

I will create a detailed tutorial soon.

**Comment by Tienisto** [comment]
https://github.com/localsend/localsend#translation

**Comment by jalenzz** [comment]
https://github.com/localsend/localsend/pull/28

someone has did

**Comment by Lapis-Apple** [comment]
~~我是不是应该出来自裁一下我没看到这个，我这是无意间半路截胡了属于是~~

**Comment by jalenzz** [comment]
没事啊
