### ISSUE TITLE
Bug report: Could not save file

### ISSUE THREAD

**Issue by yuhext** [localsend/localsend#252]
### Describe the bug

When trying to send a file to the Android side, if the Android device does not have the folder `/storage/emulated/0/Download`, the transmission will fail. Does LocalSend has no permission to create the folder?

### To reproduce

1. Use an Android device to receive files
2. Remove the folder `/storage/emulated/0/Download` of this Android device
3. Send a file to this Android device from another device

### Expected behavior

LocalSend can't send files to an Android device without folder `/storage/emulated/0/Download`

### Screenshots

![error](https://user-images.githubusercontent.com/121758421/223434723-288f8abe-fbc3-48ab-b3e0-4b4dbb285fe2.png)

### Smartphone (please complete the following information)

- Device: Android Smartphone
- OS: Android 13
- Version: 1.8.0

**Comment by ysdxz207** [comment]
Same problem.

**Comment by ysdxz207** [comment]
I found that turn off "save to album" it will be work fine.
