### ISSUE TITLE
downloaded file on Linux is missing

### ISSUE THREAD

**Issue by mscurtescu** [localsend/localsend#256]
### Describe the bug

LocalSend installed on both Linux desktop running PopOS! and Android phone.

On desktop using the default "(Downloads)" destination folder. Sending file from my phone, prompted to accept on the desktop, shows download.

First issue: destination is shown as my home folder and not Downloads.

The file is neither in home nor in Downloads. Cannot locate anywhere.

The receive history window shows the file. Neither "Open folder" nor "Open file" work here.

### To reproduce

Send from Android to Ubuntu desktop.

### Expected behavior

File is downloaded to the configured folder, which is `~/Downloads`

### Screenshots

![image](https://user-images.githubusercontent.com/942078/223586030-f2ab448c-ddf4-4a47-acfe-a2436486cf6a.png)

![image](https://user-images.githubusercontent.com/942078/223585957-fd41a598-969c-41f1-a7ff-4e91326ceeda.png)

![image](https://user-images.githubusercontent.com/942078/223586214-b9f6aa5d-d53c-4487-9109-39f410a0a54a.png)

### Desktop (please complete the following information)

- OS: Pop!_OS
- Version: 22.04

### Smartphone (please complete the following information)

- Device: Pixel 6 Pro
- OS version: Android 13

### Additional context

Setting the Destination folder, by selecting `~/Downloads` shows a very strange folder which reverts back to "(Downloads)" when clicked.

![image](https://user-images.githubusercontent.com/942078/223586815-cc1fa67e-48a6-4130-b483-de25d35106aa.png)

**Comment by Tienisto** [comment]
Do you see any logs from the app?

**Comment by mscurtescu** [comment]
Flatpak, version 1.8.0

Where would the logs be?

**Comment by TheGB0077** [comment]
This is a matter of permissions! Flatpak applications are typically sandboxed, this means that the app has indirect access to the file-system through /run, here a comparison between the flatpak app and the version I built from source: 

![Captura de tela de 2023-03-08 15-23-09](https://user-images.githubusercontent.com/39922116/223806027-fa00590e-db5e-488d-b6fd-eceddd214a4f.png)

The immediate workaround would be to allow the flatpak to use the your home environment directly with this command:

> sudo flatpak override org.localsend.localsend_app --filesystem=/home/<b>youruser</b>

Or you could download Flatseal and activate the following highlighted option:

![image](https://user-images.githubusercontent.com/39922116/223807267-55d61e32-27de-4e8b-a356-b5dc86b86cf8.png)

**Comment by TheGB0077** [comment]
![image](https://user-images.githubusercontent.com/39922116/223824684-82c6e143-ca65-43fb-b077-337fbde9a2fd.png)

I believe that adding a filesystem argument in the manifest finish-args should solve it:

`- --filesystem=home`

**Comment by mscurtescu** [comment]
Thanks @TheGB0077, the permission was it.

**Comment by TheGB0077** [comment]
> didn't work for me even after running the command

Oh yes, I made a mistake, running it with sudo will make the override to be saved only for the super user profile, instead the correct  CLI command was:

_flatpak override org.localsend.localsend_app  --filesystem=home --user=**youruser**_

Or:
_flatpak override org.localsend.localsend_app  --filesystem=/home/**youruser** --user=**youruser**_

But then again, Flatseal does the job alright.

**Comment by trymeouteh** [comment]
I have the same issues with the Flatpak version. AppImage works fine however

**Comment by Winson-Huang** [comment]
Fedora 37 flatpak, after selecting the Receive Destination as `~/Downloads` manually, the path will be like `/run/user/...../Downloads`, but files can be received to `~/Downloads`, so maybe it's not a that big bug...

**Comment by TheGB0077** [comment]
I would seem that the files on Pop OS aren't linking properly.
I just reverted the app to default settings and couldn't even complete a file transfer. I don't know if other distros can have other sorts of problems, so I think the "One-Size-Fits-All" solution would be if @proletarius101 included a `--filesystem=home` argument to the flatpak manifest, several flatpak apps do it anyway like VLC, GIMP, Audacity, etc.

**Comment by Tienisto** [comment]
@TheGB0077 can you test if the new manifest works?

```bash
flatpak install --user https://dl.flathub.org/build-repo/13524/org.localsend.localsend_app.flatpakref
```

**Comment by TheGB0077** [comment]
Yes. Now the app is accessing/writing /home/ by default.

**Comment by Ativerc** [comment]
This happened with me in Ubuntu 24.04. Installed via Flatpak.

Version 1.16.1.

Are the files saved somewhere on my system?
