### ISSUE TITLE
Transfer request cancelled by a third device simultaneous connection

### ISSUE THREAD

**Issue by TheGB0077** [localsend/localsend#257]
### The bug

While checking the error notification for "The recipient is busy with another request" I noticed that I was able to use the Close button on a third device to interrupt the transfer between the other two.

### To reproduce

1. Set up a file transfer between two devices.
2. Start a third connection on another device.
3. Press the close button on the third device before the transfer begins.

### Expected behaviour

Upon pressing the Close button the receiving end will notify that the sender has cancelled the transfer request.

### Screenshots

<details>
<summary>The "man in the middle" device:</summary>

![image](https://user-images.githubusercontent.com/39922116/223587850-ff69df3c-edba-43bf-99db-46e0d401d5e8.png)

</details>

<details>
<summary>The desktop client after the forced interruption:</summary>

![image](https://user-images.githubusercontent.com/39922116/223587139-6363a44b-02b2-40cc-a350-0391a8fd0390.png)

</details>

### Devices

Desktop: Linux Pop Os ( Recipient ) 

Phones: Android 9 device ( Sender ) , Android 11 Device (  Man in the middle )

**Comment by TheGB0077** [comment]
Update: Couldn't replicate the problem in another network that has no subnets between devices. 

The former network where I found this bug had a subnet for Wi-Fi devices (192.168.1) and a different one for wired ones (192.168.15), thus to connect to the desktop in which I tested, I had to type the full IP address to reach the device.

I believe that the problem stands from the broadcasting of the cancellation notification to the other subnet that had no precise reference of the original sender.

**Comment by TheGB0077** [comment]
I guess this behaviour would be fixed like this, but I'm not sure if there are some trickling down effects with this change. 

![image](https://user-images.githubusercontent.com/39922116/224580186-54dc2dbc-13c4-444b-8dce-bcd5d7da3a0d.png)

**Comment by Tienisto** [comment]
Thanks for your investigation.

This is a reasonable fix to avoid this behaviour. However, this should be fixed on the server side, so a "bad" person cannot interrupt others sessions.

When the server receives a cancel request, it checks the IP address to determine the legitimacy:
https://github.com/localsend/localsend/blob/main/lib/provider/network/server_provider.dart#L428

So I don't understand why this is possible.

**Comment by Tienisto** [comment]
I suspect that your Linux computer only see one single IP address when the Android phones connects to it.

**Comment by TheGB0077** [comment]
When the request is re-routed on the subnet wouldn't request.ip equal the default geteway?

**Comment by Tienisto** [comment]
Yes, the gateway removes the original IPs of the mobile phones which makes it hard for the server that only relies on IP.

I have added a PR for the protocol: https://github.com/localsend/protocol/pull/5
