### ISSUE TITLE
Rename Chinese Translation Files

### ISSUE THREAD

**Issue by graphemecluster** [localsend/localsend#260]
To better support automatic language detection for Chinese locales, I’d suggest changing the language codes from `zh-Hans`, `zh-Hant-TW` and `zh-Hant-HK` to `zh-CN`, `zh-TW` and `zh-HK` respectively.

That is all.

**Comment by graphemecluster** [comment]
That's weird. As a macrolanguage, the fallback behavior in Chinese is compilcated and requires separate handling.

The currently languages available in Flutter can be found in [`language_subtag_registry.dart`](https://github.com/flutter/flutter/blob/f1c8723a10d8bd70b33f9bf7cf826692a8da95d5/dev/tools/localization/language_subtag_registry.dart). The `Tag` and `Preferred-Value` columns is from the registry and the rightmost column shows the corresponding ideal fallback language file:

| Tag         | Preferred-Value | Ideal Fallback |
| ----------- | --------------- | -------------- |
| zh-cmn      | cmn             | zh-CN          |
| zh-cmn-Hans | cmn-Hans        | zh-CN          |
| zh-cmn-Hant | cmn-Hant        | zh-TW          |
| zh-gan      | gan             | zh-CN          |
| zh-Hans     |                 | zh-CN          |
| zh-Hans-CN  |                 | zh-CN          |
| zh-Hans-HK  |                 | zh-HK          |
| zh-Hans-MO  |                 | zh-HK          |
| zh-Hans-SG  |                 | zh-CN          |
| zh-Hans-TW  |                 | zh-TW          |
| zh-Hant     |                 | zh-TW          |
| zh-Hant-CN  |                 | zh-CN          |
| zh-Hant-HK  |                 | zh-HK          |
| zh-Hant-MO  |                 | zh-HK          |
| zh-Hant-SG  |                 | zh-CN          |
| zh-Hant-TW  |                 | zh-TW          |
| zh-wuu      | wuu             | zh-CN          |
| zh-yue      | yue             | zh-HK          |

In practice, many platforms use tags with only regional code, which are missing from the registry. When the script (Simplified or Traditional) is not indicated, the following fallbacks should be used:

| Unlisted Tag | Implies        | Ideal Fallback |
| ------------ | -------------- | -------------- |
| zh           | zh-cmn-Hans-CN | zh-CN          |
| zh-CN        | zh-cmn-Hans-CN | zh-CN          |
| zh-HK        | zh-yue-Hant-HK | zh-HK          |
| zh-MO        | zh-yue-Hant-MO | zh-HK          |
| zh-SG        | zh-cmn-Hans-SG | zh-CN          |
| zh-TW        | zh-cmn-Hant-TW | zh-TW          |

---

In general, the algorithm for fallback is as follows:

### LanguageFallback ( _language_, _extlang_, _script_, _region_ )

The abstract operation LanguageFallback takes arguments _language_ (a String or undefined), _extlang_ (a String or undefined), _script_ (a String or undefined) and _region_ (a String or undefined) and returns a String. It performs the following steps when called:

1. If _extlang_ is **"yue"**, return **"zh-HK"**.
2. If _language_ is **"zh"** or _extlang_ is one of the identifiers listed in https://iso639-3.sil.org/code/zho:
  a. If _region_ is either **"HK"** or **"MO"**, return **"zh-HK"**.
  b. If _region_ is **"TW"** or  _script_ is **"Hant"**, return **"zh-TW"**.
  c. Return **"zh-CN"**.

**Comment by graphemecluster** [comment]
If anyone here is new to language tags, you may read this article:
https://www.w3.org/International/articles/language-tags/

**Comment by graphemecluster** [comment]
Oh I know where is the code now https://github.com/Tienisto/slang/blob/master/slang/lib/api/singleton.dart
Since you're also maintaining slang, you may want to move this issue to the repo.

**Comment by Tienisto** [comment]
Thanks for your investigation, I will look into that!
