### ISSUE TITLE
Winget update??

### ISSUE THREAD

**Issue by k3v1nwrld** [localsend/localsend#262]
### Describe the bug

So I noticed that Localsend on winget hasn't been updated since last version (v1.7.0) . Is there going to be an update for it??

### To reproduce

.

### Expected behavior

.

### Desktop (please complete the following information)

- OS: [Windows]

### Smartphone (please complete the following information)

- Version [1.7.0-->1.8.0]

**Comment by Tienisto** [comment]
See #220 and #57
