### ISSUE TITLE
Can't find the laptop in the same local network

### ISSUE THREAD

**Issue by Frog4China** [localsend/localsend#27]
I have had 4 devices test.
1 PC, 1 Thinkpad laptop, 2 Pixel phones
The PC and 2 phones can find each others but the PC and phones can't find the Thinkpad.
However the Thinkpad is able to find the PC and the phones. Test and files can be sent to the PC.

remark: 
1. all are in the same local network/WiFi; 
2. all app with server started;
3. all with default port

Thank you for your nice work.

**Comment by Frog4China** [comment]
Thanks. You are right. 
it's done now.

**Comment by spidyhackx** [comment]
Thanks. changing the firewall rules on parrot os to allow in-requests for port ```53317``` fixed it
