### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ARRrui** [localsend/localsend#272]
### Describe the bug

When sending an apk file from Windows 10 to Android, an error message ‘[400] Request body malformed’ appears. However, after changing the file extension to zip, it can be sent normally.

### To reproduce

1. Select an apk file on a Windows 10 system.
2. Attempt to send the file to an Android device.
3. An error message '[400] Request body malformed' appears.

### Expected behavior

The apk file should be sent to the Android device without any error messages and it would be best if it could be installed directly after being sent.

**Comment by Tienisto** [comment]
There is a bug that APK files are treated differently since `v1.8.0`.

Either update the Android app to `v1.8.0` if possible, or wait 1-2 days until `v1.8.0` is available on F-Droid.
