### ISSUE TITLE
Feature request: Tray Icon (Desktop)

### ISSUE THREAD

**Issue by trymeouteh** [localsend/localsend#277]
### Is your feature request related to a problem? Please describe.

A tray icon for Windows, Mac and Linux

### Describe the solution you'd like

A tray icon for Windows, Mac and Linux. When you close the window, it will minimize the app to the tray. To close LocalSend, you need to click on Quit in the tray icon.

**Comment by Tienisto** [comment]
It already exists on Windows and Mac. On Linux, there is an open bug that needs to be fixed
