### ISSUE TITLE
Feature request: Remove Media Option

### ISSUE THREAD

**Issue by trymeouteh** [localsend/localsend#279]
### Is your feature request related to a problem? Please describe.

The media option when sending files to user is not needed since all that is needed is the file send option which can send any type of file including media files.

### Describe the solution you'd like

To remove media option or a setting to hide media option

**Comment by Tienisto** [comment]
The media option is useful because it provides a gallery-like selection mode which is directory independent

**Comment by trymeouteh** [comment]
> The media option is useful because it provides a gallery-like selection mode which is directory independent

I find it annoying, but if others like this feature. I would like to suggest a setting to hide the media option in the send menu.
