### ISSUE TITLE
Bug report: Apps and send setting not showing

### ISSUE THREAD

**Issue by trymeouteh** [localsend/localsend#283]
### Describe the bug

Apps and send setting not showing on LG V20

### To reproduce

Install LocalSend on LG V20 (LineageOS 18.1) from F-Droid
Launch LocalSend
Go to Send menu
Send settings button is not shown and app button under Selection is not shown

### Expected behavior

Apps button and send setting will be visible

### Screenshots

[![Screenshot-20230311-205711-Local-Send.png](https://i.postimg.cc/d3BTFJ0k/Screenshot-20230311-205711-Local-Send.png)](https://postimg.cc/8f7CBQMN)

### Smartphone (please complete the following information)

LineageOS 18.1
LG V20

### Additional context

Maybe due to LG V20 having a smaller screen size?

**Comment by Tienisto** [comment]
You use 1.7.0

Please update to 1.8.0
