### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by missyraja** [localsend/localsend#285]
### Is your feature request related to a problem? Please describe.

Often times I want to share quickly between my devices. So, utilising the existing responsive places in an UI is crucial for it.

### Describe the solution you'd like

For Android I would love to have a toggle on the notification pane to trigger the app open and start searching for devices. (Kinda similar to nearby share in Android)

In Windows 11 I would love to Share files quickly by the contextual menu. So, It would be grateful to have an option on the new contextual menu for quick sharing.

**Comment by Tienisto** [comment]
On Android, it is recommended to use the "share" feature.

On Windows, there is already an issue #271

**Comment by Jesse205** [comment]
Hello, the author should be referring to the Sharesheet for Android. It has a completely different experience

https://developer.android.com/training/sharing/send
![Screenshot_20240107_161027.jpg](https://github.com/localsend/localsend/assets/51242302/0abbcb5f-0ca1-45d4-9c1f-3e5b999de288)
