### ISSUE TITLE
[Enhancement] Tweak to file not found dialogue

### ISSUE THREAD

**Issue by TheGB0077** [localsend/localsend#287]
I worked on a small QoL feature, the option to delete from History directly from the file not found dialogue. 
If need may be for said option, I can open the Pull Request for evaluation right away! 

![Captura de tela de 2023-03-12 23-23-21](https://user-images.githubusercontent.com/39922116/224596024-7cfce3f4-c4e3-4f4e-b252-12e5cb17ad5b.png)

**Comment by Tienisto** [comment]
Sure, you can open a PR
