### ISSUE TITLE
cannot share apk file 

### ISSUE THREAD

**Issue by gkdgo** [localsend/localsend#289]
### Describe the bug

cannot send apk file 
<img width="116" alt="image" src="https://user-images.githubusercontent.com/55651847/224735318-4cc15943-55c5-4d24-954f-0546e36d4389.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/55651847/224735523-780dc7c1-015d-4fe5-95a9-4749e0e6ff72.png">
but works fine after removing the suffix .apk
<img width="87" alt="image" src="https://user-images.githubusercontent.com/55651847/224735213-5ca1f9f5-9176-49c6-a67e-92e458535705.png">

### To reproduce

share a apk file

### Expected behavior

shared

**Comment by Tienisto** [comment]
Update both devices to `1.8.0`. See #272
