### ISSUE TITLE
Remove text selection after finish

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#293]
In `Single Recipient`, files gets cleared but messages are not. Text should be cleared too.

**Comment by suman-somu** [comment]
Can you please explain ? 

Is it you want there should be a Done function like in files and media
![WhatsApp Image 2023-04-08 at 14 58 46](https://user-images.githubusercontent.com/75962762/230714284-fd335be7-77cd-4443-8762-8eba053686bc.jpeg)

and not only depends on the receiver's end to close the text ? 
![WhatsApp Image 2023-04-08 at 14 54 47](https://user-images.githubusercontent.com/75962762/230714305-3658e709-4331-406d-b868-fe59f15c84ec.jpeg)
