### ISSUE TITLE
Bug report: msix not merged by git `ref: 207eddfe797225ab2736001cbdb8fafd04946b38`

### ISSUE THREAD

**Issue by ruoduan-hub** [localsend/localsend#294]
### Describe the bug

msix:
    # https://github.com/YehudaKremer/msix/pull/174
    git:
      url: https://github.com/Tienisto/msix.git
      ref: 207eddfe797225ab2736001cbdb8fafd04946b38

### To reproduce

`flutter pub ge`

```
Could not find a file named "pubspec.yaml" in https://github.com/Tienisto/msix.git 207eddfe797225ab2736001cbdb8fafd04946b38.
pub get failed

```

### Expected behavior

- Annotate this commit. 👇🏻

  msix:
    # https://github.com/YehudaKremer/msix/pull/174
    git:
      url: https://github.com/Tienisto/msix.git
      # ref: 207eddfe797225ab2736001cbdb8fafd04946b38

**Comment by Tienisto** [comment]
This is not a bug. This is just an unmerged fork.

**Comment by Tienisto** [comment]
It works on my machine. But the hash is incorrect. It should be 5934920205cb2284a510ee2ddc58cf082d37595c

**Comment by Tienisto** [comment]
Updated dependency hash

**Comment by ruoduan-hub** [comment]
> This is not a bug. This is just an unmerged fork.

I know,  It only happens when running locally；

thanks for the update！I wish you a happy life
