### ISSUE TITLE
500, Error thrown by handler

### ISSUE THREAD

**Issue by shankargopal** [localsend/localsend#295]
### Describe the bug

I am trying to send a text from an Android device to a Debian computer.  On the Android device I get an error message '500 internal server error', and on the Debian device, when I run the AppImage from the command line, I see this error message appearing:

```
ERROR - 2023-03-16 14:13:44.142675                                                                                                                                                                
POST /api/localsend/v1/send-request                                                                                                                                                               
Error thrown by handler.                                                                                                                                                                          
Null check operator used on a null value                                                                                                                                                          
package:shelf/shelf_io.dart 137  handleRequest 
```

What does this mean?

Thank you for a great program!

### To reproduce

Desktop:

Download AppImage, run `chmod a+x`, run the software

Choose "Receive"

Android:

Install from Play Store

Choose "Send"

Choose "Add"

Choose "text"

Type in message

Choose "Confirm"

Tap on Debian device

### Expected behavior

Text will be sent from Android to Debian device

### Desktop (please complete the following information)

Output of `uname -a`:

`Linux debian 5.18.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux`

### Smartphone (please complete the following information)

- Device - Nokia 3.4
- OS - Android 12, security update up to 1 February 2023

**Comment by Tienisto** [comment]
You can try out the latest AppImage or Debian package. If this error still persist, let us know!
