### ISSUE TITLE
remember Window size and position

### ISSUE THREAD

**Issue by bachig26** [localsend/localsend#296]
### Is your feature request related to a problem? Please describe.

From my experience, I like to keep/organize the app position and size relatively along the other apps side-by-side for a multitasking perspective, but every new session relapses over the existing app/tool that I've been using and the position that I'm not comfortable with.

I use a lot with localsend from the point when I found this app, an I want a consistent and less distractive workflow, so I hope to see this feature in play.

### Describe the solution you'd like

This issue is to request an function to remember the window size and position of the localsend in desktop, also an option in the settings to toggle them.

### Additional context

_*this feature is for desktop version._

**Comment by electr1fy0** [comment]
Adding to this, I still believe the Mac app should be a Menu Bar app only.

**Comment by TheGB0077** [comment]
I'll try to sketch up the code for this! @bachig26

**Comment by Tienisto** [comment]
Thanks @TheGB0077!

You will probably need to store some keys in `PersistenceService`. Then you can write/read those keys during init (https://github.com/localsend/localsend/blob/main/lib/init.dart#L91)

**Comment by TheGB0077** [comment]
Just pushed a draft! 
I hardcoded a variable to replace the setting for now, although the UI implementation should be straightforward enough.

**Comment by bachig26** [comment]
@TheGB0077 @Tienisto is it possible include the stick to edge function along this ongoing draft?

**Comment by bachig26** [comment]
> In the next version of the app? I think it's likely. 

❤

The only thing yet to consider is if the settings option is really necessary, at least considering that having the window restore the previous position/size is a great default, so is it really necessary to let people opt out? What do you think @bachig26 ?

on second thought, I'm not sure about an option to toggle it in settings, as from my perspective I want it to be active all the time.
I don't know maybe if you want and can try it out and see if you need the toggle or not, then go for the one you like it.

**Comment by Tienisto** [comment]
I think having a settings option is not necessary. I have never seen this option on another desktop app (maybe because I didn't cared)

**Comment by sergd88** [comment]
On the contrary, I like the fact that the default location for program window is always center, this is very convenient, especially since the application supports drag-and-drop, so you can freely move the window, change its size, knowing that the next time you open app, window will be fixed in size and in the center.

**Comment by sergd88** [comment]
> I think having a settings option is not necessary. I have never seen this option on another desktop app (maybe because I didn't cared)

At first glance, there is a similar function in Total Commander. Although it is somewhat different, you can manually save the window size and position by selecting the appropriate option in the settings menu.

However, it still adheres to the use of having the user set the desired size and position and simply saving the settings. Then, when working with the program you will without worrying about having to set everything up again later.

**Comment by TheGB0077** [comment]
<h3>In the end, I did it 😆 </h3>

The app will have some extra lines added to missing translations, so I though: "One extra won't hurt  :) "
By the way, the setting is on by default @sergd88 
You will need to disable it.

![image](https://user-images.githubusercontent.com/39922116/227701985-fc7a019c-8e8b-4ef0-b31f-975dd3930664.png)
