### ISSUE TITLE
Always on Top

### ISSUE THREAD

**Issue by bachig26** [localsend/localsend#297]
### Is your feature request related to a problem? Please describe.

Sometimes I feel like having the app on the top without hiding behind the other apps when switching.

This function can help in using the localsend over the other apps without resizing or splitting the apps to work in adjacent.

### Describe the solution you'd like

Possibility of an option in settings to toggle the `Always on Top` function.

### Additional context

_*this feature is for desktop version._

**Comment by zillydev** [comment]
@bachig26 use PowerToys, it has the feature of making any app appear always on top.

**Comment by Tienisto** [comment]
Yes, PowerToys should be used.
