### ISSUE TITLE
Crashes after typing message

### ISSUE THREAD

**Issue by ZOPtTMX22zcBAl6i1HbGPbFwZzuelxkr8Zlq1t3** [localsend/localsend#303]
### Describe the bug

Crashed while sending inputting text.

### To reproduce

1. Go to 'Send'
2. Click on 'Text'
3. Input some letters
4. Crash and close

### Expected behavior

Send text to another device

### Screenshots

https://user-images.githubusercontent.com/122418163/226174460-cc469211-4cb7-428c-8509-51fb5f72441d.mp4

### Desktop (please complete the following information)

- OS: Windows 11
- Version: 1.7.0 (26)

**Comment by Tienisto** [comment]
This is likely a Flutter bug. The Flutter team needs to fix this.
