### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by person2217** [localsend/localsend#313]
### Describe the bug

设置中，静默自启动选择开启后，依旧不能开机最小化到托盘。第一此下载时，此功能正常，后续升级后，该功能出现异常。即使我使用以管理员权限打开该程序修改该选项、重装软件、下载不同版本均不能解决该问题,且因之前装过此软件，默认设置已按照默认设置。

### To reproduce

1. Go to '设置'
2. Click on '静默自启--打开'
3. Scroll down to '...'
4. See error-开机后页面打开在桌面

### Expected behavior

开机后不能最小到托盘，页面打开在桌面，设置中打开静默自启无效。

### Screenshots

![image](https://user-images.githubusercontent.com/106829332/227219574-d68dc291-1b2f-44be-8515-83726682b6a0.png)

### Desktop (please complete the following information)

-os：windows10pro
-version：1.8.0，msix

**Comment by sergd88** [comment]
+1

**Comment by sergd88** [comment]
+1
- Windows 11 Pro 22H2

**Comment by sergd88** [comment]
+1
Windows 11 Pro 22H2

**Comment by 01sv** [comment]
官网上下载的不行，那个“故障排除”解决不了。微软商店下载的可以用，但现在微软商店已经把 LocalSend 下架了。

**Comment by cdhigh** [comment]
A solution:
Copy the following three lines of text into a BAT file, then save it in the same directory as "localsend," and double-click to execute.

echo Add auto start item of localsend to register
reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run" /f /v "Localsend" /d "\"%~dp0localsend_app.exe\" autostart"
pause

**Comment by htyed** [comment]
感谢楼上提供的方法，手动操作方式如下：
1. 在 `C:\Users\用户名\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`文件夹下创建`localsend_app.exe`的快捷方式
2. 右键快捷方式 → 属性 → 目标：原路径后边加上` autostart`（注意autostart前有个空格）
