### ISSUE TITLE
Chinese language in media picker when using not supported languages by WeChat File Picker

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#314]
### Describe the bug

Thank you for a wonderful application. For me, this is just a great replacement for Snapdrop, which connects through the server, and it has been very unstable lately.

I see that it is possible to contribute to the translation of the application and I will definitely do it a little later, but at the moment, I noticed the following thing: if the Ukrainian language is selected, when adding Media, for some reason the untranslated pieces are displayed not in English, but in hieroglyphs.

There are no hieroglyphs in the files strings_uk and _missing_translations_uk, so it's not about the translation itself.

### To reproduce

-

### Expected behavior

-

### Screenshots

![1](https://user-images.githubusercontent.com/125032334/227250858-dd4e5c00-8c17-493a-b1c5-53314b4fafae.png)

**Comment by TheGB0077** [comment]
The problem is that the WeChat File Picker lib is defaulting to Chinese Ideograms instead of English for non-supported languages. The current locales supported are: 

- Chinese
- English
- Hebrew
- German
- Russian
- Japanese
- Arabic
- French

**Comment by sergd88** [comment]
> The problem is that the WeChat File Picker lib is defaulting to Chinese Ideograms instead of English for non-supported languages. The current locales supported are:
> 
> * Chinese
> * English
> * Hebrew
> * German
> * Russian
> * Japanese
> * Arabic
> * French

Oh, that's really bad, especially considering that the app is translated into a much wider list of languages. The English translation in this place is not so bad, but the ideograms are visually uncomfortable. And using the Chinese WeChat File Picker as a media file selection looks like a pretty strange solution.

As an option, perhaps there is a way to trick the library for unsupported languages by indicating that it is supposedly not an unsupported language, but English. Then instead of ideograms, there will be English words, which is a much better option.

**Comment by TheGB0077** [comment]
I read the documentation a bit and I think there is a way to override it.

**Comment by sergd88** [comment]
I changed the name of the issue because it turned out that the problem is not only with the Ukrainian language. Before publishing this issue, I tried Russian and French languages, and they display everything correctly, so I thought the problem was only with Ukrainian.

**Comment by TheGB0077** [comment]
@Tienisto Are you ok with setting up the translations for the Asset Picker in Localsend's internal i18n assets? 
Like this: https://github.com/TheGB0077/localsend/tree/Asset-Picker-i18n

By the way, how can I refresh the missing_translations files? I tried `flutter pub run slang analyze`, but that generated one unique file containing the different locales. 

Also, I don't know exactly where I should put the `asset_picker_translated_text_delegate` file in the folder structure. Where should I put it?

**Comment by Tienisto** [comment]
Hi @TheGB0077 , thanks for your effort!

The exact command is `flutter pub run slang analyze --full`.

You can move the delegate to util. These are a lot of translations... but I guess there is no better solution

**Comment by TheGB0077** [comment]
I'm trying to test the app on android, but I can't sign the apk file, I tried generating a keystore file but that didn't work. There's any way I can create it without the original file? 
![image](https://user-images.githubusercontent.com/39922116/227679625-b59f8443-d27d-406b-8611-82893b2a855e.png)

**Comment by Tienisto** [comment]
@TheGB0077 You can change the following line temporarily:

```gradle
# android/app/build.gradle
buildTypes {
  release {
    signingConfig signingConfigs.debug // using debug signing
  }
}
```
