### ISSUE TITLE
This is not a Bug report or Feature request, but a Question: Share Link

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#318]
### Is your feature request related to a problem? Please describe.

When translating, I noticed the following line: "Recipients who do not have LocalSend installed can download the selected files by opening the link in their browser." As far as I understand, it is possible to transfer files to users who do not have LocalSend installed, but I did not notice a corresponding option for transferring files in app. I tried to connect through the browser using the server's IP address, which creates the application, but also unsuccessfully. Could you explain how this feature works or how to enable it? Or did I just misunderstand something? I would appreciate your answer.

### Describe the solution you'd like

-

**Comment by Tienisto** [comment]
Hi, the translation is intended for the next version v1.9.0.

**Comment by sergd88** [comment]
> Hi, the translation is intended for the next version v1.9.0.

Okay, got it. Thx for your answer.
