### ISSUE TITLE
LocalSend exits unexpectedly after minimized to the tray

### ISSUE THREAD

**Issue by WiseClock** [localsend/localsend#32]
LocalSend: 1.6.0
OS: Windows 10 22H2 (19045.2486)

Steps to reproduce:
1. Launch LocalSend and change the settings to allow minimizing to the tray upon close
2. Close LocalSend
3. Observe that the LocalSend icon stays in the tray
4. Wait for 30~60 seconds
5. Observe icons from the tray

Expected result:
LocalSend's icon should remain in the tray and the app should function normally.

Actual result:
LocalSend's icon disappears from the tray and the Windows machine could not be found from LocalSend from other devices.

Other factors (may be irrelevant)
- Chrome is running
- The machine has a multi-monitor setup
- LocalSend is set to launch at Windows startup

**Comment by Tienisto** [comment]
Thanks for mentioning this issue!

I have fixed this problem and will release a hotfix `v1.6.1` soon.

**Comment by Tienisto** [comment]
This should be fixed in `v1.6.1` now, let me know if it still occurs
