### ISSUE TITLE
Feature request: Stylistic changes to the app design

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#320]
### Is your feature request related to a problem? Please describe.

As for me, the Receive page in the app is redundant, as it's just an embellishment and serves no function, but only confuses users, as if it suggests that files can only be received on this page. Many app use the separation of Send and Receive, but there it is structurally justified, because only on the Receive tab can you receive files. In this app, you can receive files from anywhere in the app. And so, to transfer files, you need one extra click. I understand that the Send tab is also used as a starting page where there is a logo, but perhaps it's still worth putting the Receive tab first and renaming it to Send/Receive, or something more concise, and renaming the current Send tab, for example, to Info, so as not to change anything too constructively and so that the app on mobile is not so poor with only two tabs. Perhaps, style it slightly differently.

It's also desirable to move the file transfer history to the Send/Receive page for quick access to it, given that there is quite a lot of free space on the page.

As an example, Snapdrop can be mentioned, which visually mimics AirDrop or Send Anywhere, which also use a combined page for receiving and sending files.

### Describe the solution you'd like

-

**Comment by Tienisto** [comment]
Thanks for your feedback. Please add comments to #300 instead of adding a new issue.

**Comment by sergd88** [comment]
> Thanks for your feedback. Please add comments to #300 instead of adding a new issue.

Sorry, I didn't notice that there's already an appropriate issue.
