### ISSUE TITLE
Feature request: Quite a strange behavior with the selected file after transferring it in Single recipient mode

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#321]
### Is your feature request related to a problem? Please describe.

I also noticed that when sending to a Single recipient, the file remains selected after the transfer. I saw that this was intended, but it only works on the phone. When transferring through the app on Windows, the file is deselected after the transfer.

This is a somewhat strange default behavior that I couldn't understand. Why leave the file selected after transferring it to the phone? If it's to transfer it again to another device, then that's what the Multiple recipients mode is designed for. The most common use case is probably still transferring a file to a single recipient. Therefore, it would be much more convenient to deselect the file after the transfer, because if you need to transfer another file that you forgot about, you'll have to manually deselect the previous file to avoid transferring it again. I personally ran into this situation today.

### Describe the solution you'd like

-

**Comment by Tienisto** [comment]
What kind of files did you sent? This may be related to #293

**Comment by sergd88** [comment]
> 

In my case, it's media files, namely images.

**Comment by Tienisto** [comment]
What LocalSend version do you use on Windows?

**Comment by sergd88** [comment]
> What LocalSend version do you use on Windows?

The latest version of the program is 1.8.0 (27) and it is the same on both the phone and the computer.

But the issue with selection occurs not when send from computer to phone, but the other way around, from phone to computer.

If send from the computer to the phone, the selection disappears after the transfer, but if from the phone to the computer, it does not.

**Comment by sergd88** [comment]
> What LocalSend version do you use on Windows?

Tomorrow I'll try to send file it from another Android device with a different OS and version. Maybe it's not affecting all of them.

**Comment by sergd88** [comment]
> What LocalSend version do you use on Windows?

Tomorrow I'll try to send file it from another Android device with a different OS and Android version. Maybe it's not affecting all of them.

**Comment by sergd88** [comment]
> What LocalSend version do you use on Windows?

I confirm that this is a local problem, specifically some kind of glitch, as everything works fine when send from another device.

It can be resolved by simply reinstalling the application on the device and clearing its data and cache.

And the selection not disappears because for some reason the device connection page itself was not displayed (see screenshot), and the transfer was made directly from the Send tab.

Therefore, you can close this issue.

![2023-03-25_11-08](https://user-images.githubusercontent.com/125032334/227708671-e900c0c6-e582-4e0b-b6ab-61aa942e02fb.png)

**Comment by Tienisto** [comment]
Thanks!
