### ISSUE TITLE
Sending APKs resulting in [400] Request body malformed

### ISSUE THREAD

**Issue by ID-VerNe** [localsend/localsend#327]
### Describe the bug

When using a phone with Android 13 to send an APK file to other devices, an error [400] Request body malformed may occur.
![Screenshot_20230326-084554_LocalSend](https://user-images.githubusercontent.com/49872960/227749196-311bf424-e80c-4051-b224-f2c576213ef3.png)
However, this error does not appear when sending texts, images, or files with other file extensions.
I tested the same operation on another Xiaomi phone with Android 12, and the problem did not occur.

### To reproduce

Error reproduction process: 
1. Install version 1.8.0 of localsend on a phone with Android 13. 
3. Send an APK file to other devices.

### Expected behavior

Normally, we should be able to send files directly to other devices, including APK files.

### Smartphone (please complete the following information)

xiaomi 9
PiexlExperience 13（PlusEdition）
Android13
loaclsend version：1.8.0

**Comment by Tienisto** [comment]
APK files a treated differently in 1.8.0 which means that other devices need to have 1.8.0 installed too.

**Comment by ID-VerNe** [comment]
> APK files a treated differently in 1.8.0 which means that other devices need to have 1.8.0 installed too.

On other devices, I also installed the 1.8.0 version of localsend.

**Comment by Hanmoshi** [comment]
> > APK files a treated differently in 1.8.0 which means that other devices need to have 1.8.0 installed too.
> 
> On other devices, I also installed the 1.8.0 version of localsend.

Same issue here, 1.7.0 works

**Comment by ID-VerNe** [comment]
> 

It seems like a bug that appeared in localsend 1.8.0. Recently, I tested transferring apk files between two phones that installed 1.7.0 and it worked fine. However, when transferring files from 1.8.0 to 1.7.0 or 1.8.0, the error occurs.

**Comment by ID-VerNe** [comment]
> > > APK files a treated differently in 1.8.0 which means that other devices need to have 1.8.0 installed too.
> > 
> > 
> > On other devices, I also installed the 1.8.0 version of localsend.
> 
> Same issue here, 1.7.0 works

It seems like a bug that appeared in localsend 1.8.0. Recently, I tested transferring apk files between two phones that installed 1.7.0 and it worked fine. However, when transferring files from 1.8.0 to 1.7.0 or 1.8.0, the error occurs.
