### ISSUE TITLE
Feature request (send links of web pages)

### ISSUE THREAD

**Issue by LoryPelli** [localsend/localsend#332]
### Is your feature request related to a problem? Please describe.

I don't like the thing that you can't send links of web pages

### Describe the solution you'd like

We can send link to the page by typing it or maybe with drag and drop

**Comment by Tienisto** [comment]
You can send links already. It is just a text message.

**Comment by LoryPelli** [comment]
> You can send links already. It is just a text message

Does it download a txt file on the pc?

**Comment by Tienisto** [comment]
No, except you send multiple text messages

**Comment by Tienisto** [comment]
Closing this as sending links is already possible.
