### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by LoryPelli** [localsend/localsend#333]
### Describe the bug

Drag and Drop files (windows) doesn't work

### To reproduce

Take an image from google and upload it with drag and drop

### Expected behavior

It should work

**Comment by Tienisto** [comment]
You need to drag-and-drop from Windows Explorer.

**Comment by LoryPelli** [comment]
> You need to drag-and-drop from Windows Explorer.

You should make drag and drop from every app (should I make a feature request about this)?
