### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by LoryPelli** [localsend/localsend#334]
### Is your feature request related to a problem? Please describe.

Translations

### Describe the solution you'd like

Use crowdin if possible

**Comment by Tienisto** [comment]
There are translations. If your language is missing, then you can contribute. Please read the README for further information.

**Comment by LoryPelli** [comment]
> There are translations. If your language is missing, then you can contribute. Please read the README for further information.

I mean translations from crowdin instead of forking the repo

**Comment by Tienisto** [comment]
The app uses a custom i18n format that is not supported by most third-party services. Furthermore, the current process is not much more complex if you just edit the file via Github.
