### ISSUE TITLE
Support AndroidTV

### ISSUE THREAD

**Issue by androidcn** [localsend/localsend#34]
all button can not click with Remote control center button AndroidTV
just like enter button

**Comment by Tienisto** [comment]
Android TV is currently not supported, but I will add the compatibility is a future release.

**Comment by Tienisto** [comment]
Added in `v1.8.0`

**Comment by wallismith** [comment]
@Tienisto Thanks for adding Android TV support! 

Question — will the app now be available to install via Play Store for Android TV? Or do we need to sideload the app instead? 

With the former, app updates would be simpler versus sideloading everytime there's an update 👍🏾 

Thanks again for the amazing app!

**Comment by Tienisto** [comment]
This app should be available on the play store. But I didn't tested it yet because I don't have an Android TV

**Comment by wallismith** [comment]
@Tienisto As of now, it's not available on Android TV Play Store. I checked last Saturday, but figured it was the weekend and maybe Google hadn't approved the listing for Android TV.

**Comment by Tienisto** [comment]
@wallismith I forgot to enable "TV" in the Play Store as I thought that it detects automatically.

Now it should be available in the Play Store.

**Comment by wallismith** [comment]
@Tienisto It looks like is still isn't available on Android TV Play Store. Could be another issue.

Here's a screenshot of the WireGuard app as an example:

![Screenshot_20230314-172304](https://user-images.githubusercontent.com/6549971/225140731-1f598dc6-e8ca-4cde-af2a-fa08904911b2.png)
