### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by zhyd1204** [localsend/localsend#341]
### Describe the bug

The start hidden not working

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

i hope that when i open it ,it start silently and dont show the main panel

**Comment by fandro** [comment]
mac os 10.15.7 打开后是空白窗口
![Jietu20230403-143103](https://user-images.githubusercontent.com/515874/229429071-1189b4fb-8305-48fd-a94f-c9a56a52e44b.jpg)

**Comment by Tienisto** [comment]
Closed in favor of #529 and #516
