### ISSUE TITLE
Multidevice

### ISSUE THREAD

**Issue by LoryPelli** [localsend/localsend#348]
### Is your feature request related to a problem? Please describe.

Is it possible to have the option to send to multiple devices instead of one a time?

### Describe the solution you'd like

Like airdrop thing

**Comment by Tienisto** [comment]
This is possible since v1.8.0

**Comment by LoryPelli** [comment]
> This is possible since v1.8.0

How can I do this?

**Comment by Tienisto** [comment]
On the "Send" tab, there are 3 icons next to each other. Press on the settings icon. Finally, select "Multiple Recipients"

**Comment by LoryPelli** [comment]
> On the "Send" tab, there are 3 icons next to each other. Press on the settings icon. Finally, select "Multiple Recipients"

So I think the single recipient mode should be removed at all, multiple recipients it's obviously better

**Comment by Tienisto** [comment]
There are a lot of users who have LocalSend in background, and they complained that the selection persists after a file transfer.

**Comment by LoryPelli** [comment]
> There are a lot of users who have LocalSend in background, and they complained that the selection persists after a file transfer.

You should make a discord server (if it doesn't exists already)
