### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by foreversy** [localsend/localsend#350]
### Describe the bug

PC端报错：通常每个套接字地(协议/网络地址/端)只允许使用一次，无法接收文件

### To reproduce

双击运行就出现了

### Expected behavior

希望可以正常使用

### Screenshots

![image](https://user-images.githubusercontent.com/63082366/229139344-01096f16-8185-4098-a6e5-f0766c3e8ee2.png)

### Desktop (please complete the following information)

打开后出现如下提示：SocketException: Failed to create server socket OS Error: 通常每个套接字地(协议/网络地址/端)只允许使用一次
检查过防火墙，未发现问题；自动修复也没有变化

**Comment by Ox2098** [comment]
I encountered it too, how to solve? Current version number v1.11.1 (35)
