### ISSUE TITLE
Bug report:  No longer automatically turns off the monitor after pressing Win+L 

### ISSUE THREAD

**Issue by userzzzq** [localsend/localsend#353]
### Describe the bug

No longer automatically turns off the monitor after pressing Win+L 
this is caused by LocalSend, when I exit Localsend, and it's back to normal 
（win11 system）

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Windows should automatically turns off the monitor after pressing Win+L

**Comment by Tienisto** [comment]
I cannot reproduce this

**Comment by DancingDolphins** [comment]
Win+L Means Lock current User ,but not close the monitor. there is a setting in windows let you set how many minutes shutdown the monitor,maybe you can check that setting?
