### ISSUE TITLE
静默自启无效

### ISSUE THREAD

**Issue by stonereese** [localsend/localsend#356]
### Describe the bug

设置中打开了静默自启, 但是每次开机, 软件启动后, 出现程序窗口, 不会自动缩到托盘

### To reproduce

1. Go to '设置'
2. Click on '静默自启'
3. 重启电脑
4. 出现 local send 窗口

### Expected behavior

无

**Comment by aiomkr** [comment]
https://github.com/localsend/localsend/issues/71#issuecomment-1408632153

**Comment by stonereese** [comment]
我提出的问题不是不会随系统自动启动，而是随系统启动后，不会自动最小化到托盘。补充我是用的不是便携版，而是安装版。

**Comment by jxjeff** [comment]
+1
