### ISSUE TITLE
Feature request: trust on first use

### ISSUE THREAD

**Issue by septs** [localsend/localsend#357]
### Is your feature request related to a problem? Please describe.

like [ADB](https://en.wikipedia.org/wiki/Android_Debug_Bridge) trust model, based trust on first use target device.

enhance quick save mode safety 

### Describe the solution you'd like

use two-way tls authentication

![image](https://user-images.githubusercontent.com/3842474/229725659-45a97cc9-e39c-4563-b9e3-61021e0a85f0.png)

from https://docs.solace.com/Security/Two-Way-SSL-Authentication.htm

**Comment by Tienisto** [comment]
Some kind of client authentication is planned for v2.

Maybe the certificate needs to be sent inside `/send-request`?

For example

```json5
{
  "info": {
    "alias": "Nice Orange",
    "deviceModel": "Samsung", // nullable
    "deviceType": "mobile", // mobile | desktop | web
    "cert": "-----BEGIN CERTIFICATE-----\nMIICUTCCA [...]-----END CERTIFICATE-----"
  },
  "files": {
    "some file id": {
      "id": "some file id",
      "fileName": "my image.png",
      "size": 324242, // bytes
      "fileType": "image", // image | video | pdf | text | other
      "preview": "*preview data*" // nullable
    },
    "another file id": {
      "id": "another file id",
      "fileName": "another image.jpg",
      "size": 1234,
      "fileType": "image",
      "preview": "*preview data*"
    }
  }
}
```

**Comment by Tienisto** [comment]
I need to check if Flutter supports client-side certificates.

**Comment by septs** [comment]
> Trust on first use (TOFU), or trust upon first use (TUFU), is an [authentication](https://en.wikipedia.org/wiki/Authentication) scheme[[1]](https://en.wikipedia.org/wiki/Trust_on_first_use#cite_note-1) used by client software which needs to establish a trust relationship with an unknown or not-yet-trusted endpoint. In a TOFU model, the client will try to look up the endpoint's identifier, usually either the [public identity key](https://en.wikipedia.org/wiki/Digital_signature) of the endpoint, or the [fingerprint](https://en.wikipedia.org/wiki/Public_key_fingerprint) of said identity key, in its local trust database. If no identifier exists yet for the endpoint, the client software will either prompt the user to confirm they have verified the purported identifier is authentic, or if manual verification is not assumed to be possible in the protocol, the client will simply trust the identifier which was given and record the trust relationship into its trust database. If in a subsequent connection a different identifier is received from the opposing endpoint, the client software will consider it to be untrusted.

https://en.wikipedia.org/wiki/Trust_on_first_use
