### ISSUE TITLE
Finished with error when the file transfer is about to be completed

### ISSUE THREAD

**Issue by meiMingle** [localsend/localsend#36]
![image](https://user-images.githubusercontent.com/39942874/215238377-e61bb5d4-3b0a-46c1-b42b-9b77cf0c2adb.png)
Here is the file to transfer: [ideaIU-2022.3.2.win.zip](https://download-cdn.jetbrains.com/idea/ideaIU-2022.3.2.win.zip)
Transfer from Windows to Android devices, all client versions are 1.6.1

**Comment by meiMingle** [comment]
I've tried many times and failed

**Comment by Tienisto** [comment]
Is it only this file? What happens if you rename the file?

**Comment by meiMingle** [comment]
> Is it only this file? What happens if you rename the file?
Not only this file, I have tried several relatively large files, and they will all fail with a high probability. Renaming doesn't work. In general, the larger the file, the greater the probability of failure

**Comment by kunimei** [comment]
good thankyou

**Comment by mitlearn** [comment]
Same issue
I tried to send with Win/iOS/Android to another and got same error whatever which file I sent or how large file size(Above 1GB

**Comment by yarray** [comment]
I came across similar behaviors on Android (Mac/Windows sending files to Android failed) and fixed the issue by allow NO_ISOLATED_STORAGE and MANAGE_EXTERNAL_STORAGE with App Manager. Not sure what's the mechanism, though.

**Comment by Tienisto** [comment]
In `v1.7.0`, you should be able to read the exact error message

**Comment by meiMingle** [comment]
@Tienisto Now, I get specific and detailed error message.

![image](https://user-images.githubusercontent.com/39942874/218907348-850e39f8-a54e-4971-b475-db1ace1a4e81.png)

![Screenshot_2023-02-15-09-54-31-83_df28ed62bb7da3a221841ad3d925c81c](https://user-images.githubusercontent.com/39942874/218907551-0340b86a-30c6-45e4-b714-319d442e5e41.jpg)

**Comment by meiMingle** [comment]
@Tienisto I guess that the data transmission channel may be forced to close because the data transmission time has reached the upper limit of the default connection time of a certain configuration.

**Comment by meiMingle** [comment]
@Tienisto Feel free to @ me if more information is needed in order to resolve this issue. Large file transfer is very important to me, I hope it will be resolved as soon as possible

**Comment by Tienisto** [comment]
Thanks for your help. Yes this is quite important

**Comment by meiMingle** [comment]
@Tienisto How's the progress？

**Comment by meiMingle** [comment]
@Tienisto Dear, any progress on this?

**Comment by Tienisto** [comment]
I could not reproduce it yet

**Comment by meiMingle** [comment]
@Tienisto I just tested it with the latest version of the widows client and the android client, and the problem can still be reproduced. Maybe your test file is not large enough, this usually happens with files over 1GB in size.

**Comment by wzblog** [comment]
When I send from Windows to Windows, I encounter the same problem, but when using Windows to send to Mac, it works fine. I conducted the test using the same file.

**Comment by Ginfai** [comment]
Change the MAC address in WiFi settings to the device MAC

**Comment by mirh** [comment]
I feel stupid, how do you get the actual Error to show (on both android and desktop)?
