### ISSUE TITLE
Install it from Homebrew

### ISSUE THREAD

**Issue by xiehao** [localsend/localsend#361]
### Is your feature request related to a problem? Please describe.

It is not found in Homebrew's repo.

### Describe the solution you'd like

It can be installed by `brew install --cask localsend`.

**Comment by TheGB0077** [comment]
Run 
brew tap localsend/localsend
brew install localsend

**Comment by xiehao** [comment]
> Run brew tap localsend/localsend brew install localsend

Thank you very much!
