### ISSUE TITLE
App interface crash issue in Chinese language

### ISSUE THREAD

**Issue by SHIELDXIE** [localsend/localsend#37]
Test device：Windows 11 / Android 12 (OneUI)
The file transfer confirmation screen crashes when using the Simplified Chinese interface, but there is no problem with English
<img src="https://user-images.githubusercontent.com/37254173/215240332-3080526d-755e-43e3-8f3f-3b88d9cb6289.png" width="200px">   (English interface is normal)
<img src="https://user-images.githubusercontent.com/37254173/215240036-4ddbf2ff-c5db-454e-b88a-64bf6c38aeef.jpg" width="200px">   (Android app crash screen, window is the same as this)

**Comment by WiseClock** [comment]
I hit this issue too.  There was an i18n structure change in 1.6.1, LocalSend probably isn't catching exceptions when fetching values from language files, hehe 😁.

**Comment by Tienisto** [comment]
I the progress page I used the i18n plural feature but forgot to register it for Chinese. I guess another hotfix release is needed

**Comment by saccohuo** [comment]
+1

**Comment by Tienisto** [comment]
Fixed in `v1.6.2`.

On Google Play and App Store it is already available. On Windows Store and MacOS, it will take around 12 hours.
