### ISSUE TITLE
Feature request: Selection via Clipboard

### ISSUE THREAD

**Issue by septs** [localsend/localsend#373]
### Is your feature request related to a problem? Please describe.

Reduce workflows (or steps)

### Describe the solution you'd like

Use case:

1. Copy a file or text or rtf fragment to clipboard
2. Open LocalSend App
3. Detect clipboard is has content, If has content then show window is send or not

Problem:

1. Need improve protocol, add clipboard supports

### Describe alternatives you've considered

- [Apple Universal Clipboard](https://support.apple.com/HT209460) (Apple ONLY)
- [KDE Connect](https://userbase.kde.org/KDEConnect#Clipboard) (Linux ONLY)
- [Microsoft Phone Link](https://support.microsoft.com/topic/8a0ead3c-2f15-1338-66ca-70cf4ae81fcb) (Windows ONLY)

### Additional context

see https://api.flutter.dev/flutter/services/Clipboard-class.html

**Comment by Tienisto** [comment]
Adding clipboard contents to selection does not need any protocol changes. A message transfer is just a text with `preview` included.

**Comment by cxfksword** [comment]
On the android platform,  hope that quick setting tiles can also be supported, so that can edit and send text directly without open LocalSend app

https://developer.android.com/develop/ui/views/quicksettings-tiles
