### ISSUE TITLE
[iOS] Media selection - item count bug

### ISSUE THREAD

**Issue by bachig26** [localsend/localsend#379]
### Describe the bug

When you usually see the total number of items in the media container but the app is displaying the total number of items present as 999 which suggests the counter might have some bug and don't as expected.

I thought this issue might be the permission allowed to see the media but I have given the complete permission to access the photos but still seeing this bug.

### To reproduce

1. Go to 'Send'
2. Click on 'Media'
3. Select 'images/video'

### Expected behavior

I hope to see that the total items in the folder/media as the number of items present instead of an infinite counter value.

### Screenshots

![lcsd](https://user-images.githubusercontent.com/96393348/231597665-25ea9cd4-4209-44ce-841d-6ec67ceffba6.jpg)

### Smartphone (please complete the following information)

- Device: iPhone SE 1st Gen & iPhone SE 3rd Gen
- OS: iOS 16.4.1 & iOS 15.7.3 [i use both in 2 different devices]
- App Version: 1.8.0 (build 27) App Store

**Comment by TheGB0077** [comment]
That's not how many items there are in total, but it is, in fact, a limit of how many assets you can select.

https://github.com/localsend/localsend/blob/5b2d01c2d064db8564bff9e6924151d6f001d2f0/lib/util/native/file_picker.dart#L108

**Comment by Tienisto** [comment]
Yeah, I could not find a way to make it "unlimited". But there is #376 which also addresses this issue.
