### ISSUE TITLE
最新版本启动时常报错

### ISSUE THREAD

**Issue by star2k** [localsend/localsend#38]
![Snipaste_2023-01-28_13-14-26](https://user-images.githubusercontent.com/9582078/215243517-7afeb04c-1287-4ba0-a444-46400b4c9775.png)

win10 22H2 x64系统

**Comment by star2k** [comment]
很好的app，报告几个问题：
1.无法启动后，在后台运行，一定要跳界面
2.无法传送文本内容
3.上图运行错误

**Comment by Tienisto** [comment]
Fixed in `v1.6.2`
