### ISSUE TITLE
Cannot use MSIX package for Windows 10 v1809-1909

### ISSUE THREAD

**Issue by brogers5** [localsend/localsend#398]
### Describe the bug

The MSIX package manifest does not appear to be recognized as valid for a Windows v1809-1909 system:

```ps1
PS C:\Users\vagrant\Desktop> Add-AppxPackage .\LocalSend-1.8.0.msix
Add-AppxPackage : Deployment failed with HRESULT: 0x80080204, The Appx package's manifest is invalid.
error 0xC00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 56, Column 138,
Note: The schema for MaxVersionTested specified does not recognize XML fields with namespace
"http://schemas.microsoft.com/appx/manifest/uap/windows10/10". Please ensure that you have the correct
MaxVersionTested specified. Reason: The attribute
'{http://schemas.microsoft.com/appx/manifest/uap/windows10/10}Parameters' on the element
'{http://schemas.microsoft.com/appx/manifest/desktop/windows1
error 0xC00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 56, Column 138,
Note: The schema for MaxVersionTested specified does not recognize XML fields with namespace
"http://schemas.microsoft.com/appx/manifest/uap/windows10/10". Please ensure that you have the correct
MaxVersionTested specified. Reason: The attribute
'{http://schemas.microsoft.com/appx/manifest/uap/windows10/10}Parameters' on the element
'{http://schemas.microsoft.com/appx/manifest/desktop/windows10}Extension' is not defined in the DTD/Schema.
NOTE: For additional information, look for [ActivityId] 64ed0f28-7292-0003-8a18-ed649272d901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 64ed0f28-7292-0003-8a18-ed649272d901
At line:1 char:1
+ Add-AppxPackage .\LocalSend-1.8.0.msix
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\vagran...Send-1.8.0.msix:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

```ps1
PS C:\Users\vagrant\Desktop> Get-AppPackageLog -ActivityID 64ed0f28-7292-0003-8a18-ed649272d901

Time                      ID           Message
----                      --           -------
4/18/2023 10:33:42 PM     157          The app package signature was validated for core content of the app package
                                       published by CN=Tien Do Nam, O=Tien Do Nam, S=Sachsen, C=DE. Payload won't be
                                       validated until the files are read.
4/18/2023 10:33:42 PM     135          error 0xC00CE015: App manifest validation error: The app manifest must be valid
                                       as per schema: Line 56, Column 138, Note: The schema for MaxVersionTested
                                       specified does not recognize XML fields with namespace
                                       "http://schemas.microsoft.com/appx/manifest/uap/windows10/10". Please ensure
                                       that you have the correct MaxVersionTested specified. Reason: The attribute
                                       '{http://schemas.microsoft.com/appx/manifest/uap/windows10/10}Parameters' on
                                       the element
                                       '{http://schemas.microsoft.com/appx/manifest/desktop/windows10}Extension' is
                                       not defined in the DTD/Schema.

4/18/2023 10:33:41 PM     603          Started deployment Add operation on a package with main parameter
                                       LocalSend-1.8.0.msix and Options 0 and 0. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app
                                       deployment issues.
4/18/2023 10:33:42 PM     465          error 0x80080204: Opening the package from location LocalSend-1.8.0.msix failed.
4/18/2023 10:33:42 PM     497          Error 0x80070002: Opening the Msixvc package from location LocalSend-1.8.0.msix
                                       failed. Please check whether the Msixvc support services are installed.
4/18/2023 10:33:42 PM     403          error 0x80080204: Failure to get staging session for:
                                       file:///C:/Users/vagrant/Desktop/LocalSend-1.8.0.msix.
4/18/2023 10:33:42 PM     404          AppX Deployment operation failed for package  with error 0x80080204. The
                                       specific error text for this failure is: error 0xC00CE015: App manifest
                                       validation error: The app manifest must be valid as per schema: Line 56, Column
                                       138, Note: The schema for MaxVersionTested specified does not recognize XML
                                       fields with namespace
                                       "http://schemas.microsoft.com/appx/manifest/uap/windows10/10". Please ensure
                                       that you have the correct MaxVersionTested specified. Reason: The attribute
                                       '{http://schemas.microsoft.com/appx/manifest/uap/windows10/10}Parameters' on
                                       the element
                                       '{http://schemas.microsoft.com/appx/manifest/desktop/windows10}Extension' is
                                       not defined in the DTD/Schema.
```

### To reproduce

On an affected version of Windows, either launch the MSIX installer with App Installer (double-click), or attempt installation in Windows PowerShell using the `Add-AppxPackage` cmdlet.

### Expected behavior

Installation should either complete without errors, or explicitly fail due to a version incompatibility.

### Screenshots

![LocalSend MSIX Package Parsing Error](https://user-images.githubusercontent.com/6869577/232984656-cce31678-d478-46a9-b4b3-f6159e3a1c2a.png)

### Desktop (please complete the following information)

- OS: Windows
- Version: 18363.1621
- App Installer Version: 1.19.10173.0

### Additional context

I'm the maintainer for [the recently implemented Chocolatey package](https://community.chocolatey.org/packages/localsend), the initial revision of which currently consumes the officially distributed portable ZIP archive. I would like to create a variant of this package that consumes the MSIX installer to accommodate users who have a requirement or preference for installed applications. Ideally, this would take the form of a new installer package (`localsend.install`), which I would then follow up by spinning off current functionality to a new portable package (`localsend.portable`), then converting the existing package to a metapackage.

I have several clean Windows VMs which I use to functionally validate software compatibility and dependencies (e.g. minimum OS version, bundled software, runtime requirements, etc.) for all of the Chocolatey packages I maintain. As the Chocolatey Community Repository makes published package versions immutable once they pass the moderation process, it's important that I get this right the first time to avoid needing to publish a package fix version.

While smoke testing the v1.8.0 MSIX package, I found I could not complete installation on an unpatched version of Windows 10 prior to v2004. This behavior seems to conflict with the minimum Windows version as declared in the manifest file (v1809).

I'm raising this issue mainly to get clarification for the supportability expectations of the MSIX package, as it relates to a minimum OS requirement I must declare for the planned Chocolatey package. If the intent was indeed to support v1809 forward, then this is probably something that should be fixed.

I'm admittedly not very familiar with building MSIX packages, but from some quick reading, it seems the namespace being mentioned [was introduced in v2004](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application#uap10-was-introduced-in-windows-10-version-2004-100-build-19041), so some backward compatibility may be required to properly support v1809-1909. Otherwise, the manifest may need its minimum version requirement bumped up accordingly.

**Comment by Tienisto** [comment]
Thanks for noticing this.

The msix uses`uap10:Parameters` for the [Startup Task](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-startuptasks). The app needs to know whether it was open by the user or on boot / login (which is needed for "Start minimized") so an additional parameter is added.

I could not find an alternative yet, so I guess the min version needs to be bumped to 2004.
