### ISSUE TITLE
android app broadcasts itself on all interfaces.

### ISSUE THREAD

**Issue by bitching** [localsend/localsend#399]
### Describe the bug

android app broadcasts itself on all interfaces.
which should not on ***VPN / mobile network*** interfaces, they are not "Local".

### To reproduce

1. By default connect to WLAN and with mobile data on.
2. you will see this.
3. (optional) if connects to a VPN, you will see the VPN's ip in LocalSend.

### Expected behavior

at least should not work on mobile network interface.
maybe let user choose which interface to bind helps, or just exclude the interfaces but WLAN?

### Screenshots

![1](https://user-images.githubusercontent.com/12702029/233013362-feeee892-a137-4d58-9a5f-56995856dcf4.jpg)
![2](https://user-images.githubusercontent.com/12702029/233013369-bdd754ed-845f-43c3-9d1f-6be6349391b0.jpg)

### Smartphone (please complete the following information)

Device : OnePlus
OS: Android 13

**Comment by bitching** [comment]
> I could not find a reliable solution to detect the type of the network interface.
> 
> Besides that, the only "bad" thing about this is that this interface doesn't work.
> 
> Having LocalSend in VPN is actually a feature as there are some users wo use their own VPN to send files across the internet.

but what if allow user choosing which interface to bind?
maybe a better way?

**Comment by Tienisto** [comment]
The scan happens now in all networks anyways. The user should not worry about this technical stuff.
