### ISSUE TITLE
Feature request: Use impeller for improved performance on iOS

### ISSUE THREAD

**Issue by Void48** [localsend/localsend#406]
### Is your feature request related to a problem? Please describe.

https://docs.flutter.dev/perf/impeller

### Describe the solution you'd like

I would like for impeller to be enabled so iOS users could have better app performance

**Comment by Tienisto** [comment]
This will be enabled in the next feature release (`1.10.0` or `2.0.0`).

**Comment by Tienisto** [comment]
Impeller will be used by default in Flutter 3.10 which is now in main branch.
