### ISSUE TITLE
Nearby devices are not seen

### ISSUE THREAD

**Issue by ZeroBit** [localsend/localsend#414]
### Describe the bug

All other iOS and iPad devices can see Pixel 4a with running LocalSend, but Pixel 4a itself cannot see any device.

### To reproduce

1. Go to '.Send'
2. Click or not clock 'Refresh'
3. See the fading animation with no device.

### Expected behavior

It is expected that one instance of the localsend could see all other instances on the same network.

### Screenshots

![Screenshot_20230426-170432](https://user-images.githubusercontent.com/6258813/234571485-d68e9b4d-d0a4-42d5-aed2-a6e8b0cbc3f3.png)

### Desktop (please complete the following information)

Android 13

### Smartphone (please complete the following information)

Pixel 4a

**Comment by Tienisto** [comment]
Try to tap on "Sync" on both iPad and Pixel

**Comment by ZeroBit** [comment]
I did it just now. Simultaneously on 3 devices: iPad,iPhone, Pixel. Nothing changed. iPad and iPhone can see two other devices (including Pixel). Pixel can see none.

**Comment by Tienisto** [comment]
Can you go to `Settings Tab -> About -> Debugging -> Discovery`? What do you see there on the Pixel compared to the iOS devices?

**Comment by ZeroBit** [comment]
> Can you type in the IP address manually (there is a button next to "Sync")?
Have no idea what the button means

**Comment by Tienisto** [comment]
You need to switch to "IP Address" tab to type the full IP address.

Regarding the logs, it seems that multicast (UDP) is not working on your network.
That's why your iPhone tries to detect the devices via traditional TCP scan.

This is weird, it seems that the Pixel cannot do any of these although the Pixel seem to detect the correct network (192.168.1.x)

**Comment by ZeroBit** [comment]
> You need to switch to "IP Address" tab to type the full IP address.

Error. The same
![2023-04-26 21 14 55](https://user-images.githubusercontent.com/6258813/234637764-04e51ad2-bc92-493f-8a67-13030871a13d.jpg)

**Comment by ZeroBit** [comment]
> In the settings tab under "Network", there are several configurations. Is "encryption" enabled on all devices? Basically, all options must be the same across all devices (except the alias)

All options are the same (except alias)
iPhone: 
![IMG_A7435061432B-1](https://user-images.githubusercontent.com/6258813/234640301-0a2cbfe9-0a23-4faf-a306-3c55dc52bef9.jpeg)

Pixel 4a
![2023-04-26 21 22 57](https://user-images.githubusercontent.com/6258813/234640336-dfeeeb59-4cc1-49e3-b162-a7f0973da099.jpg)

**Comment by HongbangYuan** [comment]
I got exactly the same issue! My laptop is lenovo with windows 11 and my phone is Honor 30 with android. I follow the steps provided above and the two devices still have trouble finding each other.

**Comment by decipher3114** [comment]
I turned on the Hotspot of My PC and connect my device via wifi. My PC can find the phone, but It can't find the PC from the phone. 

Simply speaking, 
PC with hotspot -> Phone with Wi-fi ✔️
Phone with Wi-fi -> PC with hotspot ❌

**Comment by dayvid3214** [comment]
![image](https://user-images.githubusercontent.com/60224905/236621851-a9fefabc-c9f1-44e7-8878-6eb43e5a4e66.png)
🇬🇧
Hello, I hope this helps. As you can see in the image (in Spanish), having the same problem as you, I have created two input rules to "free" port 53317, but it has not worked.

My Google pixel has detected the PC when I have removed the rule to block connections in public networks (those two that do not have the green check).

---
🇪🇸

Hola, espero que esto ayude. Como se puede ver en la imagen (en español), al tener el mismo problema que vosotros he creado dos reglas de entrada para "liberar" el puerto 53317, pero no ha servido.

Mi Google pixel ha detectado el PC cuando he quitado la regla de bloquear conexiones en redes públicas (las dos que no tienen el check verde).

**Comment by klawdhfzasjhaa** [comment]
I have this issue, too.

Manjaro laptop, Samsung Tablet (Stock Android) and Fairphone (LineageOS).

Laptop and Tablet can see the Fairphone, but Fairphone is "blind" and cannot receive files from the others.

I suspect something in the Android settings.. Rethink DNS and Blokada are installed, but turned off.

**Comment by Tienisto** [comment]
Closed in favor of #527

**Comment by mightywomble** [comment]
Why was this "Closed in favor of https://github.com/localsend/localsend/issues/527" ?

They are different issues.

Essentially if you use LocalSend with a VPN, even though the interface is aware of the additional IP addresses, the multicast in the protocol used just doesn't work over VPN's so stops the whole setup from working. As highlighted in other issues there is a need for a WebRTC gateway similar to pairdrop (which has the same issue, and gets round it by routing the traffic via the hosting server) to allow for comms not depending on multicast traffic. 

Someone answering the tickets however, isn't versed in this and seems to feel this is bleeding edge stuff. Its not.

**Comment by ignoramous** [comment]
> Someone answering the tickets however, isn't versed in this and seems to feel this is bleeding edge stuff. Its not.

If you're technical enough and have enough time, do consider sending a pull request. If not, do consider highlighting how one can make this change with example code / references, at least?
