### ISSUE TITLE
iPadOS & Android 13 互传失败

### ISSUE THREAD

**Issue by ashaquecat** [localsend/localsend#42]
AppStore 与 PlayStore 下载，均为20230128下载安装。

在传输文件或者图片时：
1 接收端如果不开启自动保存
2 接收端页面没有任何提示 
3 发送端一直是等待响应中
4 接收端开启自动保存
5 可收到文件

在发送文本消息时：
1 接收端不开启自动保存
2 可收到信息

权限都给到了 不确定哪里问题
Android 与iPad 无论谁做接收端 都有此问题

**Comment by idjfia** [comment]
应该是语言设置为中文的问题，后续版本会修复

https://github.com/localsend/localsend/issues/37#issuecomment-1407389950

***建议尽可能使用英语反馈，开发者可能不懂中文**

**Comment by ashaquecat** [comment]
> 应该是语言设置为中文的问题，后续版本会修复
> 
> 
> 
> https://github.com/localsend/localsend/issues/37#issuecomment-1407389950
> 
> 
> 
> ***建议尽可能使用英语反馈，开发者可能不懂中文**

确实是语言问题 感谢提醒 之后改用英语反馈
