### ISSUE TITLE
Microsoft Store release(.msix) cannot silent startup

### ISSUE THREAD

**Issue by SunshineboyZj** [localsend/localsend#421]
### Describe the bug

Microsoft Store release cannot silent startup，autostart:start hidden cannot work

### To reproduce

open and findit cannot start hidden,you can watch the uploaded video

### Expected behavior

it can be automatically minimized to the taskbar (silent startup)

### Screenshots

https://user-images.githubusercontent.com/81549837/235088990-9fdbb22e-6c59-469c-853f-e241667f2ccb.mp4

https://user-images.githubusercontent.com/81549837/235089019-9080c19d-1813-4590-bb4f-242ff905eca6.mp4

### Desktop (please complete the following information)

Windows 10 21H2
LocalSend:1.9.0

**Comment by Tienisto** [comment]
Closed in favor of #529
