### ISSUE TITLE
an file with chinese name cannot be transmitted through a link

### ISSUE THREAD

**Issue by SunshineboyZj** [localsend/localsend#422]
### Describe the bug

specifically, the webpage continues to load after clicking on download, and there is no response

### To reproduce

transmitt  an file with chinese name through a link.you can watch the uploaded video

### Expected behavior

If you can fix it，thank you very much

### Screenshots

https://user-images.githubusercontent.com/81549837/235095112-c888bc8f-7f0e-4951-8dac-5f98501ef838.mp4

### Desktop (please complete the following information)
Windows 10 21H2
PC LocalSend:1.9.0

**Comment by Tienisto** [comment]
Thank you. This has been fixed. A `1.9.1` release will come soon!
