### ISSUE TITLE
Bug report - iOS devices cannot receive full GIF files

### ISSUE THREAD

**Issue by i007x** [localsend/localsend#430]
### Describe the bug

Thanks for making this software.

Sending a GIF file on a PC to an iOS device can only display the first frame.

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Sending GIF files of any size and capacity to the iOS device shows that it is successfully completed, but only the first frame of the screen can be displayed.

### Desktop (please complete the following information)

Windows 11 22H2
v1.9.0

### Smartphone (please complete the following information)

iPhone 13mini
16.4.1
v1.9.0

**Comment by Tienisto** [comment]
What happens if you send the GIF back to Windows?

**Comment by kamtasingh27** [comment]
Tested on Ubuntu 23.04

Sending from Ubuntu to iOS - Only first frame of GIF shows
Sending from iOS to Ubuntu - GIF works properly

**Comment by Tienisto** [comment]
I guess that the Photos app on iOS does not support GIF

**Comment by kamtasingh27** [comment]
The Photos is supporting GIF when downloaded through Safari.

**Comment by kamtasingh27** [comment]
Seems like the issue was with the image_gallery_saver dependency.
I have raised a PR which should fix the issue here as well once merged,

https://github.com/hui-z/image_gallery_saver/issues/248

**Comment by Tienisto** [comment]
@kamtasingh27 Thank you for the PR. The [image_gallery_saver](https://github.com/hui-z/image_gallery_saver) package seem to be unmaintained. Maybe you can checkout https://pub.dev/packages/saver_gallery ?

**Comment by kamtasingh27** [comment]
@Tienisto I don't have mac so I can't build for iOS :(

**Comment by natsuk4ze** [comment]
@Tienisto Not long ago, I released [an alternative package](https://pub.dev/packages/gal/score). I hope you will take a look at it. Appreciate it.

**Comment by Tienisto** [comment]
Thanks @natsuk4ze does it also keep the file name? I think there was one issue that someone wanted to also keep the file name when saving to gallery

**Comment by Tienisto** [comment]
Yeah, maybe you can checkout the current implementation of [image_gallery_saver](https://pub.dev/packages/image_gallery_saver):

https://github.com/localsend/localsend/blob/f74b3ae319d8503f5dee577e263da94065c24162/lib/util/native/file_saver.dart#L45

**Comment by natsuk4ze** [comment]
@Tienisto My package has now implemented that feature and will upload it to pub.dev.

By the way, is the `name` parameter the name of the file as it is? Like `image.jpg`. Or is it the title? Like `cool image`.

**Comment by Tienisto** [comment]
It should be the file name like image.jpg

**Comment by natsuk4ze** [comment]
Okay ,now we can close this issue by migrating `image_gallery_saver` to `gal`.
So, I gonna draft PR, but I can not build this app for flutter version diff so please consider co-authoring. ok?

**Comment by Tienisto** [comment]
Sure, thanks
