### ISSUE TITLE
Feature request: save to sd card in android

### ISSUE THREAD

**Issue by smoothoperatorgr** [localsend/localsend#431]
### Is your feature request related to a problem? Please describe.

Internal storage in most android phones is limited. whereas sd card can be quite spacious

### Describe the solution you'd like

select sd card as saving location

**Comment by reddevilrulez** [comment]
+1

**Comment by wzrzt** [comment]
I tried, it can. But the way is not so smooth. First I choosed a SD card folder, it asked authority, but when I received file, it failed to save the file. 
Then I tried to send file from Android to Mac, it asked me again for the storage access, then check it in the list of many apps. Then I changed the same folder from SD card, it can saved file to it.
Hope it can help you.

**Comment by Tienisto** [comment]
Closing this in favor of https://github.com/localsend/localsend/issues/710 because this issue is more general
