### ISSUE TITLE
Cannot transfer video file from PC to iPhone

### ISSUE THREAD

**Issue by diveangel6** [localsend/localsend#434]
### Describe the bug

It happened today that any video file larger than 500MB cannot be transferred from PC (Win11) to iPhone.  Can see the file transfer progress bar moving, but when Total Progress reaches 0:00, the file cannot be downloaded/saved to Photos, and the LocalSend screen is stuck at the Receiving Files page.  All other photo and video (less than 500MB) files can be transferred with no issues.  Did I do anything incorrectly?

![IMG_2795](https://user-images.githubusercontent.com/132301525/235520003-9663f090-1251-4689-a855-0e02777e1ae7.PNG)

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Receiving the video file and store in the Photos app.

**Comment by p186-reddit** [comment]
Hi,

Did you find a resolution to this? My workaround was to zip the file as mp4 files appear not to be supported for transfers.
