### ISSUE TITLE
Cannot run on MX Linux

### ISSUE THREAD

**Issue by Zeno394** [localsend/localsend#435]
### Describe the bug

Hi,
Im running MX linux, latest updated.
I cant run LocalSend AppImage package even after giving all the permissions as a program.
Isnt there any deb package.
I would love any help or suggestion to run LocalSend successfully.
Thanks

### To reproduce

Right click on AppImage package and the select Execute. But it is not working

### Expected behavior

When I double click on the AppImage package, it should be executing the application.

### Desktop (please complete the following information)

MX Linux 21.3
Debian Version 11.7
Desktop Xfce: 4.18.1

### Smartphone (please complete the following information)

No installation problem with my Android phone yet.

**Comment by Tienisto** [comment]
You can checkout #409. You need to install `libayatana-appindicator3-dev` or something similar to run the app.

Alternatively, you can use the flatpak version which should work out-of-the-box.

**Comment by Zeno394** [comment]
Hi,
Thanks for the answer.
Signal is using the max.
I changed settings for its battery usage.
Thanks again

**Comment by Zeno394** [comment]
Hi thanks for quick reply,
I installed libayatana....... But not working.

And to install flatpack, It need installing 7 packs of total 500 or more MB. Is it true that I have to install so much for the flat pack.

Thanks again

**Comment by Zeno394** [comment]
Hi, 
Should I expect fixing of the issue in the next udate?
Thanks

**Comment by Tienisto** [comment]
@Zeno394 This should be fixed in `v1.9.1`. Just released a moment ago.

**Comment by Zeno394** [comment]
Thanks a lot. I will try it.

**Comment by Zeno394** [comment]
Thanks for your efforts.

When I tried to install latest version 1.9.1, I got these errors.

(AppImageLauncher:5347): Gtk-WARNING **: 08:40:16.784: Unable to locate theme engine in module_path: "clearlooks",

Failed to start appimagelauncherd.service: Process org.freedesktop.systemd1 exited with status 1
See user logs and 'systemctl --user status appimagelauncherd.service' for details.

(AppImageLauncher:5347): GLib-CRITICAL **: 08:40:18.299: g_file_test: assertion 'filename != NULL' failed
/tmp/.mount_LocalS1aL0EC/localsend_app: symbol lookup error: /tmp/.mount_LocalS1aL0EC/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags

Thanks again.

**Comment by TheGB0077** [comment]
@Zeno394 @spidy0x0 Both of you have Wayland active on your systems?

**Comment by spidy0x0** [comment]
no, i am running x11

![image](https://github.com/localsend/localsend/assets/40536205/4b6e6b62-5957-44cc-833f-b4472af2ab79)

**Comment by Tienisto** [comment]
I've just created a Discord server. If you want, you can debug there: https://discord.gg/GSRWmQNP87

**Comment by Zeno394** [comment]
Thanks.
But I'm not tech guy. Show me how to disable or whatever.
Thanks again

**Comment by Zeno394** [comment]
Ok

**Comment by Zeno394** [comment]
> @Zeno394 @spidy0x0 Both of you have Wayland active on your systems?

No Im using X11 : Display not Wayland. I use MX Linux OS.
Thanks

**Comment by Zeno394** [comment]
I hope this will be solved in new update soon.
Thanks

**Comment by TheGB0077** [comment]
@Zeno394 @spidy0x0 I looked it up and it should be a matter of incompatibility, the gtk lib bundled in the Appimage is expecting some Wayland flag that your system does not include. Thus, I opted to configure a Debian version, it should be available soon enough.

**Comment by spidy0x0** [comment]
> @Zeno394 @spidy0x0 I looked it up and it should be a matter of incompatibility, the gtk lib bundled in the Appimage is expecting some Wayland flag that your system does not include. Thus, I opted to configure a Debian version, it should be available soon enough.

Ok thanks. Can't wait

**Comment by Zeno394** [comment]
Thanks a lot.
This app has a lot of potential in comparison to other apps. I'm waiting for that.

**Comment by Zeno394** [comment]
HI,
The .deb version of LocalSend 1,9,1 is working well on my MX Linux.
Thanks

**Comment by Zeno394** [comment]
Solved
