### ISSUE TITLE
Feature request: Not being able to select and send other files while transfering other files

### ISSUE THREAD

**Issue by sadehtest123** [localsend/localsend#439]
### Is your feature request related to a problem? Please describe.

While transfering other files, it is not possible to select and add other files to the list or queue

### Describe the solution you'd like

Adding a selef more buttom to the transfering page would be really nice

### Additional context

Using android 12 Samsung S10+

**Comment by Tienisto** [comment]
This is expected as the receiver explicitly only accepts the given files.

It is also unlikely to support this feature as the protocol does not support this.
