### ISSUE TITLE
EXIF metadata missing when receiving on iOS

### ISSUE THREAD

**Issue by Yhangokk** [localsend/localsend#440]
### Describe the bug

Sending from an Android phone to an iPhone will lose the photo exif information and change the size of the photo, which is compressed smaller. Hope to repair

### To reproduce

If the android client selects media or files and sends them to the IOS client, the exif information will be lost.

### Expected behavior

You want to keep the exif information and not compress the size of the photo or video.

### Desktop (please complete the following information)

Android version：1.9.0（30）
ios：1.9.0（30）

### Smartphone (please complete the following information)

Android Phone: Android 13
Apple client, IOS 16.4.1

**Comment by Tienisto** [comment]
#237 is still open, no need to open another one.

You can turn off "Save media to gallery" which is a workaround as discussed in #237.
