### ISSUE TITLE
hotspot bug

### ISSUE THREAD

**Issue by baizhi1989** [localsend/localsend#444]
### Describe the bug

hotspot bug

### To reproduce

When I connect my computer to my phone's hotspot, my phone displays two IP addresses and cannot select and display the computer device, while the computer can display the phone device.

### Expected behavior

show  pc deceive

### Screenshots

![Uploading Screenshot_20230506-141510.png…]()

### Desktop (please complete the following information)

android
1.9.1
windows
1.9.1

**Comment by baizhi1989** [comment]
NOT SHOW TWO IP  , SHOW THREE IP 
like this

IP 10.118.122.53
    192.168.118.55
    10.0.0.1
PORT 53317

**Comment by Tienisto** [comment]
You can try out to restart LocalSend after you enable hotspot.

Closed in favor of #527
