### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [localsend/localsend#454]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4238966044#L974 (java11)

Java17:  [LocalSend-1.9.1.log.zip](https://github.com/localsend/localsend/files/11419214/LocalSend-1.9.1.log.zip)

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d4683d5d6dd550cb241be3ef0ec647e4b91b1399

**Comment by Tienisto** [comment]
Do you mean that Java 17 should be used?

**Comment by licaon-kter** [comment]
No, just that I thought that you've used Java17 and tried with it too, but... same differences (mostly)

**Comment by Tienisto** [comment]
I just checked the build setup. It seems that I use Java 11:

```text
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

**Comment by licaon-kter** [comment]
Ok, can you look at the log? S

**Comment by Tienisto** [comment]
I don't know why the result is different.

I rebuilt `v1.9.0` (the previous version) and the `classes.dex` do match.

When I build `v1.9.1` then my `classes.dex` won't match with yours.

**Comment by linsui** [comment]
> Ok, can you look at the log?

I guess both of you didn't look at the log closely. :rofl:

> `+ apt-get install -y openjdk-17-jdk-headless`

Jdk 17 is used in the CI build so the result is not reproducible. With jdk 11 it's reproducible. https://gitlab.com/linsui/fdroiddata/-/jobs/4408780215

1.10.0 is not reproducible though. The build-id is different. Is the SDK/NDK path changed?

**Comment by licaon-kter** [comment]
> I guess both of you didn't look at the log closely. 

Ah, that thing happened when the CI installed 17 for a different app? Pfft, I usually look at that and either ignore the fail or retry locally. I don't recall if I tested both in this case though. :shrug:

Thanks for testing. :)

**Comment by Tienisto** [comment]
Thank you @linsui 

I am currently migrating to Github Actions to have a more reproducable environment. Will upload a new apk soon.

It seems that the inputs for the build id gets changed after some reboots (maybe due to apt update, I don't know).

**Comment by Tienisto** [comment]
@linsui Can you checkout the latest apk?

https://github.com/localsend/localsend/releases/download/v1.10.0/LocalSend-1.10.0.apk

**Comment by linsui** [comment]
It works, thanks! https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13194

**Comment by Tienisto** [comment]
Nice!

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/4970074710 It's weird only lib/armeabi-v7a/libapp.so is different.

**Comment by Tienisto** [comment]
Does the latest version (1.11.1) build? https://gitlab.com/fdroid/fdroiddata/-/jobs/5014158495

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/org.localsend.localsend_app/35#site-footer Yes, it buids. Thanks! Is anything changed?

**Comment by Tienisto** [comment]
Difficult to tell. I upgraded Flutter from 3.13.1 to 3.13.2 but I doubt that it is the issue.

**Comment by licaon-kter** [comment]
So I don;t open a new one, latest is not repro: https://gitlab.com/fdroid/fdroiddata/-/jobs/6270008075#L1099

will get a difflog soon

**Comment by licaon-kter** [comment]
difflog huge: 
[loc45.log.7z.zip](https://github.com/localsend/localsend/files/14431830/loc45.log.7z.zip) _(remove `.ZIP` from name)_

**Comment by Tienisto** [comment]
I have created https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14602 which might solve this issue
