### ISSUE TITLE
Cancelling file transfer session on Receiving Device does not cancel session on Sending Device.

### ISSUE THREAD

**Issue by SelaseKay** [localsend/localsend#455]
### Describe the bug

Cancelling file transfer session on Receiving Device does not cancel session on Sending Device(File transfer session still appears to be in progress on Sending device, however, it's cancelled on receiving device).

### To reproduce

1. Open localsend on windows.
2. Open localsend on android.
3. Send file from windows.
4. Accept send request on Android
5. Cancel transfer session on Android.
6. Transfer session is still in progress on Windows(however, it's cancelled on Android).

### Expected behavior

When file transfer session is cancelled on Receiving device(Android), it should cancel on Sending device(Windows) as well.

### Desktop (please complete the following information)

OS: Windows 10
Version: 19045.2846

### Smartphone (please complete the following information)

Device: Samsung  A12
OS: Android
Version: 10

**Comment by SelaseKay** [comment]
I'm working on fix for this issue. I will open a pr soon.,

**Comment by SelaseKay** [comment]
Noted.

**Comment by Tienisto** [comment]
Your fix is now live `v1.10.0`

**Comment by SelaseKay** [comment]
Noted.
