### ISSUE TITLE
The language setting don't respect system language

### ISSUE THREAD

**Issue by lumingzh** [localsend/localsend#460]
### Describe the bug

Set the app's language to system, the language will switch to English instead of the default language of system.

Flatpak and android versions both affected by this bug.

### To reproduce

1. make sure your system language is not English
2. change app's language to "system"

### Expected behavior

The app's language will be same with system's language.

### Desktop (please complete the following information)

- OS: Fedora Silverblue 38
- DE: Gnome Shell 44.1
- App: 1.9.1 (1.9.0 has this bug as well)

### Smartphone (please complete the following information)

- Honor 30S
- Android 10

**Comment by dhruvanbhalara** [comment]
@lumingzh can you please try to reproduce the issue in the latest version?

**Comment by lumingzh** [comment]
> @lumingzh can you please try to reproduce the issue in the latest version?

This bug has been solved in the latest version.

**Comment by Tienisto** [comment]
This surprises me as there is no related change made

**Comment by lumingzh** [comment]
> This surprises me as there is no related change made

Then I don't know why.😂
