### ISSUE TITLE
Autostart: Start hidden is not working

### ISSUE THREAD

**Issue by PIndividual** [localsend/localsend#464]
### Describe the bug

My setting has autostart enabled in the Windows startup setting, and I turned on the start hidden function within the program setting. Still, every time I restart Windows, local send is opened as an active window on the desktop.

### To reproduce

1. Go to 'Setting'
2. Click on 'Auto Start: start hidden'
3. Set the option to 'On'
4. It simply doesn't work

### Expected behavior

Only the tray icon will appear on my taskbar every time I boot up Windows, without the main window pops up

### Screenshots

![image](https://github.com/localsend/localsend/assets/62368342/75254e15-a93e-4e53-a5d6-1a20d5fee778)

### Desktop (please complete the following information)

Windows 10 22H2
Version: 19045.2846

**Comment by RepentStar** [comment]
I'm having this problem too!
System: Win10 22H2 19045.3448
AppVersion: Version: 1.11.1 (35)
But I don't have this problem on my Win11 computer.
I hope this issue is resolved soon.

**Comment by Sachindhadange** [comment]
Facing same issue.

Edition	Windows 10 Pro
Version	22H2
OS build	19045.3758
Localsend: 1.13.1 (42)

**Comment by slrgt** [comment]
also facing the same issue on windows 10

**Comment by slrgt** [comment]
@mizzunet autostart is already there, it autostrats but it doesnt start hidden\minimized

**Comment by Fixer-007** [comment]
Having the same problem on windows 10

**Comment by joniturmendi** [comment]
https://github.com/localsend/localsend/issues/464#issuecomment-1875180027 solved the issue for me, thanks @mizzunet

**Comment by RPXbr** [comment]
Spectacular app, Thanks to the Developer(s)!

But this bug needed to be fixed. I managed to start minimized in the Windows 11 tray through a command line in a bat placed in the Windows start folder. But even so, the app icon appears on the taskbar but minimized, so I leave the icon in a place that doesn't bother me until I close it to the tray. The bat line is this:

`start /min "" "C:\Users\YOURUSERNAME\AppData\Local\Programs\LocalSend\localsend_app.exe"`

But creating a simple shortcut in this folder and setting it to start minimized also has the same effect.

I believe this is easy to resolve in the app.

**Comment by RPXbr** [comment]
Hello!

About this problem, I created a free installer that adds a small executable to launch the LocalSend application hidden in the Windowsw system tray. An uninstaller will be available to remove this add-in from your system whenever you want:

https://rapidshare.io/Tfw/Hide_LocalSend_V.1.0.exe

All rights of the local app LocalSend belong to its respective developer.

I hope I helped someone! God Blesses!

**Comment by RPXbr** [comment]
Hide LocalSend

For those who are also facing this problem, where LocalSend does not start with the window hidden in Windows, I created a installer for myself and my friends whit a small 2mb application called "Hide LocalSend" that started in Windows through a simple link in the start menu. It does not change any registry lines and does not alter the original LocalSend installation in any way.

You can download it from this link and share it with anyone you want:

https://fastupload.io/4bedfbf0cdcd17b6

This is the script used to create de small app in SciTE:

```
Local $sUserName = @UserName
Local $sAppFolder = "C:\Users\" & $sUserName & "\AppData\Local\Programs\LocalSend\localsend_app.exe"
Run($sAppFolder, "", @SW_HIDE)
Sleep(1000)
Exit
```


The application I created is completely free and is not for sale. It was created with simple compilers, it is clean in Windows Defender. It can be uninstalled at any time with the native Windows uninstaller. If it doesn't work for you, please let me know so I can remove the sharing link. If it works, I'm happy to help, until this problem is resolved in future verion of LocalSend app.

 God bless all.

**Comment by swanknight** [comment]
At first, I couldn't find the reg key. After a while, I discovered that the LocalSend version installed was A UWP one, so I uninstalled it, and installed a regular executable, then I found the reg key and modified it based on @mizzunet instructions.

**Comment by Crunchbits** [comment]
I was actually only able to fix this using the comment from @cr0eax in https://github.com/localsend/localsend/issues/1293#issuecomment-2105144960_ mentioning you have to add quotes in regedit:

> Currently autorun registry key value looks like this: `C:\Program Files\LocalSend\localsend_app.exe autostart` When auto started by windows I can see that "autostart" argument is missing from command line. After changing registry value to following, problem is fixed. `"C:\Program Files\LocalSend\localsend_app.exe" autostart` So, bug caused by space in the path.
> 
> I see multiple opened issues about this problem. Hope it finally gets fixed now. #687 #1231 #464
