### ISSUE TITLE
No permission when saving files in Android secondary user

### ISSUE THREAD

**Issue by wbpluto** [localsend/localsend#486]
### Describe the bug

Why no one fix this issue. It existed for years.

### To reproduce

1. Switch to secondary user in Android
2. Try to receive file in LocalSend
3. It will be failed with no permission

### Expected behavior

Saved successfully

### Smartphone (please complete the following information)

google Pixel

**Comment by Tienisto** [comment]
Please notice the "help wanted" flag in your previous issue #307.

As of most open source projects, they are driven by volunteers without financial rewards. So if this issue bothers you, then you can make a PR so other users enjoy the improvement.
