### ISSUE TITLE
[bug] GUI not showing up on Windows

### ISSUE THREAD

**Issue by haode333** [localsend/localsend#487]
### Describe the bug

no GUI show up.

### To reproduce

1. start the app

### Expected behavior

GUI shows up and the app is added to system tray

### Desktop (please complete the following information)

OS: Windows 11 22H2 22621.1778
Ver: 1.9.1

### Additional context

tried the scoop version and portable version.

**Comment by Tienisto** [comment]
Can you show me the contents of the settings file?

It should be located in `%AppData%\org.localsend\localsend_app`

**Comment by haode333** [comment]
the settings file is somehow corrupted with 60kb of 0s. I removed it and localsend works!

**Comment by Tienisto** [comment]
It only contains "0"?

**Comment by haode333** [comment]
> It only contains "0"?

yes, afaik this is what i get from hxd.
![qApexSf](https://i.imgur.com/qApexSf.png)

**Comment by Tienisto** [comment]
Thanks for your information. This will help to fix #476!

**Comment by LittleJakub** [comment]
Hello! I just installed Localsend and have the same issue - simply cannot run the app on my Win11 Surface Pro 9 (intel).

When trying the portable, same thing - the app just doesn't launch. Deleting the contents of the Localsend AppData folders doesn't fix the issue.

**Comment by LittleJakub** [comment]
Hello! I tried installing v1.15.4, and it runs on my system, and all the ones after it do not... so there must be something in the newer updates' code that makes it fail to open up 😔
