### ISSUE TITLE
"Select all" button(option) 

### ISSUE THREAD

**Issue by gitfifi** [localsend/localsend#492]
### Is your feature request related to a problem? Please describe.

When selecting media, file etc to send, a "Select all" button(option) should be provided, otherwise, the selection process will make users crazy when sending hundreds of media or files.

### Describe the solution you'd like

just add a "Select all" button(option)

**Comment by jp1017** [comment]
+1

**Comment by neil123495** [comment]
+1

**Comment by Tienisto** [comment]
Unfortunately, We cannot just add a "select all" option.
We need to use an entirely new picker instead.

Duplicate of #376
