### ISSUE TITLE
The title bar in Windows is light in color in the dark theme for some reason, instead of being dark

### ISSUE THREAD

**Issue by brrendnemG7870** [localsend/localsend#493]
### Describe the bug

The title bar in Windows is light in color in the dark theme for some reason, instead of being dark.

### To reproduce

The title bar in Windows is light in color in the dark theme for some reason, instead of being dark.

### Expected behavior

The title bar in Windows is light in color in the dark theme for some reason, instead of being dark.

### Screenshots

![202305281353](https://github.com/localsend/localsend/assets/135063783/2b6fe9e9-71a4-489e-a188-8f4a5261586d)

**Comment by TechBoyy6** [comment]
I am a newbie, can I try this?

**Comment by Tienisto** [comment]
@TechBoyy6 Sure

**Comment by TechBoyy6** [comment]
Hello 👋

So i followed this 👇 process for setup

```
flutter pub get
flutter pub run build_runner build -d
flutter run
```

but when i do `flutter run` i get this 👇 error
![image](https://github.com/localsend/localsend/assets/73435031/4f70450b-7aab-4e6f-93dc-43b47ed1f106)

can someone help?

**Comment by Tienisto** [comment]
What flutter version do you use? Can you run `flutter doctor` please?

**Comment by TechBoyy6** [comment]
![image](https://github.com/localsend/localsend/assets/73435031/844cf502-2151-4c93-bd87-40627aff66a0)

**Comment by Tienisto** [comment]
You can try to switch to the stable branch (3.10). Alternatively, you can use [fvm](https://fvm.app) to run the exact flutter version that is specified by the project.

**Comment by TechBoyy6** [comment]
I used fvm and also install 3.10.0 stable still same
![image](https://github.com/localsend/localsend/assets/73435031/4ec0e2f1-f45f-4700-b83d-079c5d9528db)
