### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by JamesDean3** [localsend/localsend#497]
### Is your feature request related to a problem? Please describe.

I like having a way to have it auto accept, I just don't necessarily always need it on. 

### Describe the solution you'd like

I think a good addition would be a way to only temporarily have quick save on, so maybe you press it, it will have a menu giving the options of keeping it on indefinitely, until the next time you leave your wifi, or only having it on for a set amount of time.

Thank you for your time on making this, so far it has been pretty useful so far

**Comment by Tienisto** [comment]
Hello, there is a "Quick Save" button in the receive tab.

**Comment by WubTheGame** [comment]
I was thinking it would be good to have an option to select devices that you auto-accept from (And toggle it per device even). Similar request so just a comment.

**Comment by Nolle10** [comment]
I believe this feature was addressed in PR #1698 @JamesDean3 @WubTheGame 
Having quick save on only for devices added to favorites
