### ISSUE TITLE
Android cannot get file from Windows

### ISSUE THREAD

**Issue by yegbert** [localsend/localsend#506]
### Describe the bug

"Quick Save" and "Save media to gallery" have been turned OFF
 
The Android error information：
FileSystemException : cannot open file
OS Error: Operation not permitted, errno = 1

The windows error information：
[500] Could not save file

### To reproduce

just send a file

### Expected behavior

send file and get file

### Screenshots

![1](https://github.com/localsend/localsend/assets/32406107/35b33722-9dc3-458f-9beb-a57288060271)
![2](https://github.com/localsend/localsend/assets/32406107/020917a8-dc45-4b61-8ceb-1cca325b06df)
![3](https://github.com/localsend/localsend/assets/32406107/c5205031-6182-4ac2-a277-e29592b11f1e)

### Desktop (please complete the following information)

- OS : Windows 10 22H2 19045.2965 /Windows Feature Experience Pack 1000.19041.1000.0
- Version 1.10.0 

### Smartphone (please complete the following information)

- Device : Redmi K30s Ultra
- OS : MIUI 14.0.5 (Android 12)
- Version 1.10.0

**Comment by Ydrec** [comment]
Had same problem, seems like app initially only requests access to media folders and that doesn't include custom folders in root. Try going into app permissions and allow access to all files or use folder inside downloads folder

**Comment by yegbert** [comment]
> 

Thanks for reply. I had given all the permissions but it didn't work……(perhaps the MIUI's strange permission system)
Finally, I change the "Destination" to the default document "(Download)", then the problem has been solved……
