### ISSUE TITLE
Feature request: Directly send the clipboard instead of typing message before sending it.

### ISSUE THREAD

**Issue by nizhiyi** [localsend/localsend#507]
In most cases, I want to share the massage from clipboard, because it is too much work to retype the text.
![Screenshot_2023-06-05-22-27-13-02_df28ed62bb7da3a221841ad3d925c81c](https://github.com/localsend/localsend/assets/83541749/d8e89d72-7b9b-4b9b-a746-a0f3f0edc6e2)

**Comment by Tienisto** [comment]
Closing this in favor of #373
