### ISSUE TITLE
It seems that the cache clearing mechanism does not work in iOS

### ISSUE THREAD

**Issue by idjfia** [localsend/localsend#51]
After sending file(s) in iOS, the storage used by LocalSend becomes larger despite starting the app multiple times. It seems that the cache clearing mechanism does not work in iOS. But it works perfectly on Android.

My device model: iPhone 13
iOS version: 16.3
LocalSend version:1.6.2

Thank you for your nice work, and excuse me that my English is poor.

**Comment by Word-Maps** [comment]
@yuttana12wr

**Comment by Tienisto** [comment]
A temporary workaround is to clear selection when you are done. All media will be cleared.

**Comment by idjfia** [comment]
Hi!

After updating to the new version (1.7.0) in iOS, the cache is effectively cleared when I select images/files in LocalSend. However, if images/files are selected from another app, such as the Photos app, for sharing to LocalSend, the cache cleaning mechanism does not appear to work.

Thank you for your nice work, and excuse me that my English is poor.

**Comment by lfpoulain** [comment]
Hello :)

I confirm the cache clearing mechanism is not working for me either from iOS photo app. I had +60GB of data and the only solution was to remove the app.

**Comment by Tienisto** [comment]
@lfpoulain Do you know if it only occurs if you share media from another app? Or also when you select via the "Media" or "File" button?

**Comment by idjfia** [comment]
it only occurs if I share media from another app

**Comment by Tienisto** [comment]
Thanks @idjfia . I have created https://github.com/ShoutSocial/share_handler/issues/45 but unfortunately it hasn't been fixed yet.
