### ISSUE TITLE
Localsend consume GPU resources when running in the background

### ISSUE THREAD

**Issue by Winches** [localsend/localsend#510]
### Describe the bug

Localsend consume GPU resources when running in the background.
<img width="773" alt="image" src="https://github.com/localsend/localsend/assets/7054776/934b4497-dd81-4a07-bb4c-3b418e26f21a">

### To reproduce

1. Run application in the backgorund.

### Expected behavior

Stop using GPU or reduce the GPU usage of the application.

### Desktop (please complete the following information)

- OS: Windows 11
- Version: 22H2 22621.1778

**Comment by Xuyiyang23333** [comment]
+1

**Comment by Tienisto** [comment]
Fixed in #626
