### ISSUE TITLE
Feature request: Share Integration(Mac)

### ISSUE THREAD

**Issue by A2Sumie** [localsend/localsend#514]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

When I right click some file or folder in Finder, there is a "share" button that allow me to choose sharing methods.
I hope localsend would appear there for quicker use.
I checked my settings and localsend doesn't seems to support this method.

### Additional context

App store version, downloaded fresh. Version 1.10.0(32)

**Comment by Tienisto** [comment]
Closing this in favor of #586
