### ISSUE TITLE
[CJK fonts] mixed font-family when displayed as ZH_CN

### ISSUE THREAD

**Issue by sky96111** [localsend/localsend#52]
When displayed in Windows with ZH_CN, font-family is mixed with Simplified Chinese, Traditional Chinese and Japanese fonts. Which makes it very disjointed to read.

It may be a default fallback font problem. A specified font-family can avoid this problem. Commanly suggested font for ZH_CN is "微软雅黑 UI" (aka. "Microsoft YaHei UI")

![example](https://i.v2ex.co/K4m7SygJ.png)

**Comment by Tienisto** [comment]
Thanks for your feedback. "Microsoft YaHei" seems to look good even in Latin characters. It will be the new default on Windows then. Added in e7b7f4e98b99b755353a7d06d7590f57d437ca16

**Comment by graphemecluster** [comment]
Microsoft YaHei is particularly designed for simplified Chinese. For traditional Chinese, Microsoft JhengHei is the default font used in Windows. For Japanese and Korean, the default fonts are Yu Gothic and Malgun Gothic respectively.
The complete list can be found in https://learn.microsoft.com/en-us/windows/apps/design/globalizing/loc-international-fonts.

**Comment by Tienisto** [comment]
@graphemecluster thanks. I added this in https://github.com/localsend/localsend/commit/10e30de68760af6b22e4facaf207f03ef08108b9
