### ISSUE TITLE
Paste images

### ISSUE THREAD

**Issue by Misakei** [localsend/localsend#521]
### Is your feature request related to a problem? Please describe.

与问题无关.

### Describe the solution you'd like

希望在Windows平台可以复制后粘贴添加图片的功能,我使用snipaste复制图片后并不能直接粘贴到localsend里,必须要保存成图片后才能通过localsend发送.
使用snipaste复制图片后能直接粘贴到Windows便笺和网页邮箱里的,希望localsend可以实现相同功能.

**Comment by phith0n** [comment]
Looking forward to this feature!
