### ISSUE TITLE
Start minimized not working in Windows

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#529]
It is recommended to create a shortcut with argument `autostart` to ensure that LocalSend knows that it was started automatically.

Example: `D:\LocalSend\localsend_app.exe autostart`

See #71 for more details.

**Comment by jgaxmey** [comment]
> It is recommended to create a shortcut with argument `autostart` to ensure that LocalSend knows that it was started automatically.
> 
> Example: `D:\LocalSend\localsend_app.exe autostart`
> 
> See #71 for more details.

I added autostart in the shortcut, but it still doesn't start on boot.

**Comment by SunshineboyZj** [comment]
The MSIX version can start automatically, but it cannot start silently and cannot add the autostart startup parameter like exe. Can you fix this problem，thank you

**Comment by HalCyonNJ** [comment]
The latest MacOS version also can't start silently, But as myself I didn't restart the system frequently so. It will be nice if you guys add this little extra. Thanks for the app btw, It really helps me alot!

**Comment by Mapaler** [comment]
> The MSIX version can start automatically, but it cannot start silently and cannot add the autostart startup parameter like exe. Can you fix this problem，thank you

I found a way to use it, but the cmd window pops up once.
https://github.com/localsend/localsend/issues/71#issuecomment-1725628652

**Comment by Tienisto** [comment]
Fixed in #1467
