### ISSUE TITLE
Can not discover win PC in iOS

### ISSUE THREAD

**Issue by powerbush** [localsend/localsend#53]
Can not discover win PC in iOS, but can be discovered by win PC.

![20230129-201405](https://user-images.githubusercontent.com/2038390/215325735-b06f0c89-6ca9-4465-b9f7-0e82fc6e05c7.jpg)

![Snipaste_2023-01-29_20-12-47](https://user-images.githubusercontent.com/2038390/215325887-70438f42-2038-4a35-bf80-ff1b6952b310.png)

My device model: iPhone 12 P M
iOS version: 16.0
LocalSend version:1.6.2(23)

PC: Win 11 22H2
LocalSend version:1.6.2(23)

**Comment by YunofHD** [comment]
Yep I meet the same problem.
I try to change the port to the same, it solved.
But actually it doesn`t need two device in same port,right？

**Comment by Tienisto** [comment]
This is most likely a firewall issue. Similar to #27

**Comment by Tienisto** [comment]
Sorry, I didn't read your comment @YunofHD 

Yes, all devices need to have the same port. This setting is only needed in special environments where the default port is unavailable.

**Comment by YunofHD** [comment]
Dear Tien
     Much thanks for your help
Best regards

Tien Do Nam ***@***.***> 于2023年2月11日周六 04:28写道：

**Comment by Tienisto** [comment]
Closed in favor of #414
