### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JPFORESTIER** [localsend/localsend#536]
### Describe the bug

Localsend, worked the first time I tried it on both PC and Smartphone.
Since then, it doesn't recognized any more PC or Smartphone. Here is a capture 
![Local send bug](https://github.com/localsend/localsend/assets/136820412/f4494714-7e7d-4388-92fb-780a8ceb046e)

### To reproduce

1. Open Local send
2. Click on Send
3. Nothing happened as expected On both PC & Smartphone

### Expected behavior

PC or Smartphone should "see" each other (as It did the very first time)

### Screenshots

![Local send bug](https://github.com/localsend/localsend/assets/136820412/dcfc9e4f-2b09-4abc-a4a4-12ee83b308cd)

### Desktop (please complete the following information)

WINDOWS 10 up to date
22H2 19045.2965

### Smartphone (please complete the following information)

OPPO A 72
Android up to date
Android 11

**Comment by Tienisto** [comment]
Please comment on #527 as discovery is one of the core features. Github is not a support service, please only create a new issue if you have explicit technical details to reproduce the error.

As stated in #527, check if configuration is the same, check if both devices are in same wifi network, etc.
