### ISSUE TITLE
I hope the exe can automate the creation of a shortcut with autostart startup parameters and automatically add it to the startup item

### ISSUE THREAD

**Issue by SunshineboyZj** [localsend/localsend#562]
### Is your feature request related to a problem? Please describe.

Yes
After creating a shortcut with the autostart startup parameter, I copied it to the Start folder on the Start menu. It can be started and automatically minimized to the tray!
But I still hope that it can automatically add startup items and create such shortcuts. No need for manual intervention

### Describe the solution you'd like

it can automatically add startup items and create such shortcuts. No need for manual intervention

**Comment by SunshineboyZj** [comment]
by the way，The MSIX version can start automatically.it cannot start silently and cannot add the autostart startup parameter like exe.

**Comment by slrgt** [comment]
hoping this is added especially being able to auto start silently

**Comment by SunshineboyZj** [comment]
I find v1.11.1 can autorun,but it cannot start hidden after autorun
