### ISSUE TITLE
support file/image transfer by pasting files from the clipboard.

### ISSUE THREAD

**Issue by AlexYuan** [localsend/localsend#568]
### Is your feature request related to a problem? Please describe.

I hope it will be possible to support file transfer by pasting files from the clipboard.

### Describe the solution you'd like

I copy files or images from the file manager, other software (such as Twitter App, Word, Photoshop) or web pages (such as twitter.com or t.cn) to the clipboard, and then paste them in LocalSend, which can be sent to other devices (it has already installed the same version of LocalSend).

![image](https://github.com/localsend/localsend/assets/1269376/47011fcd-4fbb-4963-ad25-197d95bdb699)
![image](https://github.com/localsend/localsend/assets/1269376/4a1c3cb0-6b69-4838-8eeb-2825427e6c9a)

**Comment by Tienisto** [comment]
Thanks, your UI proposal looks good to me
