### ISSUE TITLE
Add to package managers in Windows

### ISSUE THREAD

**Issue by sitiom** [localsend/localsend#57]
Here is a checklist:
- [x] Winget (https://github.com/microsoft/winget-pkgs/pull/95002)
- [x] Scoop (https://github.com/ScoopInstaller/Extras/pull/10357)
- [x] Chocolatey (https://github.com/chocolatey-community/chocolatey-package-requests/issues/1410)

Can you add an MSIX installer in the releases so I can add LocalSend to Winget? Thanks.

**Comment by Tienisto** [comment]
Hi, thanks. I need to figure out how to sign first. Currently, Microsoft signs this automatically when published to the Windows Store.

**Comment by Tienisto** [comment]
I have added one: https://github.com/localsend/localsend/releases/download/v1.6.2/LocalSend-1.6.2.msix

Let me know if something is wrong. Thank you!

**Comment by sitiom** [comment]
Hi, seems like it needs a self-signed certificate:
![image](https://user-images.githubusercontent.com/56180050/215362435-8053b1df-1789-43cd-bcfa-b817f083db9b.png)

Can't you somehow publish the Microsoft store-signed MSIX instead?

**Comment by Tienisto** [comment]
I updated the msix again. Can you test it again please?

**Comment by sitiom** [comment]
Thanks, that works. Working on adding it to Winget now!

**Comment by Tienisto** [comment]
Nice! Thank you very much!

**Comment by sitiom** [comment]
Here is the PR for Winget:
- https://github.com/microsoft/winget-pkgs/pull/95002

Once it is merged, the [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) workflow would have to be set up in this repo for automatic package updates.

**Comment by Tienisto** [comment]
Somehow the app was removed from the Microsoft store so I am unable to provide signed msix packages anymore. I contacted Microsoft to find a way to restore the account but they answered me this:

> Hello,
> Microsoft removed your developer account from the Microsoft Store based on good faith and reasonable evidence of activities that violate the terms of the account agreement.
> The account agreement allows Microsoft to remove a Microsoft Store Account for abuse of the marketplace or failure to keep your account in good standing. Termination of your account results in the removal of associated application(s) from the store. Also, the account agreement allows Microsoft to remove an application from availability in the store for breach of the agreement or for any other reason.
> We have determined that the removal of your account and published app(s) were warranted based on abusive and/or inappropriate activities. Please note that our decision is final, and when one account is in violation of the Agreement, we may also remove any related accounts.

> Thank you,
> Microsoft Store Team

**Comment by sitiom** [comment]
Did you ask for the exact reason for the suspension? Maybe you can repeal to reactivate your account again.

**Comment by Tienisto** [comment]
Unfortunately, it didn't work. Created #220

**Comment by sitiom** [comment]
If you don't get your account back, you can get a code signing certificate which is the more expensive route. Or provide MSI installers.

**Comment by Tienisto** [comment]
Yeah, I will find an alternative option.

**Comment by sitiom** [comment]
Updates on this? The Winget version is outdated.

**Comment by Tienisto** [comment]
I bought a license from signmycode.com and I am still waiting for approval

**Comment by Tienisto** [comment]
@sitiom I have added the msix in the release asset. Can you verify that it is signed correctly?

**Comment by Tienisto** [comment]
I have noticed that it is treated as a different application because of the different certificate. I don't know if it's an issue

**Comment by sitiom** [comment]
We'll see about that. I've made a for 1.8.0 now: https://github.com/microsoft/winget-pkgs/pull/99181

**Comment by dtantono** [comment]
@sitiom https://github.com/chocolatey-community/chocolatey-package-requests/issues/1410
