### ISSUE TITLE
adding more external entry poin please

### ISSUE THREAD

**Issue by Vanda688** [localsend/localsend#576]
### Is your feature request related to a problem? Please describe.

I'd like to request adding an external entry point: 

### Describe the solution you'd like

In the Android system, when text is selected various options pop up. If a function like "Send to LocalSend" or even "Send to a specific device" could be added, that would be even more convenient.
![](https://imgur.com/gallery/3zHbyau)

### Additional context

thanks

**Comment by Vanda688** [comment]
![Screenshot_2023-07-19-17-18-08-04_ae1f93045b87aacac90efbb155289789.jpg](https://github.com/localsend/localsend/assets/91307877/5b9cb094-de69-45b3-a9da-ca44c9ee1ab8)

Adding some new features here will be better ❤️

**Comment by Tienisto** [comment]
Hi, LocalSend should show up if you go to the share menu first. Adding LocalSend right into the popup would be better of course.
