### ISSUE TITLE
Feature request: Sharing plugin for macos

### ISSUE THREAD

**Issue by ShlomoCode** [localsend/localsend#586]
### Is your feature request related to a problem? Please describe.

To send files, open the software, and drag them into the software window.
It's not bad, but it would be much nicer if it was possible to right-click > localsend sharing, just like Apple's AirDrop.

### Describe the solution you'd like

The Gifski app (https://github.com/sindresorhus/Gifski) contains a sharing plugin - you can right-click File > Sharing > Gifski, and thus send a file to the software.
This thing will be very useful for localsend, to be able to share file(s) with the software, similar to sharing with the built-in AirDrop.
A short video for demonstration:

https://github.com/localsend/localsend/assets/78599753/91922928-91d0-4f41-9b58-a9487d6ac615

**Comment by ShlomoCode** [comment]
It would also be useful to allow dragging a file to the LocalSend icon in the menu bar
Similar to CleanShot app

**Comment by NayamAmarshe** [comment]
Yes! This would be great!

**Comment by RunAway189** [comment]
Yes, please. The context menu option would be very useful

**Comment by image72** [comment]
@Tienisto have any plan support this feature?

**Comment by Tienisto** [comment]
> @Tienisto have any plan support this feature?

Yes, but unfortunately, there is no ETA

**Comment by Bob-SF** [comment]
Would love access to LocalSend via the Mac share menu.

**Comment by ShlomoCode** [comment]
Ref: https://github.com/sindresorhus/Gifski/pull/156
