### ISSUE TITLE
安卓版如果使用自定义接受目录则无法保存文件

### ISSUE THREAD

**Issue by firo1603** [localsend/localsend#595]
### Describe the bug

安卓版如果使用自定义接受目录则无法保存文件

### To reproduce

手机端：MIUI14 安卓13  版本1.10
电脑端：windows11  版本1.10

同一无线网络下，双方能互相发现，手机端能发送文件，电脑端能正常接受
但是如果手机端设置-接受-保存目录，如果此处进行自定义，那么电脑端向手机端发送文件，显示[500] Could not save file
改回默认目录，则能正常保存文件
检查过手机端软件的文件权限，应该是有的

### Expected behavior

同上

### Desktop (please complete the following information)

windows11

### Smartphone (please complete the following information)

MIUI14  
安卓13
红米K60

**Comment by firo1603** [comment]
无视掉，在隐私保护-特殊权限设置里面授予所有文件访问权限打开就行了

**Comment by er2shi0** [comment]
我的小米平板4安装localSend后出现了这个问题（可以发送文件至同一局域网下的pc和手机，但无法接收文件，pc和手机向平板发送文件时会立即提示错误，错误提示代码：[500]could not save file），最后发现可能是我设置了接收文件路径是SD的缘故，在平板存储根目录下新建了一个名为[localSend]文件夹并将其设置为接收文件存储路径以后就可以正常接收了

**Comment by er2shi0** [comment]
我的小米平板4安装localSend后出现了这个问题（平板可以发送文件至同一局域网下的pc和手机，但无法接收文件，pc和手机向平板发送文件时会立即提示错误，错误提示代码：[500]could not save file），最后发现可能是我设置了接收文件路径是SD的缘故，在平板存储根目录下新建了一个名为[localSend]文件夹并将其设置为接收文件存储路径以后就可以正常接收了
