### ISSUE TITLE
Select all function

### ISSUE THREAD

**Issue by xiaoy17950** [localsend/localsend#598]
### Is your feature request related to a problem? Please describe.

When sending multiple pictures, it is inconvenient to check them one by one

### Describe the solution you'd like

Want to add a select all option, or swipe selection function

**Comment by PR4NJ41** [comment]
Specially in iOS

**Comment by antoine-1** [comment]
This feature would be very useful for transferring all the photos from an iPhone, for example.

**Comment by Tienisto** [comment]
Using the native media picker is the goal but there are some issues regarding the file name.

Closing this in favor of #376

**Comment by antoine-1** [comment]
> Using the native media picker is the goal but there are some issues regarding the file name.
> 
> Closing this in favor of #376

Oh, because the native media picker doesn't allow you to select all files

**Comment by NithinXD** [comment]
You could select all in default photos app in ios then share and then local send but theres a limit
