### ISSUE TITLE
FileSystemException on Android 13

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#603]
### Describe the bug

Thanks to russ4694 from Discord:

After the download gets finished (100%), a "FileSystemException: Cannot open file ... operation not permitted, errno=1" error is thrown.

Apparently, it works if a subdirectory within "Download" is selected.

### To reproduce

1. Start transfer from whatever to Android 13
2. Accept
3. Wait until fully received

### Expected behavior

Should save successfully

### Smartphone (please complete the following information)

 LG V60, Android 13

### Additional context

It works on Samsung Android 13

**Comment by russnash** [comment]
Further info: The folder which causes the error is created in the root of internal storage.  This translates to /storage/emulated/0/LocalSend.  See attached screen shot for the complete error.
![Screenshot_20230802-200458](https://github.com/localsend/localsend/assets/1693967/a3a1e7a8-0141-4950-90e7-11c13d897d5d)

**Comment by Jesse205** [comment]
This issue is very similar to another issue

https://github.com/localsend/localsend/issues/506

His solution is to change to the default download directory.
