### ISSUE TITLE
[Bug report]I think the transfer speed is a bit slow

### ISSUE THREAD

**Issue by bearcloney** [localsend/localsend#606]
### Describe the bug

The test environment is to turn on the 5g hotspot for the mobile phone, and connect the computer to the hotspot

Other transfer file software transfer speed 65m/s
（爱传送）

And localsend can only reach 15-25m/s

Is it caused by a protocol problem, is there a chance to fix it

Right-click menu shortcut, do you plan to do it?

I have been paying attention since #192, thank you for your unremitting efforts for half a year
Looking forward to your better work

### To reproduce

 ,

### Expected behavior

 ,

**Comment by 601958483** [comment]
Localsend传输速度比其他的确实要慢来着，作者好像是为了传输的安全性。为什么不使用爱传送呢？是有什么缺点吗？我记得之前使用过爱传送一段时间，好像它手机端软件后台或者锁屏都会断开传送连接，不知道后续版本有没有改进。

**Comment by 601958483** [comment]
最新版中的高级设置里关闭加密开关会快很多
![Clip_20230919_095925](https://github.com/localsend/localsend/assets/43309053/5dba1676-36d2-4bc5-9471-84df4ab56cf8)

**Comment by bearcloney** [comment]
> Localsend传输速度确实比其他的要慢来着，作者希望是传输的安全性。为什么不使用爱传送呢？有什么缺点吗？我记得之前使用过爱传送时间，希望是手机端软件后台或者锁屏都会断开传送连接，不知道后续版本有没有改进。

爱传送确实有断连的问题我也因此再寻找其他可代替的软件
谢谢你提醒我新版能够关掉加密协议，确实有用
