### ISSUE TITLE
arm win 32bit

### ISSUE THREAD

**Issue by wty2019wty** [localsend/localsend#609]
### Is your feature request related to a problem? Please describe.

Windows x86的32位和64位的支持
Windows arm的32位和64位的支持
linux x86的32位和64位的支持
linux arm的32位和64位的支持

希望得到全版本全架构的支持

### Describe the solution you'd like

希望得到全版本全架构的支持

**Comment by Tienisto** [comment]
ARM binaries are provided since `v1.13.0`.
For Windows, there is a separate issue: #715 
I don't plan to provide 32 bit support because the release pipeline is already too big.
