### ISSUE TITLE
The default icon color on the desktop need to be optimized? 

### ISSUE THREAD

**Issue by os9sur** [localsend/localsend#627]
### Describe the bug

The icon on windows desktop is not clear
![image](https://github.com/localsend/localsend/assets/6024166/31253040-dc39-4930-aca3-258e727abf48)

### To reproduce

by default

### Expected behavior

More clear transparent icon

**Comment by c-sanchez** [comment]
lol with a flat background color and similar to the same color of the icon, it is normal that it is not visible.
You can fix it just by using a different background.

**Comment by os9sur** [comment]
> 
LOL  your idea is ridiculous

another background color
<img width="170" alt="2023-08-24_102934" src="https://github.com/localsend/localsend/assets/6024166/eec70952-90ac-4a1d-8fe1-4edd4d9c9357">

I don't think it's a normal visual effect

**Comment by os9sur** [comment]
> 



> lol with a flat background color and similar to the same color of the icon, it is normal that it is not visible. You can fix it just by using a different background.



> lol with a flat background color and similar to the same color of the icon, it is normal that it is not visible. You can fix it just by using a different background.

LOL your idea is ridiculous

another background color

![](https://user-images.githubusercontent.com/6024166/262843764-eec70952-90ac-4a1d-8fe1-4edd4d9c9357.png)
I don't think it's a normal visual effect

These are the normal visuals on live tiles with the same background color

![](https://user-images.githubusercontent.com/6024166/262844556-6b124f59-2da9-46ff-ad06-8ea6ed780834.png)

**Comment by os9sur** [comment]
> Apparently this is only on Windows 10. On Windows 11 it looks normal:
> 
> ![grafik](https://user-images.githubusercontent.com/38380847/262918255-dc848a90-510d-4e2c-8b62-8894dd25302a.png)
> 
> Maybe using the ZIP version would be a workaround

Thank you for your continued attention!
Yep it's workaround.

Windows 10 still has a high market share, so I hope to optimize it if you have time :-)

Thank you for your excellent work, this tool is very useful, I have recommended it to many people!
