### ISSUE TITLE
Windows zip releases have slash characters in filenames

### ISSUE THREAD

**Issue by ProactiveServices** [localsend/localsend#634]
### Describe the bug

The zip releases for Windows appear to have a corrupted directory structure. Instead of having folders, many of the files have filenames with slashes in them. Extracting with either Windows' built-in zip extractor or WinZip results in the following:
![Screenshot_20230824_215048](https://github.com/localsend/localsend/assets/4228567/bb2fa8fc-7113-4640-b15f-ccd6f3c0595d)
On a Linux machine the zips extract thus:
![Screenshot_20230824_215151-1](https://github.com/localsend/localsend/assets/4228567/d8272f19-2ba2-487a-925d-662e32abaa10)

Using Info-ZIP's unzip on Windows appears to translate the slashes and result in a valid output.

### To reproduce

1. Download 1.10 or 1.9.1 Windows .zip release.
2. Unzip via File Explorer

### Expected behavior

Folder structure is created and files with valid names are extracted.

### Desktop (please complete the following information)

Windows 10 22G2

**Comment by Tienisto** [comment]
Can you redownload the zip? The zip seems ok to me

**Comment by ProactiveServices** [comment]
Just re-tested and it's working fine, apologies for the noise.
