### ISSUE TITLE
Android: Loading big files takes too much time

### ISSUE THREAD

**Issue by abe1242** [localsend/localsend#636]
### Describe the bug

Whenever I select a file to send, the loading spinner takes too much time. The larger the file the more time it takes. I think this is because the app is copying the file to its own directory before sending instead of directly opening the said file.

I don't know if this is just the nature of Android file picker but this doesn't happen in apps like Google Chrome. When I pick a large file to upload, it just starts right away.

### To reproduce

1. Go to the send tab
2. Click on 'File'
3. Select a large file
4. Loading spinner spins for a long time

### Expected behavior

Should not take too much time to load files

### Smartphone (please complete the following information)

- Device: Redmi 9
- OS: Android 12
- Version: 1.10.0

**Comment by dhruvanbhalara** [comment]
@abe1242, related to #532

**Comment by abe1242** [comment]
> @abe1242, related to #532  

Ok, I'm closing this issue
