### ISSUE TITLE
2条建议

### ISSUE THREAD

**Issue by cnhongv** [localsend/localsend#64]
1.目前传输任务完成后，它仍然显示在任务区域。优点是可以快速再次发送，缺点是下一次发送新文件，需要多次点击，操作繁琐。
建议：把任务做成列表，就像他人所说的“历史记录”。任务完成后可以“新建任务”。对于删除任务，手机端可以通过左右滑动来删除已经完成的任务。

2.目前打开“快速保存”后，传输“文本”默认保存为txt文件。
个人建议不要这么做。我建议仍然弹窗提示复制。选择“文本”的目的是为了便捷，而传输完成后还需要打开文本文档让这个操作变得繁琐。因为如果想传输“文本文件”，可以选择“文件”。

多说一点。有一条已经关闭的issue质疑买star。star增长这么快可能也和另一个因素有关，因为“[localsend](https://github.com/localsend/localsend)”已经在中国的app分享圈子传开，这意味着用户量会突然增加，自然star也会增加很多。希望越来越多的开发者注意到中国用户的“魔力”。

1.Currently after the transfer task is completed, it is still displayed in the task area. The advantage is that it can be sent again quickly, and the disadvantage is that the next time a new file is sent, it requires multiple clicks and the operation is cumbersome.
Tip: Make a list of tasks, like what others call "history." After the task is completed, you can "create a new task". For deleting tasks, the mobile phone can delete the completed tasks by swiping left and right.

2.Currently after opening "Quick Save", the transfer "Text" is saved as a txt file by default.
Personally, I don't recommend doing this. I suggest still popping up prompting copying. The purpose of choosing "text" is for convenience, and after the transfer is completed, you need to open the text document to make this operation cumbersome. Because if you want to transfer "Text File", you can select "File".

Say a little more. There is a closed issue questioning buying a star. Star's rapid growth may also have something to do with another factor, because "[localsend](https://github.com/localsend/localsend)" has spread in China's app sharing circles, which means that the number of users will suddenly increase, and naturally the star will also increase a lot. I hope that more and more developers will notice the "magic" of Chinese users.

**Comment by idjfia** [comment]
建议尽可能使用英语反馈，开发者可能不懂中文

**Comment by Tienisto** [comment]
Thanks for your suggestions. I opened #67 and #68 to keep track of both improvements separately.

**Comment by cnhongv** [comment]
感谢您的重视，希望"[localsend](https://github.com/localsend/localsend)"更加易用，帮助到更多的人。

Thank you for your attention. I hope "[localsend](https://github.com/localsend/localsend)" will be easier to use and help more people.
