### ISSUE TITLE
The color of the enabled button looks like disabled and the opposite of the disabled button

### ISSUE THREAD

**Issue by nothingshiru** [localsend/localsend#641]
![屏幕截图 2023-08-29 053015](https://github.com/localsend/localsend/assets/79258245/33e67ee4-58bf-4abc-be9d-c391fbf88684)
![屏幕截图 2023-08-29 053044](https://github.com/localsend/localsend/assets/79258245/84398c16-390d-427c-b295-5497b8f4cf77)

**Comment by Tienisto** [comment]
Do you mean it should be black? Or any other design ideas? I am also not very satisfied with the current design choice

**Comment by Hoossayn** [comment]
@Tienisto do you have any color/design you want to go with on this, i'll like to work on it

**Comment by Tienisto** [comment]
@Hoossayn Not yet... well you could design this according to Material 3 spec if you want. I am unopinionated
