### ISSUE TITLE
Bug report cannot open folder

### ISSUE THREAD

**Issue by newyorkthink** [localsend/localsend#642]
### Describe the bug

![image](https://github.com/localsend/localsend/assets/87791643/221b2862-8208-4ce3-8264-3b8f8b865aba)

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

linux version

is cannot open folder , I don't setting

### Screenshots

![image](https://github.com/localsend/localsend/assets/87791643/b4b7fa4a-3afb-4c49-b1e3-dd862ad72ea1)

**Comment by Tienisto** [comment]
Did it work in the previous version?

**Comment by newyorkthink** [comment]
> Did it work in the previous version?

yes, i download the latest version

**Comment by Tienisto** [comment]
I have uploaded a new apk: https://github.com/localsend/localsend/releases/download/v1.11.0/LocalSend-1.11.0-folder-fix.apk

Can you try this out?

**Comment by Tienisto** [comment]
Did you use the AppImage or the deb file?

**Comment by Tienisto** [comment]
Alright, I could reproduce this on Manjaro KDE. It did not work with 1.10.0 either, did you try this out?

**Comment by Tienisto** [comment]
Probably related to https://github.com/miguelpruivo/flutter_file_picker/issues/1282

**Comment by Tienisto** [comment]
Can you try out the fixed version: https://github.com/localsend/localsend/releases/download/v1.11.0/LocalSend-1.11.1-fix-x86_64.AppImage
