### ISSUE TITLE
localsend 发送多行文字（Multiline Text）时，当文字行数较多时，文本框溢出窗口，且无法滚动。

### ISSUE THREAD

**Issue by 265785** [localsend/localsend#645]
### Describe the bug

localsend 发送多行文字（Multiline Text）时，当文字行数较多时，文本框溢出窗口，且无法滚动。此问题在所有平台均出现。

### To reproduce

1. Go to 'Send'
2. Click on 'Text'
3. Select 'Multiline'
4. Paste any Multiline Text and scroll down
5. See error

### Expected behavior

文本框不会溢出窗口，且能够滚动。
最好在右侧添加滚动条，接收到的多行文本也最好在右侧添加滚动条（不强求）。

### Screenshots

![image](https://github.com/localsend/localsend/assets/56037874/b0f7d435-5aaf-46d9-9948-d805e1581b0c)

### Desktop (please complete the following information)

Windows 11

### Smartphone (please complete the following information)

Android 10 & iPadOS 16

**Comment by Tienisto** [comment]
I cannot reproduce this on v1.11.0
