### ISSUE TITLE
[Bug] errno -13, Permission denied 1.11 on Android

### ISSUE THREAD

**Issue by marryton007** [localsend/localsend#648]
### Describe the bug

Can't store file, even I have granted the storage access permission.

### To reproduce

Send file from the PC (Win11, 1.11.0(34))  to Android (Android10, 1.11.0), translate finished, but the Android app complains it can't store the file because "errno -13, Permission denied".

### Expected behavior

The Android app can receive and store the file.

### Screenshots

![local-send](https://github.com/localsend/localsend/assets/2311328/c77a2548-23c3-4b91-bfba-9f6cc1139267)

### Desktop (please complete the following information)

- OS: win11 Home edition
- version 10.0.22621 

### Smartphone (please complete the following information)

- Device: oppo r17
- OS: Android 10

### Additional context

I have reinstalled 1.10.0 on my Android mobile, it works fine.

**Comment by Tienisto** [comment]
Hello,

I have uploaded a modified version to the releases page: https://github.com/localsend/localsend/releases/download/v1.11.0/LocalSend-1.11.1-pre-fix-permission.apk

Can you try this out?

**Comment by marryton007** [comment]
It works fine.

**Comment by Xinaovo** [comment]
> Hello,
> 
> I have uploaded a modified version to the releases page: https://github.com/localsend/localsend/releases/download/v1.11.0/LocalSend-1.11.1-pre-fix-permission.apk
> 
> Can you try this out?

I also encountered this bug when I tried to send files to my Huawei Pad, running HarmonyOS2(Android 10) and app 1.11.0. However, your modified app works just fine.

**Comment by Tienisto** [comment]
Hello, you can use the latest version 1.11.1.
