### ISSUE TITLE
Add option for preserving timestamp of transferred files (file metadata)

### ISSUE THREAD

**Issue by Vilmodao** [localsend/localsend#650]
### Is your feature request related to a problem? Please describe.

Currently all received files will get a creation date equal to the time of transfer. It would be great to have an option to preserve the original timestamp of transferred files.
This is very important in many cases.
Thanks.

### Describe the solution you'd like

Add an option in the applications settings.

### Additional context

I have tried transferring files between Windows and iOS only.

**Comment by Tienisto** [comment]
Setting the creation timestamp should not be possible yet but setting the "last modified" timestamp should be possible to be implemented.

https://api.flutter.dev/flutter/dart-io/File/setLastAccessedSync.html

**Comment by GhostasDead** [comment]
It's rare for apps to perserve the 'creation date' anyway, so perserving 'modified date' is enough in most cases.
It would be great to implement that, since gallery apps usually sort files that way.

**Comment by Rafee-M** [comment]
Yeah preserving the last modified value would be just as helpful as well

**Comment by 0uros** [comment]
I hope that this function is integrated in the future, I loved how fast and easy it is to transfer files, but the fact that it does not maintain this information makes it a problem to be able to make backup of photos

**Comment by znsoooo** [comment]
Has this issue been resolved now? It seems still existing on version 1.16.1.

**Comment by znsoooo** [comment]
Has this issue been resolved now? It seems still existing on version 1.16.1.

I sent a file from my iPad to my PC, and there was no problem. I sent a file from my OPPO (Android) phone to my PC, and there was no problem. However, when I sent a file from my iPad to my OPPO (Android) phone, the file's modification date changed to the date it was received.

I confirmed this in two ways: one was by using the "ES File Explorer" on the Android to check the file's modification date, and the other was by sending the file from Android back to the PC to check (iPad->Android->PC), and both methods yielded the same conclusion.

The modification dates of the 4 files received on Android:
![image](https://github.com/user-attachments/assets/05b5bc41-665e-4c19-a2c8-966b38624b04)


The modification dates of the 4 files received on PC:
![image](https://github.com/user-attachments/assets/d65f7742-03c7-46cf-9f73-cb2c33e3fd11)

**Comment by Tienisto** [comment]
This should work on all devices where it is supported. I guess Androids API doesn't offer a reliable API to set the last modified date.

The code line setting the last modified date:

https://github.com/localsend/localsend/blob/main/app%2Flib%2Futil%2Fnative%2Ffile_saver.dart#L95

**Comment by zhaochow** [comment]
@znsoooo 
Just wanted to let you know that I can also confirm the issue you had with the timestamp when receiving on an Android device (see #2311).
It worked properly on my end once I set "Save media to gallery" to off though.

**Comment by bmix** [comment]
So, I just transmitted photos from Android to MacBook and all dates, created as well as modified, were set to the time of transmission. :-(

**Comment by OdyAsh** [comment]
Up!

**Comment by strentom** [comment]
Hello @Tienisto , I confirm this is still an issue. On the newest version of Localsend, **sending iOS -> Mac**, most files have both date-of-creation and date-of-modified set to time of transfer. However, the date of modification is preserved for some files. Notably: for `.mov` it's preserved. It's not preserved for `.jpg`, `.heic`.

**Comment by Gitoffthelawn** [comment]
Reopen?
