### ISSUE TITLE
Edge-to-Edge mode on Android hides the navigation buttons on Android 9 and older

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#653]
### Describe the bug

Issue by budhadityanayak from Discord:

Asus zenfone max pro m1, android version 9

![Screenshot_20230827-100114](https://github.com/localsend/localsend/assets/38380847/4f03fedf-01f7-42a5-ad63-12586634bad8)

This worked until LocalSend v1.8 where Edge-to-Edge has not been added.

Related to https://github.com/flutter/flutter/issues/90098

### To reproduce

Open app with Android 9 or older

### Expected behavior

Should show visible navigation buttons.

**Comment by GittBittu** [comment]
The buttons are there and we can see them by looking really close, it's the padding that is giving the same color as the buttons thus making it barely visible.
![Screenshot_20230827-275](https://github.com/localsend/localsend/assets/109446863/722a3b81-9d9c-4f5f-b5a0-516c2b25c619)
