### ISSUE TITLE
Crashes on Windows 7

### ISSUE THREAD

**Issue by 13913585904** [localsend/localsend#66]
My computer‘s operating system is Windows 7 Professional Service Pack 1.The operating system prompts crash when I run the software.
![crash](https://user-images.githubusercontent.com/103355616/215393734-c5951de3-7a53-4f90-8bba-88dfbd0e3459.PNG)

**Comment by Tienisto** [comment]
I don't have Windows 7, so I cannot test this sorry.

**Comment by Tback1** [comment]
I have the same question. also the ucrtbase.dll make the crash

**Comment by youngbais** [comment]
I have the same question. also the ucrtbase.dll make the crash.

**Comment by TheGB0077** [comment]
It looks like [this release](https://github.com/Baseflow/flutter-permission-handler/releases/tag/permission_handler_v9.2.0) of the flutter permission handler broke compatibility with Windows 7 according to reports.

**Comment by c-sanchez** [comment]
LocalSend also does not work on my computer, Windows 7 x64 with updates to date.
Apparently it's a problem Flutter, I have already seen several applications that do not work
I hope this can be resolved :(

**Comment by Tienisto** [comment]
Thanks @TheGB0077 . Your assumption was correct! LocalSend now depends on https://github.com/localsend/permission_handler_windows_noop which basically removes all functionality of permission_handler in Windows.

Released in `v1.10.0`.

**Comment by top-master** [comment]
Above mentions `v1.10.0` to support Windows 7, **however**, version `1.17.0.58` no longer works, **and** I didn't want to miss the latest features, hence I use:
https://github.com/YuZhouRen86/VxKex-NEXT/releases

With that, I was able to run the LocalSend app even without mentioned Windows 7 support.

After installing VxKex, Windows 7 support is as simple as opening `localsend_app.exe` file's properties, then in `VxKex` tab, check `Enable VxKex NEXT for this program`.
