### ISSUE TITLE
Confirm before deleting history

### ISSUE THREAD

**Issue by jasmyneokudo** [localsend/localsend#660]
### Is your feature request related to a problem? Please describe.

When I click the delete history button, it deletes immediately without confirmation, 

### Describe the solution you'd like

I'll like to see a confirm dialog that asks me if I really want to delete my history

**Comment by AshkanArabim** [comment]
I noticed the PR was merged—just wondering if there's anything else needed to close this issue?

**Comment by Tienisto** [comment]
I've forgot to close this. Good catch!
