### ISSUE TITLE
Disable client side decorations on Wayland

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [localsend/localsend#666]
### Describe the bug

Flutter inherits the long-standing problems of GTK, GTK refuses to provide reasonable default values, and refuses to adjust by end users, and hands the responsibility to software developers. 

Currently software using GTK will use client-side decorations by default. Hope this Software can handle the `GTK_CSD` environment variable to use server-side decorations when its value is `0`

### To reproduce

Just open on the Wayland

### Expected behavior

Use server side decorations in Wayland

### Screenshots

I set kde's server window decorations to only contain green (on focus) or gray borders (on loss of focus) so the application can have the most space for its content.

Except for GTK applications All other software can normally apply the server-side window decoration, and even steam can be forced to set the server-side window decoration.

![wayland](https://github.com/localsend/localsend/assets/24669431/bf0714f9-cabf-4d9b-b4d4-56e4ab1e947b)

![xwayland](https://github.com/localsend/localsend/assets/24669431/4b55a4ff-9b24-476b-a502-8136cc413a78)

### Desktop (please complete the following information)

![2023-09-06_21-09](https://github.com/localsend/localsend/assets/24669431/9ab5c56c-af5d-4c11-a976-34533f8ed252)

### Additional context

https://github.com/localsend/localsend/blob/1c3956ddeaafac3e3c87dc41d50c603bfb0ee75f/linux/my_application.cc#L30-L48C2

**Comment by I-Want-ToBelieve** [comment]
The situation under x11 is dealt with here, but wayland is missing, add a judgment on wayland, and set use_header_bar to false to solve the problem

https://github.com/localsend/localsend/blob/1c3956ddeaafac3e3c87dc41d50c603bfb0ee75f/linux/my_application.cc#L30-L48C2

```c
gboolean use_header_bar = TRUE;
#ifdef GDK_WINDOWING_X11
  GdkScreen* screen = gtk_window_get_screen(window);
  if (GDK_IS_X11_SCREEN(screen)) {
    const gchar* wm_name = gdk_x11_screen_get_window_manager_name(screen);
    if (g_strcmp0(wm_name, "GNOME Shell") != 0) {
      use_header_bar = FALSE;
    }
  }
#endif
  if (use_header_bar) {
    GtkHeaderBar* header_bar = GTK_HEADER_BAR(gtk_header_bar_new());
    gtk_widget_show(GTK_WIDGET(header_bar));
    gtk_header_bar_set_title(header_bar, "LocalSend");
    gtk_header_bar_set_show_close_button(header_bar, TRUE);
    gtk_window_set_titlebar(window, GTK_WIDGET(header_bar));
  } else {
    gtk_window_set_title(window, "LocalSend");
  }
```

**Comment by Tienisto** [comment]
Thank you for your investigation.

If you feel confident, you can make a PR. I am not using Linux nor do I know about the low level stuff that is handled there.

**Comment by I-Want-ToBelieve** [comment]
I am configuring the flutter development environment on my nixos host. Currently, the latest flutter version of nixos is 3.13.0, so I encountered the following error:

```
Resolving dependencies...
The current Flutter SDK version is 3.13.0.

Because localsend_app requires Flutter SDK version >=3.13.1, version solving
   failed.
```

I'm about to try deploying flutter's development environment in archlinux in distrobox, once I'm ready to test it, I'll submit a PR. Thanks.

**Comment by I-Want-ToBelieve** [comment]
I found that there is not much difference between flutter 3.13.2 and flutter 3.13.0, so I temporarily lowered the restriction on flutter version in pubspec.yaml to 3.13.0 for now

**Comment by Tienisto** [comment]
You can take a look at the Github action that installs all necessary dependencies:

https://github.com/localsend/localsend/blob/main/.github/workflows/release.yml#L98
