### ISSUE TITLE
Feature request: Move preferences file to the folder with the portable version of the Windows application

### ISSUE THREAD

**Issue by Vilmodao** [localsend/localsend#667]
### Is your feature request related to a problem? Please describe.

I lose all my settings when I move the portable version of the Windows app on a new system.
This is probably because the preferences file is stored in the user roaming folder and not in the program folder. Not very portable way. 

### Describe the solution you'd like

The preferences file of the portable version should be stored in the program folder by default.

### Describe alternatives you've considered

The location of the preferences file can be an option in the app settings.

**Comment by Stefanoko** [comment]
I strongly second this suggestion, to store settings in the portable app folder.

**Comment by Tienisto** [comment]
This has been implemented and will be published in the next release (1.13.0).

I didn't implement a special detection wether this app is run in portable or in installation mode.
However, you can create an empty `settings.json` file next to the EXE file. During app start, LocalSend will use this file instead.

**Comment by Stefanoko** [comment]
> you can create an empty `settings.json` file next to the EXE file. During app start, LocalSend will use this file instead.

Great. Thanks a ton, this is exactly what I was hoping for. 
Looking forward to the next release.

**Comment by Vilmodao** [comment]
Nice. Thanks.
