### ISSUE TITLE
Portable version startup error

### ISSUE THREAD

**Issue by Temacc0531** [localsend/localsend#682]
### Describe the bug

Startup program system error

![2023-09-13 180311](https://github.com/localsend/localsend/assets/101307399/a5c3866e-f77e-4c7c-bbb5-e204d86d2caa)

![2023-09-13 180437](https://github.com/localsend/localsend/assets/101307399/f721027e-381d-428c-a66a-7d4721d86246)

### To reproduce

1. Startup program
2. See error

### Expected behavior

No additional requirements, normal startup

### Desktop (please complete the following information)

- Windows 11

### Additional context

For me, I realize that this may require installing "Visual C++" related files, but maybe there should be a better solution?

**Comment by Tienisto** [comment]
What version do you use?

**Comment by Temacc0531** [comment]
I tried v1.11.1 and v1.11.0, both of which have this issue

**Comment by Tienisto** [comment]
You probably use an old version of Windows with missing updates.

Please install all the "Visual C++ Redistributable": https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

I think 2013-2019 is needed

**Comment by Temacc0531** [comment]
This problem can be solved after the installation of "Visual C++ redistributables", but can't it be solved during the development of the program?

**Comment by Tienisto** [comment]
Usually there is an installer that comes with the required dependencies but as you use a ZIP, there is no installation process.

I think that the "Redistributables" are commonly used by many programs so most users won't notice this issue.

I will try to build a traditional exe installer in the next release

**Comment by Temacc0531** [comment]
Okay, thank you very much for your help

**Comment by Temacc0531** [comment]
Addendum: This issue can be solved by installing "Microsoft Visual C++2015-2022"

**Comment by jalemann** [comment]
I get this error when installing via exe downloaded from https://localsend.org/#/download (v1.14.0).

MSIX Installer works.
