### ISSUE TITLE
Need a way to delete recevied files in /var/mobile/Containers/Data/Application/40BD02BB-943D-40FA-8060-07E63F933182/Documents on iPhone

### ISSUE THREAD

**Issue by haai-team** [localsend/localsend#686]
### Is your feature request related to a problem? Please describe.

I sent a large file from my Desktop PC to my iPhone，after used on iPhone, when I want to delete this large file, It seems no way to delete a recevied large file in /var/mobile/Containers/Data/Application/40BD02BB-943D-40FA-8060-07E63F933182/Documents on iPhone.

### Describe the solution you'd like

In history or setting pages, should has a button to clear received files.

**Comment by Tienisto** [comment]
Shouldn't this file be visible in the "Files" app of your iPhone?

**Comment by haai-team** [comment]
> Shouldn't this file be visible in the "Files" app of your iPhone?

Yes, you are right. Thanks.
Sorry for my miss report.
