### ISSUE TITLE
Auto start: start hidden didnt work at portable version

### ISSUE THREAD

**Issue by Collect-diamond** [localsend/localsend#687]
### Describe the bug

Portable version start hidden didn't work if i just enable it, i need to put its link in program start page to make it work. but in this way when my PC restart it wont able to remember its position in system tray. (my PC can recognize localsend without putting it into auto start page.) Anyway to fix it in future version? thx

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

1. autostart hidden didn't work in localsend portable version.
2. localsend in system tray reset everytime i restart my PC if i put it into program autostart installer

### Desktop (please complete the following information)

Windows10 21H2 Family 19044.3086
LocalSend v1.11.1 portable version.

**Comment by SunshineboyZj** [comment]
yes,I find "v1.11.1 can autorun ,but it cannot start hidden after autorun" too

**Comment by RepentStar** [comment]
I don't think it's a problem with the portable version, the installed version has this problem on win10 and not on win11

**Comment by SunshineboyZj** [comment]
But this is indeed a problem, and it still needs to be fixed, whether it is a problem with Win10 or the portable version




---Original---
From: ***@***.***&gt;
Date: Sun, Oct 1, 2023 10:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [localsend/localsend] Auto start: start hidden didnt work atportable version (Issue #687)




 
I don't think it's a problem with the portable version, the installed version has this problem on win10 and not on win11

**Comment by RepentStar** [comment]
> But this is indeed a problem, and it still needs to be fixed, whether it is a problem with Win10 or the portable version
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Oct 1, 2023 10:56 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [localsend/localsend] Auto start: start hidden didnt work atportable version (Issue #687) I don't think it's a problem with the portable version, the installed version has this problem on win10 and not on win11 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Sure. I'm just specifying that this is not a problem specific to the portable version. I use a translator, which may affect the understanding of the language. I would also like the author to address these issues which are of the same nature. :)

**Comment by Virgus** [comment]
Hello all,
to overcome this issue you could use a startup script like this one.
Just put it into LocalSend_app.exe folder and put a shortcut into startup folder.

Cheers,
V.

```@ECHO off
PUSHD "%~dp0"

::DISABLE REG AUTOSTART
REG delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "localsend_app" /f 2>nul

CALL :CHKPROC localsend_app.exe
IF %ERRORLEVEL%==1 START /MIN /B "" localsend_app.exe autostart
GOTO :EOF

:CHKPROC
SET "PRCNAME=%~nx1"
TASKLIST /SVC /FI "ImageName eq %PRCNAME%*" | FINDSTR /I "%PRCNAME%*" >NUL
EXIT /b %ERRORLEVEL%```

**Comment by JoshCodeStuff** [comment]
Installed Local Send recently, and this feature does not work for me either (non-portable version)

**Comment by RPXbr** [comment]
I created a quick solution in Windows until this bug is fixed. I hope this helps:

https://github.com/localsend/localsend/issues/464#issuecomment-2156997926
