### ISSUE TITLE
Add exe setup version for windows

### ISSUE THREAD

**Issue by Collect-diamond** [localsend/localsend#688]
windows10 msix app's hard to modified any files, and portable version has some issues in it, can you add a exe setup version for windows? thx

**Comment by ioank** [comment]
Search info regarding this Nullsoft Scriptable Install System

**Comment by Tienisto** [comment]
Yes this is actually planned for the next version (1.12.0)

**Comment by Nolle10** [comment]
This seems like it an executable for Windows is now available @Collect-diamond
