### ISSUE TITLE
Empty window on startup

### ISSUE THREAD

**Issue by meyt** [localsend/localsend#69]
Shows empty screen with some logs in Terminal when opening the `.AppImage`.

![image](https://user-images.githubusercontent.com/10482278/215448466-4088028f-003f-4357-b9c2-69c1bc490279.png)

```text
** (localsend_app:396452): WARNING **: 13:40:17.070: Failed to start Flutter renderer: No GL implementation is available

** (localsend_app:396452): WARNING **: 13:40:18.110: Unable to retrieve framework response: No engine to send to

** (localsend_app:396452): WARNING **: 13:40:38.483: Unable to retrieve framework response: No engine to send to

** (localsend_app:396452): WARNING **: 13:40:40.130: Unable to retrieve framework response: No engine to send to

** (localsend_app:396452): WARNING **: 13:40:51.234: Unable to retrieve framework response: No engine to send to
```

---

OS: Debian 11
DE: XFCE 4.16

**Comment by Caesarovich** [comment]
Hi @meyt 

Can you confirm that this issue still occurs with the latest version of LocalSend ?

If the issue is fixed could you please close this issue as solved if that's okay with you.

**Comment by meyt** [comment]
@Caesarovich Tested on version 1.10.0, it works now.
