### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#7]
Allow setting favorites to avoid discovering.

Each favorite should be bound to a LAN network.

Geolocation permission may be needed to implement this feature.

**Comment by trymeouteh** [comment]
It would be amazing to have the following...

A menu to manager saved network

A menu to manage saved devices
A menu to label saved devices (Mom's iPhone, My Laptop, etc)

A menu to manage which networks will allow QuickSend (For trusted devices)
A menu to manage which devices will allow QuickSend (For trusted devices)


This will allow for trusted networks and trusted devices.

**Comment by Tienisto** [comment]
Favorites are implemented in v1.12.0.

A little bit simplified but it should solve the issue of manually typing the IP address.
