### ISSUE TITLE
The function of "auto-hide window at startup" doesn't work

### ISSUE THREAD

**Issue by shui-dun** [localsend/localsend#71]
![image](https://user-images.githubusercontent.com/46079921/215476365-fef83b2a-a064-4729-b2f8-63fbff095b6a.png)

I use Windows 10 and I turn on "Autostart: Start hidden" button, but the window will still pop up when I turn on the PC.

**Comment by shui-dun** [comment]
I use the portable version.

**Comment by Tienisto** [comment]
The startup task from the Windows Store adds a `autostart` parameter, so the app know that it was started automatically.

Can you show me the app arguments when started automatically? You can see it in `Settings Tab > About LocalSend > Debugging`

**Comment by shui-dun** [comment]
debugging info:

![image](https://user-images.githubusercontent.com/46079921/215487812-e6dcd340-28a7-4579-972d-4fe5224cd9d8.png)

by the way, let me describe how I realize the autostart function. I clicked the `Autostart after login` setting button, but I didn't see localsend in the pop-up list. 

![image](https://user-images.githubusercontent.com/46079921/215489076-ba25cab0-52cb-422e-a3b5-2c2b6b6b15c0.png)

therefore, I put the shortcut of localsend into the directory `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup` to achieve the effect of autostart.

**Comment by Tienisto** [comment]
Hmm, it should show up somewhere in the bottom (at least on my machine when I tested the zip).

You could fix the autostart problem by adding `autostart` as parameter. See https://superuser.com/questions/29569/how-to-add-command-line-options-to-shortcut

It should be like `"C:\path\to\localsend.exe" autostart`

**Comment by shui-dun** [comment]
I add the `autostart` parameter manually and it works, thanks! 😁

**Comment by lllwsjlll** [comment]
> "C:\path\to\localsend.exe" autostart

Hello, may I ask where to add this code, thank you

**Comment by lllwsjlll** [comment]
> I add the `autostart` parameter manually and it works, thanks! 😁

Hello, may I ask where to add this code, thank you

**Comment by shui-dun** [comment]
> > I add the `autostart` parameter manually and it works, thanks! 😁
> 
> Hello, may I ask where to add this code, thank you

![image](https://user-images.githubusercontent.com/46079921/226098896-ffd9e991-9cc7-4258-9378-772c92e7727a.png)

Add Here

**Comment by lllwsjlll** [comment]
> > > I add the `autostart` parameter manually and it works, thanks! 😁
> > 
> > 
> > Hello, may I ask where to add this code, thank you
> 
> ![image](https://user-images.githubusercontent.com/46079921/226098896-ffd9e991-9cc7-4258-9378-772c92e7727a.png)
> 
> Add Here

emm用了你的第一个方法能自启，但不能最小化启动。
添加代码这个，不能自启。。
我还是先用安装包吧，谢谢😁

**Comment by cdchs99** [comment]
> > > > I add the `autostart` parameter manually and it works, thanks! 😁
> > > 
> > > 
> > > Hello, may I ask where to add this code, thank you
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/46079921/226098896-ffd9e991-9cc7-4258-9378-772c92e7727a.png)
> > Add Here
> 
> emm用了你的第一个方法能自启，但不能最小化启动。 添加代码这个，不能自启。。 我还是先用安装包吧，谢谢😁

我用便携版测试了下，添加`autostart`代码后，确实能够实现静默自启。你会不会没有手动把快捷方式移入“启动”文件夹？

**Comment by Mapaler** [comment]
I can't use the installed version to silently start , and even not find LocalSend in Autoruns. How do I modify startup parameters?

**Comment by Tienisto** [comment]
I don't know this progam but you should be able to add the executable path with the `autostart` parameter?

**Comment by cdchs99** [comment]
> I can't use the installed version to silently start , and even not find LocalSend in Autoruns. How do I modify startup parameters? ![Autoruns_2023-09-19_19-38-12](https://user-images.githubusercontent.com/6565860/268940429-1459e5ce-4730-4ba4-aa42-feff8bd08801.png)

This method works for the portable version. Creat the shortcut of localsend.exe, then add the `autostart` parameter to the target in the properties of localsend.ink(there're pictures in preceding posts), finally, move the localsend.ink to startup folder(eg. `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` or `C:\Users\your username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`)

**Comment by Mapaler** [comment]
> I don't know this progam but you should be able to add the executable path with the `autostart` parameter?

Autoruns is a tool in Microsoft's official toolkit, _Sysinternals Suite_.
https://learn.microsoft.com/zh-cn/sysinternals/downloads/autoruns

> This method works for the portable version. Creat the shortcut of localsend.exe, then add the `autostart` parameter to the target in the properties of localsend.ink(there're pictures in preceding posts), finally, move the localsend.ink to startup folder(eg. `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` or `C:\Users\your username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`)

Thanks for your answer.
I installed using _Winget_ so that I can easily update the version with the command line.
However, the installation version will change the file address with each version update, and the shortcut will not work.
![explorer_2023-09-19_20-40-06](https://github.com/localsend/localsend/assets/6565860/b532ecda-a439-4675-9ca6-ffae22ba6491)
Also, the user name can be modified, and the environment variable path is more accurate.
Use `%ProgramData%\Microsoft\Windows\Start Menu\Programs\StartUp` or `%AppData%\Microsoft\Windows\Start Menu\Programs\Startup`

**Comment by Mapaler** [comment]
经过试验，部分解决了问题，在CMD里运行如下命令即可静默启动安装版
`start "" "shell:AppsFolder\11157TienDoNam.LocalSend_g71aj367vb7ze!localsendapp" "autostart"`
所以启动快捷方式或者注册表启动只需要使用 cmd /c 参数传入这个命令就能实现
`cmd /c start "" "shell:AppsFolder\11157TienDoNam.LocalSend_g71aj367vb7ze!localsendapp" "autostart"`

**Comment by bearcloney** [comment]
> > > > 我`autostart`手动添加了参数，成功了，谢谢！😁
> > > 
> > > 
> > > 你好，请问这个代码在哪里添加，谢谢
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/46079921/226098896-ffd9e991-9cc7-4258-9378-772c92e7727a.png)
> > 添加这里
> 
> emm用了你的第一个方法能够自启动，但是不能最小化启动。 添加这个代码，不能自启动。。 我还是先用安装包吧，谢谢😁

Encountered the same problem as you, now solved
Autostart after login—settings
Turn off the existing localsend Autostart option
In this way, the shortcut in the %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup directory will be used.
跟你遇到了同样的问题，现在已解决
Autostart after login—settings
把已经有的localsend Autostart的选项关掉
这样才会使用%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup目录下的快捷方式

**Comment by bitjerry** [comment]
这个问题依然存在于msix版本中, 并且没有很好的解决方案. 这个程序确实在设置->启动应用中开启成功了, 但localsend并没有识别到autostart. 也无法静默自启动. 前面有人说通过shell传参, 这很不优雅, 我会改为使用便携版, 直到msix版本的这个问题被修复
