### ISSUE TITLE
Feature request ：ipv6 need

### ISSUE THREAD

**Issue by kirito201711** [localsend/localsend#719]
### Is your feature request related to a problem? Please describe.

IPv6 cannot be used

### Describe the solution you'd like

Hopefully, this software can support IPv6，IPv6 is all public IP, which means that you can quickly transfer files to friends, remotely

**Comment by hasnainmakada-99** [comment]
This issue sounds awesome, can you please give more context to this @kirito201711 ? maybe we could sort this out together

**Comment by kaechele** [comment]
Duplicate of #549
