### ISSUE TITLE
Multiline checkbox for text input not working

### ISSUE THREAD

**Issue by S-ecki** [localsend/localsend#73]
Inside the "type message" dialog checking or unchecking the "multiline" checkbox does not change the behaviour of the field.
Either way, when typing a long string, the dialog is expanded to the max width of the screen (with some padding) and after that a multiline is created.

I am testing on Android 11 on an OnePlus 6.

**Comment by S-ecki** [comment]
After looking at the code, I realize that I misinterpreted the meaning of the checkbox:

I thought: I toggles wheter the form field can be multiline, meaning it will either expand vertically if yes or be scrollable horizontally of no

Actual use case: Toggling whether a linebreak is created with the "enter" button or the message is sent

I woud argue for either renaming this feature or refactor the UI.

**Comment by Tienisto** [comment]
Yes, it needs to be horizontally scrollable. So this needs to be fixed. Thanks for mentioning this issue!

**Comment by S-ecki** [comment]
No prob! Should I look at it?

**Comment by Tienisto** [comment]
If you like, you can do it :)

**Comment by S-ecki** [comment]
@Tienisto created the PR, was an easy fix :)
