### ISSUE TITLE
A question regarding translation

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#732]
### Is your feature request related to a problem? Please describe.

As far as I understand, line 63, which was previously translated as "Clipboard", is now changed to "Paste". Judging from the "picker" block, it's more likely the top header "Selection" (screenshot 1). If that's the case, it's not the best idea at all because it looks illogical. If we were to be more explicit, it would be correct to name it "Paste from clipboard" or "Paste from the clipboard" (but without the article 'the', it looks shorter, hence a better choice). However, both of these names are quite long, so it makes sense that you tried to shorten it. But the option "Paste" – it doesn't convey the idea at all; it's unclear where to paste from. The previous option "Clipboard" sounds more logical.

I understand that in operating systems, the term "copy-paste" is used, but it's familiar and intuitive for users. However, for an average user who hasn't copied anything and simply opens an app and seeing the "Paste" tab, it might appear somewhat confusing.

### Describe the solution you'd like

Described above

### Additional context

![1](https://github.com/localsend/localsend/assets/125032334/6956e0e1-aa41-4158-bd13-cbf997598775)

**Comment by sergd88** [comment]
I have one more question regarding line: 38. "unchanged": "Unchanged". In what context is this used? I can see that this line is already translated for Ukrainian and Russian, but I don't recall translating it. So, most likely, this is a machine translation. Depending on the context, this word can be translated differently, not to mention that in Ukrainian and Russian, the gender changes, so the suffixes in words differ.

If it's not too much trouble, I would greatly appreciate a screenshot where this line is used, so I can see where exactly this word is used and the context around it. As far as I understand, this is already a translation for the next release, so I cannot independently check it.

**Comment by sergd88** [comment]
Oh, I see you've already answered my question on the main topic, so I'll close the main question, but I would appreciate an answer to the second question. So, overall, I'm not closing the topic just yet.

**Comment by Tienisto** [comment]
Hello, the string "unchanged" is probably shown when you receive files and press on "Option". There you can optionally rename the received files or leave them "unchanged"

![Bildschirmfoto 2023-10-14 um 19 02 10](https://github.com/localsend/localsend/assets/38380847/fe1a5d39-379d-4c08-9907-1db52bbbd612)
