### ISSUE TITLE
Bug report: LocalSend's Linux client cannot send files to Windows and Android

### ISSUE THREAD

**Issue by See-Night** [localsend/localsend#749]
### Describe the bug

Under the same LAN, LocalSend's Linux client cannot send files to Windows and Android, but can receive files from them. (Communication between Windows and Android clients is normal.)

Port 53317 is opened in Linux：
![image](https://github.com/localsend/localsend/assets/45226780/5f19ee81-29a9-4d86-8054-a294c4b47656)

Error information:
```
DioException [unknown]: null
Error: HandshakeException: Connection terminated during handshake
```
![image](https://github.com/localsend/localsend/assets/45226780/57118ae1-b485-4b31-a817-d0f88cf7ac9c)

### To reproduce

1. Select a file to drag into Localsend
2. Click the device you want to receive the file from
3. Wait
![image](https://github.com/localsend/localsend/assets/45226780/57118ae1-b485-4b31-a817-d0f88cf7ac9c)

### Expected behavior

The receiving device should receive a send request.

### Screenshots

![image](https://github.com/localsend/localsend/assets/45226780/57118ae1-b485-4b31-a817-d0f88cf7ac9c)

### Desktop (please complete the following information)

- OS: Ubuntu
- Version: 23.04

### Smartphone (please complete the following information)

- Device: Honor Play 4
- OS: Android
- Version: 8.1

**Comment by KunB-Fighting** [comment]
It seems that I meet a similar problem, I can not send files from ubuntu to windows, while I can send files from windows to ubuntu.

I run localsend with AppImage on ubuntu, and I got these error messages:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [connection timeout]: The request connection took l
onger than 0:00:02.000000. It was aborted.                                                                                              
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)                                                         
#1      _RootZone.runUnary (dart:async/zone.dart:1661)                                                                                  
#2      _FutureListener.handleError (dart:async/future_impl.dart:174)                                                                   
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)                                                      
#4      Future._propagateToListeners (dart:async/future_impl.dart:873)                                                                  
#5      Future._completeError (dart:async/future_impl.dart:649)                                                                         
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:60)                                                                  
#7      _Completer.completeError (dart:async/future_impl.dart:26)                                                                       
#8      Future.any.onError (dart:async/future.dart:620)                                                                                 
#9      _RootZone.runBinary (dart:async/zone.dart:1666)                                                                                 
#10     _FutureListener.handleError (dart:async/future_impl.dart:171)                                                                   
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)                                                      
#12     Future._propagateToListeners (dart:async/future_impl.dart:873)                                                                  
#13     Future._completeError (dart:async/future_impl.dart:649)                                                                         
#14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:550)                                                
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40) 
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      ConnectivityPlusLinuxPlugin._startListenConnectivity (package:connectivity_plus/src/connectivity_plus_linux.dart:65)
<asynchronous suspension>`
