### ISSUE TITLE
 Error (Xcode): Cycle inside Runner - on iPhone 15 Pro Max.

### ISSUE THREAD

**Issue by pengjinning** [localsend/localsend#758]
### Describe the bug

Error (Xcode): Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': CodeSign /Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app
○ That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output
'/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Info.plist'
○ Target 'Runner' has copy command from
'/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/ShareExtension.appex' to
'/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ShareExtension.appex'

Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/_CodeSignature ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:CodeSign
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app ->

node:
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/DKImagePickerController.framewo
rk/ ->

directoryTreeSignature: � ->

directoryContents:
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/DKImagePickerController.framewo
rk ->

CYCLE POINT ->

node:
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/DKImagePickerController.framewo
rk ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution [CP] Embed Pods Frameworks
/Users/ningjinpeng/Library/Developer/Xcode/DerivedData/Runner-geqkvxpameyqxufpznbrcjfagauw/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulat
or/Runner.build/Script-38A5402B0B18EA0E910C92D1.sh ->

node:
/Users/ningjinpeng/Library/Developer/Xcode/DerivedData/Runner-geqkvxpameyqxufpznbrcjfagauw/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulat
or/Runner.build/InputFileList-38A5402B0B18EA0E910C92D1-Pods-Runner-frameworks-Debug-input-files-263026ae2f8ab8153af86a73e3a7e867-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile
/Users/ningjinpeng/Library/Developer/Xcode/DerivedData/Runner-geqkvxpameyqxufpznbrcjfagauw/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulat
or/Runner.build/InputFileList-38A5402B0B18EA0E910C92D1-Pods-Runner-frameworks-Debug-input-files-263026ae2f8ab8153af86a73e3a7e867-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

node:
<execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3be
b2e9f90bde3f49-> ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary
/Users/ningjinpeng/Library/Developer/Xcode/DerivedData/Runner-geqkvxpameyqxufpznbrcjfagauw/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulat
or/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->

node: /Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Info.plist/ ->

directoryTreeSignature: w ->

directoryContents: /Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

node: /Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Info.plist
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/ios/Runner/Info.plist ->

node: /Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ShareExtension.appex ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/ShareExtension.appex
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/ShareExtension.appex ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks ->

node:
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-im/app/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/DKImagePickerController.framewo
rk

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

run

**Comment by esentis** [comment]
Have you checked https://github.com/flutter/flutter/issues/134256 ?

**Comment by pengjinning** [comment]
it worked by rearranging the order of **Embed Foundation Extensions** to be right after **Copy Bundle Resources**
thanks
