### ISSUE TITLE
Adding the function of manually specifying the IP address of a receiver

### ISSUE THREAD

**Issue by kevintsq** [localsend/localsend#77]
In some complex network environments such as campus networks, the software cannot automatically discover devices. Therefore, the software cannot be used. Adding the ability to manually specify the IP address of a receiver allows the software to still work in that case.

**Comment by Tienisto** [comment]
There is a button near "Nearby Devices". Maybe it's too hidden

**Comment by kevintsq** [comment]
Oh I found it. I have to long-press the button. It's indeed to hidden lol
