### ISSUE TITLE
Feature Request: Add localsend option to the share list after taking a screenshot on ipad.

### ISSUE THREAD

**Issue by ZHN202** [localsend/localsend#779]
### Is your feature request related to a problem? Please describe.

After saving a screenshot to an album on ipad, there is a localsend sharing option, but there is no localsend option in the sharing options on the screenshot screen.

### Describe the solution you'd like

Add localsend option to the share list after taking a screenshot on ipad.

**Comment by prasadsunny1** [comment]
This is very interesting. Is this already available for android?

**Comment by ZHN202** [comment]
maybe, you can try
