### ISSUE TITLE
Bug report: cant open transfer history on RTL

### ISSUE THREAD

**Issue by ShlomoCode** [localsend/localsend#797]
### Describe the bug

When the RTL language is set - Hebrew or Arabic, and I click on the history button in the application - both in the Android version and in the MacOS version, a sort of gray screen opens in the application, without the transfer history and without an `X` to exit

### To reproduce

1. Change the app language to Hebrew or Arabic
2. Click here:
![CleanShot 2023-10-25 at 02 55 28@2x](https://github.com/localsend/localsend/assets/78599753/8c37cd33-9656-4158-a4bb-700937233abf)

### Expected behavior

A list of previous transfers will be displayed

### Screenshots

https://github.com/localsend/localsend/assets/78599753/fa618411-5d6e-43ab-8b66-4d0ebb7834ec

### Desktop (please complete the following information)

- OS: MacOS
- version: 1.1.1 (35)

**Comment by ShlomoCode** [comment]
@Tienisto Did you manage to reproduce the bug?

**Comment by Tienisto** [comment]
Yes, it seems that `he` instead of `iw` should be used. On this page, it tries to format the date but it does not know `iw`. I will fix that.

**Comment by ShlomoCode** [comment]
👏

**Comment by ShlomoCode** [comment]
@Tienisto Thanks! I ran the latest code now on my computer (macos), and indeed after this correction there is no crash in Hebrew!
Close the issue as complete :)
