### ISSUE TITLE
Fastlane metadata for F-Droid should be in root path

### ISSUE THREAD

**Issue by linsui** [localsend/localsend#824]
### Describe the bug

Currently F-Droid can only find the fastlane metadata in the root path. Could you please move it back to root path? Thanks!

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

The fastlane metadata need to be put in root path.

**Comment by Tienisto** [comment]
Done

**Comment by linsui** [comment]
Thanks! Since reproducible build is enabled we can't simply use the latest commit. Could you please provide a commit cherry-picking the commit to the 1.12.0 tag or update your apk to it?

**Comment by Tienisto** [comment]
Hi, does https://github.com/localsend/localsend/commits/v1.12.0-fdroid work?

Here is the commit hash: deb36ea5461d1217b60ebacf75c47bf7e8e7e9d4

**Comment by linsui** [comment]
Updated in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13933. Thanks!

**Comment by Tienisto** [comment]
Thank you!
