### ISSUE TITLE
Bug report: After the transmission is completed, the selection is not cleared (Android)

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#829]
### Describe the bug

The issue has resurfaced again [#321](https://github.com/localsend/localsend/issues/321), [#195](https://github.com/localsend/localsend/issues/195), and for some reason, now when clearing the app's data and cache, the application settings are retained. This implies that the configuration files are located in a different place, which is also quite problematic because it makes it impossible to reset all of the application settings to their default state through standard methods.

The issue is once again that, for some reason, the transmission page itself is not displayed (see screenshot), and the transmission is carried out directly from the "Send" tab.

### To reproduce

...

### Expected behavior

...

### Screenshots

![1](https://github.com/localsend/localsend/assets/125032334/3e36b216-77c4-435f-a56b-09349090aeeb)

### Smartphone (please complete the following information)

I tried several different devices with various firmware and versions of Android.

**Comment by Tienisto** [comment]
Is it single recipient mode or multiple recipients mode? Somehow it works on my android phone

**Comment by sergd88** [comment]
> Is it single recipient mode or multiple recipients mode? Somehow it works on my android phone

Single.

**Comment by sergd88** [comment]
Somewhat everything is very strange. Background story. I updated from version 1.11.1 to version 1.12.0 through Google Play. Because sometimes updates in Google Play unfolded quite slowly, I would delete the version from Google Play and install the version from GitHub. As far as I understand, they have different digital signatures, so they are not compatible with each other in automatic updates through Google Play. Over time, when I saw that the new version was already available on Google Play, I would delete the version I had installed from GitHub and install the version from Google Play. In all these manipulations, I always cleared the app's cache and data so that no unpleasant situations would occur later, like the one I have now 😅. This time the update came quickly, so I didn't perform such manipulations, I simply updated the app through Google Play.

After this update, for some reason, I cannot clear the app's data and cache. It seems like everything is happening, but after clearing or even uninstalling the app, all the app settings are still saved. The fact that data and settings are not being deleted can be easily traced by the Alias, which does not revert to default values but retains the Alias I set. Since I tried different options and deleted the app, rolling back to the previous version of the app through Google Play is not possible. Version 1.11.1 (in which everything was ok) from GitHub cannot be updated to version 1.12.0 through Google Play due to a different digital signature. So I took version 1.11.1 from APKPure, which is compatible and can be updated to a newer version through Google Play. And with this manipulation, everything works, of course, only after clearing the app's cache and data. After that you can update through Google Play to version 1.12.0, and in it, clearing the cache and data also works.

But..., if after all these manipulations described above, you try to clear the app's cache and data again, delete the app, and want to install it directly through Google Play, to do a clean installation - old cache, data, settings come back from somewhere, and the problem with the choice not being removed after transmission completion becomes relevant again. Maybe it's a problem on the side of Google Play. I don't know. That's the story.

**Comment by Tienisto** [comment]
Weird...
I think as soon as the transmission is completed, it tries to clear the cache but fails to do so. It might be the case that the old data from the previous installation still exist but due to different signatures of the app, it does not have sufficient permission to clear it.

That's just an assumption though.

**Comment by sergd88** [comment]
> Weird... I think as soon as the transmission is completed, it tries to clear the cache but fails to do so. It might be the case that the old data from the previous installation still exist but due to different signatures of the app, it does not have sufficient permission to clear it.
> 
> That's just an assumption though.

I suspect that the app doesn't fully understand that the transfer has already occurred, as the transfer window isn't displayed at all, and the clearing process, as I think, should happen immediately after pressing the "Done" button, at least, that sounds logical. Overall, it all seems to be related to some strange glitch, which in turn is compounded by the fact that you can't clear the data as it worked last time. The data is probably stored in the system root directory, something like data/data, to which you can't gain access without root privileges. Of course, you can also try entering debugging mode through a computer, but I have no desire to deal with this.

Well, for now, judging by the fact that there are no comments on this matter, and no one has opened similar issues, I can assume that no one else has encountered this problem. Therefore, I'm closing this issue to avoid cluttering other issues with it, as searching for the cause of non-systematic problems is a waste of time. If someone else encounters this, there is a workaround that I described, although it's quite primitive, but it completely solves the problem.
