### ISSUE TITLE
EXE installer's All Users configuration installs to 32-bit Program Files directory by default

### ISSUE THREAD

**Issue by brogers5** [localsend/localsend#830]
### Describe the bug

The installation location for the new EXE installer's All Users configuration will default to the 32-bit Program Files directory (i.e. `C:\Program Files (x86)\LocalSend`).

This behavior is misleading, since LocalSend is compiled and distributed as a 64-bit application.

### To reproduce

1. Launch the new EXE installer as distributed with the v1.12.0 release.
2. In the `Select Setup Install Mode` dialog, press the `Install for all users (recommended)` option.
3. If User Account Control is enabled, press the Yes button when the UAC dialog shows.
4. In the `Select Setup Language` dialog, select the desired language, and press the `OK` button.
5. In the wizard's `Select Destination Location` page, check the default directory path that is populated by the installer.

### Expected behavior

The installation location should default to the 64-bit Program Files directory instead (i.e. `C:\Program Files\LocalSend`.

### Screenshots

![Select Destination Location page screenshot](https://github.com/localsend/localsend/assets/6869577/4c1b08ec-d32b-4b54-85b4-cd0d43292dd2)

### Desktop (please complete the following information)

- OS: Windows 11
- Version: 10.0.22621.2428 (22H2)

### Additional context

I discovered this while evaluating the new EXE installer for inclusion as part of the next version of Chocolatey's installer package (i.e. [`localsend.install`](https://community.chocolatey.org/packages/localsend.install)).

I suspect this may be because the installer is currently configured to run in [32-bit install mode](https://jrsoftware.org/ishelp/index.php?topic=32vs64bitinstalls). Notably, the Inno Setup Script's [`[Setup]` section](https://github.com/localsend/localsend/blob/b9a2f5d41e18ed98a3939e384ab3b51ae4789ec7/scripts/compile_windows_exe-inno.iss#L12) lacks an [`ArchitecturesInstallIn64BitMode`](https://jrsoftware.org/ishelp/topic_setup_architecturesinstallin64bitmode.htm) value with `x64` defined, which would be a prerequisite for the installer to execute in 64-bit install mode.

**Comment by Tienisto** [comment]
Yes, `C:\Program Files\LocalSend` would be better
