### ISSUE TITLE
EXE Installer allows for execution on 32-bit Windows

### ISSUE THREAD

**Issue by brogers5** [localsend/localsend#831]
### Describe the bug

The new EXE installer as distributed with the v1.12.0 release allows for the installation process to be stepped through to completion on 32-bit installations of Windows.

This behavior is misleading, since it implies the binaries being shipped with the installer are actually x86-compatible, when this is not actually the case. LocalSend will fail to launch after installation completes.

### To reproduce

1. Launch the EXE installer on a 32-bit installation of Windows.
2. Step through the installer to completion.

### Expected behavior

The EXE installer should display an error message stating the software's architectural incompatibility, and not allow users to install it.

### Screenshots

![LocalSend launch failure](https://github.com/localsend/localsend/assets/6869577/1bfaa6cd-3e6e-4022-a2cd-56a233341b78)

### Desktop (please complete the following information)

- OS: Windows 10, 32-bit
- Version: 10.0.19041.1348 (v2004)

### Additional context

I discovered this while evaluating the new EXE installer for inclusion as part of the next version of Chocolatey's installer package (i.e. [`localsend.install`](https://community.chocolatey.org/packages/localsend.install)).

I suspect this may be because the Inno Setup Script's [`[Setup]` section](https://github.com/localsend/localsend/blob/b9a2f5d41e18ed98a3939e384ab3b51ae4789ec7/scripts/compile_windows_exe-inno.iss#L12) currently lacks an [`ArchitecturesAllowed`](https://jrsoftware.org/ishelp/index.php?topic=setup_architecturesallowed) value with `x64` defined. If no value is defined, the installer could run on any architecture capable of executing x86 (natively or via emulation).

**Comment by Tienisto** [comment]
Thanks, I will look into that
