### ISSUE TITLE
Bug report: version 1.12.0 doesn't appear in fdroid.

### ISSUE THREAD

**Issue by not-programmer98** [localsend/localsend#838]
### Describe the bug

Right now, the last version on Google play and github releases is 1.12.0 but on fdroid still v 1.11.1

### Expected behavior

The version should appear in fdroid.

**Comment by Tienisto** [comment]
On F-droid, this usually takes a few days until a week.

**Comment by Tienisto** [comment]
The build on F-Droid was successful. LocalSend v1.12.0 should be available in 1-2 days.

https://monitor.f-droid.org/builds/log/org.localsend.localsend_app/38
