### ISSUE TITLE
Bug report: Extremely slow speed 20-30KB/s

### ISSUE THREAD

**Issue by dreamsmaner** [localsend/localsend#840]
### Describe the bug

Sending snapshots(jpg) from PC(Win10 64bit) to iPad(2021Pro). Each file is about 3MB. The speed is only 20KB/s with encrytion on and about 30KB/s with it off. Both the devices are connecting to the same home network, while the PC is wired and iPad is wireless connections. 

### To reproduce

N/A

### Expected behavior

I saw others discussing slow speed about 30MB/s+. But mine is only KB/s. Is there something I'm missing to use this sofeware?

### Screenshots

![image](https://github.com/localsend/localsend/assets/42914674/74615e75-8267-497d-af03-1b09c6062804)

### Desktop (please complete the following information)

Lenovo Legion R7000P 2020H
Win10 64bit 22H2

### Smartphone (please complete the following information)

iPad Pro 2021 11inch
iOS 17.1

### Additional context

N/A

**Comment by Rachamchen** [comment]
首先，家里的路由器发射频率如何，然后路由器是否支持2.4G Hz和5G Hz分离？如果支持，最好将无线连接的平板连到5G Hz的那个信号上。如果还是不行，可以试试平板开热点，或者笔记本开热点，然后另一个设备连接，这样暂时组成一个局域网，看看此时的收发速率是多少。

**Comment by Pentaphon** [comment]
You should investigate your router and try other devices first.

**Comment by dreamsmaner** [comment]
Router is Asus AX86U. 2.5GbE cable connection. 5GHz wireless connection on Channel 36 with 160MHz bandwidth on.
Very close distance(just steps away).
I have an iPerf3 server setup on my NAS. Test result of the iPad within the localnet is around 700-800Mbps for both upload and download. The local speed could be faster but the NAS is using an OpenWRT side gateway with 1Gbps connection.

Also, this issue does not happen every time. Sometimes the speed is good enough to not to be paid attention to.

**Comment by Pentaphon** [comment]
> Also, this issue does not happen every time. Sometimes the speed is good enough to not to be paid attention to.

How's the speed on the latest version on both devices?

**Comment by dreamsmaner** [comment]
Just tried again once. 35 files. 97MB. Finished in about 3 sec.

**Comment by Pentaphon** [comment]
> Just tried again once. 35 files. 97MB. Finished in about 3 sec.

Sounds like your issue is fixed.

**Comment by dreamsmaner** [comment]
I think so.
