### ISSUE TITLE
Feature request: localsend mobile app needs a 'select all' button when select photos from an album.

### ISSUE THREAD

**Issue by tp01-gogogo** [localsend/localsend#841]
### Is your feature request related to a problem? Please describe.

When I use localsend for iOS to send tons of photos, I think if there is a 'select all' button will be great.

### Describe the solution you'd like

When I use localsend for iOS to send tons of photos, I think if there is a 'select all' button will be great.

**Comment by JoJoJotarou** [comment]
I have the same requirement, the worse bug is that when I select 400 + and 600 + videos, all selections are lost after clicking confirm.

**Comment by Tienisto** [comment]
Let's merge this issue with #376
