### ISSUE TITLE
Upgrading to flutter 3.7 can effectively improve the problem of slow page scrolling.

### ISSUE THREAD

**Issue by HanHan666666** [localsend/localsend#85]
```
$ flutter --version
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (8 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```
[demo.zip](https://github.com/localsend/localsend/files/10552697/demo.zip)

**Comment by Tienisto** [comment]
Hi, LocalSend targets a lot of targets and uses a lot of less maintained dependencies. That's why I would like to wait a few bug fix releases to keep things stable. I think that the scroll issue is not critical.
