### ISSUE TITLE
send file from browser to phone

### ISSUE THREAD

**Issue by bazir123** [localsend/localsend#853]
### Is your feature request related to a problem? Please describe.

i haven't figured there is option like it in app or not and since there is no 32 bit windows file to use

### Describe the solution you'd like

i want app give me local ip:port   then i paste in PC browser then i drag&drop file from pc in window and it send it to phone
that's possible? if not can be added?
thanks

### Describe alternatives you've considered

someone build 32 bit exe

**Comment by Tienisto** [comment]
Please don't mix 2 issues into one. Also the file upload has already mentioned in another issue.

Duplicate of #424
