### ISSUE TITLE
Show color setting even when dynamic colors are not supported by OS

### ISSUE THREAD

**Issue by dhruvanbhalara** [localsend/localsend#854]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Option to switch to OLED theme before Android S OS. Some of the devices don't get OS updates but have OLED screens which will be a benefit for better UI Colors & devices battery as well.

**Comment by dhruvanbhalara** [comment]
@Tienisto, yes it's there but as I've Android 11 on my device with Amoled screen I'm not able to get that option. I checked the code and as per that it'll only work after Android S OS.

**Comment by Tienisto** [comment]
I see.
We need to remove the obsolete if statement in the code:

https://github.com/localsend/localsend/blob/39eac272609c91df3b39907d80751f37d54d5ec5/app/lib/pages/tabs/settings_tab.dart#L105
