### ISSUE TITLE
Recommended download format for Linux?

### ISSUE THREAD

**Issue by MMachado05** [localsend/localsend#857]
I currently have Localsend installed on my Kubuntu laptop via the Flatpak, as the README recommends using some kind of package manager. However, it seems like the Flatpak version is a bit out-of-date, whereas things like the deb file and the AppImage got new releases.

So, what exactly *is* the recommended distribution channel for Linux-based OS's? Would I more reliably have the newest version if I were to simply download the AppImage and keep tabs on whether it was up-to-date or not? Or does the flatpak usually just take a week or two in getting the updates? Thanks in advance!

**Comment by MMachado05** [comment]
Also I wanted to add the label "question" here, but I'm not sure if I have permission to do that. I didn't know where else would be the more "proper" way to pose this question, so I apologize if I'm polluting the repo a little bit here.

**Comment by Tienisto** [comment]
It seems that the Flathub bot didn't publish a PR yet

https://github.com/flathub/org.localsend.localsend_app/pulls

**Comment by MMachado05** [comment]
Ah, got it! Thanks for the info. So, if all goes as usual, the Flatpak would normally be up-to-date with the releases? Was this more of an unforeseen hiccup in the automated Flatpak-updating process?

As my primary question has been answered, I'll go ahead and close this issue!
