### ISSUE TITLE
Feature request: Show apk sending on the send screen

### ISSUE THREAD

**Issue by Zac99LOL** [localsend/localsend#871]
### Is your feature request related to a problem? Please describe.

Yes. On the send screen four types of file can be sent, file, media, text and folder. 

### Describe the solution you'd like

However, if you add something, then press to add another file, another option is shown, "App". Please show the option on both screens.

### Additional context

![Screenshot_20231106_161251](https://github.com/localsend/localsend/assets/108863371/eef8e4ac-1371-4a04-9c69-3f1c4d0e7fde)
![Screenshot_20231106_161303](https://github.com/localsend/localsend/assets/108863371/ce80dec2-cb44-446e-84c9-9b0ea9ed4fb6)

**Comment by Tienisto** [comment]
The "App" button is also shown in the send tab, just swipe to the right.
