### ISSUE TITLE
Slow startup on Gnome desktop environment

### ISSUE THREAD

**Issue by aucub** [localsend/localsend#883]
### Describe the bug

If you use the Arch Linux operating system and the Gnome desktop environment, it will take a few seconds for the application to appear. If using Nixos and Kde Plasma, the application can start quickly.

### To reproduce

1. Go to Desktop
2. Click on LocalSend
3. Wait for the app to start

### Expected behavior

Applications can be launched without noticeable delays

### Screenshots

[录屏 2023-11-10 20-50-55.webm](https://github.com/localsend/localsend/assets/78630225/bd01bcaa-50c8-4643-ac08-8d2c9b2ae997)

### Desktop (please complete the following information)

- OS: Arch Linux
- Kernel: Linux 6.6.1-zen1-1-zen
- Desktop Environment: Gnome 45.1
- Window System: Wayland

**Comment by fritzrehde** [comment]
I have this issue as well on Arch Linux with the Sway window manager (so no GNOME). I installed the AUR `localsend-bin` package. It also takes many seconds to startup, which seems strange.

**Comment by rothgar** [comment]
I don't have the same problem. I'm using

OS: ubuntu/fedora
Kernel: Linux 6.5.8-200.fc38.x86_64
Desktop Environment: Gnome 44.6
Window System: Wayland

The first open is using distrobox in an Ubuntu container installed via deb (fast to open) and the 2nd one is using the AppImage on fedora. It's not quite as fast but still faster than your example video.

[localsend.webm](https://github.com/localsend/localsend/assets/371796/30668446-97aa-4162-83a2-69ef61577d43)

**Comment by Deeepkk** [comment]
Same issue on Hyprland (Wayland Compositor) , Arch

**Comment by Bubbu0129** [comment]
Same on Arch Linux with KDE Plasma.
