### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by B4undless** [localsend/localsend#888]
### Is your feature request related to a problem? Please describe.

I trust you're doing well. I've been using LocalSend extensively and appreciate the effort put into creating a robust communication tool.

### Describe the solution you'd like

I'm writing to suggest the addition of a clipboard feature in LocalSend, akin to the functionality present in Windows 10/11. This feature would significantly enhance user experience, particularly on systems that lack native clipboard support, such as Windows 8.1.

### Describe alternatives you've considered

Implementing a clipboard feature could streamline information exchange between devices within the same local network, making LocalSend an even more versatile solution.

### Additional context

Looking forward to your insights on this suggestion.

best.

**Comment by Tienisto** [comment]
The clipboard feature should be already available in v1.12.0

**Comment by B4undless** [comment]
no I mean a clipboard same like (win 10/11 clipboard) for another OS like win 8.1

**Comment by B4undless** [comment]
so can you ?

**Comment by Tienisto** [comment]
This feature is currently out of scope of LocalSend since this is not the use case for AirDrop. Clipboard sync should be a separate app in my opinion.

Also, I think this should be implemented on OS level (Windows) because I have security concerns when implementing this. (I don't even know if it is possible to implement)

**Comment by Caesarovich** [comment]
@Tienisto This can be safely closed as **not planned**.
