### ISSUE TITLE
Add check if file is already selected

### ISSUE THREAD

**Issue by programmermager** [localsend/localsend#903]
### Describe the bug

I noticed that in LocalSend, it is still possible to send the identical files multiple times. So, when I select a file, let's say file_a.jpg, and then select it again, the file is added to the queue again, resulting in the transmission of two files.

Is this the expected behavior of the LocalSend feature, or is it a bug @Tienisto ?

### To reproduce

1. Go to tab `Send`
2. Click on File or Media
3. Select a file or image or video
4. And then add the same file with pick previously

### Expected behavior

I feel that there should be validation within a session to prevent the reselection of files that have already been chosen, unless the sending session has changed.

### Screenshots

![Screenshot_20231116-162334](https://github.com/localsend/localsend/assets/7869219/46240f3e-80a4-4094-89e2-f14eeb2caffd)
![Screenshot_20231116-162341](https://github.com/localsend/localsend/assets/7869219/f7e6cbe0-99fb-4907-b4b4-fce2bc35b92f)

### Desktop (please complete the following information)

- OS : MacOs
- Version : MacOs Ventura 13.2.1

### Smartphone (please complete the following information)

- Device : Samsung A50s
- OS : Android
- Version  : Android 11

### Additional context

I tried in MacOs and Android. But i think this is will happens to all platform

**Comment by Tienisto** [comment]
You are right, there is currently no check if the same file is selected again

**Comment by programmermager** [comment]
> You are right, there is currently no check if the same file is selected again

But should that require validation? If yes, maybe I can help with that.

**Comment by Tienisto** [comment]
Yes, a validation would be great

**Comment by programmermager** [comment]
> Yes, a validation would be great

ok, i will try on it. do you think for text and copy paste should be add the duplicate validation too?

**Comment by programmermager** [comment]
i already create the [PR](https://github.com/localsend/localsend/pull/904) for this enhancement, hope it will be merge. thx
@Tienisto
