### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by heschy2** [localsend/localsend#905]
### Describe the bug

The solution used to fix issue #426 was to add an OLED Option in the "Color" Preference in the Settings.
However this Preference is inaccessible on Android Version before 12. 

I guess this might be because without the OLED Option this preference was unusable and therefore obsolete on Android 11 and before, since you could only select "System" and "Localsend" color schemes and the "System"-scheme is based on a feature that was introduced in Android 12. However, since #426 was solved and it now contains an option that is useful for any Android version ("OLED") the preference should be visible.

### To reproduce

1. Go to 'Preferences' on an Android device That has not yet got the update to Android 12+
2. There is no Color option.

### Expected behavior

Do not hide the option on Systems below Android 12.

### Screenshots

Android 13 (Lineage OS 20.0 Unoffical) [WORKS]:
![Screenshot_20231116-150424_LocalSend](https://github.com/localsend/localsend/assets/105609148/51c0a050-0b89-4f4c-b573-21569a9c9d80)

Android 11 (/e/OS 1.16) [BUG]:
![image](https://github.com/localsend/localsend/assets/105609148/f410dd9e-6129-4627-81a2-70054536d847)

### Smartphone (please complete the following information)

Device : Samsung Galaxy S8
OS : Android 11
Android-ROM : /e/OS
Version : 1.16-r-20231017342509-stable-dreamlte

### Additional context

A good solution might be to solve #426 in another way:
Keep the Color Option hidden on devices before Android 12, and move the OLED option to a new Preference, basically like F-Droid does it: (screenshot in english, translation below)

![IMG_20231116_151124](https://github.com/localsend/localsend/assets/105609148/0f5fce56-2904-4ac4-914a-5c55fda9e6c4)
_Section "Display" in F-Droid Settings. There are two preferences ("Theme" and "use pure black background in dark theme")_

That would solve this issue, and it would finally solve issue #426.

**Comment by Tienisto** [comment]
Hello, this bug has been fixed in #854.

This is not released yet, so you need to wait for v1.13.0 or v1.12.1.

**Comment by heschy2** [comment]
Okay, great! I am sorry I did not see this Issue _(I really searched for similar issues, I promise)_
