### ISSUE TITLE
Sending too many files froze the Android app

### ISSUE THREAD

**Issue by szabolcsdombi** [localsend/localsend#907]
### Describe the bug

I have successfully used the android app to send 1k images over to my Windows computer.
I have selected the DCIM folder with 11k files in it. After a few seconds the files count and the total size of 85GB was shown (this supprized me as I cannot transfer this folder with an USB due to it hangs forever to show the files).
The app clearly froze, I have reset the app (force stop + delete data + cache) and retried.
It clearly hangs.
I was waiting for 10 minutes to see if it resolves, but not.
To define the frozen app:
Nothing happens if I touch any buttons including the Receive, or device list refresh,
I have tried to first press the device I wanted the files to be sent to.
I even tried long pressing emulating a simple press for a slow ui.

### To reproduce

1. Open the android app
2. Select aa images folder to send with 10k+ files with 80GB+ content.
3. Wait a few seconds to see the selection ready on the screen.
4. Try to press any other button.

### Expected behavior

To find some loading screen, or at least some "busy doing stuff" label, or some moving components to visualize it is not frozen.
It might be busy sending the metadata over.

### Smartphone (please complete the following information)

Pixel 6
Android 14
v1.8.0

**Comment by programmermager** [comment]
Wow its a huge files to send over wifi

**Comment by szabolcsdombi** [comment]
I could actually tether with the USB cable getting a wired connection. I do not mind the speed so I am using wifi. All types of the USB file transfers seems to fail at this file count.
Would it be possible to get past the frozen screen?
Do you have an idea why it hangs?
I can attach an adb if that would help. I do not know what to run, I use adb mostly to debug chrome.

**Comment by sergd88** [comment]
> I could actually tether with the USB cable getting a wired connection. I do not mind the speed so I am using wifi. All types of the USB file transfers seems to fail at this file count. Would it be possible to get past the frozen screen? Do you have an idea why it hangs? I can attach an adb if that would help. I do not know what to run, I use adb mostly to debug chrome.

To transfer hundreds of gigabytes, I personally use Syncthing. However, it's a synchronization application, so there are some drawbacks. You can temporarily synchronize the entire contents of the DCIM folder with your computer through it, so you don't have to copy all the necessary content to another folder strictly for synchronization. Because additional copying requires free memory for this content, and it also wears out the lifespan of your storage device.

Also, of course, it supports resumption of copying/synchronization, so in case of a connection loss, you can resume copying/synchronization without the need to start everything from the beginning.

**Comment by Tienisto** [comment]
I have added a hotfix apk to the newest v1.13.1 release. Please checkout if it can select a large number of files without freezing:

https://github.com/localsend/localsend/releases/download/v1.13.1/LocalSend-1.13.1--pick-many-files-fix.apk

**Comment by yagarea** [comment]
> I have added a hotfix apk to the newest v1.13.1 release. Please checkout if it can select a large number of files without freezing:
> 
> https://github.com/localsend/localsend/releases/download/v1.13.1/LocalSend-1.13.1--pick-many-files-fix.apk

This works. Thanks
