### ISSUE TITLE
Feature request：Optimize the icon

### ISSUE THREAD

**Issue by userzzzq** [localsend/localsend#913]
### Is your feature request related to a problem? Please describe.

LocalSend‘s icon is monochrome, it may not be visible clearly under some wallpapers.

### Describe the solution you'd like

It is recommended to add a white background. （like the right icon)

![Snipaste_2023-11-19_10-07-08](https://github.com/localsend/localsend/assets/69742519/196c7782-cac7-4c2b-8d96-10e8639bf30e)

**Comment by B4undless** [comment]
What do you think about these logos?
![local-_fill](https://github.com/localsend/localsend/assets/150511020/be31fdc3-37f9-4692-9b62-d4dabfdfac27)
![localsend](https://github.com/localsend/localsend/assets/150511020/631d4700-5b1b-4ca9-bbe0-b422c5844f94)
@Tienisto

**Comment by Tienisto** [comment]
Closing this in favor of #738
