### ISSUE TITLE
Automatically finish sessions

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#923]
### Discussed in https://github.com/localsend/localsend/discussions/921

<div type='discussions-op-text'>

<sup>Originally posted by **mensa84** November 20, 2023</sup>
Hi,

is it possible to configure the file transfer dialog on iOS to close automatically (for example after 1 or 3 seconds), when the file transfer was successfully? This will save 1 click and make it more user friendly :)</div>

**Comment by sergd88** [comment]
Sounds great, but it would be good to have a toggle switch in the settings to enable/disable this feature, as has already been done with some other functions.

**Comment by arnabs542** [comment]
It will be great if you implement this feature in windows app too. There are times, when I forget to close the dialog box after file transfer and when I try to send another file from the android app it says receiver is busy. Thanks in advance.
