### ISSUE TITLE
Can't clear cache on iPad

### ISSUE THREAD

**Issue by Tinyu-Zhao** [localsend/localsend#928]
### Describe the bug

Large amount of cache remains on iPad after accepting/sending files

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Can clear cache (without uninstalling the app)

### Screenshots

@
![IMG_1366](https://github.com/localsend/localsend/assets/44396641/a94ccb60-6772-41ab-8667-947784e4e962)

**Comment by Tienisto** [comment]
Closed with #946
