### ISSUE TITLE
Feature request: Please add an option to download the exe installer for Windows on the website

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#941]
### Is your feature request related to a problem? Please describe.

Please add an option to download the exe installer for Windows on the website.

### Describe the solution you'd like

None.

### Additional context

![202311271735](https://github.com/localsend/localsend/assets/125032334/f21637a8-3231-4b19-9d5d-0e9d8dbb939d)

**Comment by Tienisto** [comment]
Thanks for this notice!
