### ISSUE TITLE
Sometimes it is not required to accept the files, they are accepted automatically

### ISSUE THREAD

**Issue by szabolcsdombi** [localsend/localsend#944]
### Describe the bug

I have used this app many times, and I have noticed that sometimes I do not have to accept the files, transfer starts immediately. Is this a bug or a feature?

### To reproduce

1. Pick files to transfer
2. Start the app on the receiver side
3. Send the files to the newly appeared computer
4. Transfer may or may not start without accepting

### Expected behavior

require accepting

### Desktop (please complete the following information)

Windows 10
App 1.8.0

### Smartphone (please complete the following information)

Pixel 6
Android
App 1.8.0

**Comment by Tienisto** [comment]
Hello, there is a "Quick Save" button on the receive tab. You might accidentally enabled this.

**Comment by szabolcsdombi** [comment]
Usually I start the app on the receiver side [win button] + type "localsend" + [enter]
This is in my attic so I do notice if I have to go up again to accept the files.
I do not think I enabled that feature, I just tried it now and it even has a popup I have never seen before.

However, next time I will check if it was enabled.

**Comment by szabolcsdombi** [comment]
Probably "Quick Save" was the reason. I cannot reproduce it now.
Will reopen in case I can reproduce.
