### ISSUE TITLE
Shared clipboard with trusted cluster (in background)

### ISSUE THREAD

**Issue by MariMightyMedia** [localsend/localsend#991]
### Is your feature request related to a problem? Please describe.

First of all: I really like this application! Thanks a lot!

When I copy a text on my phone it takes much time until I can paste it on my PC with the text / paste feature. 

Also for now it is really not like AirDrop to send files or anything from the PC to the phone, because I always have to first start the application on the phone and then it's able to find it on the PC. 

### Describe the solution you'd like

Between apple devices there is the great feature that allows to just copy and on one device and paste on the other without any further action. They are doing it via the Apple ID and WIFI + Bluetooth connection.
My suggestion is a feature to create a trusted cluster of devices (e.g. when the ❤️ is given on both devices) where the clipboard is always shared without any further action.

It would be great if the app could somehow always be opened in the background on the phone so that I can send even if the app is not opened yet.

**Comment by Tienisto** [comment]
Sorry, this requires a lot of OS integration and is not feasable right now. LocalSend was created to easily send files from one to another device. Clipboard sync should be a separate app.
