### ISSUE TITLE
Bug report On Android, the backlight animation when switching from tab to tab isn't smooth

### ISSUE THREAD

**Issue by Orest19Marko** [localsend/localsend#993]
### Describe the bug

On Android, the backlight animation when switching from tab to tab isn't smooth. This is especially noticeable on the Send tab. This has been the case before, but with today's update, the problem has become more noticeable. I don't know why, but when recording the screen, it doesn't appear as often as during normal use. I also tried on my old phone, it also has this problem.
If anyone else has encountered this, please let me know with a 👍 under this message. I want to know if I'm not the only one like that.

### To reproduce

Open the app on your phone and try switching between the tabs several times, paying special attention to the Send tab.

### Expected behavior

Smooth animation of transitions.

### Screenshots

https://github.com/localsend/localsend/assets/153006520/ae37e6ad-b1dd-498d-894c-085194b586ba

https://github.com/localsend/localsend/assets/153006520/ee25a7a4-74ed-426c-8411-77b2fe42e403

### Smartphone (please complete the following information)

OnePlus 11, Android 13
OnePlus 7 Pro, Android 10

LocalSend v1.13.0

**Comment by Tienisto** [comment]
When you open the send tab and there are currently no nearby devices, then it will scan the network.
It should not lag if you have already found one device?

**Comment by Tienisto** [comment]
Yes, the current implementation is not optimal.
There will be a restructuring of the code to run network-related logic in a separate thread to enable #491.
