### ISSUE TITLE
Feature request: Automatic closure of the dialog window after the successful transfer of the file/files, not only from the recipient's side but also from the sender's side

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#994]
### Is your feature request related to a problem? Please describe.

In my opinion, it would have been more logical and practical to implement automatic closure of the dialog window after the successful transfer of the file/files, not only from the recipient's side but also from the sender's side. Currently, this solution seems somewhat peculiar.

Related to [#923](https://github.com/localsend/localsend/issues/923)

### Describe the solution you'd like

///

**Comment by EdwardWilsonJr** [comment]
I completely agree. I would also like to point out that instantly closing the transfer dialog doesn't look very good. Visually, it appears abrupt and as if the transfer is just being cut off. It would be much visually appealing if the window remained visible for an additional 2-3 seconds after the transfer, similar to notifications on a phone or computer, and then faded out through a reverse animation which is used for its appearance. It might be subtle, but it's noticeable and adds a smooth touch. Currently, it looks as if it was implemented hastily, especially compared to other parts of the application where everything looks smooth and polished.
