### ISSUE TITLE
F-Droid build failed due to non free lib

### ISSUE THREAD

**Issue by linsui** [localsend/localsend#995]
### Describe the bug

The in_app_purchase [added recently](https://github.com/localsend/localsend/pull/910) uses billingclient which is not free. Could you please use a free alternative or provide a flavor without it? Thanks!

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

All libs are FOSS. :)

**Comment by Tienisto** [comment]
Hi,

I have updated the APK in the [Github Release](https://github.com/localsend/localsend/releases/tag/v1.13.0).
It was built with https://github.com/localsend/localsend/tree/v1.13.0-fdroid

I also added a script that removes the propriety dependencies: [scripts/remove_proprietary_dependencies.sh](https://github.com/localsend/localsend/blob/main/scripts/remove_proprietary_dependencies.sh)
It also runs in the [Github Pipeline](https://github.com/localsend/localsend/blob/main/.github/workflows/release.yml#L33)

I guess this script must be executed on the F-Droid pipeline as well?

**Comment by linsui** [comment]
Reproducible build failed.

[diff.zip](https://github.com/localsend/localsend/files/13596852/diff.zip)

I also run scripts/remove_proprietary_dependencies.sh before build. https://gitlab.com/linsui/fdroiddata/-/commit/30ddd3d09d3e01ad9b0674b3b8fcd17f184c057a

Should I update anything?

**Comment by linsui** [comment]
> Was the original (proprietary apk) reproducable?

Let me try.

**Comment by linsui** [comment]
Where can I get the proprietary apk?

**Comment by Tienisto** [comment]
oops sorry, I added it in the releases page: https://github.com/localsend/localsend/releases/download/v1.13.0/LocalSend-1.13.0-proprietary.apk

Github didn't allow me to add this file here because it exceeded 30 MB

**Comment by linsui** [comment]
It's reproducible...

**Comment by Tienisto** [comment]
Maybe the newly released v1.13.1 works? :)
