### ISSUE TITLE
Version 1.13.0 won't start on Windows 7 and Windows 8.1

### ISSUE THREAD

**Issue by Vilmodao** [localsend/localsend#999]
### Describe the bug

I found that the application does not run on my Windows 8.1 x64. 
The problem is only with version 1.13.0. Version 1.12.0 works fine.
The application is successfully installed, but at startup I get a message like in the picture, with only close option.
![hqdefault](https://github.com/localsend/localsend/assets/11928504/8f152b9e-777c-45a1-a9cc-dab39d2246df)
_Not real screenshot. Just illustration._

Portable version behaves the same way.

I don't know what details are important. Looks like there is no useful information in the logs. 

> Faulting application name: localsend_app.exe, version: 1.13.0.40, time stamp: 0x656e62e6
> Faulting module name: unknown, version: 0.0.0.0.0, time stamp: 0x00000000
> Exception code: 0xc000001d
> Fault offset: 0x000000e1d978e9a3
> Faulting process id: 0x2318
> Faulting application start time: 0x01da27c40834703b

### To reproduce

Just start app

### Expected behavior

App starts successful

### Desktop (please complete the following information)

Windows 8.1 x64
old AMD CPU 
old Nvidia Graphics

**Comment by Tienisto** [comment]
Thanks @cdhigh.
According to the error, it seems like a bug in Flutter.
LocalSend v1.13.0 uses Flutter v3.16 while LocalSend v1.12.0 used Flutter v3.13.

It seems that this error was already fixed in a previous version but I suspect that it has been introduced in Flutter v3.16 again: https://github.com/flutter/flutter/issues/110948

**Comment by Tienisto** [comment]
You can try out this zip:

[LocalSend-1.13.0-windows-x86-64-Flutter-1.13.zip](https://github.com/localsend/localsend/files/13589126/LocalSend-1.13.0-windows-x86-64-Flutter-1.13.zip)

**Comment by cdhigh** [comment]
> You can try out this zip:
> 
> [LocalSend-1.13.0-windows-x86-64-Flutter-1.13.zip](https://github.com/localsend/localsend/files/13589126/LocalSend-1.13.0-windows-x86-64-Flutter-1.13.zip)

Tested ok, Problem solved.

**Comment by Vilmodao** [comment]
> You can try out this zip:
> 
> [LocalSend-1.13.0-windows-x86-64-Flutter-1.13.zip](https://github.com/localsend/localsend/files/13589126/LocalSend-1.13.0-windows-x86-64-Flutter-1.13.zip)

This version starts perfectly fine. Thanks.

**Comment by Tienisto** [comment]
@cdhigh @Vilmodao Can you confirm that the following zip crash as well? If it crashes, then I will send this bug report to Flutter so they can fix this issue.

[flutter-3.16-test.zip](https://github.com/localsend/localsend/files/13600728/flutter-3.16-test.zip)

**Comment by cdhigh** [comment]
> @cdhigh @Vilmodao Can you confirm that the following zip crash as well? If it crashes, then I will send this bug report to Flutter so they can fix this issue.
> 
> [flutter-3.16-test.zip](https://github.com/localsend/localsend/files/13600728/flutter-3.16-test.zip)

Opened normal.
